CollectThemAllData_Store_PermanentOffers = {
    name = "Permanent Offers",
    source = "Store",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK] = {
            { name = "Furnishing Vault" },
            { name = "Storage Chest, Fortified" },
            { name = "Storage Chest, Oaken" },
            { name = "Storage Chest, Secure" },
            { name = "Storage Chest, Sturdy" },
            { name = "Storage Coffer, Oaken" },
            { name = "Storage Coffer, Secure" },
            { name = "Storage Coffer, Sturdy" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {
            { name = "Acolyte Deras Arelas" },
            { name = "Biro-dar" },
            { name = "Javinus Tirnendo" },
            { name = "Lucilla Caprenia" },
            { name = "Lyranth" },
            { name = "Prince Irnskar" },
            { name = "Solitude Guard Jorn" },

            { name = "Armory Station" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {
            { name = "Aderene, Fargrave Dregs Dealer" },
            { name = "Baron Jangleplume, the Banker" },
            { name = "Ezabi the Banker" },
            { name = "Factotum Commerce Delegate" },
            { name = "Factotum Property Steward" },
            { name = "Fezez the Merchant" },
            { name = "Ghrasharog, Armory Assistant" },
            { name = "Giladil the Ragpicker" },
            { name = "Hoarfrost, Takubar Trader" },
            { name = "Nuzhimeh the Merchant" },
            { name = "Peddler of Prizes, the Merchant" },
            { name = "Pyroclast, Infernace Conservator" },
            { name = "Tythis Andromo, the Banker" },
            { name = "Zuqoth, Armory Advisor" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {
            { name = "Tanlorin" },
            { name = "Zerith-var" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Badger Bear" },
            { name = "Falkreath Riding-Lynx" },
            { name = "Black Heights Camel" },
            { name = "Dapple Gray Palfrey" },
            { name = "Duo-Dynamo Dwarven Spider" },
            { name = "Spiritwalker Pillion Elk" },
            { name = "Eldersblood Peak Ram" },
            { name = "Dunewalker Senche-Raht" },
            { name = "Sagacious Psijic Senche-Raht" },
            { name = "Hivethief Vvardvark" },
            { name = "Autumn Messenger Fox" },
            { name = "Painted Wolf" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Bristleneck War Boar" },
            { name = "Explorer's Pack Donkey" },
            { name = "Mournhold Packrat" },

            { name = "Fiendroth" },
            { name = "Larval Yaghra" },
            { name = "Markarth Bear-Dog" },
            { name = "Pale Pass Mountain Hare" },
            { name = "Psijic Domino Pig" },
            { name = "Wrothgar Buck Goat" },
            { name = "Cave Bear Cub" },
            { name = "Desert Lynx" },
            { name = "Fawn Echalette" },
            { name = "Kindlespit Dragon Frog" },
            { name = "Moonlight Senche-Tiger" },
            { name = "Prong-Eared Grimalkin" },
            { name = "Senche-Lion Cub" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Dragon Call", info = "Dragon Hunter Emote Pack" },
            { name = "Drink From Horn", info = "Dragon Hunter Emote Pack" },
            { name = "Polish Dragon Trophy", info = "Dragon Hunter Emote Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Legendary Dragon", armorOnly = true, info = "Legendary Dragon Armor Pack" },
            { name = "Legendary Dragon", weaponOnly = true, info = "Legendary Dragon Arms Pack" },

            { name = "Blessed Inheritor", motif = 119, q = 4 },
            { name = "Blind Path Cultist", motif = 125, q = 4 },
            { name = "Coldharbour Dominator", motif = 133, q = 4 },
            { name = "Dead Keeper", motif = 122, q = 4 },
            { name = "Firesong", motif = 117, q = 4 },
            { name = "Hazardous Alchemy", motif = 91, q = 4 },
            { name = "House Mornard", motif = 118, q = 4 },
            { name = "Lucent Sentinel", motif = 128, q = 4 },
            { name = "Moongrave Fane", motif = 78, q = 4 },
            { name = "Scribes of Mora", motif = 120, q = 4 },
            { name = "Shardborn", motif = 126, q = 4 },
            { name = "Steadfast Society", motif = 113, q = 4 },
            { name = "The Recollection", motif = 124, q = 4 },
            { name = "Tide-Born", motif = 134, q = 4 },
            { name = "Wayward Guardian", motif = 97, q = 4 },
            { name = "West Weald Legion", motif = 127, q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Recall of the Crusader" },
            { name = "Druidstone Mine" },
            { name = "Karth River Cleave" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {
            { name = "Commander" },
            { name = "Duchess" },
            { name = "Cheerful", info = "Personality Emotions Pack" },
            { name = "Furious", info = "Personality Emotions Pack" },
            { name = "Melancholy", info = "Personality Emotions Pack" },
            { name = "Thief" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Blood-Forged" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Alinor Twilight Dancing Dress" },
            { name = "Budi-Shirt and Galligaskins" },
            { name = "Crystal Tower Sapiarchs' Gown" },
            { name = "Dark Passions Regalia" },
            { name = "Deepwoods Pod-Singer Tunic" },
            { name = "Eveli's Adventuring Leathers" },
            { name = "Ever Auridon Sateen Gown" },
            { name = "Ever Damp Reed-Fiber Kilt" },
            { name = "Holiday in Balmora Outfit" },
            { name = "Moonlit Cove Sojourner's Wraps" },
            { name = "New Moons Cross-Sash Robe" },
            { name = "Noble Dress" },
            { name = "Noble Suit" },
            { name = "Ranger's Crocskin Overkilt" },
            { name = "Rawhide-Laced Riften Jerkin" },
            { name = "Reeve's Formal Apparel" },
            { name = "Royal Court Jester" },
            { name = "Rumare Waterfront Casual Wear" },
            { name = "Sand-Kissed Salwar Ensemble" },
            { name = "Shimmerene Soiree Gown" },
            { name = "Singing Skald" },
            { name = "Vampire Noble" },
            { name = "Wedding Dress" },
            { name = "Wedding Suit" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Abah's Watch Turban" },
            { name = "Abah's Watch Turban with Mask" },
            { name = "Breath of Y'ffre Mask", info = "House of Reveries Mask Pack" },
            { name = "Enigmatic Mood Mask", info = "House of Reveries Mask Pack" },
            { name = "Garden Serenade Mask", info = "House of Reveries Mask Pack" },
            { name = "Tranquil Reverie Mask", info = "House of Reveries Mask Pack" },
            { name = "Reveries Flowervine Mask", info = "Reveries Operatic Mask Pack" },
            { name = "Reveries Quarto Mask", info = "Reveries Operatic Mask Pack" },
            { name = "Reveries Red Visage Mask", info = "Reveries Operatic Mask Pack" },
            { name = "Reveries Veiled Mask", info = "Reveries Operatic Mask Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
