CollectThemAllData_Store_LimitedEventStyles = {
    name = "Limited Event Styles",
    source = "Store",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Apocrypha Expedition", weaponOnly = true, info = "Apocrypha Expedition Arms Pack" },
            { name = "Earthbone Ayleid", weaponOnly = true, info = "Earthbone Ayleid Arms Pack" },
            { name = "Jester's Feast", weaponOnly = true, info = "Jester's Feast Arms Pack" },
            { name = "Bristleback Hunter", weaponOnly = true, info = "Bristleback Hunter Arms Pack" },
            { name = "Bonemold", weaponOnly = true, info = "Bonemold Arms Pack" },
            { name = "Claw-Dance Acolyte", weaponOnly = true, info = "Claw-Dance Acolyte Arms Pack" },
            { name = "Evergreen", weaponOnly = true, info = "Evergreen Arms Pack" },
            { name = "Crowborne Hunter", weaponOnly = true, info = "Crowborne Hunter Arms Pack" },
            { name = "Eltheric Revenant", weaponOnly = true, info = "Eltheric Revenant Arms Pack" },
            { name = "Wickerchain Soul", weaponOnly = true, info = "Wickerchain Soul Arms Pack" },
            { name = "Witchmother's Servant", weaponOnly = true, info = "Witchmother's Servant Arms Pack" },
            { name = "Oaken Order", weaponOnly = true, info = "Oaken Order Arms Pack" },
            { name = "Saberkeel Armaments", weaponOnly = true, info = "Saberkeel Armaments Pack" },
            { name = "Timbercrow", weaponOnly = true, info = "Timbercrow Arms Pack" },
            { name = "Evergloam Champion", armorOnly = true, info = "Evergloam Champion Armor Pack" },
            { name = "Nord Carved", weaponOnly = true, info = "Nord Carved Arms Pack" },
            { name = "Imperial Champion", armorOnly = true, info = "Imperial Champion Armor Pack" },
            { name = "Regal Regalia", weaponOnly = true, info = "Regal Regalia Arms Pack" },
            { name = "Doctrine Ordinator", weaponOnly = true, info = "Doctrine Ordinator Arms Pack" },
            { name = "Ebonsteel Knight", weaponOnly = true, info = "Ebonsteel Knight Arms Pack" },
            { name = "Second Legion", weaponOnly = true, info = "Second Legion Arms Pack" },
            { name = "Ayleid Lich", weaponOnly = true, info = "Ayleid Lich Arms Pack" },
            { name = "Worm Cult Hunter", weaponOnly = true, info = "Worm Cult Hunter Arms Pack" },
            { name = "Gold Road Dragoon", weaponOnly = true, info = "Gold Road Dragoon Arms Pack" },
            { name = "Legacy of the Draoife", weaponOnly = true, info = "Legacy of the Draoife Arms Pack" },
            { name = "Cadwell's \"Cuirass\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Gauntlets\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Girdle\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Greaves\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Helmet\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Pauldrons\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Sabatons\"", info = "Cadwell's Kitchen Style Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
