CollectThemAllData_Store_LimitedMonsterArms = {
    name = "Limited Monster Arms",
    source = "Store",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Molten Demise", weaponOnly = true, info = "Molten Demise Arms Pack" },
            { name = "Euphotic Gatekeeper", weaponOnly = true, info = "Euphotic Gatekeeper Arms Pack" },
            { name = "Kjalnar's Nightmare", weaponOnly = true, info = "Kjalnar's Nightmare Arms Pack" },
            { name = "Encratis's Behemoth", weaponOnly = true, info = "Encratis's Behemoth Arms Pack" },
            { name = "Nazaray", weaponOnly = true, info = "Nazaray Arms Pack" },
            { name = "Lady Thorn", weaponOnly = true, info = "Lady Thorn Arms Pack" },
            { name = "Prior Thierric", weaponOnly = true, info = "Prior Thierric Arms Pack" },
            { name = "Baron Zaudrus", weaponOnly = true, info = "Baron Zaudrus Arms Pack" },
            { name = "Mother Ciannait", weaponOnly = true, info = "Mother Ciannait Arms Pack" },
            { name = "Grundwulf", weaponOnly = true, info = "Grundwulf Arms Pack" },
            { name = "Maarselok", weaponOnly = true, info = "Maarselok Arms Pack" },
            { name = "Thurvokun", weaponOnly = true, info = "Thurvokun Arms Pack" },
            { name = "Selene", weaponOnly = true, info = "Selene Arms Pack" },
            { name = "Vykosa", weaponOnly = true, info = "Vykosa Arms Pack" },
            { name = "Zaan", weaponOnly = true, info = "Zaan Arms Pack" },
            { name = "Stonekeeper", weaponOnly = true, info = "Stonekeeper Arms Pack" },
            { name = "Symphony of Blades", weaponOnly = true, info = "Symphony of Blades Arms Pack" },
            { name = "Infernal Guardian", weaponOnly = true, info = "Infernal Guardian Arms Pack" },
            { name = "Sentinel of Rkugamz", weaponOnly = true, info = "Sentinel of Rkugamz Arms Pack" },
            { name = "Kra'gh", weaponOnly = true, info = "Kra'gh Arms Pack" },
            { name = "Tremorscale", weaponOnly = true, info = "Tremorscale Arms Pack" },
            { name = "Maw of the Infernal", weaponOnly = true, info = "Maw of the Infernal Arms Pack" },
            { name = "Earthgore", weaponOnly = true, info = "Earthgore Arms Pack" },
            { name = "Nerien'eth", weaponOnly = true, info = "Nerien'eth Arms Pack" },
            { name = "Domihaus", weaponOnly = true, info = "Domihaus Arms Pack" },
            { name = "Scourge Harvester", weaponOnly = true, info = "Scourge Harvester Arms Pack" },
            { name = "Balorgh", weaponOnly = true, info = "Balorgh Arms Pack" },
            { name = "Stormfist", weaponOnly = true, info = "Stormfist Arms Pack" },
            { name = "Slimecraw", weaponOnly = true, info = "Slimecraw Arms Pack" },
            { name = "Valkyn Skoria", weaponOnly = true, info = "Valkyn Skoria Arms Pack" },
            { name = "Iceheart", weaponOnly = true, info = "Iceheart Arms Pack" },
            { name = "Pirate Skeleton", weaponOnly = true, info = "Pirate Skeleton Arms Pack" },
            { name = "Chokethorn", weaponOnly = true, info = "Chokethorn Arms Pack" },
            { name = "Velidreth", weaponOnly = true, info = "Velidreth Arms Pack" },
            { name = "Mighty Chudan", weaponOnly = true, info = "Mighty Chudan Arms Pack" },
            { name = "Lord Warden", weaponOnly = true, info = "Lord Warden Arms Pack" },
            { name = "Lord Warden's", weaponOnly = true, info = "Lord Warden Arms Pack" },
            { name = "Nightflame", weaponOnly = true, info = "Nightflame Arms Pack" },
            { name = "Engine Guardian", weaponOnly = true, info = "Engine Guardian Arms Pack" },
            { name = "Sellistrix", weaponOnly = true, info = "Sellistrix Arms Pack" },
            { name = "Swarm Mother", weaponOnly = true, info = "Swarm Mother Arms Pack" },
            { name = "Bloodspawn", weaponOnly = true, info = "Bloodspawn Arms Pack" },
            { name = "Troll King", weaponOnly = true, info = "Troll King Arms Pack" },
            { name = "Grothdarr", weaponOnly = true, info = "Grothdarr Arms Pack" },
            { name = "Shadowrend", weaponOnly = true, info = "Shadowrend Arms Pack" },
            { name = "Molag Kena", weaponOnly = true, info = "Molag Kena Arms Pack" },
            { name = "Ilambris", weaponOnly = true, info = "Ilambris Arms Pack" },
            -- { name = "Anthelmir's Construct", weaponOnly = true, info = "Anthelmir's Construct Arms Pack" },
            -- { name = "Archdruid Devyric", weaponOnly = true, info = "Archdruid Devyric Arms Pack" },
            -- { name = "Bar-Sakka", weaponOnly = true, info = "Bar-Sakka Arms Pack" },
            -- { name = "Black Gem Monstrosity", weaponOnly = true, info = "Black Gem Monstrosity Arms Pack" },
            { name = "Kargaeda", weaponOnly = true, info = "Kargaeda Arms Pack" },
            -- { name = "Magma Incarnate", weaponOnly = true, info = "Magma Incarnate Arms Pack" },
            -- { name = "Orpheon the Tactician", weaponOnly = true, info = "Orpheon the Tactician Arms Pack" },
            -- { name = "Ozezan the Inferno", weaponOnly = true, info = "Ozezan the Inferno Arms Pack" },
            { name = "Roksa the Warped", weaponOnly = true, info = "Roksa the Warped Arms Pack" },
            { name = "Spawn of Mephala", weaponOnly = true, info = "Spawn of Mephala Arms Pack" },
            -- { name = "Squall of Retribution", weaponOnly = true, info = "Squall of Retribution Arms Pack" },
            { name = "The Blind", weaponOnly = true, info = "The Blind Arms Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
