CollectThemAllData_Store_LimitedBundles = {
    name = "Limited Bundles",
    source = "Store",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {
            { name = "Drinweth, Valenwood Armorer", info = "Grace of the Green Bundle" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Isle of Contemplation Indrik", info = "Blossom-Lover Bundle" },
            { name = "Daredevil's Dapper Lion", info = "Dapper Daredevil Bundle" },
            { name = "Evenfall Brekka", info = "Evenshade Brekka Bundle" },
            { name = "Redoran Foyada Vvardvark", info = "Foyada Vvardvark Bundle" },
            { name = "Gloam Senche", info = "Gloam Senche Bundle" },
            { name = "Shor's Fox", info = "Hare and Fox Bundle" },
            { name = "Highland Spotted Lynx", info = "Highland Spotted Lynx Bundle" },
            { name = "Mara's Awe Bear", info = "Mara's Awe Bundle" },
            { name = "Soul Gem Senche", info = "Soul Gem Senche Bundle" },
            { name = "Wildburn Tharriker", info = "Wildburn Tharriker and Boar Bundle" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Pridehome Jerboa", info = "Blossom-Lover Bundle" },
            { name = "Daredevil's Dapper Cub", info = "Dapper Daredevil Bundle" },
            { name = "Evenshade Brekka Calf", info = "Evenshade Brekka Bundle" },
            { name = "Magmaflow Vvardvark", info = "Foyada Vvardvark Bundle" },
            { name = "Gloam Senche Cub", info = "Gloam Senche Bundle" },
            { name = "Abyssal Bunny", info = "Hare and Fox Bundle" },
            { name = "Highland Spotted Lynx Cub", info = "Highland Spotted Lynx Bundle" },
            { name = "Mara's Awe Cub", info = "Mara's Awe Bundle" },
            { name = "Soul Gem Senche Cub", info = "Soul Gem Senche Bundle" },
            { name = "Wildburn Boar", info = "Wildburn Tharriker and Boar Bundle" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Shimmering Gala Gown Veil", info = "Summer's Shimmer Wedding Bundle" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Clippers", info = "Soul Gem, Parchment, Clippers" },
            { name = "Parchment", info = "Soul Gem, Parchment, Clippers" },
            { name = "Soul Gem", info = "Soul Gem, Parchment, Clippers" },
            { name = "Rolling Pin", info = "The Intrepid Gourmet Bundle" },
            { name = "Salty", info = "The Intrepid Gourmet Bundle" },
            { name = "Slice Food", info = "The Intrepid Gourmet Bundle" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Dapper Daredevil", info = "Dapper Daredevil Bundle" },
            { name = "Y'ffre-Bound", info = "Grace of the Green Bundle", waeponOnly = true },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Baker", info = "The Intrepid Gourmet Bundle" },
            { name = "Naryu's Morag Tong Costume", info = "Naryu's Morag Tong Costume Bundle" },
            { name = "Summerset Gala Wedding Gown", info = "Summer's Shimmer Wedding Bundle" },
            { name = "Baker", info = "The Intrepid Gourmet Bundle" },
            { name = "Lion Guard Elite", info = "Armored Knights Pack" },
            { name = "Lion Guard Knight", info = "Armored Knights Pack" },
            { name = "Knight of the Flame", info = "Armored Knights Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Ass-Ears Jester Cap", info = "Jester's Festival Hat Pack" },
            { name = "Bi-Color Coxcomb Cap", info = "Jester's Festival Hat Pack" },
            { name = "Fool's Cap and Masque", info = "Jester's Festival Hat Pack" },
            { name = "Camlorn \"Lucky Bouquet\" Top Hat", info = "Camlorn Top Hat Pack" },
            { name = "Camlorn Top Hat with Buckle", info = "Camlorn Top Hat Pack" },
            { name = "Camlorn Top Hat with Shamrock", info = "Camlorn Top Hat Pack" },
            { name = "Deluxe Mourning Hat", info = "Flatbrim Mourning Hat Pack" },
            { name = "Modest Mourning Hat", info = "Flatbrim Mourning Hat Pack" },
            { name = "Plumed Mourning Hat", info = "Flatbrim Mourning Hat Pack" },
            { name = "Dibella's Doll Mask, Argonian", info = "Dibella's Doll Mask Pack" },
            { name = "Dibella's Doll Mask, Human / Elf", info = "Dibella's Doll Mask Pack" },
            { name = "Dibella's Doll Mask, Khajiiti", info = "Dibella's Doll Mask Pack" },
            { name = "Nightmare Daemon Mask, Argonian", info = "Nightmare Daemon Mask Pack" },
            { name = "Nightmare Daemon Mask, Human/Elf", info = "Nightmare Daemon Mask Pack" },
            { name = "Nightmare Daemon Mask, Khajiiti", info = "Nightmare Daemon Mask Pack" },
            { name = "Visage of Bani", info = "Icereach Masks Pack Pack" },
            { name = "Visage of Gohlla", info = "Icereach Masks Pack Pack" },
            { name = "Winter Corsage Broadbrim", info = "Winter Broadbrim Hat Pack" },
            { name = "Winter Garland Broadbrim", info = "Winter Broadbrim Hat Pack" },
            { name = "Winter Wreath Broadbrim", info = "Winter Broadbrim Hat Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Morag Tong Spatter Lenses", info = "Naryu's Morag Tong Costume Bundle" },
            { name = "Star-Made Circlet", info = "Whitestrake's Mayhem Crowns pack (Midyear Mayhem Crowns Pack)" },
            { name = "Star-Made Diamond Diadem", info = "Whitestrake's Mayhem Crowns pack (Midyear Mayhem Crowns Pack)" },
            { name = "Star-Made Sword Coronet", info = "Whitestrake's Mayhem Crowns pack (Midyear Mayhem Crowns Pack)" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
