CollectThemAllData_Store_LimitedHouses = {
    name = "Limited Houses",
    source = "Store",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {
            { name = "Dancing Waters Wellspring", no = 129 },
            { name = "Buccaneer Bay", no = 125 },
            { name = "Druidspring Conservatory", no = 123 },
            { name = "Cradle of the Worm Colossus", no = 122 },
            { name = "Hiddenspring Cottage", no = 120 },
            { name = "Theater of the Ancestors", no = 119 },
            { name = "Castle Skingrad", no = 116 },
            { name = "Shattered Mirror Isle", no = 115 },
            { name = "Kthendral Deep Mines", no = 113 },
            { name = "Zhan Khaj Crest", no = 108 },
            { name = "Willowpond Haven", no = 107 },
            { name = "Tower of Unutterable Truths", no = 106 },
            { name = "Gladesong Arboretum", no = 105 },
            { name = "Shadow Queen's Labyrinth", no = 102 },
            { name = "The Fair Winds", no = 99 },
            { name = "Fogbreak Lighthouse", no = 98 },
            { name = "Highhallow Hold", no = 96 },
            { name = "Seaveil Spire", no = 94 },
            { name = "Agony's Ascent", no = 93 },
            { name = "Ossa Accentium", no = 92 },
            { name = "Sweetwater Cascades", no = 91 },
            { name = "Pantherfang Chapel", no = 89 },
            { name = "Varlaisvea Ayleid Ruins", no = 86 },
            { name = "Kushalit Sanctuary", no = 85 },
            { name = "Stone Eagle Aerie", no = 83 },
            { name = "Shalidor's Shrouded Realm", no = 82 },
            { name = "Antiquarian's Alpine Gallery", no = 81 },
            { name = "Bastion Sanguinaris", no = 79 },
            { name = "Thieves' Oasis", no = 76 },
            { name = "Forgemaster Falls", no = 75 },
            { name = "Potentate's Retreat", no = 74 },
            { name = "Wraithhome", no = 72 },
            { name = "Jode's Embrace", no = 69 },
            { name = "Elinhir Private Arena", no = 66 },
            { name = "Frostvault Chasm", no = 65 },
            { name = "Lakemire Xanmeer Manor", no = 64 },
            { name = "Enchanted Snow Globe Home", no = 63, info = "Only available during New Life Festival" },
            { name = "Grand Psijic Villa", no = 62 },
            { name = "Hunter's Glade", no = 61 },
            { name = "Colossal Aldmeri Grotto", no = 60 },
            { name = "Princely Dawnlight Palace", no = 57 },
            { name = "The Erstwhile Sanctuary", no = 56 },
            { name = "Pariah's Pinnacle", no = 54 },
            { name = "Exorcised Coven Cottage", no = 49, info = "Only available during Witches Festival" },
            { name = "Linchal Grand Manor", no = 46 },
            { name = "Tel Galen", no = 45 },
            { name = "Grand Topal Hideaway", no = 40 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
