CollectThemAllData_Store_PermanentStyleParlor = {
    name = "Permanent Style Parlor",
    source = "Store",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Dominion Warrior Body Tattoos", info = "Aldmeri Dominion Tattoos" },
            { name = "Chevron Slashmarks", info = "Chevron Slash Markings" },
            { name = "Covenant Warrior Body Tattoos", info = "Daggerfall Covenant Tattoos" },
            { name = "Dark Crescent Moons", info = "Dark Moons Markings" },
            { name = "Pact Warrior Body Tattoos", info = "Ebonheart Pact Tattoos" },
            { name = "Wings of the Wind Goddess", info = "Winged Herald Markings" },

            { name = "Arrow Scars, including Knee", info = "Cosmetic Pack: Body Markings" },
            { name = "Bear-Claw Scars", info = "Cosmetic Pack: Body Markings" },
            { name = "Bite Marks on Neck", info = "Cosmetic Pack: Body Markings" },
            { name = "Black Limb-Bands", info = "Cosmetic Pack: Body Markings" },
            { name = "Black Scarab Chest", info = "Cosmetic Pack: Body Markings" },
            { name = "Black Strokes, Red Stitches", info = "Cosmetic Pack: Body Markings" },
            { name = "Black Sun Paint Pauldrons", info = "Cosmetic Pack: Body Markings" },
            { name = "Blood Stripes Chest Paint", info = "Cosmetic Pack: Body Markings" },
            { name = "Bloody Chest Veil", info = "Cosmetic Pack: Body Markings" },
            { name = "Blue Skeleton Body Paint", info = "Cosmetic Pack: Body Markings" },
            { name = "Blue Spider Daedra Paint", info = "Cosmetic Pack: Body Markings" },
            { name = "Blue Stripes Chest Paint", info = "Cosmetic Pack: Body Markings" },
            { name = "Broad Half-Body Ember Smear", info = "Cosmetic Pack: Body Markings" },
            { name = "Broad Half-Body Smearing", info = "Cosmetic Pack: Body Markings" },
            { name = "Brown Radiant Blotches", info = "Cosmetic Pack: Body Markings" },
            { name = "Brown Radiant Strokes", info = "Cosmetic Pack: Body Markings" },
            { name = "Brown Spider Strokes", info = "Cosmetic Pack: Body Markings" },
            { name = "Burned Chest Scars", info = "Cosmetic Pack: Body Markings" },
            { name = "Concentric Dot Scars", info = "Cosmetic Pack: Body Markings" },
            { name = "Covenant Lion Dark Blue", info = "Cosmetic Pack: Body Markings" },
            { name = "Cracked Mud Tattoos", info = "Cosmetic Pack: Body Markings" },
            { name = "Dark Red Pact Chest Dragon", info = "Cosmetic Pack: Body Markings" },
            { name = "Deep Dark Paint Gorget", info = "Cosmetic Pack: Body Markings" },
            { name = "Deep Dark Red-Trim Gorget", info = "Cosmetic Pack: Body Markings" },
            { name = "Dotted Line Scar Chevrons", info = "Cosmetic Pack: Body Markings" },
            { name = "Extensive Burn Scarring", info = "Cosmetic Pack: Body Markings" },
            { name = "Freckles and Moles", info = "Cosmetic Pack: Body Markings" },
            { name = "Geometric Placket Scarring", info = "Cosmetic Pack: Body Markings" },
            { name = "Gold Dominion Chest Eagle", info = "Cosmetic Pack: Body Markings" },
            { name = "Gold Stippled Tattoo Swirls", info = "Cosmetic Pack: Body Markings" },
            { name = "Golden Ocean Geometry", info = "Cosmetic Pack: Body Markings" },
            { name = "Golden Paisley", info = "Cosmetic Pack: Body Markings" },
            { name = "Golden Wraparound Wyrm", info = "Cosmetic Pack: Body Markings" },
            { name = "Heart-Cross Scars", info = "Cosmetic Pack: Body Markings" },
            { name = "Horizontal Dotted Scar Lines", info = "Cosmetic Pack: Body Markings" },
            { name = "Ink Pendant Neck and Arms", info = "Cosmetic Pack: Body Markings" },
            { name = "Inky Chest Veil", info = "Cosmetic Pack: Body Markings" },
            { name = "Intermittent Swirl Tattoos", info = "Cosmetic Pack: Body Markings" },
            { name = "Light Blue Chest Wings", info = "Cosmetic Pack: Body Markings" },
            { name = "Light Blue Covenant Lion", info = "Cosmetic Pack: Body Markings" },
            { name = "No Body Marking", info = "Cosmetic Pack: Body Markings" },
            { name = "Ocean Geometry Full Body", info = "Cosmetic Pack: Body Markings" },
            { name = "Ominous Handprints", info = "Cosmetic Pack: Body Markings" },
            { name = "Open-Front Dense Swirls", info = "Cosmetic Pack: Body Markings" },
            { name = "Outline Chest Wyrm", info = "Cosmetic Pack: Body Markings" },
            { name = "Pact Dragon Chest", info = "Cosmetic Pack: Body Markings" },
            { name = "Painted Chevron Strokes", info = "Cosmetic Pack: Body Markings" },
            { name = "Painted Coal and Blue Strokes", info = "Cosmetic Pack: Body Markings" },
            { name = "Painted Coal and Embers", info = "Cosmetic Pack: Body Markings" },
            { name = "Painted Coal and Green Strokes", info = "Cosmetic Pack: Body Markings" },
            { name = "Painted Double Crosses", info = "Cosmetic Pack: Body Markings" },
            { name = "Painted Rising Lines", info = "Cosmetic Pack: Body Markings" },
            { name = "Painted Sacred Insect", info = "Cosmetic Pack: Body Markings" },
            { name = "Painted Spider Strokes", info = "Cosmetic Pack: Body Markings" },
            { name = "Painted Vertical Strokes", info = "Cosmetic Pack: Body Markings" },
            { name = "Painted Zigzag Crosses", info = "Cosmetic Pack: Body Markings" },
            { name = "Paisley Arms and Half Chest", info = "Cosmetic Pack: Body Markings" },
            { name = "Prominent Pockmarks", info = "Cosmetic Pack: Body Markings" },
            { name = "Radiant Blotches", info = "Cosmetic Pack: Body Markings" },
            { name = "Radiant Lines and Dots", info = "Cosmetic Pack: Body Markings" },
            { name = "Red Skeleton Body Paint", info = "Cosmetic Pack: Body Markings" },
            { name = "Right Shoulder Scar", info = "Cosmetic Pack: Body Markings" },
            { name = "Smoke Swirl Arm Tattoos", info = "Cosmetic Pack: Body Markings" },
            { name = "Solid Wraparound Wyrm", info = "Cosmetic Pack: Body Markings" },
            { name = "Spider Daedra Chest Paint", info = "Cosmetic Pack: Body Markings" },
            { name = "Stippled Tattoo Swirls", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Pendant Neck and Arms", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Pockmarks", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Swirl Tattoos", info = "Cosmetic Pack: Body Markings" },
            { name = "Tentacle Thistle Chest Ink", info = "Cosmetic Pack: Body Markings" },
            { name = "Triple Blue Chest Wings", info = "Cosmetic Pack: Body Markings" },
            { name = "Triple-Ink Chest Wings", info = "Cosmetic Pack: Body Markings" },
            { name = "Twisted Briar Shoulder Tats", info = "Cosmetic Pack: Body Markings" },
            { name = "Vertical Dotted Scar Lines", info = "Cosmetic Pack: Body Markings" },
            { name = "Widespread Subtle Burns", info = "Cosmetic Pack: Body Markings" },
            { name = "Wild-Eyed Wolf Chest", info = "Cosmetic Pack: Body Markings" },

            { name = "Black Panther", info = "Cosmetic Pack: Body Markings" },
            { name = "Black-Eared Puma", info = "Cosmetic Pack: Body Markings" },
            { name = "Blotchy Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Bronze Serpent Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Copper Serpent Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Croco-Spots", info = "Cosmetic Pack: Body Markings" },
            { name = "Dark Gray Lizard Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Dark Mottled Lizard Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Gray Lizard with Armbands", info = "Cosmetic Pack: Body Markings" },
            { name = "Gray Pebbled Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Gray Serpent Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Green Pebbled Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Greenish Gray Lizard Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Ink-Blot Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Jaguar Rosettes", info = "Cosmetic Pack: Body Markings" },
            { name = "Leopard Spots", info = "Cosmetic Pack: Body Markings" },
            { name = "Light Cheetah", info = "Cosmetic Pack: Body Markings" },
            { name = "Light Gray Lizard Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Light Mottled Lizard Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Light Serval Spots", info = "Cosmetic Pack: Body Markings" },
            { name = "Medium Mottled Lizard Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Oval Cheetah Spots", info = "Cosmetic Pack: Body Markings" },
            { name = "Puma Fur", info = "Cosmetic Pack: Body Markings" },
            { name = "Red Caracal", info = "Cosmetic Pack: Body Markings" },
            { name = "Red-Gold Serpent Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Ruddy Serpent Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Rusty Silver Serpent Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Rusty Steel Serpent Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Silver-Black Serpent Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Striated Tiger", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Cheetah", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Jaguar", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Leopard", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Puma", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Red Caracal", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Serval", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Striated", info = "Cosmetic Pack: Body Markings" },
            { name = "Subtle Tiger", info = "Cosmetic Pack: Body Markings" },
            { name = "Tiger Stripes", info = "Cosmetic Pack: Body Markings" },
            { name = "Verdigris Lizard Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Verdigris Tin Serpent Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Warm Gray Lizard Scales", info = "Cosmetic Pack: Body Markings" },
            { name = "Zebra Stripes", info = "Cosmetic Pack: Body Markings" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Double Diagonal Face Warpaint", info = "Barbarian Warrior Cosmetic Pack" },
            { name = "Eye-Briar Gemmed Tattoo", info = "Barbaric Beauty Pack" },

            { name = "Dominion Warrior Head Tattoos", info = "Aldmeri Dominion Tattoos" },
            { name = "Chevron Head Paint", info = "Chevron Slash Markings" },
            { name = "Chevron Headwrap", info = "Chevron Slash Markings" },
            { name = "Covenant Warrior Face Tattoos", info = "Daggerfall Covenant Tattoos" },
            { name = "Dark Moons Headwrap", info = "Dark Moons Markings" },
            { name = "Pact Warrior Face Tattoos", info = "Ebonheart Pact Tattoos" },
            { name = "Winged Brows", info = "Winged Herald Markings" },

            { name = "Climbing Briar Face Tattoo" },

            { name = "Black and Red X Domino", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Ballista Face", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Bleeding Right Eye", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Brow, Cheeks, Chin", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Brows, Red Strokes", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Cheek & Chin Bars", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Cross with Right Top Bar", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Cross, Cheek Diagonals", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Eye Pools, Red Crossbar", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Eyeliner and Lips", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Eyeliner, Blue Lips", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Forehead, Blue Strokes", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Forehead, Green Strokes", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Mask, Lips Sealed", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Paint Domino Mask", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Pointy Paint Pattern", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Radiant Paint Smears", info = "Cosmetic Pack: Face Markings" },
            { name = "Black Scoops with Pendants", info = "Cosmetic Pack: Face Markings" },
            { name = "Blue and Coal Skull", info = "Cosmetic Pack: Face Markings" },
            { name = "Blue Ballista Face", info = "Cosmetic Pack: Face Markings" },
            { name = "Brow Shield, Cheek Chevrons", info = "Cosmetic Pack: Face Markings" },
            { name = "Brown Brow & Cheek Chevrons", info = "Cosmetic Pack: Face Markings" },
            { name = "Brown Brow, Cheeks, Chin", info = "Cosmetic Pack: Face Markings" },
            { name = "Brown Cheek and Chin Bars", info = "Cosmetic Pack: Face Markings" },
            { name = "Brown Diagonal Cheek Bars", info = "Cosmetic Pack: Face Markings" },
            { name = "Brown Pointy Paint Pattern", info = "Cosmetic Pack: Face Markings" },
            { name = "Brown Radiant Diagonals", info = "Cosmetic Pack: Face Markings" },
            { name = "Brown Scoops with Pendants", info = "Cosmetic Pack: Face Markings" },
            { name = "Brown Vertical Eye Smears", info = "Cosmetic Pack: Face Markings" },
            { name = "Central Black Lip Smear", info = "Cosmetic Pack: Face Markings" },
            { name = "Chalk and Coal Skull", info = "Cosmetic Pack: Face Markings" },
            { name = "Chalky White Lips", info = "Cosmetic Pack: Face Markings" },
            { name = "Copper Bug Leg Tattoos", info = "Cosmetic Pack: Face Markings" },
            { name = "Dark Eyeliner", info = "Cosmetic Pack: Face Markings" },
            { name = "Dark Red Lip Dye", info = "Cosmetic Pack: Face Markings" },
            { name = "Deep Black Sunken Eyes", info = "Cosmetic Pack: Face Markings" },
            { name = "Geometric Brow Scars", info = "Cosmetic Pack: Face Markings" },
            { name = "Gold Lips and Eyeliner", info = "Cosmetic Pack: Face Markings" },
            { name = "Large Black-and-Blue Domino", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Black Triangle Smear", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Cheek Diagonal Scar", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Eye Diagonal Scar", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Eye Topographic Spiral", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Side Half-Brown Smear", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Side Half-Chalk Smear", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Side Half-Coal Smear", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Side Half-Green Smear", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Side Half-Red Smear", info = "Cosmetic Pack: Face Markings" },
            { name = "Mask of Black Triangles", info = "Cosmetic Pack: Face Markings" },
            { name = "Mask of Copper Triangles", info = "Cosmetic Pack: Face Markings" },
            { name = "Namira's Icky Black Leg Tats", info = "Cosmetic Pack: Face Markings" },
            { name = "No Head Marking", info = "Cosmetic Pack: Face Markings" },
            { name = "Paint Mask plus Cheek Smears", info = "Cosmetic Pack: Face Markings" },
            { name = "Radiant Blue Strokes on Black", info = "Cosmetic Pack: Face Markings" },
            { name = "Radiant Red Strokes on Black", info = "Cosmetic Pack: Face Markings" },
            { name = "Radiant Ritual Brow Scars", info = "Cosmetic Pack: Face Markings" },
            { name = "Red and Black Death Mask", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Ballista Face", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Bleeding Right Eye", info = "Cosmetic Pack: Face Markings" },
            { name = "Right Eye Scar", info = "Cosmetic Pack: Face Markings" },
            { name = "Right Side Half-Blue Smear", info = "Cosmetic Pack: Face Markings" },
            { name = "Right Side Half-Coal Smear", info = "Cosmetic Pack: Face Markings" },
            { name = "Rivet Scars: Cheeks and Forehead", info = "Cosmetic Pack: Face Markings" },
            { name = "Scars, Cheek and Left Eye", info = "Cosmetic Pack: Face Markings" },
            { name = "Spidermouth Scars", info = "Cosmetic Pack: Face Markings" },
            { name = "Subtle Blue Eye Shadow", info = "Cosmetic Pack: Face Markings" },
            { name = "Subtle Freckles", info = "Cosmetic Pack: Face Markings" },
            { name = "Subtle Natural Makeup", info = "Cosmetic Pack: Face Markings" },
            { name = "Subtle Red Eye Shadow", info = "Cosmetic Pack: Face Markings" },
            { name = "Sunken Eyes with Insect Legs", info = "Cosmetic Pack: Face Markings" },
            { name = "V-Y-Y Black Paint Strokes", info = "Cosmetic Pack: Face Markings" },
            { name = "V-Y-Y Brown Paint Strokes", info = "Cosmetic Pack: Face Markings" },
            { name = "Vertical Blue Strokes on Black", info = "Cosmetic Pack: Face Markings" },
            { name = "Vertical Eye Mask Smears", info = "Cosmetic Pack: Face Markings" },
            { name = "Vertical Red Strokes on Black", info = "Cosmetic Pack: Face Markings" },
            { name = "White Highlight Lip Dye", info = "Cosmetic Pack: Face Markings" },

            { name = "Assorted Smaller Scars", info = "Cosmetic Pack: Face Markings" },
            { name = "Blood Fangs and Eye Shadow", info = "Cosmetic Pack: Face Markings" },
            { name = "Bloodmuzzle", info = "Cosmetic Pack: Face Markings" },
            { name = "Bloodred Sunken Eyes", info = "Cosmetic Pack: Face Markings" },
            { name = "Bloody Muzzle, Cheeks, & Brow", info = "Cosmetic Pack: Face Markings" },
            { name = "Bloody V Face Cradle", info = "Cosmetic Pack: Face Markings" },
            { name = "Bloody Zigzag Cheeks", info = "Cosmetic Pack: Face Markings" },
            { name = "Brow and Snout Scars", info = "Cosmetic Pack: Face Markings" },
            { name = "Brown Concentric Paint Rings", info = "Cosmetic Pack: Face Markings" },
            { name = "Burn-Scarred Nose and Chin", info = "Cosmetic Pack: Face Markings" },
            { name = "Chalk and Coal Scale Skull", info = "Cosmetic Pack: Face Markings" },
            { name = "Claw-Scarred Brow and Nose", info = "Cosmetic Pack: Face Markings" },
            { name = "Concentric Blood Rings", info = "Cosmetic Pack: Face Markings" },
            { name = "Double-Scarred Left Eye", info = "Cosmetic Pack: Face Markings" },
            { name = "Five Red Rings", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Cheek-Chin Diagonal Scar", info = "Cosmetic Pack: Face Markings" },
            { name = "Left Diagonal Snout Scar", info = "Cosmetic Pack: Face Markings" },
            { name = "Many Small Healed Scars", info = "Cosmetic Pack: Face Markings" },
            { name = "Nose-Radiant Blood Smears", info = "Cosmetic Pack: Face Markings" },
            { name = "Purple Paint Cheek Slashes", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Block Scale Lines", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Brow Dots & Eye Lines", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Bullseye Face Paint", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Concentric Face Rings", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Eye Mask with Drips", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Magicka Eyes", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Over-Nose Blood Bridle", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Paint Brows and Goatee", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Paint Diagonal Slashes", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Paint Double Square", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Paint Face Tentacles", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Paint Radiant Strokes", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Slash Eye Accent", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Sunken Eye Smears", info = "Cosmetic Pack: Face Markings" },
            { name = "Red Zigzag Domino", info = "Cosmetic Pack: Face Markings" },
            { name = "Right Brow Scar", info = "Cosmetic Pack: Face Markings" },
            { name = "Right Cheek-Chin Diagonal Scar", info = "Cosmetic Pack: Face Markings" },
            { name = "Right Diagonal Snout Scar", info = "Cosmetic Pack: Face Markings" },
            { name = "Scarred Right Brow and Cheek", info = "Cosmetic Pack: Face Markings" },
            { name = "Scarred Right Eye", info = "Cosmetic Pack: Face Markings" },
            { name = "Small Diagonal Snout Scar", info = "Cosmetic Pack: Face Markings" },
            { name = "This One Would Like a New Nose", info = "Cosmetic Pack: Face Markings" },
            { name = "This One's Very Worn Nose", info = "Cosmetic Pack: Face Markings" },
            { name = "This One's Worn Nose", info = "Cosmetic Pack: Face Markings" },
            { name = "Vertical Black Fang Strokes", info = "Cosmetic Pack: Face Markings" },
            { name = "Vertical Red Eye Smears", info = "Cosmetic Pack: Face Markings" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Wrapped Horsetail", info = "Barbarian Warrior Cosmetic Pack" },
            { name = "Barbaric Windblown Hair", info = "Barbaric Beauty Pack" },

            { name = "Balding But Distinguished", info = "Cosmetic Pack: Hair Styles" },
            { name = "Beaded Crested Dreads", info = "Cosmetic Pack: Hair Styles" },
            { name = "Bedhead Bob", info = "Cosmetic Pack: Hair Styles" },
            { name = "Braided Ponytail", info = "Cosmetic Pack: Hair Styles" },
            { name = "Breton Tonsure", info = "Cosmetic Pack: Hair Styles" },
            { name = "Bruma Burr Cut", info = "Cosmetic Pack: Hair Styles" },
            { name = "By Kyne, It's Humid", info = "Cosmetic Pack: Hair Styles" },
            { name = "Center-Part Long", info = "Cosmetic Pack: Hair Styles" },
            { name = "Center-Part Medium", info = "Cosmetic Pack: Hair Styles" },
            { name = "Coil with Long Fall", info = "Cosmetic Pack: Hair Styles" },
            { name = "Heroic Pony Dreads", info = "Cosmetic Pack: Hair Styles" },
            { name = "Long and Combed Back", info = "Cosmetic Pack: Hair Styles" },
            { name = "Long Crested Dreads", info = "Cosmetic Pack: Hair Styles" },
            { name = "Long Full Dreads", info = "Cosmetic Pack: Hair Styles" },
            { name = "Management Material", info = "Cosmetic Pack: Hair Styles" },
            { name = "Medium Cornrows", info = "Cosmetic Pack: Hair Styles" },
            { name = "Midhair Center Crest", info = "Cosmetic Pack: Hair Styles" },
            { name = "Mini-Pony with Braids", info = "Cosmetic Pack: Hair Styles" },
            { name = "No Hair Style", info = "Cosmetic Pack: Hair Styles" },
            { name = "Ponied Pigtails", info = "Cosmetic Pack: Hair Styles" },
            { name = "Pony Mullet", info = "Cosmetic Pack: Hair Styles" },
            { name = "Ponytail with Braidlocks", info = "Cosmetic Pack: Hair Styles" },
            { name = "Shaved Warrior Ponytail", info = "Cosmetic Pack: Hair Styles" },
            { name = "Shaved Warrior Topknot", info = "Cosmetic Pack: Hair Styles" },
            { name = "Short Back-Pulled Pony", info = "Cosmetic Pack: Hair Styles" },
            { name = "Short Imperial", info = "Cosmetic Pack: Hair Styles" },
            { name = "Short Tight Curls", info = "Cosmetic Pack: Hair Styles" },
            { name = "Shorthair Center Crest", info = "Cosmetic Pack: Hair Styles" },
            { name = "Shorthair Fuzz Crest", info = "Cosmetic Pack: Hair Styles" },
            { name = "Tallhair Center Crest", info = "Cosmetic Pack: Hair Styles" },
            { name = "The New Recruit", info = "Cosmetic Pack: Hair Styles" },
            { name = "Tight-Curled Hair Helmet", info = "Cosmetic Pack: Hair Styles" },
            { name = "Widow's Peak Comb-Back", info = "Cosmetic Pack: Hair Styles" },
            { name = "Wrapped Pony Dreads", info = "Cosmetic Pack: Hair Styles" },

            { name = "Anterior Antlers", info = "Cosmetic Pack: Hair Styles" },
            -- { name = "Bald Pate", info = "Cosmetic Pack: Hair Styles" },
            { name = "Beaded Dreadacles", info = "Cosmetic Pack: Hair Styles" },
            { name = "Broad Web Ears", info = "Cosmetic Pack: Hair Styles" },
            { name = "Central Spine Crest", info = "Cosmetic Pack: Hair Styles" },
            { name = "Coil with Ring Braids", info = "Cosmetic Pack: Hair Styles" },
            { name = "Cranial Spine Cluster", info = "Cosmetic Pack: Hair Styles" },
            { name = "Crested Shag Mullet", info = "Cosmetic Pack: Hair Styles" },
            { name = "Curly Back Bun", info = "Cosmetic Pack: Hair Styles" },
            { name = "Curly Mane", info = "Cosmetic Pack: Hair Styles" },
            { name = "Daedra Horns with Spike Cluster", info = "Cosmetic Pack: Hair Styles" },
            { name = "Don't Touch My Pigtails", info = "Cosmetic Pack: Hair Styles" },
            { name = "Dread Turban Bun", info = "Cosmetic Pack: Hair Styles" },
            { name = "Dreadmax Ponytail", info = "Cosmetic Pack: Hair Styles" },
            { name = "Dual Forehead Horns", info = "Cosmetic Pack: Hair Styles" },
            { name = "Dual Hind Horns", info = "Cosmetic Pack: Hair Styles" },
            { name = "Fore-and-Aft Webbed Spike Crest", info = "Cosmetic Pack: Hair Styles" },
            { name = "Four Sheathed Spikes", info = "Cosmetic Pack: Hair Styles" },
            { name = "Frisee Pouffee", info = "Cosmetic Pack: Hair Styles" },
            { name = "Geyser Ponytail", info = "Cosmetic Pack: Hair Styles" },
            { name = "Herd of Ponies", info = "Cosmetic Pack: Hair Styles" },
            { name = "Heroic Hind Braid", info = "Cosmetic Pack: Hair Styles" },
            { name = "Left-Parted Bob", info = "Cosmetic Pack: Hair Styles" },
            { name = "Left-Parted Cropped", info = "Cosmetic Pack: Hair Styles" },
            { name = "Leftside Bun Twist", info = "Cosmetic Pack: Hair Styles" },
            { name = "Long Beaded Mane", info = "Cosmetic Pack: Hair Styles" },
            { name = "Long Cornrows", info = "Cosmetic Pack: Hair Styles" },
            { name = "Long Curly Crown Braid", info = "Cosmetic Pack: Hair Styles" },
            { name = "Long Hind Braid", info = "Cosmetic Pack: Hair Styles" },
            { name = "Long Matted Mane", info = "Cosmetic Pack: Hair Styles" },
            { name = "Long Pulled-Back Pony", info = "Cosmetic Pack: Hair Styles" },
            { name = "Long Rightside Bang", info = "Cosmetic Pack: Hair Styles" },
            { name = "Maximum Frisee", info = "Cosmetic Pack: Hair Styles" },
            { name = "Maximum Ponytail", info = "Cosmetic Pack: Hair Styles" },
            { name = "Medium Dread Mane", info = "Cosmetic Pack: Hair Styles" },
            { name = "Medium Shoulder Mane", info = "Cosmetic Pack: Hair Styles" },
            { name = "Modest Dual Crests", info = "Cosmetic Pack: Hair Styles" },
            { name = "Orsinium Ponytail", info = "Cosmetic Pack: Hair Styles" },
            { name = "Outrigger Side Spikes", info = "Cosmetic Pack: Hair Styles" },
            { name = "Parted Bob Bun", info = "Cosmetic Pack: Hair Styles" },
            { name = "Pulled Back Curl Cluster", info = "Cosmetic Pack: Hair Styles" },
            { name = "Quadratic Web Crest", info = "Cosmetic Pack: Hair Styles" },
            { name = "Right-Parted Cropped", info = "Cosmetic Pack: Hair Styles" },
            { name = "Short Dreadacles", info = "Cosmetic Pack: Hair Styles" },
            { name = "Short Mane", info = "Cosmetic Pack: Hair Styles" },
            { name = "Short Mane with Ponytail", info = "Cosmetic Pack: Hair Styles" },
            { name = "Sideswept Bun", info = "Cosmetic Pack: Hair Styles" },
            { name = "Six-Spike Parietal Array", info = "Cosmetic Pack: Hair Styles" },
            { name = "Small Averted Spines", info = "Cosmetic Pack: Hair Styles" },
            { name = "Spiked Frisee", info = "Cosmetic Pack: Hair Styles" },
            { name = "Spiky Cranial Cluster", info = "Cosmetic Pack: Hair Styles" },
            { name = "Spiky Sweptback Updo", info = "Cosmetic Pack: Hair Styles" },
            { name = "Sweetroll Dreads", info = "Cosmetic Pack: Hair Styles" },
            { name = "Tall Dual Web Crests", info = "Cosmetic Pack: Hair Styles" },
            { name = "The Spines of Welcome", info = "Cosmetic Pack: Hair Styles" },
            { name = "Tight Braided Crown", info = "Cosmetic Pack: Hair Styles" },
            { name = "Topknot Ponytail", info = "Cosmetic Pack: Hair Styles" },
            { name = "Triple Web Crest", info = "Cosmetic Pack: Hair Styles" },
            { name = "Widespread Cranial Spikes", info = "Cosmetic Pack: Hair Styles" },

            { name = "Covenant Lizard-Plumes" },
            { name = "Covenant War-Locks" },
            { name = "Crest with Pony Braid" },
            { name = "Dominion Lizard-Locks" },
            { name = "Dominion War-Locks" },
            { name = "Fine Upstanding Spines" },
            { name = "Lizard Rhinoceros" },
            { name = "Long Elven Braid" },
            { name = "Long Wild Locks" },
            { name = "Pact Lizard Battle Crest" },
            { name = "Pact Veteran's Battle Crest" },
            { name = "Ragged Royal Page Cut" },
            { name = "Short-Spiked Crest" },
            { name = "Sidelong Sweep" },
            { name = "The Tousled Bard" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {
            { name = "Ringed and Gathered War Beard", info = "Barbarian Warrior Cosmetic Pack" },
            { name = "Dark Emphasis Eyelashes", info = "Barbaric Beauty Pack" },

            { name = "Beaded Sideburn Mane", info = "Cosmetic Pack: Adornments" },
            { name = "Beard with Battle Bars", info = "Cosmetic Pack: Adornments" },
            { name = "Blind Left Eye", info = "Cosmetic Pack: Adornments" },
            { name = "Blind Right Eye", info = "Cosmetic Pack: Adornments" },
            { name = "Boar's Nest", info = "Cosmetic Pack: Adornments" },
            { name = "Bosun's Droop", info = "Cosmetic Pack: Adornments" },
            { name = "Braided Beard", info = "Cosmetic Pack: Adornments" },
            { name = "Braided Goatee", info = "Cosmetic Pack: Adornments" },
            { name = "Budding Temple Horns", info = "Cosmetic Pack: Adornments" },
            { name = "Caracal Ear Tufts", info = "Cosmetic Pack: Adornments" },
            { name = "Cheekbone and Brow Studs", info = "Cosmetic Pack: Adornments" },
            { name = "Chin Strip Solo", info = "Cosmetic Pack: Adornments" },
            { name = "Chin Stripe", info = "Cosmetic Pack: Adornments" },
            { name = "Chin Talons", info = "Cosmetic Pack: Adornments" },
            { name = "Chops Shave and Circle", info = "Cosmetic Pack: Adornments" },
            { name = "Dainty Antlers", info = "Cosmetic Pack: Adornments" },
            { name = "Delicate Daedra Horns", info = "Cosmetic Pack: Adornments" },
            { name = "Dignified Goatee", info = "Cosmetic Pack: Adornments" },
            { name = "Double Sinus Spikes", info = "Cosmetic Pack: Adornments" },
            { name = "Facial Spike Cluster", info = "Cosmetic Pack: Adornments" },
            { name = "Fluffy Ear Tufts", info = "Cosmetic Pack: Adornments" },
            { name = "Forked and Tied Goatee", info = "Cosmetic Pack: Adornments" },
            { name = "Four Frontal Facial Spikes", info = "Cosmetic Pack: Adornments" },
            { name = "Goatee & Stubble", info = "Cosmetic Pack: Adornments" },
            { name = "Goatee Stripe", info = "Cosmetic Pack: Adornments" },
            { name = "Handlebar Mustache", info = "Cosmetic Pack: Adornments" },
            { name = "Long Knotted Beard", info = "Cosmetic Pack: Adornments" },
            { name = "Lowhung Sideburns", info = "Cosmetic Pack: Adornments" },
            { name = "Lynx Chops", info = "Cosmetic Pack: Adornments" },
            { name = "Minor Rhino Spino", info = "Cosmetic Pack: Adornments" },
            { name = "Modest Manly Mustache", info = "Cosmetic Pack: Adornments" },
            { name = "Mustache and Soul Patch", info = "Cosmetic Pack: Adornments" },
            { name = "Muttonchops and Mustache", info = "Cosmetic Pack: Adornments" },
            { name = "Nasal Antenna Spikes", info = "Cosmetic Pack: Adornments" },
            { name = "No Facial Hair", info = "Cosmetic Pack: Adornments" },
            { name = "Nose Spike with Chin Studs", info = "Cosmetic Pack: Adornments" },
            { name = "Oracle Eyes", info = "Cosmetic Pack: Adornments" },
            { name = "Pencil Mustache", info = "Cosmetic Pack: Adornments" },
            { name = "Poet's Stubble", info = "Cosmetic Pack: Adornments" },
            { name = "Quad Beaded Beardlet", info = "Cosmetic Pack: Adornments" },
            { name = "Sideburn Mane", info = "Cosmetic Pack: Adornments" },
            { name = "Slim and Contoured", info = "Cosmetic Pack: Adornments" },
            { name = "Small Brow Spines", info = "Cosmetic Pack: Adornments" },
            { name = "Soul Patch", info = "Cosmetic Pack: Adornments" },
            { name = "Spike Goatee", info = "Cosmetic Pack: Adornments" },
            { name = "Spiked Nose and Chin", info = "Cosmetic Pack: Adornments" },
            { name = "Spiky Nose and Brows", info = "Cosmetic Pack: Adornments" },
            { name = "Starfish Chin Spikes", info = "Cosmetic Pack: Adornments" },
            { name = "Stubble Chin", info = "Cosmetic Pack: Adornments" },
            { name = "Studded Nose Line", info = "Cosmetic Pack: Adornments" },
            { name = "Studded Temples", info = "Cosmetic Pack: Adornments" },
            { name = "Subtle Nose Spikes", info = "Cosmetic Pack: Adornments" },
            { name = "Swallowtail", info = "Cosmetic Pack: Adornments" },
            { name = "The Hrothgar Hermit", info = "Cosmetic Pack: Adornments" },
            { name = "The Swashbuckler", info = "Cosmetic Pack: Adornments" },
            { name = "The Veteran", info = "Cosmetic Pack: Adornments" },
            { name = "Three Central Nose Spikes", info = "Cosmetic Pack: Adornments" },
            { name = "Three Nasal Studs", info = "Cosmetic Pack: Adornments" },
            { name = "Tied Imperial Goatee", info = "Cosmetic Pack: Adornments" },
            { name = "Tiger Mane", info = "Cosmetic Pack: Adornments" },
            { name = "Two-Spike Goatee", info = "Cosmetic Pack: Adornments" },
            { name = "Upper Lip and Chin Strip", info = "Cosmetic Pack: Adornments" },
            { name = "V-Spiked Unibrow", info = "Cosmetic Pack: Adornments" },
            { name = "Veteran with Mini Chops", info = "Cosmetic Pack: Adornments" },
            { name = "Warrior's Beard Knot", info = "Cosmetic Pack: Adornments" },
            { name = "Woodsman Goatee", info = "Cosmetic Pack: Adornments" },

            { name = "Four-Spike Wattle" },
            { name = "Head Horns Aplenty" },
            { name = "Tousled Temple Tufts" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Studded Leather Brow Band", info = "Barbarian Warrior Cosmetic Pack" },
            { name = "Wire Cage Half-Mask", info = "Barbaric Beauty Pack" },

            { name = "Fancy Eye Patch", info = "Cosmetic Pack: Adornments" },
            { name = "Leather Band Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "No Major Adornment", info = "Cosmetic Pack: Adornments" },
            { name = "Sightless Master Blindfold", info = "Cosmetic Pack: Adornments" },
            { name = "Third Eye Ruby", info = "Cosmetic Pack: Adornments" },
            { name = "Third Eye Topaz", info = "Cosmetic Pack: Adornments" },
            { name = "Alik'r Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Beaded Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Braided Strip Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Crimson Begonia", info = "Cosmetic Pack: Adornments" },
            { name = "Crimson Flower Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Elven Infinity Half-Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Ice-Blue Begonia", info = "Cosmetic Pack: Adornments" },
            { name = "Imperial Moonstones", info = "Cosmetic Pack: Adornments" },
            { name = "Lavender Begonia", info = "Cosmetic Pack: Adornments" },
            { name = "Metalwing Half-Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Red Diamond Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Scarab Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Scholar's Half-Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Tiara Half-Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Tooled Turquoise Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Victory Brow", info = "Cosmetic Pack: Adornments" },
            { name = "White Flower Circlet", info = "Cosmetic Pack: Adornments" },
            { name = "Woven Strip Circlet", info = "Cosmetic Pack: Adornments" },

            { name = "Covenant Lion Circlet" },
            { name = "Covenant Lion Coronet" },
            { name = "Dominion Topaz Circlet" },
            { name = "Dominion Topaz Coronet" },
            { name = "Golden Brow Wing" },
            { name = "Goldenwing Circlet" },
            { name = "Pact Dragonclaw Circlet" },
            { name = "Pact Dragonclaw Coronet" },
            { name = "Talon Veil" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Fierce Pierce Facial Rings", info = "Barbarian Warrior Cosmetic Pack" },
            { name = "Dangling Triple-Chain Earrings", info = "Barbaric Beauty Pack" },

            { name = "Blue Chin Studs", info = "Cosmetic Pack: Adornments" },
            { name = "Kris Earring", info = "Cosmetic Pack: Adornments" },
            { name = "No Minor Adornment", info = "Cosmetic Pack: Adornments" },
            { name = "Nose Pincers", info = "Cosmetic Pack: Adornments" },
            { name = "Nose Ring and Earlobe Studs", info = "Cosmetic Pack: Adornments" },
            { name = "Quarter-Moon Earrings", info = "Cosmetic Pack: Adornments" },
            { name = "Crescent Earrings", info = "Cosmetic Pack: Adornments" },
            { name = "Double Disc Earrings", info = "Cosmetic Pack: Adornments" },
            { name = "Doubling Diamond Earrings", info = "Cosmetic Pack: Adornments" },
            { name = "Ear Lobe Stinger", info = "Cosmetic Pack: Adornments" },
            { name = "Ear-Runes", info = "Cosmetic Pack: Adornments" },
            { name = "Floral Droplet", info = "Cosmetic Pack: Adornments" },
            { name = "Head and Cheekbone Studs", info = "Cosmetic Pack: Adornments" },
            { name = "Imperial Twist Earrings", info = "Cosmetic Pack: Adornments" },
            { name = "Left Double Brow Studs", info = "Cosmetic Pack: Adornments" },
            { name = "Left Nostril Rings", info = "Cosmetic Pack: Adornments" },
            { name = "Nose Ring and Head Stud", info = "Cosmetic Pack: Adornments" },
            { name = "Nostril Ring and Chin Stud", info = "Cosmetic Pack: Adornments" },
            { name = "Pearl Drop Earring", info = "Cosmetic Pack: Adornments" },
            { name = "Quicksilver Teardrop", info = "Cosmetic Pack: Adornments" },
            { name = "Scarab Earrings", info = "Cosmetic Pack: Adornments" },
            { name = "Single Crescent", info = "Cosmetic Pack: Adornments" },
            { name = "Six Brow Rings", info = "Cosmetic Pack: Adornments" },
            { name = "Three-Hoop Earrings", info = "Cosmetic Pack: Adornments" },
            { name = "Topaz Nose & Ear Rings", info = "Cosmetic Pack: Adornments" },
            { name = "Triple Diamond Earrings", info = "Cosmetic Pack: Adornments" },
            { name = "Triune Loops", info = "Cosmetic Pack: Adornments" },
            { name = "Two-Loop Earrings", info = "Cosmetic Pack: Adornments" },
            { name = "Wing-Lobes", info = "Cosmetic Pack: Adornments" },

            { name = "Sabre Cat Brow Spike" },
            { name = "Sabre Cat Ear-Fang" },
        },
    },
}
