CollectThemAllData_Store_LimitedOutfitStyles = {
    name = "Limited Outfit Styles",
    source = "Store",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Justiciar of Stendarr", info = "Justiciar of Stendarr Bundle" },
            { name = "Apocryphabound", weaponOnly = true, info = "Apocryphabound Arms Pack" },
            { name = "Deepsea Corsair", weaponOnly = true, info = "Deepsea Corsair Arms Pack" },
            { name = "Black Kiergo Brigand", armorOnly = true, info = "Black Kiergo Brigand Style Pack" },
            { name = "Passion Dancer's", weaponOnly = true, info = "Passion Dancer's Arms Pack" },
            { name = "Gloambound", weaponOnly = true, info = "Gloambound Arms Pack" },
            { name = "Chitinous", weaponOnly = true, info = "Chitinous Arms Pack" },
            { name = "Crested Viper", armorOnly = true, info = "Crested Viper Armor Pack" },
            { name = "Paravant's Letale", armorOnly = true, info = "Paravant's Letale Armor Pack" },
            { name = "Ysgramor's Ascendance", armorOnly = true, info = "Ysgramor's Ascendance Armor Pack" },
            { name = "Stalhrim Frostguard", armorOnly = true, info = "Stalhrim Armor Pack" },
            { name = "Ancient Dragon Hunter", armorOnly = true, info = "Ancient Dragon Hunter Armor Pack" },
            { name = "Ancient Dragon Hunter", weaponOnly = true, info = "Ancient Dragon Hunter Arms Pack" },
            { name = "Elder Dragon Hunter", armorOnly = true, info = "Elder Dragon Hunter Armor Pack" },
            { name = "Elder Dragon Hunter", weaponOnly = true, info = "Elder Dragon Hunter Arms Pack" },
            { name = "Namira's Hunger", weaponOnly = true, info = "Namira's Hunger Arms Pack" },
            { name = "Aldmeri Eagle Knight", armorOnly = true, info = "Aldmeri Eagle Knight Armor Pack" },
            { name = "Giantkin", armorOnly = true, info = "Giantkin Armor Pack" },
            { name = "Khenarthi's Pride", armorOnly = true, info = "Khenarthi's Pride Armor Pack" },
            { name = "Sentinel Regal Guard", armorOnly = true, info = "Sentinel Regal Guard Armor Pack" },
            { name = "Vinedusk Assassin", armorOnly = true, info = "Vinedusk Assassin Armor Pack" },
            { name = "Yaghra's Bane", armorOnly = true, info = "Yaghra's Bane Armor Pack" },
            { name = "Yaghra's Bane", weaponOnly = true, info = "Yaghra's Bane Arms Pack" },
            { name = "Aetheriusbound", weaponOnly = true, info = "Aetheriusbound Arms Pack" },
            { name = "Alliance Accord", weaponOnly = true, info = "Alliance Accord Arms Pack" },
            { name = "Anvil of Zenithar", weaponOnly = true, info = "Anvil of Zenithar Arms Pack" },
            { name = "Cruel Corelanya", weaponOnly = true, info = "Cruel Corelanya Arms Pack" },
            { name = "Guild's Eye", weaponOnly = true, info = "Guild's Eye Arms Pack" },
            { name = "Redoran Lava Shalk", weaponOnly = true, info = "Redoran Lava Shalk Arms Pack" },
            { name = "Tarnished Red Petal", weaponOnly = true, info = "Tarnished Red Petal Arms Pack" },
            { name = "Truth and Logic", weaponOnly = true, info = "Truth and Logic Arms Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
