CollectThemAllData_Store_PermanentHouses = {
    name = "Permanent Houses",
    source = "Store",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {
            { name = "Bismuth Steam Baths", no = 117 },
            { name = "Merryvine Estate", no = 110 },
            { name = "Emissary's Enclave", no = 101 },
            -- { name = "UNRELEASED", no = 97 },
            { name = "Water's Edge", no = 88 },
            -- { name = "UNRELEASED", no = 84 },
            { name = "Stillwaters Retreat", no = 80 },
            { name = "Proudspire Manor", no = 78 },
            { name = "Lucky Cat Landing", no = 73 },
            { name = "Moon-Sugar Meadow", no = 71 },
            -- { name = "UNRELEASED", no = 67 },
            { name = "Alinor Crest Townhouse", no = 59 },
            { name = "The Orbservatory Prior", no = 55 },
            -- { name = "UNRELEASED", no = 53 },
            -- { name = "UNRELEASED", no = 52 },
            -- { name = "UNRELEASED", no = 51 },
            -- { name = "UNRELEASED", no = 50 },
            { name = "Hakkvild's High Hall", no = 48 },
            { name = "Coldharbour Surreal Estate", no = 47 },
            { name = "Ald Velothi Harbor House", no = 44 },
            { name = "Amaya Lake Lodge", no = 43 },
            { name = "Earthtear Cavern", no = 41 },
            { name = "Ebonheart Chateau", no = 39 },
            { name = "Daggerfall Overlook", no = 38 },
            { name = "Serenity Falls Estate", no = 37 },
            { name = "Hunding's Palatial Hall", no = 36 },
            { name = "House of the Silent Magnifico", no = 35 },
            { name = "Twin Arches", no = 34 },
            { name = "Forsaken Stronghold", no = 33 },
            { name = "Mournoth Keep", no = 32 },
            { name = "Hammerdeath Bungalow", no = 31 },
            { name = "Old Mistveil Manor", no = 30 },
            { name = "Grymharth's Woe", no = 29 },
            { name = "Autumn's-Gate", no = 28 },
            { name = "Strident Springs Demesne", no = 27 },
            { name = "Domus Phrasticus", no = 26 },
            { name = "Cyrodilic Jungle House", no = 25 },
            { name = "Dawnshadow", no = 24 },
            { name = "Sleek Creek House", no = 23 },
            { name = "Moonmirth House", no = 22 },
            { name = "Quondam Indorilia", no = 21 },
            { name = "Velothi Reverie", no = 20 },
            { name = "Kragenhome", no = 19 },
            { name = "Gardner House", no = 18 },
            { name = "Ravenhurst", no = 17 },
            { name = "Captain Margaux's Place", no = 16 },
            { name = "The Gorinir Estate", no = 15 },
            { name = "Bouldertree Refuge", no = 14 },
            { name = "Snugpod", no = 13 },
            { name = "Stay-Moist Mansion", no = 12 },
            { name = "The Ample Domicile", no = 11 },
            { name = "Humblemud", no = 10 },
            { name = "Mathiisen Manor", no = 9 },
            { name = "Cliffshade", no = 8 },
            { name = "Black Vine Villa", no = 7 },
            { name = "Flaming Nix Deluxe Garret", no = 6 },
            { name = "Sisters of the Sands Apartment", no = 5 },
            { name = "Barbed Hook Private Room", no = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
