CollectThemAllData_Store_LimitedOffers = {
    name = "Limited Offers",
    source = "Store",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {
            { name = "Chronometer of the Tribunal" },
            { name = "Sea Witch Weather Totem" },

            -- Housguests
            { name = "Ashur" },
            { name = "Adusa-daro" },
            { name = "Arox the Mutilator" },
            { name = "Captain Isara Davaux" },
            { name = "Caska" },
            { name = "Clan Mother Tadali" },
            { name = "Crafty Lerisa" },
            { name = "Dhulef" },
            { name = "Druid Ryvana" },
            { name = "Duchess Elea Dufort" },
            { name = "Elsbytte" },
            { name = "Erilthel" },
            { name = "Fennorian" },
            { name = "Hezehk" },
            { name = "Heiruna" },
            { name = "Hildegard" },
            { name = "Hroltar the Boaster" },
            { name = "Imperial Legionary Larina" },
            { name = "J'baanluk" },
            { name = "Jakarn" },
            { name = "Keldora" },
            { name = "Kor" },
            { name = "M'aiq the Liar" },
            { name = "Makes-Many-Soups" },
            { name = "Mel Adrys" },
            { name = "Narboth" },
            { name = "Relic-Apprentice Marafar" },
            { name = "Rigurt the Brash" },
            { name = "Scruut" },
            { name = "Sereyne" },
            { name = "Sister Gellenna" },
            { name = "Skordo the Knife" },
            { name = "Squire Caw" },
            { name = "Stefan Mornard" },
            { name = "Stibbons" },
            { name = "Za'ji" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {
            { name = "Pontius Remus, Lupine Scavenger" },
            { name = "Voko, Carnaval Weapondancer" },
            { name = "Eri, Barking Banker" },
            { name = "Siluruz, Realm Craftsmaster" },
            { name = "Tzozabrar, Dwarven Deconstructor" },
            { name = "Terilorne, Dibellan Freetrader" },
            { name = "Xyn, Planar Purveyor" },
            { name = "Celia Tyde, Lost Fleet Bursar" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Alkosh's Timely Recall", gems = 400 },
            { name = "Ashen Runegathering" },
            { name = "Coldfire Recall", gems = 400 },
            { name = "Dwarven Sphere Chop" },
            { name = "Grovetender's Sweep" },
            { name = "Jaws of Oblivion Recall" },
            { name = "Lunar Oregathering" },
            { name = "Malacath's Harvest" },
            { name = "Personal Plant Thief" },
            { name = "Sanguine Runegathering" },
            { name = "Stonelore Split" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {
            { name = "Overload, Lightning Yellow" },
            { name = "Boneyard, Fiery Torment" },
            { name = "Circle of Protection, Julianos" },
            { name = "Blessing of Protection, Verdant Green" },
            { name = "Critical Charge, Winter's Gale", info = "New Life Styles: Winter pack" },
            { name = "Meteor, Winter's Blast", info = "New Life Styles: Winter pack" },
            { name = "Volley, Winterfall", info = "New Life Styles: Winter pack" },
            { name = "Dawnbreaker, Vibrant Yellow" },
            { name = "Dive, Nocturnal Crow", info = "Nocturnal Styles: Night's Crows pack" },
            { name = "Dragon Leap, Nocturnal", info = "Nocturnal Styles: Night's Crows pack" },
            { name = "Swarm, Murder of Crows", info = "Nocturnal Styles: Night's Crows pack" },
            { name = "Fatecarver, Aetherius" },
            { name = "Feral Guardian, Snow Bear" },
            { name = "Low Slash, Ruby Red" },
            { name = "Magelight, Passion Blossom" },
            { name = "Reverse Slash, Namira's Hunger" },
            { name = "Snipe, Sanguine's Rose" },
            { name = "Summon Winged Twilight, Warrior" },
            { name = "The Unblinking Eye, Hollowjack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Azure Blight Spriggan" },
            { name = "Bloodroot Spriggan" },
            { name = "Dread Anka-Ra" },
            { name = "Pumpkin Spectre" },
            { name = "Reaper's End Scarecrow Spectre" },
            { name = "Scarecrow Spectre" },
            { name = "Shadowsilk Goblin" },
            { name = "Sylvan Spriggan" },
            { name = "Tidal Wave Incarnate" },
            { name = "Vampiric Soulrazer Knight" },
            { name = "Werewolf Lord" },
            { name = "Winterborn Spriggan" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {
            { name = "Blacksmith" },
            { name = "Brassy Assassin" },
            { name = "Drunk" },
            { name = "Jester" },
            { name = "Minstrel" },
            { name = "Scholar" },
            { name = "Swashbuckler" },
            { name = "Treasure Hunter" },
            { name = "Zombie" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Southern Leviathan" },
            { name = "Ayleid Ruins Wildgrowth" },
            { name = "Azure Imp Epidermis" },
            { name = "Cold-Flame Epidermis" },
            { name = "Culanda-Born Skin" },
            { name = "Ebony Epidermis" },
            { name = "Kyne's Fury" },
            { name = "Magnifico's Majesty" },
            { name = "Marshmist Palescale" },
            { name = "Meridian Purified" },
            { name = "Mind-Shriven" },
            { name = "Scales of the Celestial Serpent" },
            { name = "Shivering Isles Anointment" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Ne Quin-Al Wrap" },
            { name = "Anchorwright Raiment" },
            { name = "Chef" },
            { name = "Clockwork Tinker" },
            { name = "Covenant Scout" },
            { name = "Day of Release Roisterer" },
            { name = "Doeskin-and-Chamois Woods Wear" },
            { name = "Drifting Sand Tunic and Sash" },
            { name = "Egg-Sister Bias-Cut Casual Wear" },
            { name = "Fashion Witch Ensemble" },
            { name = "Frostbane Dragon Priest" },
            { name = "Greenspeaker's Garb" },
            { name = "Grim Harvester" },
            { name = "Grisly Mummy Wrap" },
            { name = "High Rock Pioneer Outfit" },
            { name = "Jakarn's Ensemble" },
            { name = "Jarl's Deluxe Moot Regalia", notice = "Wiki mentioned, that this should be also in Akatosh vs. Alduin Crown Crates, but there is no evidence" },
            { name = "Jarl's Justice Formal Frock" },
            { name = "Liespinner's Vestments" },
            { name = "Mages Guildmaster Garb" },
            { name = "Magnifica's Sundas Wear" },
            { name = "Mercymother's Attire" },
            { name = "Negligee of the Coven Shrike" },
            { name = "New Moon Dragon Cult Garb" },
            { name = "Night Mother's Evangelist" },
            { name = "Pact Mother Elite Ensemble" },
            { name = "Pellitine Tea-Fete Gown" },
            { name = "Rimmen Fountain-Side Loungewear" },
            { name = "Sentinel Vest and Salvar" },
            { name = "Shrike's Nocturnal Frock" },
            { name = "Sisei Flowering Dress" },
            { name = "Solitude Stevedore's Jerkin" },
            { name = "Star-Made Wolfshead" },
            { name = "Subterrane Excavator" },
            { name = "Treethane Ceremonial Dress" },
            { name = "Vinedusk Vigilant" },
            { name = "Wandering Brewer" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Floral Skull Fascinator" },
            { name = "Modest Mourning Hat" },
            { name = "New Life Festival Cap" },
            { name = "New Life Monk's Cap" },
            { name = "Plumed Mourning Hat" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Druidic Knotwork Body Tattoos" },
            { name = "Mirrorweb of Memories Body Art" },
            { name = "Vortex Body Veil" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Anequine Oasis Eyes" },
            { name = "Crimson Trickster Face Paint" },
            { name = "Floral Skull Face Tattoo" },
            { name = "Mirrorweb of Memories Face Art" },
            { name = "Spoked Skull Face Tattoo" },
            { name = "Verdant Skull Face Tattoo" },
            { name = "Warrior-Poet Skull Tattoo" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Adorable Assassin" },
            { name = "Long Foregathered Mane" },
            { name = "Multi-Spined Skull Crest" },
            { name = "Short Mussed Wave" },
            { name = "The Casual Rascal" },
            { name = "The Heroic Poet" },
            { name = "The Standing Wave" },
            { name = "Wavy Triple Braided Updo" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {
            { name = "Brigand's Beard" },
            { name = "Dragonfly Wing Lashes" },
            { name = "Long Patriarch Beard" },
            { name = "Sailor's Squid Goatee" },
            { name = "Subtle Dark Lashes" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Horned Brow Plate" },
            { name = "Prize-Hunter's Patch" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
