CollectThemAllData_Store_PermanentBundles = {
    name = "Permanent Bundles",
    source = "Store",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE] = {
            { name = "Any Race, Any Alliance", info = "Any Race, Any Alliance Bundle" },
            { name = "Imperial Race and Outfit Style", info = "Digital Imperial Edition Upgrade" },
            { name = "Swordthane Outfit Style", info = "Greymoor Collector's Pack" },
            { name = "Ascendant Outfit Style", info = "High Isle Collector's Pack" },
            { name = "Morag Tong Outfit Style", info = "Morrowind Collector's Pack" },
            { name = "Knowledge Eater Outfit Style", info = "Necrom Deluxe Pack" },
            { name = "Divine Prosecution Outfit Style", info = "Summerset Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Alliance War Horse", info = "Any Race, Any Alliance Bundle" },
            { name = "White Mane Horse", info = "Starter Pack, Adept" },
            { name = "Whiterun Windsteed", info = "Steadfast Stablemaster Bundle" },
            { name = "Battlefield Nightmare Senche", info = "Blackwood Collector's Pack" },
            { name = "Imperial Horse", info = "Digital Imperial Edition Upgrade" },
            { name = "Senche-Raht", info = "Elsweyr Collector's Pack" },
            { name = "West Weald Tharriker", info = "Gold Road Deluxe Pack" },
            { name = "Crypt Warden Death Hound", info = "Greymoor Collector's Pack" },
            { name = "Amenos Ornaug", info = "High Isle Collector's Pack" },
            { name = "Dwarven War Horse", info = "Morrowind Collector's Pack" },
            { name = "Hermitage Servitor", info = "Necrom Deluxe Pack" },
            { name = "Bloodshadow Wraith Steed", info = "Summerset Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Alliance War Dog", info = "Any Race, Any Alliance Bundle" },
            { name = "Striped Senche-Panther Cub", info = "Starter Pack" },
            { name = "Deadlands Wamasu", info = "Blackwood Collector's Pack" },
            { name = "Jewel-Feathered Sep Adder", info = "Blackwood Collector's Pack" },
            { name = "Nibenay Mudcrab", info = "Digital Imperial Edition Upgrade" },
            { name = "Ashen Scar Jerboa", info = "Elsweyr Collector's Pack" },
            { name = "Blue Dragon Imp", info = "Elsweyr Collector's Pack" },
            { name = "Eyebright Raven", info = "Gold Road Deluxe Pack" },
            { name = "Skingrad Guard Mastiff", info = "Gold Road Deluxe Pack" },
            { name = "Death Hound", info = "Greymoor Collector's Pack" },
            { name = "Sacrificial Pocket Mammoth", info = "Greymoor Collector's Pack" },
            { name = "Balfiera Senche Cub", info = "High Isle Collector's Pack" },
            { name = "Knights of the Flame Pup", info = "High Isle Collector's Pack" },
            { name = "Dwarven Spider", info = "Morrowind Collector's Pack" },
            { name = "Dwarven War Dog", info = "Morrowind Collector's Pack" },
            { name = "Apocryphal Bookwyrm", info = "Necrom Deluxe Pack" },
            { name = "Cipher's Eye Pocket Watcher", info = "Necrom Deluxe Pack" },
            { name = "Fledgling Gryphon", info = "Summerset Collector's Pack" },
            { name = "Pocket Salamander", info = "Summerset Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Temperamental Grimoire", info = "Blackwood Collector's Pack" },
            { name = "Archaic Lore Tablets", info = "Elsweyr Collector's Pack" },
            { name = "Ulfsild's Tome of Legends", info = "Gold Road Deluxe Pack" },
            { name = "Orb of Magnus", info = "Greymoor Collector's Pack" },
            { name = "Hoard of the Schemers", info = "High Isle Collector's Pack" },
            { name = "Dark Lady's Headrest", info = "Necrom Deluxe Pack" },
            { name = "Psijic Scrying Talisman", info = "Summerset Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Offer Weapon", info = "Blackwood Collector's Pack" },
            { name = "Cat Contemplation", info = "Elsweyr Collector's Pack" },
            { name = "Feline Hygiene", info = "Elsweyr Collector's Pack" },
            { name = "Pedlar Beckoning", info = "Elsweyr Collector's Pack" },
            { name = "Make Cheese", info = "Gold Road Deluxe Pack" },
            { name = "Sommelier Swirl", info = "Gold Road Deluxe Pack" },
            { name = "Stomp Grapes", info = "Gold Road Deluxe Pack" },
            { name = "Arrow to the Knee", info = "Greymoor Collector's Pack" },
            { name = "Missing Sweetroll", info = "Greymoor Collector's Pack" },
            { name = "Play Ragnar the Red", info = "Greymoor Collector's Pack" },
            { name = "Air the Heir", info = "High Isle Collector's Pack" },
            { name = "Elite Seat", info = "High Isle Collector's Pack" },
            { name = "Wait the Great", info = "High Isle Collector's Pack" },
            { name = "Kiss This", info = "Morrowind Collector's Pack" },
            { name = "Teatime", info = "Morrowind Collector's Pack" },
            { name = "Belly Laugh", info = "Morrowind Collector's Pack" },
            { name = "Go Quietly", info = "Morrowind Collector's Pack" },
            { name = "Leaning Scholar", info = "Necrom Deluxe Pack" },
            { name = "Sitting Scholar", info = "Necrom Deluxe Pack" },
            { name = "Standing Scholar", info = "Necrom Deluxe Pack" },
            { name = "Happy Face", info = "Summerset Collector's Pack" },
            { name = "Sad Face", info = "Summerset Collector's Pack" },
            { name = "Ta-Dah!", info = "Summerset Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Deadlands Gladiator", info = "Blackwood Collector's Pack" },
            { name = "Dremora Kynreeve", info = "Blackwood Collector's Pack", armorOnly = true },
            { name = "Imperial", info = "Digital Imperial Edition Upgrade" },
            { name = "Dragon Bone", info = "Elsweyr Collector's Pack" },
            { name = "Skingrad Vedette", info = "Gold Road Deluxe Pack", armorOnly = true },
            { name = "Swordthane", info = "Greymoor Collector's Pack" },
            { name = "Ascendant Knight", info = "High Isle Collector's Pack", armorOnly = true },
            { name = "Morag Tong", info = "Morrowind Collector's Pack" },
            { name = "Knowledge Eater", info = "Necrom Deluxe Pack", armorOnly = true },
            { name = "Divine Prosecution", info = "Summerset Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {
            { name = "Feral Guardian, Slate Gray", info = "Morrowind Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Mind-Shriven", info = "Imperial City Collector's Bundle" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Alliance Rider Outfit", info = "Any Race, Any Alliance Bundle" },
            { name = "Crafty Lerisa's Thief Outfit", info = "Starter Pack, Adept" },
            { name = "Knight of the Flame", info = "Starter Pack, Adept" },
            { name = "Mages Guild Research Robes", info = "Starter Pack, Adept" },
            { name = "Noble Clan-Chief", info = "Elsweyr Collector's Pack" },
            { name = "Strid River Fisherfolk", info = "Gold Road Deluxe Pack" },
            { name = "Jarl Finery", info = "Greymoor Collector's Pack" },
            { name = "Abecean Privateer's Apparel", info = "High Isle Collector's Pack" },
            { name = "Austere Warden Outfit", info = "Morrowind Collector's Pack" },
            { name = "Sadrith Mora Formal Attire", info = "Necrom Deluxe Pack" },
            { name = "Court of Bedlam", info = "Summerset Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Alliance Rider Hood", info = "Any Race, Any Alliance Bundle" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Jarl Crown", info = "Greymoor Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
