-- Auto-generated by ExtractChainData.ps1 -- do not edit by hand
-- Regenerate: run _Tools/ExtractChainData.ps1
--
-- SPT.chainData[skillPointQuestId] = ordered array, chain starter first.
-- Each step: { id=questId, x=localX, y=localY, map="zone/mapKey" }
-- x/y = -1 means no coordinate data available (skip for waypoint).
-- Quest names are fetched at runtime via GetQuestName(id).
if SPT == nil then SPT = {} end
SPT.chainData = {
  [465] = {
    { id = 4902, x = 0.8387507796, y = 0.5824304223, map = "rivenspire/shornhelm_base_0" },
    { id = 4903, x = 0.5944975615, y = 0.2089016289, map = "rivenspire/shornhelm_base_0" },
    { id = 465, x = 0.2929956317, y = 0.4519065917, map = "rivenspire/rivenspire_base_0" }, -- skill point
  },
  [467] = {
    { id = 736, x = 0.2965085804, y = 0.3043400049, map = "stormhaven/stormhaven_base_0" },
    { id = 737, x = 0.2968885601, y = 0.3042800128, map = "stormhaven/stormhaven_base_0" },
    { id = 467, x = 0.3268457055, y = 0.3003028631, map = "stormhaven/stormhaven_base_0" }, -- skill point
  },
  [575] = {
    { id = 1536, x = 0.4302542806, y = 0.3712314367, map = "stormhaven/stormhaven_base_0" },
    { id = 1529, x = 0.4314028621, y = 0.3711085618, map = "stormhaven/stormhaven_base_0" },
    { id = 1541, x = 0.4476428628, y = 0.3945371509, map = "stormhaven/stormhaven_base_0" },
    { id = 499, x = 0.4506942928, y = 0.4173657000, map = "stormhaven/stormhaven_base_0" },
    { id = 2495, x = 0.3173314333, y = 0.6117371321, map = "stormhaven/stormhaven_base_0" },
    { id = 2496, x = 0.2956714332, y = 0.5777314305, map = "stormhaven/stormhaven_base_0" },
    { id = 2497, x = 0.2956885695, y = 0.5777999759, map = "stormhaven/stormhaven_base_0" },
    { id = 1633, x = 0.3101085722, y = 0.6135828495, map = "stormhaven/stormhaven_base_0" },
    { id = 1639, x = 0.4505171478, y = 0.4174457192, map = "stormhaven/stormhaven_base_0" },
    { id = 1437, x = 0.7427942753, y = 0.4850771427, map = "stormhaven/stormhaven_base_0" },
    { id = 1346, x = 0.7517200112, y = 0.4302914143, map = "stormhaven/stormhaven_base_0" },
    { id = 3637, x = 0.7415885925, y = 0.4839028716, map = "stormhaven/stormhaven_base_0" },
    { id = 521, x = 0.7425228357, y = 0.4836885631, map = "stormhaven/stormhaven_base_0" },
    { id = 575, x = 0.4292431176, y = 0.4634388983, map = "stormhaven/wayrest_base_0" }, -- skill point
  },
  [1633] = {
    { id = 1536, x = 0.4302542806, y = 0.3712314367, map = "stormhaven/stormhaven_base_0" },
    { id = 1529, x = 0.4314028621, y = 0.3711085618, map = "stormhaven/stormhaven_base_0" },
    { id = 1541, x = 0.4476428628, y = 0.3945371509, map = "stormhaven/stormhaven_base_0" },
    { id = 499, x = 0.4506942928, y = 0.4173657000, map = "stormhaven/stormhaven_base_0" },
    { id = 2495, x = 0.3173314333, y = 0.6117371321, map = "stormhaven/stormhaven_base_0" },
    { id = 2496, x = 0.2956714332, y = 0.5777314305, map = "stormhaven/stormhaven_base_0" },
    { id = 2497, x = 0.2956885695, y = 0.5777999759, map = "stormhaven/stormhaven_base_0" },
    { id = 1633, x = 0.3101085722, y = 0.6135828495, map = "stormhaven/stormhaven_base_0" }, -- skill point
  },
  [2192] = {
    { id = 2130, x = 0.1769811958, y = 0.4559027851, map = "alikr/sentinel_base_0" },
    { id = 2146, x = 0.2881000000, y = 0.4879000000, map = "alikr/alikr_base_0" },
    { id = 2184, x = 0.3982300162, y = 0.5759721398, map = "alikr/alikr_base_0" },
    { id = 2192, x = 0.4025665820, y = 0.5304182172, map = "alikr/alikr_base_0" }, -- skill point
  },
  [2222] = {
    { id = 2130, x = 0.1769811958, y = 0.4559027851, map = "alikr/sentinel_base_0" },
    { id = 2146, x = 0.2881000000, y = 0.4879000000, map = "alikr/alikr_base_0" },
    { id = 2184, x = 0.3982300162, y = 0.5759721398, map = "alikr/alikr_base_0" },
    { id = 2192, x = 0.4025665820, y = 0.5304182172, map = "alikr/alikr_base_0" },
    { id = 2222, x = 0.6238212585, y = 0.3392581642, map = "alikr/alikr_base_0" }, -- skill point
  },
  [2997] = {
    { id = 2130, x = 0.1769811958, y = 0.4559027851, map = "alikr/sentinel_base_0" },
    { id = 2146, x = 0.2881000000, y = 0.4879000000, map = "alikr/alikr_base_0" },
    { id = 2184, x = 0.3982300162, y = 0.5759721398, map = "alikr/alikr_base_0" },
    { id = 2192, x = 0.4025665820, y = 0.5304182172, map = "alikr/alikr_base_0" },
    { id = 2222, x = 0.6238212585, y = 0.3392581642, map = "alikr/alikr_base_0" },
    { id = 2997, x = 0.8404331803, y = 0.3406372964, map = "alikr/alikr_base_0" }, -- skill point
  },
  [3006] = {
    { id = 3000, x = 0.5982427001, y = 0.4150178730, map = "glenumbra/daggerfall_base_0" },
    { id = 3006, x = 0.4370212257, y = 0.4602361917, map = "glenumbra/daggerfall_base_0" }, -- skill point
  },
  [3235] = {
    { id = 3191, x = 0.3624068201, y = 0.5739597082, map = "glenumbra/glenumbra_base_0" },
    { id = 3235, x = 0.3371922076, y = 0.5263868570, map = "glenumbra/glenumbra_base_0" }, -- skill point
  },
  [3267] = {
    { id = 3064, x = 0.5633128285, y = 0.3990013301, map = "glenumbra/glenumbra_base_0" },
    { id = 3189, x = 0.5339671373, y = 0.3621373475, map = "glenumbra/glenumbra_base_0" },
    { id = 3267, x = 0.5216037035, y = 0.3334060907, map = "glenumbra/glenumbra_base_0" }, -- skill point
  },
  [3379] = {
    { id = 3082, x = 0.6219017506, y = 0.2614970803, map = "glenumbra/glenumbra_base_0" },
    { id = 3277, x = 0.5931327343, y = 0.2333398014, map = "glenumbra/glenumbra_base_0" },
    { id = 3338, x = 0.6231332421, y = 0.2605727911, map = "glenumbra/glenumbra_base_0" },
    { id = 3379, x = 0.4041858912, y = 0.3765195608, map = "glenumbra/cathbedraud_base_0" }, -- skill point
  },
  [3634] = {
    { id = 3585, x = 0.8794000000, y = 0.3089000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3587, x = 0.8782000000, y = 0.3099000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3588, x = 0.8105000000, y = 0.3223000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3615, x = 0.7455440164, y = 0.5789119601, map = "stonefalls/stonefalls_base_0" },
    { id = 3616, x = 0.7739904523, y = 0.6442596912, map = "stonefalls/stonefalls_base_0" },
    { id = 3734, x = 0.7266657352, y = 0.5496606827, map = "stonefalls/stonefalls_base_0" },
    { id = 3735, x = 0.7338166237, y = 0.4100196362, map = "stonefalls/stonefalls_base_0" },
    { id = 3584, x = 0.4754066169, y = 0.5449719429, map = "stonefalls/stonefalls_base_0" },
    { id = 3632, x = 0.2396102101, y = 0.2609001696, map = "stonefalls/stonefalls_base_0" },
    { id = 3633, x = 0.1849000000, y = 0.2696000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3634, x = 0.1816404909, y = 0.2482501417, map = "stonefalls/stonefalls_base_0" }, -- skill point
  },
  [3735] = {
    { id = 3585, x = 0.8794000000, y = 0.3089000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3587, x = 0.8782000000, y = 0.3099000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3588, x = 0.8105000000, y = 0.3223000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3615, x = 0.7455440164, y = 0.5789119601, map = "stonefalls/stonefalls_base_0" },
    { id = 3616, x = 0.7739904523, y = 0.6442596912, map = "stonefalls/stonefalls_base_0" },
    { id = 3734, x = 0.7266657352, y = 0.5496606827, map = "stonefalls/stonefalls_base_0" },
    { id = 3735, x = 0.7338166237, y = 0.4100196362, map = "stonefalls/stonefalls_base_0" }, -- skill point
  },
  [3797] = {
    { id = 3673, x = 0.2819134593, y = 0.4541570842, map = "deshaan/deshaan_base_0" },
    { id = 3705, x = 0.4534000000, y = 0.3558000000, map = "deshaan/deshaan_base_0" },
    { id = 3797, x = 0.3201000000, y = 0.4196000000, map = "deshaan/deshaan_base_0" }, -- skill point
  },
  [3817] = {
    { id = 4453, x = 0.4082000000, y = 0.4927000000, map = "deshaan/deshaan_base_0" },
    { id = 4459, x = 0.4188000000, y = 0.5980000000, map = "deshaan/deshaan_base_0" },
    { id = 3817, x = 0.4243000000, y = 0.5558000000, map = "deshaan/deshaan_base_0" }, -- skill point
  },
  [3831] = {
    { id = 3810, x = 0.5340982676, y = 0.7787545323, map = "deshaan/eidolonshollow2_base_0" },
    { id = 3831, x = 0.5049196482, y = 0.0884920284, map = "deshaan/eidolonshollow2_base_0" }, -- skill point
  },
  [3868] = {
    { id = 3585, x = 0.8794000000, y = 0.3089000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3587, x = 0.8782000000, y = 0.3099000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3588, x = 0.8105000000, y = 0.3223000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3615, x = 0.7455440164, y = 0.5789119601, map = "stonefalls/stonefalls_base_0" },
    { id = 3616, x = 0.7739904523, y = 0.6442596912, map = "stonefalls/stonefalls_base_0" },
    { id = 3734, x = 0.7266657352, y = 0.5496606827, map = "stonefalls/stonefalls_base_0" },
    { id = 3735, x = 0.7338166237, y = 0.4100196362, map = "stonefalls/stonefalls_base_0" },
    { id = 3584, x = 0.4754066169, y = 0.5449719429, map = "stonefalls/stonefalls_base_0" },
    { id = 3632, x = 0.2396102101, y = 0.2609001696, map = "stonefalls/stonefalls_base_0" },
    { id = 3633, x = 0.1849000000, y = 0.2696000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3634, x = 0.1816404909, y = 0.2482501417, map = "stonefalls/stonefalls_base_0" },
    { id = 3695, x = 0.4732958674, y = 0.2219322026, map = "stonefalls/kragenmoor_base_0" },
    { id = 3696, x = 0.4391961992, y = 0.4271492064, map = "stonefalls/kragenmoor_base_0" },
    { id = 3826, x = 0.3641615212, y = 0.6132585406, map = "stonefalls/stonefalls_base_0" },
    { id = 3837, x = 0.3764000000, y = 0.6447000000, map = "stonefalls/stonefalls_base_0" },
    { id = 3868, x = 0.3890000000, y = 0.6551000000, map = "stonefalls/stonefalls_base_0" }, -- skill point
  },
  [3910] = {
    { id = 3686, x = 0.4672333300, y = 0.2861999869, map = "shadowfen/shadowfen_base_0" },
    { id = 3687, x = 0.4459000000, y = 0.2690000000, map = "shadowfen/shadowfen_base_0" },
    { id = 4587, x = 0.6186733246, y = 0.3773533404, map = "shadowfen/shadowfen_base_0" },
    { id = 4590, x = 0.6669200063, y = 0.4088366628, map = "shadowfen/shadowfen_base_0" },
    { id = 4606, x = 0.5219699740, y = 0.5844333172, map = "shadowfen/shadowfen_base_0" },
    { id = 3909, x = 0.2691766620, y = 0.7117833495, map = "shadowfen/shadowfen_base_0" },
    { id = 3910, x = 0.2311966717, y = 0.6768266558, map = "shadowfen/shadowfen_base_0" }, -- skill point
  },
  [3968] = {
    { id = 3928, x = 0.4513125122, y = 0.2986674905, map = "therift/therift_base_0" },
    { id = 3957, x = 0.4362375140, y = 0.3086675107, map = "therift/therift_base_0" },
    { id = 3968, x = 0.4311524928, y = 0.3058249950, map = "therift/therift_base_0" }, -- skill point
  },
  [4061] = {
    { id = 4058, x = 0.8460990191, y = 0.3566954136, map = "eastmarch/windhelm_base_0" },
    { id = 4059, x = 0.4984000000, y = 0.2671000000, map = "eastmarch/eastmarch_base_0" },
    { id = 4060, x = 0.4971000000, y = 0.2672000000, map = "eastmarch/eastmarch_base_0" },
    { id = 4061, x = 0.4961000000, y = 0.2663000000, map = "eastmarch/eastmarch_base_0" }, -- skill point
  },
  [4115] = {
    { id = 4150, x = 0.7917674184, y = 0.0900465250, map = "eastmarch/fortamol_base_0" },
    { id = 4158, x = 0.5054755211, y = 0.3418192267, map = "eastmarch/fortamol_base_0" },
    { id = 4166, x = 0.6963164806, y = 0.4273146689, map = "eastmarch/fortamol_base_0" },
    { id = 4203, x = 0.4301387668, y = 0.7563948631, map = "eastmarch/fortamol_base_0" },
    { id = 4115, x = 0.4358150065, y = 0.6370825171, map = "eastmarch/eastmarch_base_0" }, -- skill point
  },
  [4117] = {
    { id = 4150, x = 0.7917674184, y = 0.0900465250, map = "eastmarch/fortamol_base_0" },
    { id = 4158, x = 0.5054755211, y = 0.3418192267, map = "eastmarch/fortamol_base_0" },
    { id = 4166, x = 0.6963164806, y = 0.4273146689, map = "eastmarch/fortamol_base_0" },
    { id = 4203, x = 0.4301387668, y = 0.7563948631, map = "eastmarch/fortamol_base_0" },
    { id = 4115, x = 0.4358150065, y = 0.6370825171, map = "eastmarch/eastmarch_base_0" },
    { id = 4123, x = 0.4571425021, y = 0.6738899946, map = "eastmarch/eastmarch_base_0" },
    { id = 4069, x = 0.6621375084, y = 0.6047199965, map = "eastmarch/eastmarch_base_0" },
    { id = 4078, x = 0.6814075112, y = 0.5779150128, map = "eastmarch/eastmarch_base_0" },
    { id = 4116, x = 0.6809949875, y = 0.5156224966, map = "eastmarch/eastmarch_base_0" },
    { id = 4117, x = 0.8399775028, y = 0.4923824966, map = "eastmarch/eastmarch_base_0" }, -- skill point
  },
  [4139] = {
    { id = 3978, x = 0.1136000007, y = 0.2668874860, map = "therift/therift_base_0" },
    { id = 4139, x = 0.3922350109, y = 0.5099974871, map = "therift/therift_base_0" }, -- skill point
  },
  [4143] = {
    { id = 4193, x = 0.3889435232, y = 0.8011964560, map = "malabaltor/velynharbor_base_0" },
    { id = 4194, x = 0.6894191504, y = 0.5023376942, map = "malabaltor/velynharbor_base_0" },
    { id = 4458, x = 0.5415594578, y = 0.2301567048, map = "malabaltor/velynharbor_base_0" },
    { id = 4452, x = 0.4037620723, y = 0.5564343333, map = "malabaltor/malabaltor_base_0" },
    { id = 4456, x = 0.4271174073, y = 0.4887737334, map = "malabaltor/malabaltor_base_0" },
    { id = 4124, x = 0.6782412529, y = 0.7914747000, map = "malabaltor/malabaltor_base_0" },
    { id = 4477, x = 0.7083985209, y = 0.6743085384, map = "malabaltor/malabaltor_base_0" },
    { id = 4143, x = 0.7386516333, y = 0.3578552902, map = "malabaltor/malabaltor_base_0" }, -- skill point
  },
  [4188] = {
    { id = 4186, x = 0.8003774881, y = 0.6777650118, map = "therift/therift_base_0" },
    { id = 4188, x = 0.7848374844, y = 0.7471399903, map = "therift/therift_base_0" }, -- skill point
  },
  [4222] = {
    { id = 4255, x = 0.6293000000, y = 0.9531000000, map = "auridon/auridon_base_0" },
    { id = 4256, x = 0.6419000000, y = 0.9009000000, map = "auridon/auridon_base_0" },
    { id = 4217, x = 0.4330000000, y = 0.7420000000, map = "auridon/auridon_base_0" },
    { id = 4222, x = 0.4374392033, y = 0.7090147138, map = "auridon/auridon_base_0" }, -- skill point
  },
  [4261] = {
    { id = 4255, x = 0.6293000000, y = 0.9531000000, map = "auridon/auridon_base_0" },
    { id = 4256, x = 0.6419000000, y = 0.9009000000, map = "auridon/auridon_base_0" },
    { id = 4330, x = 0.6364000000, y = 0.5031000000, map = "auridon/auridon_base_0" },
    { id = 4331, x = 0.7892147899, y = 0.5109017491, map = "auridon/auridon_base_0" },
    { id = 4345, x = 0.8216311932, y = 0.5177026391, map = "auridon/auridon_base_0" },
    { id = 4260, x = 0.2444000000, y = 0.2421000000, map = "auridon/auridon_base_0" },
    { id = 4261, x = 0.5056541562, y = 0.4919193685, map = "auridon/firsthold_base_0" }, -- skill point
  },
  [4345] = {
    { id = 4255, x = 0.6293000000, y = 0.9531000000, map = "auridon/auridon_base_0" },
    { id = 4256, x = 0.6419000000, y = 0.9009000000, map = "auridon/auridon_base_0" },
    { id = 4330, x = 0.6364000000, y = 0.5031000000, map = "auridon/auridon_base_0" },
    { id = 4331, x = 0.7892147899, y = 0.5109017491, map = "auridon/auridon_base_0" },
    { id = 4345, x = 0.8216311932, y = 0.5177026391, map = "auridon/auridon_base_0" }, -- skill point
  },
  [4386] = {
    { id = 4385, x = 0.4370000000, y = 0.7450000000, map = "grahtwood/reliquaryofstars_base_0" },
    { id = 4386, x = 0.4299880266, y = 0.7344030142, map = "grahtwood/reliquaryofstars_base_0" }, -- skill point
  },
  [4452] = {
    { id = 4193, x = 0.3889435232, y = 0.8011964560, map = "malabaltor/velynharbor_base_0" },
    { id = 4194, x = 0.6894191504, y = 0.5023376942, map = "malabaltor/velynharbor_base_0" },
    { id = 4458, x = 0.5415594578, y = 0.2301567048, map = "malabaltor/velynharbor_base_0" },
    { id = 4452, x = 0.4037620723, y = 0.5564343333, map = "malabaltor/malabaltor_base_0" }, -- skill point
  },
  [4474] = {
    { id = 4831, x = -1, y = -1, map = "" },
    { id = 4474, x = 0.4738000000, y = 0.6167000000, map = "stonefalls/ebonheart_base_0" }, -- skill point
  },
  [4479] = {
    { id = 4460, x = 0.2444130480, y = 0.2956069708, map = "reapersmarch/reapersmarch_base_0" },
    { id = 4461, x = 0.3097724319, y = 0.2551230192, map = "reapersmarch/reapersmarch_base_0" },
    { id = 4689, x = 0.4913000000, y = 0.4852000000, map = "reapersmarch/arenthia_base_0" },
    { id = 4712, x = 0.4884000000, y = 0.5524000000, map = "reapersmarch/reapersmarch_base_0" },
    { id = 4479, x = 0.3304843605, y = 0.8118692040, map = "reapersmarch/reapersmarch_base_0" }, -- skill point
  },
  [4552] = {
    { id = 4831, x = -1, y = -1, map = "" },
    { id = 4474, x = 0.4738000000, y = 0.6167000000, map = "stonefalls/ebonheart_base_0" },
    { id = 4552, x = 0.6428000000, y = 0.2446000000, map = "auridon/firsthold_base_0" }, -- skill point
  },
  [4590] = {
    { id = 3686, x = 0.4672333300, y = 0.2861999869, map = "shadowfen/shadowfen_base_0" },
    { id = 3687, x = 0.4459000000, y = 0.2690000000, map = "shadowfen/shadowfen_base_0" },
    { id = 4587, x = 0.6186733246, y = 0.3773533404, map = "shadowfen/shadowfen_base_0" },
    { id = 4590, x = 0.6669200063, y = 0.4088366628, map = "shadowfen/shadowfen_base_0" }, -- skill point
  },
  [4602] = {
    { id = 4679, x = 0.2308175862, y = 0.6641231179, map = "coldharbor/coldharbour_base_0" },
    { id = 4602, x = 0.7002583742, y = 0.5669681430, map = "coldharbor/lightlessoubliette_base_0" }, -- skill point
  },
  [4606] = {
    { id = 3686, x = 0.4672333300, y = 0.2861999869, map = "shadowfen/shadowfen_base_0" },
    { id = 3687, x = 0.4459000000, y = 0.2690000000, map = "shadowfen/shadowfen_base_0" },
    { id = 4587, x = 0.6186733246, y = 0.3773533404, map = "shadowfen/shadowfen_base_0" },
    { id = 4590, x = 0.6669200063, y = 0.4088366628, map = "shadowfen/shadowfen_base_0" },
    { id = 4606, x = 0.5219699740, y = 0.5844333172, map = "shadowfen/shadowfen_base_0" }, -- skill point
  },
  [4607] = {
    { id = 4831, x = -1, y = -1, map = "" },
    { id = 4474, x = 0.4738000000, y = 0.6167000000, map = "stonefalls/ebonheart_base_0" },
    { id = 4552, x = 0.6428000000, y = 0.2446000000, map = "auridon/firsthold_base_0" },
    { id = 4607, x = 0.7281000000, y = 0.4262000000, map = "rivenspire/shornhelm_base_0" }, -- skill point
  },
  [4690] = {
    { id = 4735, x = 0.6096693277, y = 0.4879100621, map = "greenshade/woodhearth_base_0" },
    { id = 4546, x = 0.6296000000, y = 0.3821000000, map = "greenshade/greenshade_base_0" },
    { id = 4690, x = 0.4840302765, y = 0.2768185735, map = "greenshade/greenshade_base_0" }, -- skill point
  },
  [4712] = {
    { id = 4460, x = 0.2444130480, y = 0.2956069708, map = "reapersmarch/reapersmarch_base_0" },
    { id = 4461, x = 0.3097724319, y = 0.2551230192, map = "reapersmarch/reapersmarch_base_0" },
    { id = 4689, x = 0.4913000000, y = 0.4852000000, map = "reapersmarch/arenthia_base_0" },
    { id = 4712, x = 0.4884000000, y = 0.5524000000, map = "reapersmarch/reapersmarch_base_0" }, -- skill point
  },
  [4720] = {
    { id = 4460, x = 0.2444130480, y = 0.2956069708, map = "reapersmarch/reapersmarch_base_0" },
    { id = 4461, x = 0.3097724319, y = 0.2551230192, map = "reapersmarch/reapersmarch_base_0" },
    { id = 4689, x = 0.4913000000, y = 0.4852000000, map = "reapersmarch/arenthia_base_0" },
    { id = 4712, x = 0.4884000000, y = 0.5524000000, map = "reapersmarch/reapersmarch_base_0" },
    { id = 4479, x = 0.3304843605, y = 0.8118692040, map = "reapersmarch/reapersmarch_base_0" },
    { id = 4550, x = 0.1193336397, y = 0.4688522220, map = "reapersmarch/dune_base_0" },
    { id = 4719, x = 0.6414183378, y = 0.5036374927, map = "reapersmarch/dune_base_0" },
    { id = 4720, x = 0.4919148982, y = 0.3861702085, map = "reapersmarch/planeofjodehubhillbos_base_0" }, -- skill point
  },
  [4730] = {
    { id = 4626, x = 0.7143993378, y = 0.6849459410, map = "coldharbor/coldharbour_base_0" },
    { id = 4730, x = 0.2377199978, y = 0.6444933414, map = "coldharbor/greatshackle1_base_0" }, -- skill point
  },
  [4750] = {
    { id = 4573, x = 0.6876000000, y = 0.5043000000, map = "greenshade/greenshade_base_0" },
    { id = 4593, x = 0.6454796195, y = 0.6578338742, map = "greenshade/greenshade_base_0" },
    { id = 4750, x = 0.5617000000, y = 0.8324000000, map = "greenshade/greenshade_base_0" }, -- skill point
  },
  [4758] = {
    { id = 4605, x = 0.5204775929, y = 0.7725441456, map = "coldharbor/coldharbour_base_0" },
    { id = 4610, x = 0.5191000000, y = 0.7026000000, map = "coldharbor/coldharbour_base_0" },
    { id = 4701, x = 0.5065449476, y = 0.6771463156, map = "coldharbor/coldharbour_base_0" },
    { id = 4715, x = 0.5090472102, y = 0.5175563097, map = "coldharbor/coldharbour_base_0" },
    { id = 4774, x = 0.5188490748, y = 0.4196681082, map = "coldharbor/coldharbour_base_0" },
    { id = 4758, x = 0.4711894691, y = 0.3273891807, map = "coldharbor/coldharbour_base_0" }, -- skill point
  },
  [4764] = {
    { id = 4831, x = -1, y = -1, map = "" },
    { id = 4474, x = 0.4738000000, y = 0.6167000000, map = "stonefalls/ebonheart_base_0" },
    { id = 4552, x = 0.6428000000, y = 0.2446000000, map = "auridon/firsthold_base_0" },
    { id = 4607, x = 0.7281000000, y = 0.4262000000, map = "rivenspire/shornhelm_base_0" },
    { id = 4764, x = 0.8536000000, y = 0.3942000000, map = "stonefalls/stonefalls_base_0" }, -- skill point
  },
  [4765] = {
    { id = 4735, x = 0.6096693277, y = 0.4879100621, map = "greenshade/woodhearth_base_0" },
    { id = 4574, x = 0.6802287698, y = 0.5446338058, map = "greenshade/woodhearth_base_0" },
    { id = 4580, x = 0.4353552759, y = 0.3572787344, map = "greenshade/woodhearth_base_0" },
    { id = 4739, x = 0.2828539610, y = 0.4042039514, map = "greenshade/greenshade_base_0" },
    { id = 4765, x = 0.2155560851, y = 0.3681418598, map = "greenshade/greenshade_base_0" }, -- skill point
  },
  [4832] = {
    { id = 4831, x = -1, y = -1, map = "" },
    { id = 4474, x = 0.4738000000, y = 0.6167000000, map = "stonefalls/ebonheart_base_0" },
    { id = 4552, x = 0.6428000000, y = 0.2446000000, map = "auridon/firsthold_base_0" },
    { id = 4607, x = 0.7281000000, y = 0.4262000000, map = "rivenspire/shornhelm_base_0" },
    { id = 4764, x = 0.8536000000, y = 0.3942000000, map = "stonefalls/stonefalls_base_0" },
    { id = 4836, x = 0.4006000000, y = 0.6741000000, map = "shadowfen/shadowfen_base_0" },
    { id = 4837, x = 0.2233000000, y = 0.4698000000, map = "alikr/alikr_base_0" },
    { id = 4867, x = 0.2967000000, y = 0.1359000000, map = "eastmarch/fortamol_base_0" },
    { id = 4832, x = 0.7281000000, y = 0.4262000000, map = "rivenspire/shornhelm_base_0" }, -- skill point
  },
  [4836] = {
    { id = 4831, x = -1, y = -1, map = "" },
    { id = 4474, x = 0.4738000000, y = 0.6167000000, map = "stonefalls/ebonheart_base_0" },
    { id = 4552, x = 0.6428000000, y = 0.2446000000, map = "auridon/firsthold_base_0" },
    { id = 4607, x = 0.7281000000, y = 0.4262000000, map = "rivenspire/shornhelm_base_0" },
    { id = 4764, x = 0.8536000000, y = 0.3942000000, map = "stonefalls/stonefalls_base_0" },
    { id = 4836, x = 0.4006000000, y = 0.6741000000, map = "shadowfen/shadowfen_base_0" }, -- skill point
  },
  [4837] = {
    { id = 4831, x = -1, y = -1, map = "" },
    { id = 4474, x = 0.4738000000, y = 0.6167000000, map = "stonefalls/ebonheart_base_0" },
    { id = 4552, x = 0.6428000000, y = 0.2446000000, map = "auridon/firsthold_base_0" },
    { id = 4607, x = 0.7281000000, y = 0.4262000000, map = "rivenspire/shornhelm_base_0" },
    { id = 4764, x = 0.8536000000, y = 0.3942000000, map = "stonefalls/stonefalls_base_0" },
    { id = 4836, x = 0.4006000000, y = 0.6741000000, map = "shadowfen/shadowfen_base_0" },
    { id = 4837, x = 0.2233000000, y = 0.4698000000, map = "alikr/alikr_base_0" }, -- skill point
  },
  [4847] = {
    { id = 4831, x = -1, y = -1, map = "" },
    { id = 4474, x = 0.4738000000, y = 0.6167000000, map = "stonefalls/ebonheart_base_0" },
    { id = 4552, x = 0.6428000000, y = 0.2446000000, map = "auridon/firsthold_base_0" },
    { id = 4607, x = 0.7281000000, y = 0.4262000000, map = "rivenspire/shornhelm_base_0" },
    { id = 4764, x = 0.8536000000, y = 0.3942000000, map = "stonefalls/stonefalls_base_0" },
    { id = 4836, x = 0.4006000000, y = 0.6741000000, map = "shadowfen/shadowfen_base_0" },
    { id = 4837, x = 0.2233000000, y = 0.4698000000, map = "alikr/alikr_base_0" },
    { id = 4867, x = 0.2967000000, y = 0.1359000000, map = "eastmarch/fortamol_base_0" },
    { id = 4832, x = 0.7281000000, y = 0.4262000000, map = "rivenspire/shornhelm_base_0" },
    { id = 4847, x = 0.5027000000, y = 0.6749000000, map = "coldharbor/coldharbour_base_0" }, -- skill point
  },
  [4867] = {
    { id = 4831, x = -1, y = -1, map = "" },
    { id = 4474, x = 0.4738000000, y = 0.6167000000, map = "stonefalls/ebonheart_base_0" },
    { id = 4552, x = 0.6428000000, y = 0.2446000000, map = "auridon/firsthold_base_0" },
    { id = 4607, x = 0.7281000000, y = 0.4262000000, map = "rivenspire/shornhelm_base_0" },
    { id = 4764, x = 0.8536000000, y = 0.3942000000, map = "stonefalls/stonefalls_base_0" },
    { id = 4836, x = 0.4006000000, y = 0.6741000000, map = "shadowfen/shadowfen_base_0" },
    { id = 4837, x = 0.2233000000, y = 0.4698000000, map = "alikr/alikr_base_0" },
    { id = 4867, x = 0.2967000000, y = 0.1359000000, map = "eastmarch/fortamol_base_0" }, -- skill point
  },
  [4884] = {
    { id = 4902, x = 0.8387507796, y = 0.5824304223, map = "rivenspire/shornhelm_base_0" },
    { id = 4903, x = 0.5944975615, y = 0.2089016289, map = "rivenspire/shornhelm_base_0" },
    { id = 465, x = 0.2929956317, y = 0.4519065917, map = "rivenspire/rivenspire_base_0" },
    { id = 4857, x = 0.5519000000, y = 0.7697000000, map = "rivenspire/shornhelm_base_0" },
    { id = 4958, x = 0.5999255776, y = 0.4799529910, map = "rivenspire/rivenspire_base_0" },
    { id = 4972, x = 0.4569857419, y = 0.1731737703, map = "rivenspire/northpoint_base_0" },
    { id = 5024, x = 0.5080381632, y = 0.5713533163, map = "rivenspire/northpoint_base_0" },
    { id = 4884, x = 0.2232988328, y = 0.2578176558, map = "rivenspire/shroudedpass_base_0" }, -- skill point
  },
  [4891] = {
    { id = 1799, x = 0.2408170551, y = 0.5996610522, map = "bangkorai/evermore_base_0" },
    { id = 3280, x = 0.3451788425, y = 0.5055035353, map = "bangkorai/evermore_base_0" },
    { id = 1834, x = 0.6989578605, y = 0.1780853122, map = "bangkorai/bangkorai_base_0" },
    { id = 4891, x = 0.6026015878, y = 0.1464848071, map = "bangkorai/bangkorai_base_0" }, -- skill point
  },
  [4912] = {
    { id = 1799, x = 0.2408170551, y = 0.5996610522, map = "bangkorai/evermore_base_0" },
    { id = 3280, x = 0.3451788425, y = 0.5055035353, map = "bangkorai/evermore_base_0" },
    { id = 1834, x = 0.6989578605, y = 0.1780853122, map = "bangkorai/bangkorai_base_0" },
    { id = 4891, x = 0.6026015878, y = 0.1464848071, map = "bangkorai/bangkorai_base_0" },
    { id = 4912, x = 0.4715167582, y = 0.5493511558, map = "bangkorai/bangkorai_base_0" }, -- skill point
  },
  [4960] = {
    { id = 1799, x = 0.2408170551, y = 0.5996610522, map = "bangkorai/evermore_base_0" },
    { id = 3280, x = 0.3451788425, y = 0.5055035353, map = "bangkorai/evermore_base_0" },
    { id = 1834, x = 0.6989578605, y = 0.1780853122, map = "bangkorai/bangkorai_base_0" },
    { id = 4891, x = 0.6026015878, y = 0.1464848071, map = "bangkorai/bangkorai_base_0" },
    { id = 4912, x = 0.4715167582, y = 0.5493511558, map = "bangkorai/bangkorai_base_0" },
    { id = 4959, x = 0.4419698119, y = 0.8389187455, map = "bangkorai/bangkorai_base_0" },
    { id = 4960, x = 0.7250214219, y = 0.6024453044, map = "bangkorai/hallofheroes_base_0" }, -- skill point
  },
  [4972] = {
    { id = 4902, x = 0.8387507796, y = 0.5824304223, map = "rivenspire/shornhelm_base_0" },
    { id = 4903, x = 0.5944975615, y = 0.2089016289, map = "rivenspire/shornhelm_base_0" },
    { id = 465, x = 0.2929956317, y = 0.4519065917, map = "rivenspire/rivenspire_base_0" },
    { id = 4857, x = 0.5519000000, y = 0.7697000000, map = "rivenspire/shornhelm_base_0" },
    { id = 4958, x = 0.5999255776, y = 0.4799529910, map = "rivenspire/rivenspire_base_0" },
    { id = 4972, x = 0.4569857419, y = 0.1731737703, map = "rivenspire/northpoint_base_0" }, -- skill point
  },
  [5447] = {
    { id = 5450, x = 0.5272041559, y = 0.2612756193, map = "glenumbra/daggerfall_base_0" },
    { id = 5329, x = 0.7471000000, y = 0.6639000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5447, x = 0.6832000000, y = 0.6970000000, map = "wrothgar/wrothgar_base_0" }, -- skill point
  },
  [5468] = {
    { id = 5450, x = 0.5272041559, y = 0.2612756193, map = "glenumbra/daggerfall_base_0" },
    { id = 5329, x = 0.7471000000, y = 0.6639000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5447, x = 0.6832000000, y = 0.6970000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5458, x = 0.6681000000, y = 0.6125000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5348, x = 0.7107000000, y = 0.6679000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5468, x = 0.6706000000, y = 0.6983000000, map = "wrothgar/wrothgar_base_0" }, -- skill point
  },
  [5481] = {
    { id = 5450, x = 0.5272041559, y = 0.2612756193, map = "glenumbra/daggerfall_base_0" },
    { id = 5329, x = 0.7471000000, y = 0.6639000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5447, x = 0.6832000000, y = 0.6970000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5458, x = 0.6681000000, y = 0.6125000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5348, x = 0.7107000000, y = 0.6679000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5468, x = 0.6706000000, y = 0.6983000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5349, x = 0.6691000000, y = 0.6989000000, map = "wrothgar/wrothgar_base_0" },
    { id = 5481, x = 0.7295000000, y = 0.6580000000, map = "wrothgar/wrothgar_base_0" }, -- skill point
  },
  [5482] = {
    { id = 5496, x = 0.4844294190, y = 0.4803589880, map = "cyrodiil/westelsweyrgate_base_0" },
    { id = 5473, x = 0.5535171032, y = 0.3062666655, map = "cyrodiil/imperialcity_base_0" },
    { id = 5482, x = 0.0613836460, y = 0.6253458858, map = "cyrodiil/imperialsewer_daggerfall1_base_0" }, -- skill point
  },
  [5532] = {
    { id = 5531, x = 0.6639270186, y = 0.6559546590, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5534, x = 0.4146981537, y = 0.4711286128, map = "vvardenfell/vvardenfelloutlawrefuge_base_0" },
    { id = 5532, x = 0.1955000000, y = 0.4362000000, map = "thievesguild/abahslanding_base_0" }, -- skill point
  },
  [5534] = {
    { id = 5531, x = 0.6639270186, y = 0.6559546590, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5534, x = 0.4146981537, y = 0.4711286128, map = "vvardenfell/vvardenfelloutlawrefuge_base_0" }, -- skill point
  },
  [5540] = {
    { id = 5538, x = 0.5271636248, y = 0.4111942053, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5540, x = 0.3566000000, y = 0.6182000000, map = "darkbrotherhood/goldcoast_base_0" }, -- skill point
  },
  [5545] = {
    { id = 5531, x = 0.6639270186, y = 0.6559546590, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5534, x = 0.4146981537, y = 0.4711286128, map = "vvardenfell/vvardenfelloutlawrefuge_base_0" },
    { id = 5532, x = 0.1955000000, y = 0.4362000000, map = "thievesguild/abahslanding_base_0" },
    { id = 5556, x = 0.1955000000, y = 0.4362000000, map = "thievesguild/abahslanding_base_0" },
    { id = 5549, x = 0.1955000000, y = 0.4362000000, map = "thievesguild/abahslanding_base_0" },
    { id = 5545, x = 0.1955000000, y = 0.4362000000, map = "thievesguild/abahslanding_base_0" }, -- skill point
  },
  [5549] = {
    { id = 5531, x = 0.6639270186, y = 0.6559546590, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5534, x = 0.4146981537, y = 0.4711286128, map = "vvardenfell/vvardenfelloutlawrefuge_base_0" },
    { id = 5532, x = 0.1955000000, y = 0.4362000000, map = "thievesguild/abahslanding_base_0" },
    { id = 5556, x = 0.1955000000, y = 0.4362000000, map = "thievesguild/abahslanding_base_0" },
    { id = 5549, x = 0.1955000000, y = 0.4362000000, map = "thievesguild/abahslanding_base_0" }, -- skill point
  },
  [5556] = {
    { id = 5531, x = 0.6639270186, y = 0.6559546590, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5534, x = 0.4146981537, y = 0.4711286128, map = "vvardenfell/vvardenfelloutlawrefuge_base_0" },
    { id = 5532, x = 0.1955000000, y = 0.4362000000, map = "thievesguild/abahslanding_base_0" },
    { id = 5556, x = 0.1955000000, y = 0.4362000000, map = "thievesguild/abahslanding_base_0" }, -- skill point
  },
  [5567] = {
    { id = 5538, x = 0.5271636248, y = 0.4111942053, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5540, x = 0.3566000000, y = 0.6182000000, map = "darkbrotherhood/goldcoast_base_0" },
    { id = 5542, x = 0.4701959193, y = 0.3964151740, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5708, x = 0.1404751986, y = 0.8457690477, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5595, x = 0.1471446455, y = 0.8215923309, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5599, x = 0.7924135327, y = 0.5135473013, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5596, x = 0.4785327315, y = 0.4126719534, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5567, x = 0.4764485061, y = 0.4001667500, map = "darkbrotherhood/dbsanctuary_base_0" }, -- skill point
  },
  [5595] = {
    { id = 5538, x = 0.5271636248, y = 0.4111942053, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5540, x = 0.3566000000, y = 0.6182000000, map = "darkbrotherhood/goldcoast_base_0" },
    { id = 5542, x = 0.4701959193, y = 0.3964151740, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5708, x = 0.1404751986, y = 0.8457690477, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5595, x = 0.1471446455, y = 0.8215923309, map = "darkbrotherhood/dbsanctuary_base_0" }, -- skill point
  },
  [5596] = {
    { id = 5538, x = 0.5271636248, y = 0.4111942053, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5540, x = 0.3566000000, y = 0.6182000000, map = "darkbrotherhood/goldcoast_base_0" },
    { id = 5542, x = 0.4701959193, y = 0.3964151740, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5708, x = 0.1404751986, y = 0.8457690477, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5595, x = 0.1471446455, y = 0.8215923309, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5599, x = 0.7924135327, y = 0.5135473013, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5596, x = 0.4785327315, y = 0.4126719534, map = "darkbrotherhood/dbsanctuary_base_0" }, -- skill point
  },
  [5597] = {
    { id = 5538, x = 0.5271636248, y = 0.4111942053, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5540, x = 0.3566000000, y = 0.6182000000, map = "darkbrotherhood/goldcoast_base_0" },
    { id = 5542, x = 0.4701959193, y = 0.3964151740, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5708, x = 0.1404751986, y = 0.8457690477, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5595, x = 0.1471446455, y = 0.8215923309, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5599, x = 0.7924135327, y = 0.5135473013, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5596, x = 0.4785327315, y = 0.4126719534, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5567, x = 0.4764485061, y = 0.4001667500, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5597, x = 0.5043768287, y = 0.5689870715, map = "darkbrotherhood/dbsanctuary_base_0" }, -- skill point
  },
  [5598] = {
    { id = 5538, x = 0.5271636248, y = 0.4111942053, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5540, x = 0.3566000000, y = 0.6182000000, map = "darkbrotherhood/goldcoast_base_0" },
    { id = 5542, x = 0.4701959193, y = 0.3964151740, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5708, x = 0.1404751986, y = 0.8457690477, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5595, x = 0.1471446455, y = 0.8215923309, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5599, x = 0.7924135327, y = 0.5135473013, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5596, x = 0.4785327315, y = 0.4126719534, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5567, x = 0.4764485061, y = 0.4001667500, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5597, x = 0.5043768287, y = 0.5689870715, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5598, x = 0.4772821963, y = 0.4047519863, map = "darkbrotherhood/dbsanctuary_base_0" }, -- skill point
  },
  [5599] = {
    { id = 5538, x = 0.5271636248, y = 0.4111942053, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5540, x = 0.3566000000, y = 0.6182000000, map = "darkbrotherhood/goldcoast_base_0" },
    { id = 5542, x = 0.4701959193, y = 0.3964151740, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5708, x = 0.1404751986, y = 0.8457690477, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5595, x = 0.1471446455, y = 0.8215923309, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5599, x = 0.7924135327, y = 0.5135473013, map = "darkbrotherhood/dbsanctuary_base_0" }, -- skill point
  },
  [5600] = {
    { id = 5538, x = 0.5271636248, y = 0.4111942053, map = "westweald/u42_skingrad_or_base_0" },
    { id = 5540, x = 0.3566000000, y = 0.6182000000, map = "darkbrotherhood/goldcoast_base_0" },
    { id = 5542, x = 0.4701959193, y = 0.3964151740, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5708, x = 0.1404751986, y = 0.8457690477, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5595, x = 0.1471446455, y = 0.8215923309, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5599, x = 0.7924135327, y = 0.5135473013, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5596, x = 0.4785327315, y = 0.4126719534, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5567, x = 0.4764485061, y = 0.4001667500, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5597, x = 0.5043768287, y = 0.5689870715, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5598, x = 0.4772821963, y = 0.4047519863, map = "darkbrotherhood/dbsanctuary_base_0" },
    { id = 5600, x = 0.5235514641, y = 0.4514380991, map = "darkbrotherhood/dbsanctuary_base_0" }, -- skill point
  },
  [5922] = {
    { id = 5799, x = 0.2929757237, y = 0.4706740975, map = "vvardenfell/sadrithmora_base_0" },
    { id = 5859, x = 0.3753976226, y = 0.3030415177, map = "vvardenfell/sadrithmora_base_0" },
    { id = 5901, x = 0.3353740871, y = 0.3603425026, map = "vvardenfell/sadrithmora_base_0" },
    { id = 5914, x = 0.3462896049, y = 0.3883175850, map = "vvardenfell/sadrithmora_base_0" },
    { id = 5922, x = 0.7745858431, y = 0.4822115004, map = "vvardenfell/vvardenfell_base_0" }, -- skill point
  },
  [5948] = {
    { id = 5887, x = 0.5430318117, y = 0.6689666510, map = "vvardenfell/balmora_base_0" },
    { id = 5919, x = 0.2393896580, y = 0.4469888210, map = "vvardenfell/balmora_base_0" },
    { id = 5933, x = 0.2935701311, y = 0.4876473248, map = "vvardenfell/balmora_base_0" },
    { id = 5948, x = 0.3094769418, y = 0.4812336564, map = "vvardenfell/balmora_base_0" }, -- skill point
  },
  [6003] = {
    { id = 5803, x = 0.2491242290, y = 0.2286347896, map = "vvardenfell/viviccity_base_0" },
    { id = 5880, x = 0.5006300807, y = 0.7569873333, map = "vvardenfell/viviccity_base_0" },
    { id = 5888, x = 0.5045741796, y = 0.7514806390, map = "vvardenfell/viviccity_base_0" },
    { id = 5893, x = 0.4994959533, y = 0.7555885911, map = "vvardenfell/viviccity_base_0" },
    { id = 5902, x = 0.3823255897, y = 0.6091473103, map = "vvardenfell/vivecthroneroom02_base_0" },
    { id = 5905, x = 0.4951938093, y = 0.3164341152, map = "vvardenfell/vivecthroneroom02_base_0" },
    { id = 6003, x = 0.4982945621, y = 0.3246511519, map = "vvardenfell/vivecthroneroom02_base_0" }, -- skill point
  },
  [6025] = {
    { id = 6050, x = 0.2015000000, y = 0.3221000000, map = "clockwork/dranilkirisland_base_0" },
    { id = 6057, x = 0.4993130863, y = 0.4488049746, map = "clockwork/clockwork_base_0" },
    { id = 6063, x = 0.3709515631, y = 0.5351094007, map = "clockwork/brassfortress_base_0" },
    { id = 6025, x = 0.5274575353, y = 0.3127463460, map = "clockwork/basilica_01_base_0" }, -- skill point
  },
  [6046] = {
    { id = 6050, x = 0.2015000000, y = 0.3221000000, map = "clockwork/dranilkirisland_base_0" },
    { id = 6057, x = 0.4993130863, y = 0.4488049746, map = "clockwork/clockwork_base_0" },
    { id = 6063, x = 0.3709515631, y = 0.5351094007, map = "clockwork/brassfortress_base_0" },
    { id = 6025, x = 0.5274575353, y = 0.3127463460, map = "clockwork/basilica_01_base_0" },
    { id = 6052, x = 0.8688616753, y = 0.5368224382, map = "clockwork/basilica_01_base_0" },
    { id = 6046, x = 0.3041223288, y = 0.4581691027, map = "clockwork/basilica_01_base_0" }, -- skill point
  },
  [6047] = {
    { id = 6050, x = 0.2015000000, y = 0.3221000000, map = "clockwork/dranilkirisland_base_0" },
    { id = 6057, x = 0.4993130863, y = 0.4488049746, map = "clockwork/clockwork_base_0" },
    { id = 6063, x = 0.3709515631, y = 0.5351094007, map = "clockwork/brassfortress_base_0" },
    { id = 6025, x = 0.5274575353, y = 0.3127463460, map = "clockwork/basilica_01_base_0" },
    { id = 6052, x = 0.8688616753, y = 0.5368224382, map = "clockwork/basilica_01_base_0" },
    { id = 6046, x = 0.3041223288, y = 0.4581691027, map = "clockwork/basilica_01_base_0" },
    { id = 6047, x = 0.6627131104, y = 0.0589662381, map = "clockwork/ccunderground02_base_0" }, -- skill point
  },
  [6048] = {
    { id = 6050, x = 0.2015000000, y = 0.3221000000, map = "clockwork/dranilkirisland_base_0" },
    { id = 6057, x = 0.4993130863, y = 0.4488049746, map = "clockwork/clockwork_base_0" },
    { id = 6063, x = 0.3709515631, y = 0.5351094007, map = "clockwork/brassfortress_base_0" },
    { id = 6025, x = 0.5274575353, y = 0.3127463460, map = "clockwork/basilica_01_base_0" },
    { id = 6052, x = 0.8688616753, y = 0.5368224382, map = "clockwork/basilica_01_base_0" },
    { id = 6046, x = 0.3041223288, y = 0.4581691027, map = "clockwork/basilica_01_base_0" },
    { id = 6047, x = 0.6627131104, y = 0.0589662381, map = "clockwork/ccunderground02_base_0" },
    { id = 6048, x = 0.5234566927, y = 0.2492072433, map = "clockwork/basilica_01_base_0" }, -- skill point
  },
  [6052] = {
    { id = 6050, x = 0.2015000000, y = 0.3221000000, map = "clockwork/dranilkirisland_base_0" },
    { id = 6057, x = 0.4993130863, y = 0.4488049746, map = "clockwork/clockwork_base_0" },
    { id = 6063, x = 0.3709515631, y = 0.5351094007, map = "clockwork/brassfortress_base_0" },
    { id = 6025, x = 0.5274575353, y = 0.3127463460, map = "clockwork/basilica_01_base_0" },
    { id = 6052, x = 0.8688616753, y = 0.5368224382, map = "clockwork/basilica_01_base_0" }, -- skill point
  },
  [6057] = {
    { id = 6050, x = 0.2015000000, y = 0.3221000000, map = "clockwork/dranilkirisland_base_0" },
    { id = 6057, x = 0.4993130863, y = 0.4488049746, map = "clockwork/clockwork_base_0" }, -- skill point
  },
  [6063] = {
    { id = 6050, x = 0.2015000000, y = 0.3221000000, map = "clockwork/dranilkirisland_base_0" },
    { id = 6057, x = 0.4993130863, y = 0.4488049746, map = "clockwork/clockwork_base_0" },
    { id = 6063, x = 0.3709515631, y = 0.5351094007, map = "clockwork/brassfortress_base_0" }, -- skill point
  },
  [6113] = {
    { id = 6096, x = 0.2326681465, y = 0.6644926071, map = "summerset/shimmerene_base_0" },
    { id = 6112, x = 0.6453855634, y = 0.2693812847, map = "summerset/artaeum_base_0" },
    { id = 6132, x = 0.8388324976, y = 0.6041666865, map = "summerset/dreamingcave02_base_0" },
    { id = 6142, x = 0.4402092099, y = 0.6166618466, map = "summerset/lillandrill_base_0" },
    { id = 6109, x = 0.8517343402, y = 0.6170685291, map = "summerset/dreamingcave02_base_0" },
    { id = 6113, x = 0.5632643700, y = 0.5895531178, map = "summerset/dreamingcave01_base_0" }, -- skill point
  },
  [6126] = {
    { id = 6096, x = 0.2326681465, y = 0.6644926071, map = "summerset/shimmerene_base_0" },
    { id = 6112, x = 0.6453855634, y = 0.2693812847, map = "summerset/artaeum_base_0" },
    { id = 6132, x = 0.8388324976, y = 0.6041666865, map = "summerset/dreamingcave02_base_0" },
    { id = 6142, x = 0.4402092099, y = 0.6166618466, map = "summerset/lillandrill_base_0" },
    { id = 6109, x = 0.8517343402, y = 0.6170685291, map = "summerset/dreamingcave02_base_0" },
    { id = 6113, x = 0.5632643700, y = 0.5895531178, map = "summerset/dreamingcave01_base_0" },
    { id = 6125, x = 0.3826723099, y = 0.3851868808, map = "summerset/dreamingcave01_base_0" },
    { id = 6126, x = 0.4072546661, y = 0.4360723495, map = "summerset/dreamingcave02_base_0" }, -- skill point
  },
  [6132] = {
    { id = 6096, x = 0.2326681465, y = 0.6644926071, map = "summerset/shimmerene_base_0" },
    { id = 6112, x = 0.6453855634, y = 0.2693812847, map = "summerset/artaeum_base_0" },
    { id = 6132, x = 0.8388324976, y = 0.6041666865, map = "summerset/dreamingcave02_base_0" }, -- skill point
  },
  [6241] = {
    { id = 6246, x = 0.4674140811, y = 0.4619996548, map = "murkmire/lilmothcity_base_0" },
    { id = 6266, x = 0.4934308231, y = 0.2466465831, map = "murkmire/lilmothcity_base_0" },
    { id = 6241, x = 0.4954956472, y = 0.2551505864, map = "murkmire/lilmothcity_base_0" }, -- skill point
  },
  [6243] = {
    { id = 6246, x = 0.4674140811, y = 0.4619996548, map = "murkmire/lilmothcity_base_0" },
    { id = 6266, x = 0.4934308231, y = 0.2466465831, map = "murkmire/lilmothcity_base_0" },
    { id = 6241, x = 0.4954956472, y = 0.2551505864, map = "murkmire/lilmothcity_base_0" },
    { id = 6259, x = 0.4934155047, y = 0.2503632605, map = "murkmire/lilmothcity_base_0" },
    { id = 6243, x = 0.4220237136, y = 0.4886876643, map = "murkmire/murkmire_base_0" }, -- skill point
  },
  [6244] = {
    { id = 6246, x = 0.4674140811, y = 0.4619996548, map = "murkmire/lilmothcity_base_0" },
    { id = 6266, x = 0.4934308231, y = 0.2466465831, map = "murkmire/lilmothcity_base_0" },
    { id = 6241, x = 0.4954956472, y = 0.2551505864, map = "murkmire/lilmothcity_base_0" },
    { id = 6259, x = 0.4934155047, y = 0.2503632605, map = "murkmire/lilmothcity_base_0" },
    { id = 6243, x = 0.4220237136, y = 0.4886876643, map = "murkmire/murkmire_base_0" },
    { id = 6244, x = 0.4186555445, y = 0.4904839396, map = "murkmire/rootwhisper_base_0" }, -- skill point
  },
  [6245] = {
    { id = 6246, x = 0.4674140811, y = 0.4619996548, map = "murkmire/lilmothcity_base_0" },
    { id = 6266, x = 0.4934308231, y = 0.2466465831, map = "murkmire/lilmothcity_base_0" },
    { id = 6241, x = 0.4954956472, y = 0.2551505864, map = "murkmire/lilmothcity_base_0" },
    { id = 6259, x = 0.4934155047, y = 0.2503632605, map = "murkmire/lilmothcity_base_0" },
    { id = 6243, x = 0.4220237136, y = 0.4886876643, map = "murkmire/murkmire_base_0" },
    { id = 6244, x = 0.4186555445, y = 0.4904839396, map = "murkmire/rootwhisper_base_0" },
    { id = 6245, x = 0.4867945611, y = 0.5376062393, map = "murkmire/rootwhisper_base_0" }, -- skill point
  },
  [6259] = {
    { id = 6246, x = 0.4674140811, y = 0.4619996548, map = "murkmire/lilmothcity_base_0" },
    { id = 6266, x = 0.4934308231, y = 0.2466465831, map = "murkmire/lilmothcity_base_0" },
    { id = 6241, x = 0.4954956472, y = 0.2551505864, map = "murkmire/lilmothcity_base_0" },
    { id = 6259, x = 0.4934155047, y = 0.2503632605, map = "murkmire/lilmothcity_base_0" }, -- skill point
  },
  [6266] = {
    { id = 6246, x = 0.4674140811, y = 0.4619996548, map = "murkmire/lilmothcity_base_0" },
    { id = 6266, x = 0.4934308231, y = 0.2466465831, map = "murkmire/lilmothcity_base_0" }, -- skill point
  },
  [6304] = {
    { id = 6336, x = 0.5015237927, y = 0.1998542398, map = "elsweyr/elsweyr_base_0" },
    { id = 6338, x = 0.5006983876, y = 0.1754045486, map = "elsweyr/elsweyr_base_0" },
    { id = 6296, x = 0.5003008842, y = 0.1758075804, map = "elsweyr/elsweyr_base_0" },
    { id = 6304, x = 0.5030000000, y = 0.1765000000, map = "elsweyr/elsweyr_base_0" }, -- skill point
  },
  [6315] = {
    { id = 6336, x = 0.5015237927, y = 0.1998542398, map = "elsweyr/elsweyr_base_0" },
    { id = 6338, x = 0.5006983876, y = 0.1754045486, map = "elsweyr/elsweyr_base_0" },
    { id = 6296, x = 0.5003008842, y = 0.1758075804, map = "elsweyr/elsweyr_base_0" },
    { id = 6304, x = 0.5030000000, y = 0.1765000000, map = "elsweyr/elsweyr_base_0" },
    { id = 6297, x = 0.7755556703, y = 0.3676254153, map = "elsweyr/rimmen_base_0" },
    { id = 6305, x = 0.8310000000, y = 0.2683000000, map = "elsweyr/elsweyr_base_0" },
    { id = 6315, x = 0.8310000000, y = 0.2684000000, map = "elsweyr/elsweyr_base_0" }, -- skill point
  },
  [6393] = {
    { id = 6401, x = 0.5821303725, y = 0.5995892286, map = "southernelsweyr/senchal_base_0" },
    { id = 6409, x = 0.9153884053, y = 0.3462212086, map = "southernelsweyr/els_dg_sanctuary02_base_0" },
    { id = 6394, x = 0.5063671470, y = 0.3753636181, map = "southernelsweyr/els_dragonguard_island01_base_0" },
    { id = 6399, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" },
    { id = 6403, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" },
    { id = 6404, x = 0.5004334450, y = 0.3587570190, map = "southernelsweyr/els_dragonguard_island01_base_0" },
    { id = 6393, x = -1, y = -1, map = "" }, -- skill point
  },
  [6394] = {
    { id = 6401, x = 0.5821303725, y = 0.5995892286, map = "southernelsweyr/senchal_base_0" },
    { id = 6409, x = 0.9153884053, y = 0.3462212086, map = "southernelsweyr/els_dg_sanctuary02_base_0" },
    { id = 6394, x = 0.5063671470, y = 0.3753636181, map = "southernelsweyr/els_dragonguard_island01_base_0" }, -- skill point
  },
  [6397] = {
    { id = 6401, x = 0.5821303725, y = 0.5995892286, map = "southernelsweyr/senchal_base_0" },
    { id = 6409, x = 0.9153884053, y = 0.3462212086, map = "southernelsweyr/els_dg_sanctuary02_base_0" },
    { id = 6394, x = 0.5063671470, y = 0.3753636181, map = "southernelsweyr/els_dragonguard_island01_base_0" },
    { id = 6399, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" },
    { id = 6403, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" },
    { id = 6404, x = 0.5004334450, y = 0.3587570190, map = "southernelsweyr/els_dragonguard_island01_base_0" },
    { id = 6393, x = -1, y = -1, map = "" },
    { id = 6397, x = -1, y = -1, map = "" }, -- skill point
  },
  [6399] = {
    { id = 6401, x = 0.5821303725, y = 0.5995892286, map = "southernelsweyr/senchal_base_0" },
    { id = 6409, x = 0.9153884053, y = 0.3462212086, map = "southernelsweyr/els_dg_sanctuary02_base_0" },
    { id = 6394, x = 0.5063671470, y = 0.3753636181, map = "southernelsweyr/els_dragonguard_island01_base_0" },
    { id = 6399, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" }, -- skill point
  },
  [6402] = {
    { id = 6401, x = 0.5821303725, y = 0.5995892286, map = "southernelsweyr/senchal_base_0" },
    { id = 6409, x = 0.9153884053, y = 0.3462212086, map = "southernelsweyr/els_dg_sanctuary02_base_0" },
    { id = 6394, x = 0.5063671470, y = 0.3753636181, map = "southernelsweyr/els_dragonguard_island01_base_0" },
    { id = 6399, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" },
    { id = 6403, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" },
    { id = 6404, x = 0.5004334450, y = 0.3587570190, map = "southernelsweyr/els_dragonguard_island01_base_0" },
    { id = 6393, x = -1, y = -1, map = "" },
    { id = 6397, x = -1, y = -1, map = "" },
    { id = 6402, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" }, -- skill point
  },
  [6403] = {
    { id = 6401, x = 0.5821303725, y = 0.5995892286, map = "southernelsweyr/senchal_base_0" },
    { id = 6409, x = 0.9153884053, y = 0.3462212086, map = "southernelsweyr/els_dg_sanctuary02_base_0" },
    { id = 6394, x = 0.5063671470, y = 0.3753636181, map = "southernelsweyr/els_dragonguard_island01_base_0" },
    { id = 6399, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" },
    { id = 6403, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" }, -- skill point
  },
  [6404] = {
    { id = 6401, x = 0.5821303725, y = 0.5995892286, map = "southernelsweyr/senchal_base_0" },
    { id = 6409, x = 0.9153884053, y = 0.3462212086, map = "southernelsweyr/els_dg_sanctuary02_base_0" },
    { id = 6394, x = 0.5063671470, y = 0.3753636181, map = "southernelsweyr/els_dragonguard_island01_base_0" },
    { id = 6399, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" },
    { id = 6403, x = -1, y = -1, map = "southernelsweyr/els_dg_sanctuary_base_0" },
    { id = 6404, x = 0.5004334450, y = 0.3587570190, map = "southernelsweyr/els_dragonguard_island01_base_0" }, -- skill point
  },
  [6409] = {
    { id = 6401, x = 0.5821303725, y = 0.5995892286, map = "southernelsweyr/senchal_base_0" },
    { id = 6409, x = 0.9153884053, y = 0.3462212086, map = "southernelsweyr/els_dg_sanctuary02_base_0" }, -- skill point
  },
  [6466] = {
    { id = 6467, x = 0.7005860209, y = 0.5199787021, map = "skyrim/skrtut_deepwoodvale_base_0" },
    { id = 6476, x = 0.3403919637, y = 0.3197782636, map = "skyrim/westernskryim_base_0" },
    { id = 6462, x = 0.2145856470, y = 0.4814524651, map = "skyrim/solitudecity_base_0" },
    { id = 6466, x = 0.8552749157, y = 0.7178165317, map = "skyrim/solitudecity_base_0" }, -- skill point
  },
  [6476] = {
    { id = 6467, x = 0.7005860209, y = 0.5199787021, map = "skyrim/skrtut_deepwoodvale_base_0" },
    { id = 6476, x = 0.3403919637, y = 0.3197782636, map = "skyrim/westernskryim_base_0" }, -- skill point
  },
  [6481] = {
    { id = 6467, x = 0.7005860209, y = 0.5199787021, map = "skyrim/skrtut_deepwoodvale_base_0" },
    { id = 6476, x = 0.3403919637, y = 0.3197782636, map = "skyrim/westernskryim_base_0" },
    { id = 6462, x = 0.2145856470, y = 0.4814524651, map = "skyrim/solitudecity_base_0" },
    { id = 6466, x = 0.8552749157, y = 0.7178165317, map = "skyrim/solitudecity_base_0" },
    { id = 6456, x = 0.8512064219, y = 0.7230163217, map = "skyrim/solitudecity_base_0" },
    { id = 6464, x = 0.8252942562, y = 0.7552379370, map = "skyrim/solitudecity_base_0" },
    { id = 6481, x = 0.2784195840, y = 0.3430585563, map = "skyrim/solitudecity_base_0" }, -- skill point
  },
  [6547] = {
    { id = 6550, x = 0.3465833962, y = 0.4786488414, map = "reach/reach_base_0" },
    { id = 6551, x = 0.3413461447, y = 0.3302401602, map = "reach/markunderstonekeep_base_0" },
    { id = 6547, x = 0.3658372164, y = 0.2054186314, map = "reach/u28_blackreach_base_0" }, -- skill point
  },
  [6548] = {
    { id = 6550, x = 0.3465833962, y = 0.4786488414, map = "reach/reach_base_0" },
    { id = 6551, x = 0.3413461447, y = 0.3302401602, map = "reach/markunderstonekeep_base_0" },
    { id = 6547, x = 0.3658372164, y = 0.2054186314, map = "reach/u28_blackreach_base_0" },
    { id = 6548, x = 0.5615376234, y = 0.5216572881, map = "reach/reach_base_0" }, -- skill point
  },
  [6551] = {
    { id = 6550, x = 0.3465833962, y = 0.4786488414, map = "reach/reach_base_0" },
    { id = 6551, x = 0.3413461447, y = 0.3302401602, map = "reach/markunderstonekeep_base_0" }, -- skill point
  },
  [6552] = {
    { id = 6467, x = 0.7005860209, y = 0.5199787021, map = "skyrim/skrtut_deepwoodvale_base_0" },
    { id = 6476, x = 0.3403919637, y = 0.3197782636, map = "skyrim/westernskryim_base_0" },
    { id = 6462, x = 0.2145856470, y = 0.4814524651, map = "skyrim/solitudecity_base_0" },
    { id = 6466, x = 0.8552749157, y = 0.7178165317, map = "skyrim/solitudecity_base_0" },
    { id = 6456, x = 0.8512064219, y = 0.7230163217, map = "skyrim/solitudecity_base_0" },
    { id = 6464, x = 0.8252942562, y = 0.7552379370, map = "skyrim/solitudecity_base_0" },
    { id = 6481, x = 0.2784195840, y = 0.3430585563, map = "skyrim/solitudecity_base_0" },
    { id = 6552, x = 0.7047147155, y = 0.6162623763, map = "reach/markarthcity_base_0" }, -- skill point
  },
  [6554] = {
    { id = 6550, x = 0.3465833962, y = 0.4786488414, map = "reach/reach_base_0" },
    { id = 6551, x = 0.3413461447, y = 0.3302401602, map = "reach/markunderstonekeep_base_0" },
    { id = 6547, x = 0.3658372164, y = 0.2054186314, map = "reach/u28_blackreach_base_0" },
    { id = 6554, x = 0.5607072711, y = 0.5147185326, map = "reach/reach_base_0" }, -- skill point
  },
  [6560] = {
    { id = 6467, x = 0.7005860209, y = 0.5199787021, map = "skyrim/skrtut_deepwoodvale_base_0" },
    { id = 6476, x = 0.3403919637, y = 0.3197782636, map = "skyrim/westernskryim_base_0" },
    { id = 6462, x = 0.2145856470, y = 0.4814524651, map = "skyrim/solitudecity_base_0" },
    { id = 6466, x = 0.8552749157, y = 0.7178165317, map = "skyrim/solitudecity_base_0" },
    { id = 6456, x = 0.8512064219, y = 0.7230163217, map = "skyrim/solitudecity_base_0" },
    { id = 6464, x = 0.8252942562, y = 0.7552379370, map = "skyrim/solitudecity_base_0" },
    { id = 6481, x = 0.2784195840, y = 0.3430585563, map = "skyrim/solitudecity_base_0" },
    { id = 6552, x = 0.7047147155, y = 0.6162623763, map = "reach/markarthcity_base_0" },
    { id = 6560, x = 0.5729511380, y = 0.4517771900, map = "reach/u28_orrerychamber_base_0" }, -- skill point
  },
  [6566] = {
    { id = 6550, x = 0.3465833962, y = 0.4786488414, map = "reach/reach_base_0" },
    { id = 6551, x = 0.3413461447, y = 0.3302401602, map = "reach/markunderstonekeep_base_0" },
    { id = 6547, x = 0.3658372164, y = 0.2054186314, map = "reach/u28_blackreach_base_0" },
    { id = 6554, x = 0.5607072711, y = 0.5147185326, map = "reach/reach_base_0" },
    { id = 6566, x = 0.1454301625, y = 0.4370548427, map = "reach/u28_blackreach_base_0" }, -- skill point
  },
  [6570] = {
    { id = 6467, x = 0.7005860209, y = 0.5199787021, map = "skyrim/skrtut_deepwoodvale_base_0" },
    { id = 6476, x = 0.3403919637, y = 0.3197782636, map = "skyrim/westernskryim_base_0" },
    { id = 6462, x = 0.2145856470, y = 0.4814524651, map = "skyrim/solitudecity_base_0" },
    { id = 6466, x = 0.8552749157, y = 0.7178165317, map = "skyrim/solitudecity_base_0" },
    { id = 6456, x = 0.8512064219, y = 0.7230163217, map = "skyrim/solitudecity_base_0" },
    { id = 6464, x = 0.8252942562, y = 0.7552379370, map = "skyrim/solitudecity_base_0" },
    { id = 6481, x = 0.2784195840, y = 0.3430585563, map = "skyrim/solitudecity_base_0" },
    { id = 6552, x = 0.7047147155, y = 0.6162623763, map = "reach/markarthcity_base_0" },
    { id = 6560, x = 0.5729511380, y = 0.4517771900, map = "reach/u28_orrerychamber_base_0" },
    { id = 6570, x = 0.7015032172, y = 0.6119234562, map = "reach/markarthcity_base_0" }, -- skill point
  },
  [6616] = {
    { id = 6615, x = 0.4732389748, y = 0.0773304552, map = "blackwood/u30_leyawiincity_base_0" },
    { id = 6616, x = 0.8662417531, y = 0.6619018316, map = "blackwood/u30_leyawiincity_base_0" }, -- skill point
  },
  [6619] = {
    { id = 6615, x = 0.4732389748, y = 0.0773304552, map = "blackwood/u30_leyawiincity_base_0" },
    { id = 6616, x = 0.8662417531, y = 0.6619018316, map = "blackwood/u30_leyawiincity_base_0" },
    { id = 6630, x = 0.7771945596, y = 0.5393213630, map = "blackwood/u30_leyawiincity_base_0" },
    { id = 6619, x = 0.6391054392, y = 0.3870710731, map = "blackwood/u30_gideoncity_base_0" }, -- skill point
  },
  [6660] = {
    { id = 6615, x = 0.4732389748, y = 0.0773304552, map = "blackwood/u30_leyawiincity_base_0" },
    { id = 6616, x = 0.8662417531, y = 0.6619018316, map = "blackwood/u30_leyawiincity_base_0" },
    { id = 6630, x = 0.7771945596, y = 0.5393213630, map = "blackwood/u30_leyawiincity_base_0" },
    { id = 6619, x = 0.6391054392, y = 0.3870710731, map = "blackwood/u30_gideoncity_base_0" },
    { id = 6617, x = 0.6297444701, y = 0.3859614134, map = "blackwood/u30_gideoncity_base_0" },
    { id = 6614, x = 0.6301143765, y = 0.3846810460, map = "blackwood/u30_gideoncity_base_0" },
    { id = 6660, x = 0.2885480523, y = 0.2897394001, map = "blackwood/blackwood_base_0" }, -- skill point
  },
  [6693] = {
    { id = 6723, x = 0.5719507933, y = 0.7916684151, map = "deadlands/u32_fargrave_base_0" },
    { id = 6724, x = 0.5136011243, y = 0.2995912731, map = "deadlands/u32_fargrave_base_0" },
    { id = 6707, x = 0.4569016993, y = 0.3213578165, map = "deadlands/u32_fargrave_base_0" },
    { id = 6708, x = 0.7087277770, y = 0.4545153677, map = "deadlands/u32deadlandszone_base_0" },
    { id = 6699, x = 0.4613023102, y = 0.3175723255, map = "deadlands/u32_fargrave_base_0" },
    { id = 6700, x = 0.4598768651, y = 0.3207249343, map = "deadlands/u32_fargrave_base_0" },
    { id = 6696, x = 0.4597881436, y = 0.3199323416, map = "deadlands/u32_fargrave_base_0" },
    { id = 6697, x = 0.4566710293, y = 0.3199500740, map = "deadlands/u32_fargrave_base_0" },
    { id = 6693, x = 0.7067619562, y = 0.4542667568, map = "deadlands/u32deadlandszone_base_0" }, -- skill point
  },
  [6696] = {
    { id = 6723, x = 0.5719507933, y = 0.7916684151, map = "deadlands/u32_fargrave_base_0" },
    { id = 6724, x = 0.5136011243, y = 0.2995912731, map = "deadlands/u32_fargrave_base_0" },
    { id = 6707, x = 0.4569016993, y = 0.3213578165, map = "deadlands/u32_fargrave_base_0" },
    { id = 6708, x = 0.7087277770, y = 0.4545153677, map = "deadlands/u32deadlandszone_base_0" },
    { id = 6699, x = 0.4613023102, y = 0.3175723255, map = "deadlands/u32_fargrave_base_0" },
    { id = 6700, x = 0.4598768651, y = 0.3207249343, map = "deadlands/u32_fargrave_base_0" },
    { id = 6696, x = 0.4597881436, y = 0.3199323416, map = "deadlands/u32_fargrave_base_0" }, -- skill point
  },
  [6697] = {
    { id = 6723, x = 0.5719507933, y = 0.7916684151, map = "deadlands/u32_fargrave_base_0" },
    { id = 6724, x = 0.5136011243, y = 0.2995912731, map = "deadlands/u32_fargrave_base_0" },
    { id = 6707, x = 0.4569016993, y = 0.3213578165, map = "deadlands/u32_fargrave_base_0" },
    { id = 6708, x = 0.7087277770, y = 0.4545153677, map = "deadlands/u32deadlandszone_base_0" },
    { id = 6699, x = 0.4613023102, y = 0.3175723255, map = "deadlands/u32_fargrave_base_0" },
    { id = 6700, x = 0.4598768651, y = 0.3207249343, map = "deadlands/u32_fargrave_base_0" },
    { id = 6696, x = 0.4597881436, y = 0.3199323416, map = "deadlands/u32_fargrave_base_0" },
    { id = 6697, x = 0.4566710293, y = 0.3199500740, map = "deadlands/u32_fargrave_base_0" }, -- skill point
  },
  [6699] = {
    { id = 6723, x = 0.5719507933, y = 0.7916684151, map = "deadlands/u32_fargrave_base_0" },
    { id = 6724, x = 0.5136011243, y = 0.2995912731, map = "deadlands/u32_fargrave_base_0" },
    { id = 6707, x = 0.4569016993, y = 0.3213578165, map = "deadlands/u32_fargrave_base_0" },
    { id = 6708, x = 0.7087277770, y = 0.4545153677, map = "deadlands/u32deadlandszone_base_0" },
    { id = 6699, x = 0.4613023102, y = 0.3175723255, map = "deadlands/u32_fargrave_base_0" }, -- skill point
  },
  [6700] = {
    { id = 6723, x = 0.5719507933, y = 0.7916684151, map = "deadlands/u32_fargrave_base_0" },
    { id = 6724, x = 0.5136011243, y = 0.2995912731, map = "deadlands/u32_fargrave_base_0" },
    { id = 6707, x = 0.4569016993, y = 0.3213578165, map = "deadlands/u32_fargrave_base_0" },
    { id = 6708, x = 0.7087277770, y = 0.4545153677, map = "deadlands/u32deadlandszone_base_0" },
    { id = 6699, x = 0.4613023102, y = 0.3175723255, map = "deadlands/u32_fargrave_base_0" },
    { id = 6700, x = 0.4598768651, y = 0.3207249343, map = "deadlands/u32_fargrave_base_0" }, -- skill point
  },
  [6707] = {
    { id = 6723, x = 0.5719507933, y = 0.7916684151, map = "deadlands/u32_fargrave_base_0" },
    { id = 6724, x = 0.5136011243, y = 0.2995912731, map = "deadlands/u32_fargrave_base_0" },
    { id = 6707, x = 0.4569016993, y = 0.3213578165, map = "deadlands/u32_fargrave_base_0" }, -- skill point
  },
  [6708] = {
    { id = 6723, x = 0.5719507933, y = 0.7916684151, map = "deadlands/u32_fargrave_base_0" },
    { id = 6724, x = 0.5136011243, y = 0.2995912731, map = "deadlands/u32_fargrave_base_0" },
    { id = 6707, x = 0.4569016993, y = 0.3213578165, map = "deadlands/u32_fargrave_base_0" },
    { id = 6708, x = 0.7087277770, y = 0.4545153677, map = "deadlands/u32deadlandszone_base_0" }, -- skill point
  },
  [6724] = {
    { id = 6723, x = 0.5719507933, y = 0.7916684151, map = "deadlands/u32_fargrave_base_0" },
    { id = 6724, x = 0.5136011243, y = 0.2995912731, map = "deadlands/u32_fargrave_base_0" }, -- skill point
  },
  [6753] = {
    { id = 6752, x = 0.4729067087, y = 0.4067583680, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6753, x = 0.7392344475, y = 0.4727272689, map = "systres/u34_gonfalonbaycity_base_0" }, -- skill point
  },
  [6765] = {
    { id = 6752, x = 0.4729067087, y = 0.4067583680, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6753, x = 0.7392344475, y = 0.4727272689, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6754, x = 0.7432416081, y = 0.4383971393, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6764, x = 0.7377990484, y = 0.4460526407, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6765, x = 0.7382774949, y = 0.4163277447, map = "systres/u34_gonfalonbaycity_base_0" }, -- skill point
  },
  [6781] = {
    { id = 6752, x = 0.4729067087, y = 0.4067583680, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6753, x = 0.7392344475, y = 0.4727272689, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6754, x = 0.7432416081, y = 0.4383971393, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6764, x = 0.7377990484, y = 0.4460526407, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6765, x = 0.7382774949, y = 0.4163277447, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6766, x = 0.7433612347, y = 0.4381578863, map = "systres/u34_gonfalonbaycity_base_0" },
    { id = 6781, x = 0.3113705814, y = 0.6564498544, map = "systres/u34_systreszone_base_0" }, -- skill point
  },
  [6847] = {
    { id = 6849, x = 0.6552308798, y = 0.4478363991, map = "galen/u36_vastyrcity_base_0" },
    { id = 6850, x = 0.1887620687, y = 0.5548726916, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6855, x = 0.1975416988, y = 0.5618963838, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6859, x = 0.2765455842, y = 0.2372009456, map = "galen/u36_galenisland_base_0" },
    { id = 6852, x = 0.2151009589, y = 0.5460930467, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6853, x = 0.2036874443, y = 0.5531167984, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6847, x = -1, y = -1, map = "" }, -- skill point
  },
  [6848] = {
    { id = 6849, x = 0.6552308798, y = 0.4478363991, map = "galen/u36_vastyrcity_base_0" },
    { id = 6850, x = 0.1887620687, y = 0.5548726916, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6855, x = 0.1975416988, y = 0.5618963838, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6859, x = 0.2765455842, y = 0.2372009456, map = "galen/u36_galenisland_base_0" },
    { id = 6852, x = 0.2151009589, y = 0.5460930467, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6853, x = 0.2036874443, y = 0.5531167984, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6847, x = -1, y = -1, map = "" },
    { id = 6848, x = -1, y = -1, map = "" }, -- skill point
  },
  [6850] = {
    { id = 6849, x = 0.6552308798, y = 0.4478363991, map = "galen/u36_vastyrcity_base_0" },
    { id = 6850, x = 0.1887620687, y = 0.5548726916, map = "galen/u36_vastyrcitycastle_base_0" }, -- skill point
  },
  [6852] = {
    { id = 6849, x = 0.6552308798, y = 0.4478363991, map = "galen/u36_vastyrcity_base_0" },
    { id = 6850, x = 0.1887620687, y = 0.5548726916, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6855, x = 0.1975416988, y = 0.5618963838, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6859, x = 0.2765455842, y = 0.2372009456, map = "galen/u36_galenisland_base_0" },
    { id = 6852, x = 0.2151009589, y = 0.5460930467, map = "galen/u36_vastyrcitycastle_base_0" }, -- skill point
  },
  [6853] = {
    { id = 6849, x = 0.6552308798, y = 0.4478363991, map = "galen/u36_vastyrcity_base_0" },
    { id = 6850, x = 0.1887620687, y = 0.5548726916, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6855, x = 0.1975416988, y = 0.5618963838, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6859, x = 0.2765455842, y = 0.2372009456, map = "galen/u36_galenisland_base_0" },
    { id = 6852, x = 0.2151009589, y = 0.5460930467, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6853, x = 0.2036874443, y = 0.5531167984, map = "galen/u36_vastyrcitycastle_base_0" }, -- skill point
  },
  [6855] = {
    { id = 6849, x = 0.6552308798, y = 0.4478363991, map = "galen/u36_vastyrcity_base_0" },
    { id = 6850, x = 0.1887620687, y = 0.5548726916, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6855, x = 0.1975416988, y = 0.5618963838, map = "galen/u36_vastyrcitycastle_base_0" }, -- skill point
  },
  [6859] = {
    { id = 6849, x = 0.6552308798, y = 0.4478363991, map = "galen/u36_vastyrcity_base_0" },
    { id = 6850, x = 0.1887620687, y = 0.5548726916, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6855, x = 0.1975416988, y = 0.5618963838, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6859, x = 0.2765455842, y = 0.2372009456, map = "galen/u36_galenisland_base_0" }, -- skill point
  },
  [6894] = {
    { id = 6849, x = 0.6552308798, y = 0.4478363991, map = "galen/u36_vastyrcity_base_0" },
    { id = 6850, x = 0.1887620687, y = 0.5548726916, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6855, x = 0.1975416988, y = 0.5618963838, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6859, x = 0.2765455842, y = 0.2372009456, map = "galen/u36_galenisland_base_0" },
    { id = 6852, x = 0.2151009589, y = 0.5460930467, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6853, x = 0.2036874443, y = 0.5531167984, map = "galen/u36_vastyrcitycastle_base_0" },
    { id = 6847, x = -1, y = -1, map = "" },
    { id = 6848, x = -1, y = -1, map = "" },
    { id = 6894, x = -1, y = -1, map = "" }, -- skill point
  },
  [6975] = {
    { id = 6971, x = 0.4898484349, y = 0.5050149560, map = "telvanni/u38_necrom_base_0" },
    { id = 6975, x = 0.5798045993, y = 0.5289337635, map = "telvanni/u38_necrom_base_0" }, -- skill point
  },
  [6976] = {
    { id = 6971, x = 0.4898484349, y = 0.5050149560, map = "telvanni/u38_necrom_base_0" },
    { id = 6975, x = 0.5798045993, y = 0.5289337635, map = "telvanni/u38_necrom_base_0" },
    { id = 6976, x = 0.4113605320, y = 0.4395471513, map = "apocrypha/u38_ciphersmidden_city_base_0" }, -- skill point
  },
  [6977] = {
    { id = 6971, x = 0.4898484349, y = 0.5050149560, map = "telvanni/u38_necrom_base_0" },
    { id = 6975, x = 0.5798045993, y = 0.5289337635, map = "telvanni/u38_necrom_base_0" },
    { id = 6976, x = 0.4113605320, y = 0.4395471513, map = "apocrypha/u38_ciphersmidden_city_base_0" },
    { id = 7025, x = 0.5823164582, y = 0.5192688704, map = "telvanni/u38_necrom_base_0" },
    { id = 6991, x = 0.4565293789, y = 0.4006246328, map = "apocrypha/u38_ciphersmidden_city_base_0" },
    { id = 6977, x = 0.4032012522, y = 0.4443099797, map = "apocrypha/u38_ciphersmidden_city_base_0" }, -- skill point
  },
  [6991] = {
    { id = 6971, x = 0.4898484349, y = 0.5050149560, map = "telvanni/u38_necrom_base_0" },
    { id = 6975, x = 0.5798045993, y = 0.5289337635, map = "telvanni/u38_necrom_base_0" },
    { id = 6976, x = 0.4113605320, y = 0.4395471513, map = "apocrypha/u38_ciphersmidden_city_base_0" },
    { id = 7025, x = 0.5823164582, y = 0.5192688704, map = "telvanni/u38_necrom_base_0" },
    { id = 6991, x = 0.4565293789, y = 0.4006246328, map = "apocrypha/u38_ciphersmidden_city_base_0" }, -- skill point
  },
  [7025] = {
    { id = 6971, x = 0.4898484349, y = 0.5050149560, map = "telvanni/u38_necrom_base_0" },
    { id = 6975, x = 0.5798045993, y = 0.5289337635, map = "telvanni/u38_necrom_base_0" },
    { id = 6976, x = 0.4113605320, y = 0.4395471513, map = "apocrypha/u38_ciphersmidden_city_base_0" },
    { id = 7025, x = 0.5823164582, y = 0.5192688704, map = "telvanni/u38_necrom_base_0" }, -- skill point
  },
  [7072] = {
    { id = 7071, x = 0.1399838328, y = 0.6785500050, map = "westweald/westwealdoverland_base_0" },
    { id = 7072, x = 0.4376652837, y = 0.7362687588, map = "westweald/u42_skingrad_base_0" }, -- skill point
  },
  [7073] = {
    { id = 7071, x = 0.1399838328, y = 0.6785500050, map = "westweald/westwealdoverland_base_0" },
    { id = 7072, x = 0.4376652837, y = 0.7362687588, map = "westweald/u42_skingrad_base_0" },
    { id = 7073, x = 0.4366736412, y = 0.7331974506, map = "westweald/u42_skingrad_base_0" }, -- skill point
  },
  [7074] = {
    { id = 7071, x = 0.1399838328, y = 0.6785500050, map = "westweald/westwealdoverland_base_0" },
    { id = 7072, x = 0.4376652837, y = 0.7362687588, map = "westweald/u42_skingrad_base_0" },
    { id = 7073, x = 0.4366736412, y = 0.7331974506, map = "westweald/u42_skingrad_base_0" },
    { id = 7074, x = 0.4376101792, y = 0.7381693721, map = "westweald/u42_skingrad_base_0" }, -- skill point
  },
  [7075] = {
    { id = 7071, x = 0.1399838328, y = 0.6785500050, map = "westweald/westwealdoverland_base_0" },
    { id = 7072, x = 0.4376652837, y = 0.7362687588, map = "westweald/u42_skingrad_base_0" },
    { id = 7073, x = 0.4366736412, y = 0.7331974506, map = "westweald/u42_skingrad_base_0" },
    { id = 7074, x = 0.4376101792, y = 0.7381693721, map = "westweald/u42_skingrad_base_0" },
    { id = 7075, x = 0.4367562830, y = 0.7333489656, map = "westweald/u42_skingrad_base_0" }, -- skill point
  },
  [7076] = {
    { id = 7071, x = 0.1399838328, y = 0.6785500050, map = "westweald/westwealdoverland_base_0" },
    { id = 7072, x = 0.4376652837, y = 0.7362687588, map = "westweald/u42_skingrad_base_0" },
    { id = 7073, x = 0.4366736412, y = 0.7331974506, map = "westweald/u42_skingrad_base_0" },
    { id = 7074, x = 0.4376101792, y = 0.7381693721, map = "westweald/u42_skingrad_base_0" },
    { id = 7075, x = 0.4367562830, y = 0.7333489656, map = "westweald/u42_skingrad_base_0" },
    { id = 7076, x = 0.4380922318, y = 0.7355112433, map = "westweald/u42_skingrad_base_0" }, -- skill point
  },
  [7077] = {
    { id = 7071, x = 0.1399838328, y = 0.6785500050, map = "westweald/westwealdoverland_base_0" },
    { id = 7072, x = 0.4376652837, y = 0.7362687588, map = "westweald/u42_skingrad_base_0" },
    { id = 7073, x = 0.4366736412, y = 0.7331974506, map = "westweald/u42_skingrad_base_0" },
    { id = 7074, x = 0.4376101792, y = 0.7381693721, map = "westweald/u42_skingrad_base_0" },
    { id = 7075, x = 0.4367562830, y = 0.7333489656, map = "westweald/u42_skingrad_base_0" },
    { id = 7076, x = 0.4380922318, y = 0.7355112433, map = "westweald/u42_skingrad_base_0" },
    { id = 7077, x = 0.4368939996, y = 0.7374118567, map = "westweald/u42_skingrad_base_0" }, -- skill point
  },
  [7078] = {
    { id = 7071, x = 0.1399838328, y = 0.6785500050, map = "westweald/westwealdoverland_base_0" },
    { id = 7072, x = 0.4376652837, y = 0.7362687588, map = "westweald/u42_skingrad_base_0" },
    { id = 7073, x = 0.4366736412, y = 0.7331974506, map = "westweald/u42_skingrad_base_0" },
    { id = 7074, x = 0.4376101792, y = 0.7381693721, map = "westweald/u42_skingrad_base_0" },
    { id = 7075, x = 0.4367562830, y = 0.7333489656, map = "westweald/u42_skingrad_base_0" },
    { id = 7076, x = 0.4380922318, y = 0.7355112433, map = "westweald/u42_skingrad_base_0" },
    { id = 7077, x = 0.4368939996, y = 0.7374118567, map = "westweald/u42_skingrad_base_0" },
    { id = 7078, x = 0.4376514852, y = 0.7377837300, map = "westweald/u42_skingrad_base_0" }, -- skill point
  },
  [7220] = {
    { id = 7104, x = 0.3528536856, y = 0.8098970056, map = "westweald/u42_skingrad_base_0" },
    { id = 7220, x = 0.4348033369, y = 0.1715218723, map = "westweald/u42_base_sc_library_0" }, -- skill point
  },
  [7294] = {
    { id = 7314, x = 0.2156086415, y = 0.5171797276, map = "solstice/u46_sunport_base_0" },
    { id = 7294, x = 0.4029463232, y = 0.6024183631, map = "solstice/u46_sunport_base_0" }, -- skill point
  },
  [7295] = {
    { id = 7314, x = 0.2156086415, y = 0.5171797276, map = "solstice/u46_sunport_base_0" },
    { id = 7295, x = 0.7579937577, y = 0.5096436143, map = "solstice/u46_sunport_base_0" }, -- skill point
  },
  [7296] = {
    { id = 7314, x = 0.2156086415, y = 0.5171797276, map = "solstice/u46_sunport_base_0" },
    { id = 7295, x = 0.7579937577, y = 0.5096436143, map = "solstice/u46_sunport_base_0" },
    { id = 7296, x = 0.7585046887, y = 0.5107506514, map = "solstice/u46_sunport_base_0" }, -- skill point
  },
  [7329] = {
    { id = 7284, x = -1, y = -1, map = "" },
    { id = 7329, x = -1, y = -1, map = "" }, -- skill point
  },
  [7393] = {
    { id = 7286, x = -1, y = -1, map = "" },
    { id = 7393, x = -1, y = -1, map = "" }, -- skill point
  },
}
