CollectThemAllData_Others_DLCs = {
    name = "DLCs",
    source = "Others",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_DLC] = {
            { name = "Blackwood" },
            { name = "Elsweyr" },
            { name = "Gold Road" },
            { name = "Greymoor" },
            { name = "High Isle" },
            { name = "Morrowind" },
            { name = "Necrom" },
            { name = "Solstice" },
            { name = "Summerset" },

            { name = "Imperial City", info = "Imperial City Collector's Bundle" },
            { name = "Orsinium", info = "Orsinium Collector's Bundle" },
            { name = "Hew's Bane Thieves Guild", info = "Thieves Guild Collector's Edition" },
            { name = "Dark Brotherhood", info = "Dark Brotherhood Collector's Edition" },
            { name = "Clockwork City", info = "Clockwork City Collector's Bundle" },
            { name = "Murkmire", info = "Murkmire Collector's Bundle" },
            { name = "Dragonhold", info = "Dragonhold Collector's Bundle" },
            { name = "Markarth", info = "Markarth Collector's Bundle" },
            { name = "The Deadlands", info = "The Deadlands Collector's Bundle" },
            { name = "Firesong", info = "Firesong Collector's Bundle" },
    
            -- { name = "White-Gold Tower", info = "Imperial City Collector's Bundle" },
            -- { name = "Imperial City Prison", info = "Imperial City Collector's Bundle" },
            { name = "Cradle of Shadows", info = "Shadows of the Hist Collector's Bundle" },
            { name = "Ruins of Mazzatun", info = "Shadows of the Hist Collector's Bundle" },
            { name = "Bloodroot Forge", info = "Horns of the Reach Collector's Bundle" },
            { name = "Falkreath Hold", info = "Horns of the Reach Collector's Bundle" },
            { name = "Fang Lair", info = "Dragon Bones Collector's Bundle" },
            { name = "Scalecaller Peak", info = "Dragon Bones Collector's Bundle" },
            { name = "March of Sacrifices", info = "Wolfhunter Collector's Bundle" },
            { name = "Moon Hunter Keep", info = "Wolfhunter Collector's Bundle" },
            { name = "Depths of Malatar", info = "Wrathstone Collector's Bundle" },
            { name = "Frostvault", info = "Wrathstone Collector's Bundle" },
            { name = "Moongrave Fane", info = "Scalebreaker Collector's Bundle" },
            { name = "Lair of Maarselok", info = "Scalebreaker Collector's Bundle" },
            { name = "Icereach", info = "Harrowstorm Collector's Bundle" },
            { name = "Unhallowed Grave", info = "Harrowstorm Collector's Bundle" },
            { name = "Stone Garden", info = "Stonethorn Collector's Bundle" },
            { name = "Castle Thorn", info = "Stonethorn Collector's Bundle" },
            { name = "The Cauldron", info = "Flames of Ambition Collector's Bundle" },
            { name = "Black Drake Villa", info = "Flames of Ambition Collector's Bundle" },
            { name = "The Dread Cellar", info = "Waking Flame Collector's Bundle" },
            { name = "Red Petal Bastion", info = "Waking Flame Collector's Bundle" },
            { name = "Coral Aerie", info = "Ascending Tide Collector's Bundle" },
            { name = "Shipwright's Regret", info = "Ascending Tide Collector's Bundle" },
            { name = "Earthen Root Enclave", info = "Lost Depths Collector's Bundle" },
            { name = "Graven Deep", info = "Lost Depths Collector's Bundle" },
            { name = "Bal Sunnar", info = "Scribes of Fate Collector's Bundle" },
            { name = "Scrivener's Hall", info = "Scribes of Fate Collector's Bundle" },
            { name = "Bedlam Veil", info = "Scions of Ithelia Collector's Pack" },
            { name = "Oathsworn Pit", info = "Scions of Ithelia Collector's Pack" },

            { name = "Exiled Redoubt", info = "Fallen Banners DLC" },
            { name = "Lep Seclusa", info = "Fallen Banners DLC" },
            { name = "Black Gem Foundry", info = "Feast of Shadows DLC" },
            { name = "Naj-Caldeesh", info = "Feast of Shadows DLC" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "10-Year Lion Guard Steed", info = "Available by pre-ordering the 2025 Content Pass or 2025 Premium Edition" },
            { name = "Skulltooth Coastal Durzog", info = "Bonus award available by purchasing the 2025 Content Pass or the 2025 Premium Edition." },
            { name = "Holdbreaker Warhorse", info = "Available as a pre-purchase bonus for the Greymoor Chapter." },
            { name = "Nagahide Welwa Ravager", info = "Available as a bonus to anyone who pre-ordered the Blackwood Chapter." },
            { name = "Nightmare Senche", info = "Free with any pre-order of the Summerset Chapter" },
            { name = "Palefrost Elk Mount", info = "Available as a pre-purchase bonus for the High Isle Chapter." },
            { name = "Rahd-m'Athra", info = "Was acquired by pre-ordering any edition of Elsweyr." },
            { name = "Sadrith Mora Spore Steed", info = "Available as a bonus to anyone who pre-ordered the Necrom Chapter." },
            { name = "Welkyndstone Ruins Wolf", info = "Being distributed to players who pre-purchase the Gold Road chapter." },

            { name = "Mind-Shriven Horse", info = "Imperial City Collector's Bundle" },
            { name = "Cave Bear", info = "Orsinium Collector's Bundle" },
            { name = "Hammerfell Camel", info = "Thieves Guild Collector's Edition" },
            { name = "Highland Wolf", info = "Dark Brotherhood Collector's Edition" },
            { name = "Hist Guar", info = "Shadows of the Hist Collector's Bundle" },
            { name = "Karthwolf Charger", info = "Horns of the Reach Collector's Bundle" },
            { name = "Kagouti Fabricant", info = "Clockwork City Collector's Bundle" },
            { name = "Fang Lair Courser", info = "Dragon Bones Collector's Bundle" },
            { name = "Silver Dawn Argent Charger", info = "Wolfhunter Collector's Bundle" },
            { name = "Shellback Warhorse", info = "Murkmire Collector's Bundle" },
            { name = "Treasure Hunter's Horse", info = "Wrathstone Collector's Bundle" },
            { name = "Ancient Dragon Hunter Horse", info = "Scalebreaker Collector's Bundle" },
            { name = "Legendary Dragon Horse", info = "Dragonhold Collector's Bundle" },
            { name = "Pyre Watch Jackal", info = "Harrowstorm Collector's Bundle" },
            { name = "Frostborn Durzog Mangler", info = "Stonethorn Collector's Bundle" },
            { name = "Chaurus Egg Chaser's Horse", info = "Markarth Collector's Bundle" },
            { name = "Falinesti's Faithful Totem Elk", info = "Flames of Ambition Collector's Bundle" },
            { name = "Silver Rose Senche-Serval", info = "Waking Flame Collector's Bundle" },
            { name = "Nightmare Bear", info = "The Deadlands Collector's Bundle" },
            { name = "Dreadsail Howler", info = "Ascending Tide Collector's Bundle" },
            { name = "Turquoise War Pangrit", info = "Lost Depths Collector's Bundle" },
            { name = "Cinderstone Kagouti", info = "Firesong Collector's Bundle" },
            { name = "Antecedent Scholar's Guar", info = "Scribes of Fate Collector's Bundle" },
            { name = "Ashbone Sabre Cat", info = "Scions of Ithelia Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "10-Year Anniversary Mudcrab", info = "Available as a pre-purchase bonus for the 2025 Content Pass." },
            { name = "Golden Eagle", info = "Available by purchasing the 2025 Content Pass or the 2025 Premium Edition." },
            { name = "Nightmare Bear Cub", info = "Pre-order bonus for those who pre-ordered the Blackwood Chapter." },
            { name = "Palefrost Elk Fawn", info = "Available as a pre-purchase bonus for the High Isle Chapter" },
            { name = "Sadrith Mora Spore Pony", info = "Available as a bonus to anyone who pre-ordered the Necrom Chapter." },
            { name = "Welkyndstone Ruins Pup", info = "Was distributed to players who pre-purchased the Gold Road chapter" },

            { name = "Daedrat", info = "Imperial City Collector's Bundle" },
            { name = "Cave Bear Cub", info = "Orsinium Collector's Bundle" },
            { name = "Kindlespit Dragon Frog", info = "Thieves Guild Collector's Edition" },
            { name = "Sylvan Nixad", info = "Dark Brotherhood Collector's Edition" },
            { name = "Haj Mota Hatchling", info = "Shadows of the Hist Collector's Bundle" },
            { name = "Karthwolf Shepherd", info = "Horns of the Reach Collector's Bundle" },
            { name = "Clockwork Skeevaton", info = "Clockwork City Collector's Bundle" },
            { name = "Small Bone Dragon Construct", info = "Dragon Bones Collector's Bundle" },
            { name = "Silver Daenian Werewolf Tracker", info = "Wolfhunter Collector's Bundle" },
            { name = "Cantaloupe Swamp Jelly", info = "Murkmire Collector's Bundle" },
            { name = "Carnelian Theodolite", info = "Wrathstone Collector's Bundle" },
            { name = "Ancient Dragon Hunter Wolf", info = "Scalebreaker Collector's Bundle" },
            { name = "Legendary Dragon Wolf", info = "Dragonhold Collector's Bundle" },
            { name = "Hallin's Jackal", info = "Harrowstorm Collector's Bundle" },
            { name = "Snowsnarl Durzog", info = "Stonethorn Collector's Bundle" },
            { name = "Teacup Chaurus Chitterling", info = "Markarth Collector's Bundle" },
            { name = "Clearspring Striped Fawn", info = "Flames of Ambition Collector's Bundle" },
            { name = "Ironclad Senche-Serval Kitten", info = "Waking Flame Collector's Bundle" },
            { name = "Deadlands Bantam Guar", info = "The Deadlands Collector's Bundle" },
            { name = "Iliac Bay Crab", info = "Ascending Tide Collector's Bundle" },
            { name = "Pangrit Nymphling", info = "Lost Depths Collector's Bundle" },
            { name = "Companion's Wolf Pup", info = "Firesong Collector's Bundle" },
            { name = "Blightlord's Skeever", info = "Scribes of Fate Collector's Bundle" },
            { name = "Ashbone Echalette", info = "Scions of Ithelia Collector's Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Remnant of Meridia's Light", info = "Available by pre-ordering the 2025 Content Pass or 2025 Premium Edition" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Beachside Bask", info = "Available by pre-ordering the 2025 Content Pass or 2025 Premium Edition" },
            { name = "Beachside Drink", info = "Available by pre-ordering the 2025 Content Pass or 2025 Premium Edition" },
            { name = "Teeba Trick", info = "Available by pre-ordering the 2025 Content Pass or 2025 Premium Edition" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Mages Guild Recall", info = "Available by pre-ordering the 2025 Content Pass or 2025 Premium Edition" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Mind-Shriven", info = "Imperial City Collector's Bundle" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
