CollectThemAllData_Others_TwitchDrops = {
    name = "Twitch Drops",
    source = "Others",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_DLC] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Auroran Warhorse", info = "Writhing Wall event Twitch drop in October 2025" },
            { name = "Sungold Bay Thoroughbred", info = "For watching a total of 8 hours of ESO content and streamers on participating Twitch channels on June 16, 2022. It was also available as a free promotional reward to NVIDIA GeForce Now members from May 30 to June 30, 2024." },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Imperial War Mastiff", info = "Writhing Wall event Twitch drop in October 2025" },
            { name = "Flame Atronach Pack Wolf", info = "Bethesda's QuakeCon Keynote livestream on Twitch on August 10, 2018" },
            { name = "Flame Atronach Pocket Horse", info = "For watching QuakeCon in August of 2020. /For watching the Blackwood Chapter Preview Event on March 31, 2021" },
            { name = "Flame Atronach Pony Guar", info = "For watching QuakeCon on August 18 and 19, 2022." },
            { name = "Flame Atronach Senche-Jaguar", info = "ESO Panel at QuakeCon live on Twitch on July 27, 2019" },
            { name = "Barnacle-Back Coral Crab", info = "ESO's 2022 Global Reveal Event on January 27, 2022" },
            { name = "Chaosball Cohort", info = "ESO Live: Battlegrounds, In-Game Events & More livestream on September 10, 2024" },
            { name = "Viridescent Dragon Frog", info = "Blackwood Global Reveal Event on January 26, 2021" },
            { name = "Hot Pepper Bantam Guar", info = "Elder Scrolls Online: Elsweyr announcement stream" },
            { name = "Long-Winged Bat", info = "Given for free to those who watched the The Elder Scrolls Online: Greymoor announcement livestream on Twitch" },
            { name = "Nibenese Pony", info = "Gates of Oblivion Year-End Stream on Twitch on October 1, 2021" },
            { name = "Purple Torchbug", info = "ESO High Isle Preview Event on September 19, 2020, also on April 15, 2022" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Pyromancer's Quandary", info = "ESO Global Reveal Event livestream on January 18, 2024. Available via a limited number of codes from Alienware Arena on June 10, 2024." },
            { name = "Ritual Casting", info = "ESO Global Reveal Event livestream on January 25, 2023." },
            { name = "Skingrad Noble Snack", info = "10-Year Anniversary Celebration livestream on April 5, 2024. Free to NVIDIA's GeForce NOW members from August 9 to September 8, 2024." },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Grim Harvester", info = "For watching 4 hours of ESO content and streams by Twitch streamers over on Twitch on June 10, 2022 - June 16, 2022. / Twitch Drops Fest on January 20, 2025 - January 31, 2025" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Moon-and-Star Earrings", info = "Necrom Chapter Preview Event on April 12, 2023" },
        },
    },
}
