CollectThemAllData_Others_ExtraRewards = {
    name = "Extra Rewards",
    source = "Others",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_DLC] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {
            { name = "Senche-Raht Statue, Battle-Bound", info = "Granted in the summer of 2019 as thanks for participating in an Elder Scrolls Online gifting promotion" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Windhelm Cliff Ram", info = "Cliff Ram Pack - promotional bundle available via Prime Gaming or Xbox Game Pass Ultimate from June 28 to September 20, 2022." },
            { name = "Nix-Ox War-Steed", info = "Was given away for free to those who owned the Morrowind Chapter during certain promotional periods. It was first given away to Morrowind owners who logged in at any point from November 17 to 26, 2017." },
            { name = "Noweyr Steed", info = "It was first available in the Realm of Noweyr Pack via Twitch Prime Loot from August 27 through September 24, 2019. It was made available again in the Noweyr Pack via Prime Gaming Loot and Xbox Game Pass Ultimate from August 16 to November 8 2022." },
            { name = "Pineblossom Vale Elk", info = "It was first available during a NVIDIA GeForce promo during January of 2025." },
            { name = "Striped Senche-Tiger", info = "Was rewarded for 300 days of subscription time as part of the discontinued Loyalty Program." },
            { name = "Whiterun Mountain Charger", info = "Tamriel Together Sweepstakes, 25 people who entered the Tamriel Together sweepstakes won a bundle of five in-game mounts" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Devoted Torchbug", info = "Ascent of the Arcanist Reward Bundle - promotional bundle available from July 18 to July 28, 2023. It could be claimed via the Crown Store by players who had purchased the Necrom Chapter and obtained the Neophyte Researcher achievement." },
            { name = "Firebelly Shalk", info = "From August 5 to September 3, 2024, players who had completed the Oblivion Obliterator achievement." },
            { name = "Hot-Blooded Bantam Guar", info = "Granted for attending conventions in-person in 2019. Codes were also available as a possible prize from the Claw Machine located at the 2024 in-person 10th anniversary event in Amsterdam." },
            { name = "Infernium Dwarven Spiderling", info = "It was first made available to users who verified the email associate with their Elder Scrolls Online account and opt in to marketing emails in their account preferences." },
            { name = "10-Year Anniversary Monkey", info = "It was first available from the code \"2025ESODirect\" shown during the 2025 ESO Direct, which can redeemed from the account page, from April 10 until June 20, 2025." },
            { name = "Atmoran Bantam Guar", info = "Available via code redemption, initially after completing an survey received via email from Zenimax. Only a small number of players were contacted in this manner. Codes were also distributed in 2024 as a possible Claw Machine prize at the in-person 10th Anniversary event in Amsterdam." },
            { name = "Azure Fledgling Gryphon", info = "This pet is acquired by redeeming a code acquired through purchase of the Gaming Heads ESO Gryphon plush. The codes can only be redeemed on PC/Mac either in-game or on the official website." },
            { name = "Bristlegut Piglet", info = "Part of official competitions and giveaways in 2014 and 2015. It was also included as part of the Humble Monthly Promotion in 2017." },
            { name = "Crony Scrib", info = "Can be obtained on PC/Mac only via the use of a promotional code included with the official Fighters Guild Journeyman figure from Symbiote Studios" },
            { name = "Eerie Violet Bantam Guar", info = "Promotional pet available via codes distributed by certain ESO streamers." },
            { name = "Flame Skin Salamander", info = "Exclusively available as part of the Newcomer Pack for PC/Mac. It could be purchased on Steam or the online store on the official ESO website." },
            { name = "Frisky Scrib", info = "PS4 exclusive; given to players who pre-ordered ESO: Morrowind through the PlayStation Store" },
            { name = "Galen Wisp", info = " It was available in the Crown Store for free from December 22, 2022 to January 4, 2023. It was made free during the New Life Festival as \"a way to say happy holidays from all of us\" by Zenimax, who called it a season for spreading holiday cheer and giving." },
            { name = "High Hrothgar Wraith", info = "Was given for three months paid subscription as part of the discontinued loyalty program." },
            { name = "Imgakin Monkey", info = "Was given to players who participated in any of the weekend PC beta events." },
            { name = "Loyal Dwarven Sphere", info = "Was given as a loyalty reward for six months paid subscription." },
            { name = "Noweyr Pony", info = "It was first available in the Realm of Noweyr Pack via Twitch Prime Loot from August 27 through September 24, 2019. It was made available again in the Noweyr Pack via Prime Gaming Loot and Xbox Game Pass Ultimate from August 16 to November 8 2022." },
            { name = "Pink Pearl Pig", info = "Available to users who gifted 1,000 Crowns worth of gifts to 2 or more people during the month of February, 2019." },
            { name = "Pink Torchbug", info = "Received via code redemption. Codes for this pet are being given away at raffles during Twitch streams in 2021. Codes have been distributed for giveaways to select ESO streamers and partners, and are also given away during ESO livestreams on Bethesda's Twitch channel." },
            { name = "Pony Guar", info = "A code for the pet comes with the purchase of the official guar plush toy (redeemable only on PC/Mac)." },
            { name = "Rufous Mudcrab", info = "Came with the purchase of the official mudcrab plush toy (redeemable only on PC/Mac)." },
            { name = "Shock Skin Salamander", info = "Was exclusively available as part of the Newcomer Pack for PlayStation, which could be purchased on the PlayStation Store." },
            { name = "Steam-Driven Brassilisk", info = "Was available in the Crown Store for free exclusively to PC/Mac players from November 7, 2017 to January 2, 2018." },
            { name = "Toxin Skin Salamander", info = "Was exclusively available as part of the Newcomer Pack for Xbox, which could be purchased on the Microsoft Store from October 1, 2019 to August 30, 2024." },
            { name = "Vermilion Scuttler", info = "Was previously available as a part of the Explorer's Pack, which was included with every pre-order of ESO and its Imperial Edition. The Explorer's Pack was also temporarily made available again during the Japanese free trial campaign, almost two months after launch in Japan." },
            { name = "Whiterun Wolfhound", info = "Free gift to those who ordered the Imperial Edition on Steam before July 21, 2014. It also comes with the purchase of the official Elder Scrolls Online Nord figurine from Symbiote Studios (redeemable only on PC/Mac; not to be confused with the Funko Pop! Vinyl Nord figurine)." },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Apprentice's Flower Trick", info = "Available from Stream Team giveaways celebrating the release of the Gold Road chapter from June 4 to 9, 2024" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Mask of Cheerful Slaughter", info = "It was given as a reward for having paid for a subscription for nine months in 2015." },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Scrawl of the Arcanist Tattoos", info = "Ascent of the Arcanist Reward Bundle - promotional bundle available from July 18 to July 28, 2023. It could be claimed via the Crown Store by players who had purchased the Necrom Chapter and obtained the Neophyte Researcher achievement. This collectible could be available again in the Gold Cost Bazzaar, because Devoted Torchbug pet from the same bundle already is." },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Druidic Knotwork Face Tattoos", info = "Cliff Ram Pack - promotional bundle available via Prime Gaming or Xbox Game Pass Ultimate from June 28 to September 20, 2022." },
            { name = "Scrawl of the Arcanist Visage", info = "Ascent of the Arcanist Reward Bundle - promotional bundle available from July 18 to July 28, 2023. It could be claimed via the Crown Store by players who had purchased the Necrom Chapter and obtained the Neophyte Researcher achievement. This collectible could be available again in the Gold Cost Bazzaar, because Devoted Torchbug pet from the same bundle already is." },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Effigy Earrings of Saint Vorys", info = "Obtainable for free in the Crown Store as a gift to players from December 21, 2023 to January 4, 2024" },
        },
    },
}
