CollectThemAllData_Others_Unobtainable = {
    name = "Unobtainable",
    source = "Others",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {
            { name = "Larry, Duke of the Dance", info = "Granted to the grand prize winner of the 2020 Tamriel Together Sweepstakes" },
            { name = "Statue of Gloria", info = "Given to the grand prize winner of the Tamriel Together Sweepstakes" },

            { name = "Music Box, Oath of the Keepers", info = "This seems not to be collectible, available in Gold Coast Bazaar" },

            { name = "Barbas", info = "Unreleased" },
            { name = "Filbert Cienne", info = "Unreleased" },
            { name = "Keshu the Black Fin", info = "Unreleased" },
            { name = "Narsis Dren", info = "Unreleased" },

            { name = "Painting: Lair of Maarselok", info = "Unreleased" },
            { name = "Painting: Systres Seaside Manor", info = "Datamined" },
            { name = "Statuette: Imperial Warrior", info = "Datamined" },
            { name = "Statuette: St. Olms the Just", info = "Unreleased" },
            { name = "Statuette: Telvanni Magister", info = "Datamined" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {
            { name = "Allaria Erwen the Exporter", info = "Unreleased" },
            { name = "Cassus Andronicus the Mercenary", info = "Unreleased" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Bonds of Battle Destrier", info = "Distributed to members of Dauntless Bananas, winner of the Tamriel Together guild contest" },
            { name = "Guild's Pride Charger", info = "Distributed to members of Goldleaf Acquisitions, winner of the Tamriel Together guild contest" },

            { name = "Wraithtide Horse", info = "Though it shares the theme of the Wraithtide Crate, for unknown reasons, it is not part of it. This makes it the first crate to not have an Apex horse mount." },

            { name = "Adamant Dwarven Wolf", info = "Unreleased" },
            { name = "Arboreon Elk", info = "Datamined" },
            { name = "Ash-Tipped Durzog", info = "Datamined" },
            { name = "Ashmourning Vvardvark", info = "Unreleased" },
            { name = "Cinder Skeletal Horse", info = "Datamined" },
            { name = "Cinder Skeletal Senche", info = "Datamined" },
            { name = "Daenian Great Ram", info = "Datamined" },
            { name = "Duo-Dynamo Burnished Spider", info = "Unreleased" },
            { name = "Duo-Dynamo Guardian Spider", info = "Datamined" },
            { name = "Frost Draugr Skeletal Wolf", info = "Datamined" },
            { name = "Ghostwhite Vvardvark", info = "Datamined" },
            { name = "Grand Joust Destrier", info = "Unreleased" },
            { name = "Hew's Bane Hyena", info = "Datamined" },
            { name = "Jade-Crown Dragonslayer Horse", info = "Unreleased" },
            { name = "Jouster's Charger", info = "Unreleased" },
            { name = "Kvatch Outrider's Warhorse", info = "Unreleased" },
            { name = "Lavender Guar", info = "Unreleased" },
            { name = "Moonstone Bear", info = "Unreleased" },
            { name = "Plague Husk Senche", info = "Unreleased" },
            { name = "Plague Husk Skeletal Wolf", info = "Datamined" },
            { name = "Psijic Bear V2", info = "Datamined" },
            { name = "Psijic Camel V2", info = "Datamined" },
            { name = "Psijic Guar V2", info = "Datamined" },
            { name = "Psijic Wolf V2", info = "Datamined" },
            { name = "Reindeer", info = "Datamined" },
            { name = "Spellscar Kagouti", info = "Unreleased" },
            { name = "Su-Zahleel Horse-Lizard", info = "Datamined" },
            { name = "Trappers Peak Wolf", info = "Datamined" },
            { name = "Verkarth Senche-Lioness", info = "Unreleased" },
            { name = "Vitrine Dwarven Horse", info = "Datamined" },
            { name = "Vitrine Dwarven Senche", info = "Datamined" },
            { name = "Whale Shark War Pangrit", info = "Datamined" },
            { name = "White Fall Hinterland Ram", info = "Unreleased" },
            { name = "Winterbloom Warmblood", info = "Datamined" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Belle", info = "Unique to ESO's Creative Director Rich Lambert and his wife Terri. The pet is not available to other players." },

            { name = "Alabaster Vvardvark", info = "Datamined" },
            { name = "Ash Hopper", info = "Unreleased" },
            { name = "Ash-Tipped Durzog Pup", info = "Unreleased" },
            { name = "Bear-Lizard Cub", info = "Unreleased" },
            { name = "Bitter Coast Wasp", info = "Unreleased" },
            { name = "Blackwood Monkey", info = "Unreleased" },
            { name = "Blue Torchbug", info = "Unreleased" },
            { name = "Brassilisk", info = "Unreleased" },
            { name = "Crow Court Pony Guar", info = "Unreleased" },
            { name = "Dawnstar Dovah-Fly", info = "Datamined" },
            { name = "Dragonguard Cat", info = "Datamined" },
            { name = "Dread Father's Goat", info = "Unreleased" },
            { name = "Elinhir Hare", info = "Datamined" },
            { name = "Emerald Vale Fawn", info = "Unreleased" },
            { name = "Firepot Spider", info = "Datamined" },
            { name = "Firepot Spider Melee", info = "Datamined" },
            { name = "Frostmoss Imp", info = "Unreleased" },
            { name = "Gem-Bellied Sep Adder", info = "Datamined" },
            { name = "Green Feathered Sep Adder", info = "Datamined" },
            { name = "Heartwood Dauber", info = "Unreleased" },
            { name = "Hew's Bane Hyena Cub", info = "Datamined" },
            { name = "High Rock Red Lemur", info = "Unreleased" },
            { name = "Illusionist's Torchbug", info = "Datamined" },
            { name = "Imperial War Dog Unarmored", info = "Datamined" },
            { name = "Jade-Crown Dragonslayer Wolf", info = "Unreleased" },
            { name = "Karth Winter Hound", info = "Unreleased" },
            { name = "Kiss of Sithis Spider", info = "Unreleased" },
            { name = "M'aiq the Badger", info = "Unreleased" },
            { name = "Mage's Sentry Kitten", info = "Unreleased" },
            { name = "Mind-Shriven Reef Viper", info = "Datamined" },
            { name = "Moonstone Bear Cub", info = "Unreleased" },
            { name = "Nightmare Great Dane", info = "Datamined" },
            { name = "Pale Pass Pony", info = "Unreleased" },
            { name = "Rustpelt Sabre Cat", info = "Unreleased" },
            { name = "Sabre Leopard Cub", info = "Unreleased" },
            { name = "Senche Cub (White Tiger)", info = "Datamined" },
            { name = "Senche-Lizard Cub", info = "Unreleased" },
            { name = "Shock Theodolite", info = "Datamined" },
            { name = "Skeletal Cat", info = "Unreleased" },
            { name = "Trappers Peak Wolf Cub", info = "Datamined" },
            { name = "Vashabar Petal Moth", info = "Unreleased" },
            { name = "Vivec's Promise Butterfly", info = "Unreleased" },
            { name = "White Butterfly", info = "Datamined" },
            { name = "White Morthal Mastiff Pup", info = "Datamined" },
            { name = "White Torchbug", info = "Unreleased" },
            { name = "Yellow Feathered Sep Adder", info = "Datamined" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Antiquarian's Eye", id = 7864, info = "Usable as Tool only" },
            { name = "Boomerang Blunder", info = "Unreleased" },
            { name = "Cadwell's Chaotic Portal", info = "Unreleased" },
            { name = "Inspiring Voskrona Figurine", info = "Datamined" },
            { name = "Spellcrafted Sand Stronghold", info = "Datamined" },
            { name = "NOT IN USE", info = "Datamined" },
            { name = "Pint of Belching", info = "Datamined" },
            { name = "Plant Parley", info = "Datamined" },
            { name = "Riften Leafpile", info = "Datamined" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Argonian Greeting", info = "Datamined" },
            { name = "Befuddled", info = "Datamined" },
            { name = "Bright Throat Greeting", info = "Datamined" },
            { name = "Carve Knickknack", info = "Datamined" },
            { name = "Chair Slam", info = "Datamined" },
            { name = "Commune with Hist", info = "Datamined" },
            { name = "Contemplation of Aetheric Arms", info = "Datamined" },
            { name = "Dead-Water Greeting", info = "Datamined" },
            { name = "Factotum Dance", info = "Datamined" },
            { name = "Forbidden Dinner", info = "Datamined" },
            { name = "Frolicking Frog", info = "Datamined" },
            { name = "Get Out", info = "Datamined" },
            { name = "Hist Greeting", info = "Datamined" },
            { name = "Iceblossom Summoning", info = "Datamined" },
            { name = "Kiss the Frog", info = "Datamined" },
            { name = "No Dice", info = "Datamined" },
            { name = "Orb Juggling", info = "Datamined" },
            { name = "Sheor's Beard!", info = "Datamined" },
            { name = "Sneaky Sneeze Attack", info = "Datamined" },
            { name = "Spit Take", info = "Datamined" },
            { name = "Teeba Ready Position", info = "Datamined" },
            { name = "Wargame Ballista", info = "Datamined" },
            { name = "Wash My Hands of This", info = "Datamined" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Scalecaller Dragonflame", info = "Datamined" },
            { name = "Prophet's Jerkin", info = "Probably was never available" },
            { name = "Dramaturge's Delirium", info = "Unreleased" },
            { name = "Faithful Housecarl", info = "Unreleased" },
            { name = "Reclaimed Soul", info = "Unreleased" },
            { name = "Arkay Unending Cycle", weaponOnly = true, info = "Unreleased" },
            { name = "Clockwork Factotum", weaponOnly = true, info = "Unreleased" },
            { name = "Golden Khajiit", weaponOnly = true, info = "Unreleased" },
            { name = "Rose of Sanguine", weaponOnly = true, info = "Unreleased" },
            { name = "Tava's Goshawk", weaponOnly = true, info = "Unreleased" },

            { name = "Order of the Lamp Girdle", info = "Excluded from Order of the Lamp Crown Crate" },
            { name = "Unfeathered Axe", info = "Excluded from Unfeathered Crown Crate" },
            { name = "Unfeathered Battle Axe", info = "Excluded from Unfeathered Crown Crate" },
            { name = "Unfeathered Dagger", info = "Excluded from Unfeathered Crown Crate" },
            { name = "Unfeathered Maul", info = "Excluded from Unfeathered Crown Crate" },
            { name = "Unfeathered Sword", info = "Excluded from Unfeathered Crown Crate" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Celestial Recall", info = "Unreleased" },
            { name = "Gloamcrow Runegathering", info = "Unreleased" },
            { name = "Gloamwing Gather", info = "Unreleased" },
            { name = "Murder of Crows Mining", info = "Unreleased" },
            { name = "Wraith-of-Crows Woodchop", info = "Unreleased" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {
            { name = "Arrow Spray, Vibrant Yellow", info = "Datamined" },
            { name = "Twin Slashes, Coin Gold", info = "Datamined" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Gold Atronach", info = "Datamined" },
            { name = "Witches Fest Skeleton", info = "Datamined" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {
            { name = "Factotum", info = "Unreleased" },

            { name = "Test 05 Default Idle", info = "Internal placeholder for testing" },
            { name = "Test 06 Injured", info = "Internal placeholder for testing" },
            { name = "Test 07 Goblin", info = "Internal placeholder for testing" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Ocean Lamellar", info = "Datamined" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Abah's Watch Full Armor", info = "Datamined" },
            { name = "Abah's Watch Night Patrol", info = "Datamined" },
            { name = "Abah's Watch Pursuit Suit", info = "Datamined" },
            { name = "Barbarian", info = "Unreleased" },
            { name = "Dar-m'Athra Stealth Outfit", info = "Datamined" },
            { name = "Do-m'Athra Battle Armor", info = "Datamined" },
            { name = "Elder Void Priest Raiment", info = "Datamined" },
            { name = "Fighters Guild Combat Armor", info = "Datamined" },
            { name = "Fighters Guild Cool-Weather Gear", info = "Datamined" },
            { name = "Fighters Guild Warm-Weather Gear", info = "Datamined" },
            { name = "Fire Drakes Outfit", info = "Datamined" },
            { name = "Gold Coast 1", info = "Datamined" },
            { name = "Gold Coast 2", info = "Datamined" },
            { name = "Gold Coast 3", info = "Datamined" },
            { name = "Jo-m'Athra Spellcaster Suit", info = "Datamined" },
            { name = "Kamali Akaviri Assassin Outfit", info = "Datamined" },
            { name = "NAME ME Summer Robe", info = "Datamined" },
            { name = "Pellitine Dancer's Garb", info = "Unreleased" },
            { name = "Pit Daemon Outfit", info = "Unused. Initially intended as an individual outfit with all pieces present, it was later turned into the Pit Daemon Style." },
            { name = "Red Sail 1", info = "Datamined" },
            { name = "Red Sail 2", info = "Datamined" },
            { name = "Red Sail 3", info = "Datamined" },
            { name = "Singing Skald Female", info = "Datamined" },
            { name = "Spirit of Memories", info = "Datamined" },
            { name = "Storm Lord Outfit", info = "Datamined" },
            { name = "Thorn's Bite Revelry Gown", info = "Datamined" },
            { name = "Tsaesci Akaviri Assassin Outfit", info = "Unreleased" },
            { name = "Unknown Akaviri Assassin Outfit", info = "Datamined" },
            { name = "Vampire Lord", info = "Datamined" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Archaeologist Hat", info = "Unreleased" },
            { name = "Arkthzand Flanged Auspice Shroud", info = "Unreleased" },
            { name = "Bull Antelope Tricorne", info = "Unreleased" },
            { name = "Dwemerdelve Scavenger Helm", info = "Unreleased" },
            { name = "Flame Atronach Face Visor", info = "Unreleased" },
            { name = "Forester's Hood with Berries", info = "Unreleased" },
            { name = "Han Helsing Tier 1", info = "Datamined" },
            { name = "Han Helsing Tier 2", info = "Datamined" },
            { name = "Ragebound Mask", info = "Unreleased" },
            { name = "Rootbrim Hat with Berries", info = "Unreleased" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Alliance Viper Pit Body Marking", info = "Unreleased" },
            { name = "Automaton Body Tattoos", info = "Unreleased" },
            { name = "Covenant Lion Violet", info = "Datamined" },
            { name = "Dark Experimental Body Scars", info = "Datamined" },
            { name = "Ebon Dwemer Body Markings", info = "Unknown - should be an antiquity, but unknown location" },
            { name = "Lunar Orbit Lattice", info = "Unreleased" },
            { name = "Mystic Geometries", info = "Unreleased" },
            { name = "Serpentguard Rider Body Marks", info = "Unreleased" },
            { name = "Square Spiral Fractal", info = "Unreleased" },
            { name = "Xivilai Gleamwoe Linework Brand", info = "Unreleased" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Alliance Viper Pit Face Marking", info = "Unreleased" },
            { name = "Automaton Face Tattoos", info = "Unreleased" },
            { name = "Dark Experimental Face Scars", info = "Datamined" },
            { name = "Ebon Dwemer Face Marking", info = "Unknown - should be an antiquity, but unknown location" },
            { name = "Lunar Lattice Headwrap", info = "Unreleased" },
            { name = "Serpentguard Rider Face Marks", info = "Unreleased" },
            { name = "Squarejaw Headwrap", info = "Unreleased" },
            { name = "Xivilai Gleamwoe Linework Visage", info = "Unreleased" },
            { name = "Zyggazag", info = "Unreleased" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Assassin-Style Sunset Crest", info = "Unreleased" },
            { name = "Fluttering Forehead Feathers", info = "Unreleased" },
            { name = "Mid-Parted Shoulder-Length", info = "Unreleased" },
            { name = "Portside Shave", info = "Unreleased" },
            { name = "Warrior Topknots", info = "Unreleased" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {
            { name = "Long Glitter Lashes", info = "Unreleased" },
            { name = "Plum Color Eyeshadow", info = "Unreleased" },
            { name = "Spiny Lashes", info = "Unreleased" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Barred Feather Horns", info = "Unreleased" },
            { name = "Bird Skull Brow Bauble", info = "Unreleased" },
            { name = "Elder Dragon Hunter Coronal", info = "Unreleased" },
            { name = "Shaman's Bird-Bone Circlet", info = "Unreleased" },
            { name = "Six-Spike Tail Trim", info = "Unreleased" },
            { name = "Spellsword Coronet", info = "Unreleased" },
            { name = "Sporty Tail Tuft", info = "Unreleased" },
            { name = "Temple Spike Torc", info = "Unreleased" },
            { name = "Count Stefan Mornard", info = "Datamined" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Dead-Water Jaw-Fin Fringe", info = "Unreleased" },
            { name = "Elder Dragon Hunter Piercing", info = "Unreleased" },
        },
    },
}
