CollectThemAllData_Others_DailyRewards = {
    name = "Daily Rewards",
    source = "Others",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_DLC] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {
            { name = "Sword-Singer's Redoubt", info = "May 2024 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {
            { name = "Keldora", info = "February 2021 Daily Reward" },
            { name = "Jester Anglidor", info = "April 2022 Daily Reward" },
            { name = "Mizzik Thunderboots", info = "November 2023 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Glowgill Guar", info = "December 2018 Daily Reward" },
            { name = "Verdant Tattoo Shorn Camel", info = "May 2019 Daily Reward" },
            { name = "White Lion", info = "April 2022 Daily Reward" },
            { name = "Flint-Pelt Fox", info = "August 2023 Daily Reward" },
            { name = "Gnisis Durzog", info = "January 2024 Daily Reward" },
            { name = "Iron Orc Welwa", info = "March 2024 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Dusky Fennec Fox", info = "June 2018 Daily Reward" },
            { name = "Psijic Mascot Guar Calf", info = "July 2018 Daily Reward" },
            { name = "Haunted House Cat", info = "October 2018 Daily Reward" },
            { name = "Psijic Mascot Bear Cub", info = "November 2018 Daily Reward" },
            { name = "Noble Riverhold Senche-Lion Cub", info = "January 2019 Daily Reward" },
            { name = "Psijic Mascot Wolf Pup", info = "March 2019 Daily Reward" },
            { name = "Mara's Spring Chicken", info = "April 2019 Daily Reward" },
            { name = "Grisly Banekin Mummy", info = "October 2019 Daily Reward" },
            { name = "Flame Atronach Bear Cub", info = "February 2020 Daily Reward" },
            { name = "Scruffy Skyrim Paint Pony", info = "March 2020 Daily Reward" },
            { name = "Wickerfright Banekin", info = "May 2020 Daily Reward" },
            { name = "Psijic Mascot Senche Cub", info = "July 2020 Daily Reward" },
            { name = "Nenalata Ayleid Wolf Pup", info = "April 2021 Daily Reward" },
            { name = "Coldharbour Bantam Guar", info = "June 2021 Daily Reward" },
            { name = "Fledgling Terror Bird", info = "July 2021 Daily Reward" },
            { name = "Spectral Mudcrab", info = "October 2021 Daily Reward" },
            { name = "Salamandrine Pony Guar", info = "August 2022 Daily Reward" },
            { name = "Pony-Lizard", info = "September 2022 Daily Reward" },
            { name = "Nightrose Vale Fawn", info = "February 2023 Daily Reward" },
            { name = "Anchorborn Pony", info = "December 2023 Daily Reward" },
            { name = "Bright Moons Dragon Imp", info = "February 2024 Daily Reward" },
            { name = "Craglorn Welwa", info = "March 2024 Daily Reward" },
            { name = "Ayrenn's Fledgling Gryphon", info = "April 2024 Daily Reward" },
            { name = "Bruma Spotted Pig", info = "May 2024 Daily Reward" },
            { name = "Ghostly Breton Terrier", info = "July 2025 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Dibella's Sweetroll Stack", info = "April 2024 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Wash Your Damn Hands", info = "October 2020 Daily Reward" },
            { name = "Flower Fling", info = "March 2022 Daily Reward" },
            { name = "Pop the Cork", info = "June 2022 Daily Reward" },
            { name = "Warm Hands", info = "December 2022 Daily Reward" },
            { name = "Uh … Never Mind", info = "March 2023 Daily Reward" },
            { name = "Trumpet Solo", info = "June 2023 Daily Reward" },
            { name = "Ash Hopper Chomp", info = "October 2023 Daily Reward" },
            { name = "Sit and Drink", info = "November 2023 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Baandari Pedlar Shield", info = "July 2019 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Murkmire Harvest", info = "April 2025 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Skald's Damask Jerkin", info = "September 2018 Daily Reward" },
            { name = "Bardic Tavern-Singer's Dress", info = "February 2019 Daily Reward" },
            { name = "Fisherfolk Work Wear", info = "July 2019 Daily Reward" },
            { name = "Sailor-at-Arms", info = "November 2022 Daily Reward" },
            { name = "Cumberland Anniversary Attire", info = "April 2024 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Crow-Heart Skull Sallet", info = "June 2020 Daily Reward" },
            { name = "Netch Handler Cap", info = "May 2021 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Ancient Dragon Body Marks", info = "October 2019 Daily Reward" },
            { name = "Maddening Mishap Body Markings", info = "September 2020 Daily Reward" },
            { name = "Druidic Knotwork Body Tattoos", info = "July 2022 Daily Reward" },
            { name = "Eldertide Body Ink", info = "April 2023 Daily Reward" },
            { name = "Rose of Tamriel Body Marks", info = "August 2024 Daily Reward" },
            { name = "Cycle Behind the Stars Body Art", info = "November 2024 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Ancient Dragon Face Marks", info = "October 2019 Daily Reward" },
            { name = "Maddening Mishap Face Markings", info = "September 2020 Daily Reward" },
            { name = "Enchanting Cherry Blossom Visage", info = "May 2022 Daily Reward" },
            { name = "Eldertide Face Ink", info = "April 2023 Daily Reward" },
            { name = "Rose of Tamriel Face Marks", info = "August 2024 Daily Reward" },
            { name = "Cycle Behind the Stars Face Art", info = "November 2024 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Draping Locks", info = "October 2022 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {
            { name = "Old Salt's Chin-Trinket", info = "August 2020 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Seastone Browplate", info = "August 2020 Daily Reward" },
            { name = "Shrouded Crown", info = "March 2021 Daily Reward" },
            { name = "Dremora Deceiver's Diadem", info = "November 2021 Daily Reward" },
            { name = "Thrafey Debutante Circlet", info = "February 2022 Daily Reward" },
            { name = "Miscarcand Monocle", info = "July 2024 Daily Reward" },
            { name = "Weald Arbor Headdress", info = "September 2024 Daily Reward" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Chaurus Egg Ear Studs", info = "September 2023 Daily Reward" },
            { name = "Soul Harvester Earrings", info = "June 2025 Daily Reward" },
        },
    },
}
