ZO_CreateStringId("SI_BINDING_NAME_PERFORM_SMART_EMOTE", "Perform Smart Emote")
ZO_CreateStringId("SI_BINDING_NAME_SHOW/HIDE_LOREWEAR_CLOTHES", "Show/Hide LoreWear Clothes")
ZO_CreateStringId("SI_BINDING_NAME_TOGGLE_IDLEEMOTES_ON/OFF", "Toggle IdleEmotes On/Off")
ZO_CreateStringId("SI_BINDING_NAME_FORCE_EQUIP_CITY_OUTFIT", "Force Equip City Outfit")
ZO_CreateStringId("SI_BINDING_NAME_FORCE_EQUIP_HOUSING_OUTFIT", "Force Equip Housing Outfit")
ZO_CreateStringId("SI_BINDING_NAME_FORCE_EQUIP_DUNGEON_OUTFIT", "Force Equip Dungeon Outfit")
ZO_CreateStringId("SI_BINDING_NAME_FORCE_EQUIP_ADVENTURE_OUTFIT", "Force Equip Adventure Outfit")