
J2EUpdate.traitDataTable = {
    [SI_ITEMTRAITTYPE1]     = "Powered",
    [SI_ITEMTRAITTYPE2]     = "Charged",
    [SI_ITEMTRAITTYPE3]     = "Precise",
    [SI_ITEMTRAITTYPE4]     = "Infused",
    [SI_ITEMTRAITTYPE5]     = "Defending",
    [SI_ITEMTRAITTYPE6]     = "Training",
    [SI_ITEMTRAITTYPE7]     = "Sharpened",
    [SI_ITEMTRAITTYPE8]     = "Decisive",
    [SI_ITEMTRAITTYPE9]     = "Intricate",
    [SI_ITEMTRAITTYPE10]    = "Ornate",

    [SI_ITEMTRAITTYPE11]    = "Sturdy",
    [SI_ITEMTRAITTYPE12]    = "Impenetrable",
    [SI_ITEMTRAITTYPE13]    = "Reinforced",
    [SI_ITEMTRAITTYPE14]    = "Well-fitted",
    [SI_ITEMTRAITTYPE15]    = "Training",
    [SI_ITEMTRAITTYPE16]    = "Infused",
    [SI_ITEMTRAITTYPE17]    = "Invigorating",
    [SI_ITEMTRAITTYPE18]    = "Divines",
    [SI_ITEMTRAITTYPE19]    = "Ornate",
    [SI_ITEMTRAITTYPE20]    = "Intricate",

    [SI_ITEMTRAITTYPE21]    = "Healthy",
    [SI_ITEMTRAITTYPE22]    = "Arcane",
    [SI_ITEMTRAITTYPE23]    = "Robust",
    [SI_ITEMTRAITTYPE24]    = "Ornate",
    [SI_ITEMTRAITTYPE25]    = "Nirnhoned",
    [SI_ITEMTRAITTYPE26]    = "Nirnhoned",
    [SI_ITEMTRAITTYPE27]    = "Intricate",
    [SI_ITEMTRAITTYPE28]    = "Swift",
    [SI_ITEMTRAITTYPE29]    = "Harmony",
    [SI_ITEMTRAITTYPE30]    = "Triune",

    [SI_ITEMTRAITTYPE31]    = "Bloodthirsty",
    [SI_ITEMTRAITTYPE32]    = "Protective",
    [SI_ITEMTRAITTYPE33]    = "Infused",
    [SI_ITEMTRAITTYPE34]    = "Quickened",
    [SI_ITEMTRAITTYPE35]    = "Prolific",
    [SI_ITEMTRAITTYPE36]    = "Focused",
    [SI_ITEMTRAITTYPE37]    = "Shattering",
    [SI_ITEMTRAITTYPE38]    = "Aggressive",
    [SI_ITEMTRAITTYPE39]    = "Soothing",
    [SI_ITEMTRAITTYPE40]    = "Augmented",

    [SI_ITEMTRAITTYPE41]    = "Bolstered",
    [SI_ITEMTRAITTYPE42]    = "Vigorous",
    [SI_ITEMTRAITTYPE43]    = "Quickened",
    [SI_ITEMTRAITTYPE44]    = "Prolific",
    [SI_ITEMTRAITTYPE45]    = "Focused",
    [SI_ITEMTRAITTYPE46]    = "Shattering",
    [SI_ITEMTRAITTYPE47]    = "Aggressive",
    [SI_ITEMTRAITTYPE48]    = "Soothing",
    [SI_ITEMTRAITTYPE49]    = "Augmented",
    [SI_ITEMTRAITTYPE50]    = "Bolstered",

    [SI_ITEMTRAITTYPE51]    = "Vigorous",
    [SI_ITEMTRAITTYPE52]    = "Quickened",
    [SI_ITEMTRAITTYPE53]    = "Prolific",
    [SI_ITEMTRAITTYPE54]    = "Focused",
    [SI_ITEMTRAITTYPE55]    = "Shattering",
    [SI_ITEMTRAITTYPE56]    = "Aggressive",
    [SI_ITEMTRAITTYPE57]    = "Soothing",
    [SI_ITEMTRAITTYPE58]    = "Augmented",
    [SI_ITEMTRAITTYPE59]    = "Bolstered",
    [SI_ITEMTRAITTYPE60]    = "Vigorous",

}

