
J2EUpdate.nameFormatTable = {
    ["-"]   ="<<1>> <<2>>",
    ["J-"]  ="Jerkin <<2>>",
    ["R-"]  ="Robe <<2>>",

    ["n"]   ="<<1>>^n",
    ["nR"]  ="Robe^n",
    ["nJ"]  ="Jerkin^n",

    --["s"]   ="<<2>> <<1>>",
    [""]    ="<<2>> <<1>>",
    ["A"]   ="<<2>> Amulet",
    ["G"]   ="<<2>> Guise",
    ["H"]   ="<<2>> Hammer",
    ["J"]   ="<<2>> Jerkin",
    ["M"]   ="<<2>> Mask",
    ["P"]   ="<<2>> Pauldrons", -- Pauldron[s]
    ["R"]   ="<<2>> Robe",
    ["S"]   ="<<2>> Shirt",
    ["V"]   ="<<2>> Visage",

    --["'"]   ="<<2>>'s <<1>>",
    --["'A"]  ="<<2>>'s Amulet",
    --["'G"]  ="<<2>>'s Guise",
    --["'H"]  ="<<2>>'s Hammer",
    --["'J"]  ="<<2>>'s Jerkin",
    --["'M"]  ="<<2>>'s Mask",
    --["'P"]  ="<<2>>'s Pauldrons", -- Pauldron[s]
    --["'R"]  ="<<2>>'s Robe",
    --["'S"]  ="<<2>>'s Shirt",
    --["'V"]  ="<<2>>'s Visage",

    ["o"]   ="<<1>> of <<2>>",
    ["Ao"]  ="Amulet of <<2>>",
    ["Ho"]  ="Hammer of <<2>>",
    ["Jo"]  ="Jerkin of <<2>>",
    ["Lo"]  ="Locket of <<2>>",
    ["Po"]  ="Pauldrons of <<2>>", -- Pauldron[s]
    ["Ro"]  ="Robe of <<2>>",
    ["So"]  ="Shirt of <<2>>",

    ["T"]   ="<<1>> of the <<2>>",
    ["AT"]  ="Amulet of the <<2>>",
    ["HT"]  ="Hammer of the <<2>>",
    ["JT"]  ="Jerkin of the <<2>>",
    ["LT"]  ="Locket of the <<2>>",
    ["PT"]  ="Pauldrons of the <<2>>", -- Pauldron[s]
    ["RT"]  ="Robe of the <<2>>",
    ["ST"]  ="Shirt of the <<2>>",

    ["C"]  ="Companion's <<1>>",
    ["CP"] ="Companion's Pauldrons", -- Pauldron[s]
    ["CJ"] ="Companion's Jerkin",
    ["CR"] ="Companion's Robe",

    ["ep"]="Pact's <<1>>",
    ["dc"]="Covenant's <<1>>",
    ["ad"]="Dominion's <<1>>",
    ["exN"]="Exemplary Nirnhoned <<1>>",

    ["66"] ="<<1>> of Hist Sap",                     -- Robes of the Hist
    ["101"]="<<1>> of Affliction",                   -- Affliction
    ["124"]="<<1>> of the Worm Cult",                -- The Worm's Raiment
    ["136"]="<<1>> of the Yokeda",                   -- Immortal Warrior
    ["139"]="Aether <<1>> of Strategy",              -- Wise Mage
    ["140"]="Aether <<1>> of Destruction",           -- Destructive Mage
    ["142"]="Ophidian <<1>> of Celerity",            -- Quick Serpent
    ["143"]="Ophidian <<1>> of Venom",               -- Poisonous Serpent
    ["187"]="<<1>> of Toxic Defiance",               -- Swamp Raider
    ["188"]="Shock Master's <<1>>",                  -- Storm Master
    ["493"]="Perfected <<1>> of Kyne's Wind",        -- Perfected Kyne's Wind
    ["590"]="Perfected <<1>> of Sul-Xan's Torment",  -- Perfected Sul-Xan's Torment
    ["591"]="Perfected <<1>> of Bahsei's Mania",     -- Perfected Bahsei's Mania
    ["653"]="Perfected <<1>> of the Depths",         -- Perfected Whorl of the Depths
}




-- [set] http://esoitem.uesp.net/viewlog.php?sort=gameId&sortorder=a&record=setSummary
J2EUpdate.defaultItemSetTable = {
    [19]="Vestments of the Warlock",
    [20]="Witchman Armor",
    [21]="Akaviri Dragonguard",
    [22]="Dreamer's Mantle",
    [23]="Archer's Mind",
    [24]="Footman's Fortune",
    [25]="Desert Rose",
    [26]="Prisoner's Rags",
    [27]="Fiord's Legacy",
    [28]="Barkskin",
    [29]="Sergeant's Mail",
    [30]="Thunderbug's Carapace",
    [31]="Silks of the Sun",
    [32]="Healer's Habit",
    [33]="Viper's Sting",
    [34]="Night Mother's Embrace",
    [35]="Knightmare",
    [36]="Armor of the Veiled Heritance",
    [37]="Death's Wind",
    [38]="Twilight's Embrace",
    [39]="Alessian Order",
    [40]="Night's Silence",
    [41]="Whitestrake's Retribution",
    [43]="Armor of the Seducer",
    [44]="Vampire's Kiss",
    [46]="Noble Duelist's Silks",
    [47]="Robes of the Withered Hand",
    [48]="Magnus' Gift",
    [49]="Shadow of the Red Mountain",
    [50]="The Morag Tong",
    [51]="Night Mother's Gaze",
    [52]="Beckoning Steel",
    [53]="The Ice Furnace",
    [54]="Ashen Grip",
    [55]="Prayer Shawl",
    [56]="Stendarr's Embrace",
    [57]="Syrabane's Grip",
    [58]="Hide of the Werewolf",
    [59]="Kyne's Kiss",
    [60]="Darkstride",
    [61]="Dreugh King Slayer",
    [62]="Hatchling's Shell",
    [63]="The Juggernaut",
    [64]="Shadow Dancer's Raiment",
    [65]="Bloodthorn's Touch",
    [66]="Robes of the Hist",
    [67]="Shadow Walker",
    [68]="Stygian",
    [69]="Ranger's Gait",
    [70]="Seventh Legion Brute",
    [71]="Durok's Bane",
    [72]="Nikulas' Heavy Armor",
    [73]="Oblivion's Foe",
    [74]="Spectre's Eye",
    [75]="Torug's Pact",
    [76]="Robes of Alteration Mastery",
    [77]="Crusader",
    [78]="Hist Bark",
    [79]="Willow's Path",
    [80]="Hunding's Rage",
    [81]="Song of Lamae",
    [82]="Alessia's Bulwark",
    [83]="Elf Bane",
    [84]="Orgnum's Scales",
    [85]="Almalexia's Mercy",
    [86]="Queen's Elegance",
    [87]="Eyes of Mara",
    [88]="Robes of Destruction Mastery",
    [89]="Sentry",
    [90]="Senche's Bite",
    [91]="Oblivion's Edge",
    [92]="Kagrenac's Hope",
    [93]="Storm Knight's Plate",
    [94]="Meridia's Blessed Armor",
    [95]="Shalidor's Curse",
    [96]="Armor of Truth",
    [97]="The Arch-Mage",
    [98]="Necropotence",
    [99]="Salvation",
    [100]="Hawk's Eye",
    [101]="Affliction",
    [102]="Duneripper's Scales",
    [103]="Magicka Furnace",
    [104]="Curse Eater",
    [105]="Twin Sisters",
    [106]="Wilderqueen's Arch",
    [107]="Wyrd Tree's Blessing",
    [108]="Ravager",
    [109]="Light of Cyrodiil",
    [110]="Sanctuary",
    [111]="Ward of Cyrodiil",
    [112]="Night Terror",
    [113]="Crest of Cyrodiil",
    [114]="Soulshine",
    [116]="The Destruction Suite",
    [117]="Relics of the Physician, Ansur",
    [118]="Treasures of the Earthforge",
    [119]="Relics of the Rebellion",
    [120]="Arms of Infernace",
    [121]="Arms of the Ancestors",
    [122]="Ebon Armory",
    [123]="Hircine's Veneer",
    [124]="The Worm's Raiment",
    [125]="Wrath of the Imperium",
    [126]="Grace of the Ancients",
    [127]="Deadly Strike",
    [128]="Blessing of the Potentates",
    [129]="Vengeance Leech",
    [130]="Eagle Eye",
    [131]="Bastion of the Heartland",
    [132]="Shield of the Valiant",
    [133]="Buffer of the Swift",
    [134]="Shroud of the Lich",
    [135]="Draugr's Heritage",
    [136]="Immortal Warrior",
    [137]="Berserking Warrior",
    [138]="Defending Warrior",
    [139]="Wise Mage",
    [140]="Destructive Mage",
    [141]="Healing Mage",
    [142]="Quick Serpent",
    [143]="Poisonous Serpent",
    [144]="Twice-Fanged Serpent",
    [145]="Way of Fire",
    [146]="Way of Air",
    [147]="Way of Martial Knowledge",
    [148]="Way of the Arena",
    [155]="Undaunted Bastion",
    [156]="Undaunted Infiltrator",
    [157]="Undaunted Unweaver",
    [158]="Embershield",
    [159]="Sunderflame",
    [160]="Burning Spellweave",
    [161]="Twice-Born Star",
    [162]="Spawn of Mephala",
    [163]="Blood Spawn",
    [164]="Lord Warden",
    [165]="Scourge Harvester",
    [166]="Engine Guardian",
    [167]="Nightflame",
    [168]="Nerien'eth",
    [169]="Valkyn Skoria",
    [170]="Maw of the Infernal",
    [171]="Eternal Warrior",
    [172]="Infallible Mage",
    [173]="Vicious Serpent",
    [176]="Noble's Conquest",
    [177]="Redistributor",
    [178]="Armor Master",
    [179]="Black Rose",
    [180]="Powerful Assault",
    [181]="Meritorious Service",
    [183]="Molag Kena",
    [184]="Brands of Imperium",
    [185]="Spell Power Cure",
    [186]="Jolting Arms",
    [187]="Swamp Raider",
    [188]="Storm Master's",
    [190]="Scathing Mage",
    [193]="Overwhelming Surge",
    [194]="Combat Physician",
    [195]="Sheer Venom",
    [196]="Leeching Plate",
    [197]="Tormentor",
    [198]="Essence Thief",
    [199]="Shield Breaker",
    [200]="Phoenix",
    [201]="Reactive Armor",
    [204]="Endurance",
    [205]="Willpower",
    [206]="Agility",
    [207]="Law of Julianos",
    [208]="Trial by Fire",
    [209]="Armor of the Code",
    [210]="Mark of the Pariah",
    [211]="Permafrost",
    [212]="Briarheart",
    [213]="Glorious Defender",
    [214]="Para Bellum",
    [215]="Elemental Succession",
    [216]="Hunt Leader",
    [217]="Winterborn",
    [218]="Trinimac's Valor",
    [219]="Morkuldin",
    [224]="Tava's Favor",
    [225]="Clever Alchemist",
    [226]="Eternal Hunt",
    [227]="Bahraha's Curse",
    [228]="Syvarra's Scales",
    [229]="Twilight Remedy",
    [230]="Moondancer",
    [231]="Lunar Bastion",
    [232]="Roar of Alkosh",
    [234]="Marksman's Crest",
    [235]="Robes of Transmutation",
    [236]="Vicious Death",
    [237]="Leki's Focus",
    [238]="Fasalla's Guile",
    [239]="Warrior's Fury",
    [240]="Kvatch Gladiator",
    [241]="Varen's Legacy",
    [242]="Pelinal's Aptitude",
    [243]="Hide of Morihaus",
    [244]="Flanking Strategist",
    [245]="Sithis' Touch",
    [246]="Galerion's Revenge",
    [247]="Vicecanon of Venom",
    [248]="Thews of the Harbinger",
    [253]="Imperial Physique",
    [256]="Mighty Chudan",
    [257]="Velidreth",
    [258]="Amber Plasm",
    [259]="Heem-Jas' Retribution",
    [260]="Aspect of Mazzatun",
    [261]="Gossamer",
    [262]="Widowmaker",
    [263]="Hand of Mephala",
    [264]="Giant Spider's",
    [265]="Shadowrend",
    [266]="Kra'gh",
    [267]="Swarm Mother",
    [268]="Sentinel of Rkugamz",
    [269]="Chokethorn",
    [270]="Slimecraw",
    [271]="Sellistrix's",
    [272]="Infernal Guardian",
    [273]="Ilambris",
    [274]="Iceheart",
    [275]="Stormfist",
    [276]="Tremorscale",
    [277]="Pirate Skeleton",
    [278]="Troll King",
    [279]="Selene",
    [280]="Grothdarr",
    [281]="Armor of the Trainee",
    [282]="Vampire Cloak",
    [283]="Sword-Singer's",
    [284]="Order of Diagna",
    [285]="Vampire Lord",
    [286]="Spriggan's Thorns",
    [287]="Green Pact",
    [288]="Beekeeper's Gear",
    [289]="Spinner's Garments",
    [290]="Skooma Smuggler",
    [291]="Shalk Exoskeleton",
    [292]="Mother's Sorrow",
    [293]="Plague Doctor's",
    [294]="Ysgramor's Birthright",
    [295]="Jailbreaker",
    [296]="Spelunker's",
    [297]="Spider Cultist Cowl",
    [298]="Light Speaker's",
    [299]="Toothrow",
    [300]="Netch's Touch",
    [301]="Strength of the Automaton",
    [302]="Leviathan",
    [303]="Lamia's Song",
    [304]="Medusa",
    [305]="Treasure Hunter",
    [307]="Draugr Hulk",
    [308]="Bone Pirate's Tatters",
    [309]="Knight-errant's Mail",
    [310]="Sword Dancer",
    [311]="Rattlecage",
    [312]="Tremorscale",
    [313]="Titanic Cleave",
    [314]="Puncturing Remedy",
    [315]="Stinging Slashes",
    [316]="Caustic Arrow",
    [317]="Destructive Impact",
    [318]="Grand Rejuvenation",
    [320]="War Maiden",
    [321]="Defiler's",
    [322]="Warrior-Poet",
    [323]="Assassin's Guile",
    [324]="Daedric Trickery",
    [325]="Shacklebreaker",
    [326]="Vanguard's Challenge",
    [327]="Coward's Gear",
    [328]="Knight Slayer",
    [329]="Wizard's Riposte",
    [330]="Automated Defense",
    [331]="War Machine",
    [332]="Master Architect",
    [333]="Inventor's Guard",
    [334]="Impregnable Armor",
    [335]="Draugr's Rest",
    [336]="Pillar of Nirn",
    [337]="Ironblood",
    [338]="Flame Blossom",
    [339]="Blooddrinker",
    [340]="Hagraven's Garden",
    [341]="Earthgore",
    [342]="Domihaus",
    [343]="Caluurion's Legacy",
    [344]="Trappings of Invigoration",
    [345]="Ulfnor's Favor",
    [346]="Jorvuld's Guidance",
    [347]="Plague Slinger",
    [348]="Curse of Doylemish",
    [349]="Thurvokun",
    [350]="Zaan",
    [351]="Innate Axiom",
    [352]="Fortified Brass",
    [353]="Mechanical Acuity",
    [354]="Mad Tinkerer's",
    [355]="Unfathomable Darkness",
    [356]="Livewire",
    [357]="Disciplined Slash (Perfected)",
    [358]="Defensive Position (Perfected)",
    [359]="Chaotic Whirlwind (Perfected)",
    [360]="Piercing Spray (Perfected)",
    [361]="Concentrated Force (Perfected)",
    [362]="Timeless Blessing (Perfected)",
    [363]="Disciplined Slash",
    [364]="Defensive Position",
    [365]="Chaotic Whirlwind",
    [366]="Piercing Spray",
    [367]="Concentrated Force",
    [368]="Timeless Blessing",
    [369]="Merciless Charge",
    [370]="Rampaging Slash",
    [371]="Cruel Flurry",
    [372]="Thunderous Volley",
    [373]="Crushing Wall",
    [374]="Precise Regeneration",
    [380]="Prophet's",
    [381]="Broken Soul",
    [382]="Grace of Gloom",
    [383]="Gryphon's Ferocity",
    [384]="Wisdom of Vanus",
    [385]="Adept Rider",
    [386]="Sload's Semblance",
    [387]="Nocturnal's Favor",
    [388]="Aegis of Galenwe",
    [389]="Arms of Relequen",
    [390]="Mantle of Siroria",
    [391]="Vestment of Olorime",
    [392]="Perfected Aegis of Galenwe",
    [393]="Perfected Arms of Relequen",
    [394]="Perfected Mantle of Siroria",
    [395]="Perfected Vestment of Olorime",
    [397]="Balorgh",
    [398]="Vykosa",
    [399]="Hanu's Compassion",
    [400]="Blood Moon",
    [401]="Haven of Ursus",
    [402]="Moon Hunter",
    [403]="Savage Werewolf's",
    [404]="Jailer's Tenacity",
    [405]="Bright-Throat's Boast",
    [406]="Dead-Water's Guile",
    [407]="Champion of the Hist",
    [408]="Grave-Stake Collector",
    [409]="Naga Shaman",
    [410]="Might of the Lost Legion",
    [411]="Gallant Charge",
    [412]="Radial Uppercut",
    [413]="Spectral Cloak",
    [414]="Virulent Shot",
    [415]="Wild Impulse",
    [416]="Mender's Ward",
    [417]="Indomitable Fury",
    [418]="Spell Strategist",
    [419]="Battlefield Acrobat",
    [420]="Soldier of Anguish",
    [421]="Steadfast Hero",
    [422]="Battalion Defender",
    [423]="Perfect Gallant Charge",
    [424]="Perfect Radial Uppercut",
    [425]="Perfect Spectral Cloak",
    [426]="Perfect Virulent Shot",
    [427]="Perfect Wild Impulse",
    [428]="Perfect Mender's Ward",
    [429]="Mighty Glacier's",
    [430]="Tzogvin's Warband",
    [431]="Icy Conjurer's",
    [432]="Stonekeeper",
    [433]="Frozen Watcher's",
    [434]="Scavenging Demise",
    [435]="Auroran's Thunder",
    [436]="Symphony of Blades",
    [437]="Coldharbour's Favorite",
    [438]="Senche-raht's Grit",
    [439]="Vastarie's Tutelage",
    [440]="Crafty Alfiq's",
    [441]="Vesture of Darloc Brae",
    [442]="Call of the Undertaker",
    [443]="Eye of Nahviintaas",
    [444]="False God's Devotion",
    [445]="Tooth of Lokkestiiz",
    [446]="Claw of Yolnahkriin",
    [448]="Perfected Eye of Nahviintaas",
    [449]="Perfected False God's Devotion",
    [450]="Perfected Tooth of Lokkestiiz",
    [451]="Perfected Claw of Yolnahkriin",
    [452]="Hollowfang Thirst",
    [453]="Dro'Zakar's Claws",
    [454]="Renald's Resolve",
    [455]="Z'en's Redress",
    [456]="Azureblight Reaper",
    [457]="Dragon's Defilement",
    [458]="Grundwulf",
    [459]="Maarselok",
    [465]="Senchal Defender's",
    [466]="Marauder's Haste",
    [467]="Dragonguard Elite's",
    [468]="Daring Corsair's",
    [469]="Ancient Dragonguard's",
    [470]="New Moon Acolyte's",
    [471]="Hiti's Hearth",
    [472]="Lyris Titanborn's",
    [473]="Bani's Torment",
    [474]="Draugrkin's Grip",
    [475]="Aegis Caller's",
    [476]="Grave Guardian's",
    [478]="Mother Ciannait",
    [479]="Kjalnar's Nightmare",
    [480]="Critical Riposte",
    [481]="Unchained Aggressor's",
    [482]="Dauntless Combatant's",
    [487]="Winter's Respite",
    [488]="Venomous Smite",
    [489]="Eternal Vigor",
    [490]="Stuhn's Favor",
    [491]="Dragon's Appetite",
    [492]="Kyne's Wind",
    [493]="Perfected Kyne's Wind",
    [494]="Vrol's Command",
    [495]="Perfected Vrol's Command",
    [496]="Roaring Opportunist's",
    [497]="Perfected Roaring Opportunist",
    [498]="Yandir's Might",
    [499]="Perfected Yandir's Might",
    [501]="Thrassian Stranglers",
    [503]="Ring of the Wild Hunt",
    [505]="Torc of Tonal Constancy",
    [506]="Spell Parasite's",
    [513]="Talfyg's Treachery",
    [514]="Unleashed Terror",
    [515]="Crimson Twilight",
    [516]="Elemental Catalyst",
    [517]="Kraglen's Howl",
    [518]="Arkasis's Genius",
    [519]="Snow Treaders",
    [520]="Malacath's Band of Brutality",
    [521]="Bloodlord's Embrace",
    [522]="Perfected Merciless Charge",
    [523]="Perfected Rampaging Slash",
    [524]="Perfected Cruel Flurry",
    [525]="Perfected Thunderous Volley",
    [526]="Perfected Crushing Wall",
    [527]="Perfected Precise Regeneration",
    [528]="Perfected Titanic Cleave",
    [529]="Perfected Puncturing Remedy",
    [530]="Perfected Stinging Slashes",
    [531]="Perfected Caustic Arrow",
    [532]="Perfected Destructive Impact",
    [533]="Perfected Grand Rejuvenation",
    [534]="Stone Husk",
    [535]="Lady Thorn",
    [536]="Radiant Bastion",
    [537]="Voidcaller",
    [538]="Witch-Knight's Defiance",
    [539]="Red Eagle's Fury",
    [540]="Legacy of Karth",
    [541]="Aetherial Ascension",
    [542]="Hex Siphon",
    [543]="Pestilent Host",
    [544]="Explosive Rebuke",
    [557]="Executioner's Blade",
    [558]="Void Bash",
    [559]="Frenzied Momentum",
    [560]="Point-Blank Snipe",
    [561]="Wrath of Elements",
    [562]="Force Overflow",
    [563]="Perfected Executioner's Blade",
    [564]="Perfected Void Bash",
    [565]="Perfected Frenzied Momentum",
    [567]="Perfected Wrath of Elements",
    [568]="Perfected Force Overflow",
    [569]="True-Sworn Fury",
    [570]="Kinras's Wrath",
    [571]="Drake's Rush",
    [572]="Unleashed Ritualist",
    [573]="Dagon's Dominion",
    [574]="Foolkiller's Ward",
    [575]="Ring of the Pale Order",
    [576]="Pearls of Ehlnofey",
    [577]="Encratis's Behemoth",
    [578]="Baron Zaudrus",
    [579]="Frostbite",
    [580]="Deadlands Assassin's",
    [581]="Bog Raider's",
    [582]="Hist Whisperer's",
    [583]="Heartland Conqueror's",
    [584]="Diamond's Victory",
    [585]="Saxhleel Champion's",
    [586]="Sul-Xan's Torment",
    [587]="Bahsei's Mania",
    [588]="Stone-Talker's Oath",
    [589]="Perfected Saxhleel Champion",
    [590]="Perfected Sul-Xan's Torment",
    [591]="Perfected Bahsei's Mania",
    [592]="Perfected Stone-Talker's Oath",
    [593]="Gaze of Sithis",
    [594]="Harpooner's Wading Kilt",
    [596]="Death Dealer's Fete",
    [597]="Shapeshifter's Chain",
    [598]="Zoal the Ever-Wakeful's",
    [599]="Immolator Charr's",
    [600]="Glorgoloch the Destroyer's",
    [602]="Crimson Oath's Rive",
    [603]="Scorion's Feast",
    [604]="Rush of Agony",
    [605]="Silver Rose Vigil",
    [606]="Thunder Caller's",
    [607]="Grisly Gourmet's",
    [608]="Prior Thierric",
    [609]="Magma Incarnate",
    [610]="Wretched Vitality",
    [611]="Deadlands Demolisher's",
    [612]="Iron Flask",
    [613]="Eye of the Grasp",
    [614]="Hexos' Ward",
    [615]="Kynmarcher's Cruelty",
    [616]="Dark Convergence",
    [617]="Plaguebreak",
    [618]="Hrothgar's Chill",
    [619]="Maligalig's Maelstrom",
    [620]="Gryphon's Reprisal",
    [621]="Glacial Guardian's",
    [622]="Turning Tide",
    [623]="Storm-Cursed's Revenge",
    [624]="Spriggan's Vigor",
    [625]="Markyn Ring of Majesty",
    [626]="Belharza's Band",
    [627]="Spaulder of Ruin",
    [629]="Rallying Cry",
    [630]="Hew and Sunder",
    [631]="Enervating Aura",
    [632]="Kargaeda",
    [633]="Nazaray",
    [634]="Nunatak's",
    [635]="Lady Malygda's",
    [636]="Baron Thirsk's",
    [640]="Order's Wrath",
    [641]="Serpent's Disdain",
    [643]="Blessing of High Isle",
    [644]="Steadfast's Mettle",
    [645]="Systres' Scowl",
    [647]="Coral Riptide",
    [648]="Pearlescent Ward",
    [642]="Druid's Braid",
    [646]="Whorl of the Depths",
    [649]="Pillager's Profit",
    [650]="Perfected Pillager's Profit",
    [651]="Perfected Pearlescent Ward",
    [652]="Perfected Coral Riptide",
    [653]="Perfected Whorl of the Depths",
    [654]="Mora's Whispers",
    [655]="Dov-rha Sabatons",
    [656]="Lefthander's Aegis Belt",
    [657]="Sea-Serpent's Coil",
    [658]="Oakensoul Ring",
    [660]="Deeproot Zeal",
    [661]="Stone's Accord",
    [663]="Pangrit Denmother's",
    [662]="Rage of the Ursauk",
    [664]="Grave Inevitability",
    [665]="Phylactery's Grasp",
    [666]="Archdruid Devyric's",
    [667]="Euphotic Gatekeeper",
    [668]="Languor of Peryite",
    [669]="Nocturnal's Ploy",
    [670]="Mara's Balm",
    [671]="Back-Alley Gourmand",
    [672]="Phoenix Moth Theurge",
    [673]="Bastion of the Draoife",
    [674]="Faun's Lark Cladding",
    [675]="Stormweaver's Cavort",
    [676]="Syrabane's Ward",
    [677]="Chimera's Rebuke",
    [678]="Old Growth Brewer",
    [679]="Claw of the Forest Wraith",
    [680]="Ritemaster's Bond",
    [681]="Nix-Hound's Howl",
    [682]="Telvanni Enforcer",
    [683]="Roksa the Warped",
    [684]="Runecarver's Blaze",
    [685]="Apocryphal Inspiration",
    [686]="Abyssal Brace",
    [687]="Ozezan the Inferno",
    [688]="Snake in the Stars",
    [689]="Shell Splitter",
    [690]="Judgement of Akatosh",
    [694]="Velothi Ur-Mage's Amulet",
    [695]="Shattered Fate",
    [696]="Telvanni Efficiency",
    [697]="Seeker Synthesis",
    [698]="Vivec's Duality",
    [699]="Camonna Tong",
    [700]="Adamant Lurker",
    [701]="Peace and Serenity",
    [702]="Ansuul's Torment",
    [703]="Test of Resolve",
    [704]="Transformative Hope",
    [705]="Perfected Transformative Hope",
    [707]="Perfected Ansuul's Torment",
    [708]="Perfected Peace and Serenity",
    [730]="Cinders of Anthelmir",
    [731]="Sluthrug's Hunger",
    [732]="Black-Glove Grounding",
    [735]="Blind Path Induction",
    [736]="Tarnished Nightmare",
    [737]="Reflected Fury",
    [754]="Oakfather's Retribution",
    [755]="Blunted Blades",
    [756]="Baan Dar's Blessing",
    [757]="Symmetry of the Weald",
    [758]="Macabre Vintage",
    [759]="Ayleid Refuge",
    [763]="Tharriker's Strike",
    [764]="Highland Sentinel",
    [765]="Threads of War",
}


J2EUpdate.defaultOfNameTable = {
    [19]="Warlock",                       -- Vestments of the Warlock
    [20]="Witchman's",                    -- Witchman Armor
    [21]="Dragon",                        -- Akaviri Dragonguard
    [22]="Dreamer's",                     -- Dreamer's Mantle
    [24]="Footman",                       -- Footman's Fortune
    [26]="Prisoner's",                    -- Prisoner's Rags
    [27]="Fiord's",                       -- Fiord's Legacy
    [29]="Sergeant",                      -- Sergeant's Mail
    [30]="Thunderbug's",                  -- Thunderbug's Carapace
    [31]="Sun",                           -- Silks of the Sun
    [32]="Healer",                        -- Healer's Habit
    [33]="Of The Viper",                  -- Viper's Sting
    [34]="Mother's Embrace",              -- Night Mother's Embrace
    [36]="Veiled Heritance",              -- Armor of the Veiled Heritance
    [39]="Alessian",                      -- Alessian Order
    [41]="Whitestrake's",                 -- Whitestrake's Retribution
    [43]="Seducer",                       -- Armor of the Seducer
    [46]="Noble Duelist",                 -- Noble Duelist's Silks
    [47]="Withered Hand",                 -- Robes of the Withered Hand
    [48]="Magnus'",                       -- Magnus' Gift
    [49]="Red Mountain",                  -- Shadow of the Red Mountain
    [50]="Morag Tong",                    -- The Morag Tong
    [51]="Night Mother",                  -- Night Mother's Gaze
    [53]="Ice Furnace",                   -- The Ice Furnace
    [55]="Prayer",                        -- Prayer Shawl
    [56]="Stendarr",                      -- Stendarr's Embrace
    [57]="Syrabane",                      -- Syrabane's Grip
    [58]="Werewolf Hide",                 -- Hide of the Werewolf
    [63]="Juggernaut",                    -- The Juggernaut
    [64]="Shadow Dancer",                 -- Shadow Dancer's Raiment
    [65]="Bloodthorn",                    -- Bloodthorn's Touch
    [66]="Onslaught",                     -- Robes of the Hist
    [69]="Ranger",                        -- Ranger's Gait
    [70]="Seventh Legion's",              -- Seventh Legion Brute
    [72]="Nikulas",                       -- Nikulas' Heavy Armor
    [76]="Alteration Mastery",            -- Robes of Alteration Mastery
    [86]="Elegant",                       -- Queen's Elegance
    [88]="Destruction Mastery",           -- Robes of Destruction Mastery
    [90]="Senche's",                      -- Senche's Bite
    [91]="Oblivion",                      -- Oblivion's Edge
    [93]="Storm Knight",                  -- Storm Knight's Plate
    [94]="Blessed",                       -- Meridia's Blessed Armor
    [96]="Truth",                         -- Armor of Truth
    [101]="Afflicted",                    -- Affliction
    [102]="Duneripper",                   -- Duneripper's Scales
    [104]="Curse-Eating",                 -- Curse Eater
    [106]="Wilderqueen",                  -- Wilderqueen's Arch
    [107]="Wyrd Tree",                    -- Wyrd Tree's Blessing
    [108]="Ravaging",                     -- Ravager
    [109]="Cyrodiil's Light",             -- Light of Cyrodiil
    [111]="Cyrodiil's Ward",              -- Ward of Cyrodiil
    [113]="Cyrodiil's Crest",             -- Crest of Cyrodiil
    [122]="Ebon",                         -- Ebon Armory
    [123]="Hircine's",                    -- Hircine's Veneer
    [124]="Worm",                         -- The Worm's Raiment
    [125]="Imperial Wrath",               -- Wrath of the Imperium
    [126]="Ancient Grace",                -- Grace of the Ancients
    [127]="Deadly",                       -- Deadly Strike
    [128]="Potentates",                   -- Blessing of the Potentates
    [131]="Heartland",                    -- Bastion of the Heartland
    [132]="Valiant",                      -- Shield of the Valiant
    [133]="Swift",                        -- Buffer of the Swift
    [134]="Lich",                         -- Shroud of the Lich
    [135]="Draugr Heritage",              -- Draugr's Heritage
    [136]="Immortal Yokeda",              -- Immortal Warrior
    [137]="Advancing Yokeda",             -- Berserking Warrior
    [138]="Resilient Yokeda",             -- Defending Warrior
    [139]="Aether",                       -- Wise Mage
    [141]="Mending",                      -- Healing Mage
    [144]="Two-Fanged Snake",             -- Twice-Fanged Serpent
    [145]="Fire",                         -- Way of Fire
    [146]="Air",                          -- Way of Air
    [147]="Martial Knowledge",            -- Way of Martial Knowledge
    [148]="Arena",                        -- Way of the Arena
    [163]="Bloodspawn",                   -- Blood Spawn
    [164]="Lord Warden Dusk's",           -- Lord Warden
    [165]="Malubeth the Scourger's",      -- Scourge Harvester
    [166]="The Engine Guardian",          -- Engine Guardian
    [167]="Bogdan the Nightflame",        -- Nightflame
    [171]="Eternal Yokeda",               -- Eternal Warrior
    [172]="Of The Infallible Aether",     -- Infallible Mage
    [173]="Of The Vicious Ophidian",      -- Vicious Serpent
    [177]="Redistribution",               -- Redistributor
    [184]="Imperium",                     -- Brands of Imperium
    [186]="Jolting",                      -- Jolting Arms
    [187]="Swamp Raider's",               -- Swamp Raider
    [193]="Overwhelming",                 -- Overwhelming Surge
    [196]="Leeching",                     -- Leeching Plate
    [201]="Reactive",                     -- Reactive Armor
    [207]="Julianos",                     -- Law of Julianos
    [208]="Trials",                       -- Trial by Fire
    [210]="Pariah",                       -- Mark of the Pariah
    [213]="Glory",                        -- Glorious Defender
    [215]="Succession",                   -- Elemental Succession
    [216]="Hunt",                         -- Hunt Leader
    [232]="Alkosh",                       -- Roar of Alkosh
    [234]="Marksman's",                   -- Marksman's Crest
    [235]="Transmutation",                -- Robes of Transmutation
    [237]="Leki's",                       -- Leki's Focus
    [239]="Fury",                         -- Warrior's Fury
    [240]="Gladiator's",                  -- Kvatch Gladiator
    [242]="Pelinal's",                    -- Pelinal's Aptitude
    [243]="Morihaus",                     -- Hide of Morihaus
    [244]="Flanking",                     -- Flanking Strategist
    [245]="Sithis'",                      -- Sithis' Touch
    [246]="Galerion's",                   -- Galerion's Revenge
    [247]="The Vicecanon's",              -- Vicecanon of Venom
    [248]="Harbinger",                    -- Thews of the Harbinger
    [259]="Heem-Jas'",                    -- Heem-Jas' Retribution
    [260]="Mazzatun",                     -- Aspect of Mazzatun
    [263]="Mephala's Hand",               -- Hand of Mephala
    [278]="The Troll King",               -- Troll King
    [281]="Trainee",                      -- Armor of the Trainee
    [282]="Vampire's Cloak",              -- Vampire Cloak
    [285]="Vampire Lord's",               -- Vampire Lord
    [286]="Spriggan's",                   -- Spriggan's Thorns
    [288]="Beekeeper's",                  -- Beekeeper's Gear
    [289]="Spinner's",                    -- Spinner's Garments
    [290]="Smuggler's",                   -- Skooma Smuggler
    [291]="Shalk's",                      -- Shalk Exoskeleton
    [292]="a Mother's Sorrow",            -- Mother's Sorrow
    [294]="Ysgramor's",                   -- Ysgramor's Birthright
    [297]="Spider Cultist's",             -- Spider Cultist Cowl
    [301]="Automaton's",                  -- Strength of the Automaton
    [303]="Lamia's",                      -- Lamia's Song
    [305]="Treasure Hunter's",            -- Treasure Hunter
    [307]="Hulking Draugr's",             -- Draugr Hulk
    [308]="Bone Pirate's",                -- Bone Pirate's Tatters
    [309]="Knight-Errant's",              -- Knight-errant's Mail
    [310]="Sword Dancer's",               -- Sword Dancer
    [313]="The Master's",                 -- Titanic Cleave
    [314]="The Master's",                 -- Puncturing Remedy
    [315]="The Master's",                 -- Stinging Slashes
    [316]="The Master's",                 -- Caustic Arrow
    [317]="The Master's",                 -- Destructive Impact
    [318]="The Master's",                 -- Grand Rejuvenation
    [320]="War Maiden's",                 -- War Maiden
    [322]="Warrior-Poet's",               -- Warrior-Poet
    [323]="Assassin's",                   -- Assassin's Guile
    [357]="The Asylum's Perfected",       -- Disciplined Slash (Perfected)
    [358]="The Asylum's Perfected",       -- Defensive Position (Perfected)
    [359]="The Asylum's Perfected",       -- Chaotic Whirlwind (Perfected)
    [360]="The Asylum's Perfected",       -- Piercing Spray (Perfected)
    [361]="The Asylum's Perfected",       -- Concentrated Force (Perfected)
    [362]="The Asylum's Perfected",       -- Timeless Blessing (Perfected)
    [363]="The Asylum's",                 -- Disciplined Slash
    [364]="The Asylum's",                 -- Defensive Position
    [365]="The Asylum's",                 -- Chaotic Whirlwind
    [366]="The Asylum's",                 -- Piercing Spray
    [367]="The Asylum's",                 -- Concentrated Force
    [368]="The Asylum's",                 -- Timeless Blessing
    [369]="The Maelstrom's",              -- Merciless Charge
    [370]="The Maelstrom's",              -- Rampaging Slash
    [371]="The Maelstrom's",              -- Cruel Flurry
    [372]="The Maelstrom's",              -- Thunderous Volley
    [373]="The Maelstrom's",              -- Crushing Wall
    [374]="The Maelstrom's",              -- Precise Regeneration
    [382]="Gloom-Graced",                 -- Grace of Gloom
    [383]="Gryphon's",                    -- Gryphon's Ferocity
    [384]="Vanus's",                      -- Wisdom of Vanus
    [385]="Adept Rider's",                -- Adept Rider
    [386]="Sload's",                      -- Sload's Semblance
    [387]="Nocturnal's Favored",          -- Nocturnal's Favor
    [388]="Galenwe's",                    -- Aegis of Galenwe
    [389]="Relequen's",                   -- Arms of Relequen
    [390]="Siroria's",                    -- Mantle of Siroria
    [391]="Olorime's",                    -- Vestment of Olorime
    [392]="Galenwe's Perfected",          -- Perfect Aegis of Galenwe
    [393]="Relequen's Perfected",         -- Perfect Arms of Relequen
    [394]="Siroria's Perfected",          -- Perfect Mantle of Siroria
    [395]="Olorime's Perfected",          -- Perfect Vestment of Olorime
    [399]="Hanu's",                       -- Hanu's Compassion
    [401]="Ursus",                        -- Haven of Ursus
    [404]="Jailer's",                     -- Jailer's Tenacity
    [411]="Blackrose",                    -- Gallant Charge
    [412]="Blackrose",                    -- Radial Uppercut
    [413]="Blackrose",                    -- Spectral Cloak
    [414]="Blackrose",                    -- Virulent Shot
    [415]="Blackrose",                    -- Wild Impulse
    [416]="Blackrose",                    -- Mender's Ward
    [423]="Blackrose Perfected",          -- Perfect Gallant Charge
    [424]="Blackrose Perfected",          -- Perfect Radial Uppercut
    [425]="Blackrose Perfected",          -- Perfect Spectral Cloak
    [426]="Blackrose Perfected",          -- Perfect Virulent Shot
    [427]="Blackrose Perfected",          -- Perfect Wild Impulse
    [428]="Blackrose Perfected",          -- Perfect Mender's Ward
    [430]="Tzogvin's",                    -- Tzogvin's Warband
    [435]="Auroran's",                    -- Auroran's Thunder
    [438]="Senche-raht's",                -- Senche-raht's Grit
    [439]="Vastarie's",                   -- Vastarie's Tutelage
    [441]="Darloc Brae's",                -- Vesture of Darloc Brae
    [442]="Undertaker's",                 -- Call of the Undertaker
    [443]="Nahviintaas's",                -- Eye of Nahviintaas
    [444]="False God's",                  -- False God's Devotion
    [445]="Lokkestiiz's",                 -- Tooth of Lokkestiiz
    [446]="Yolnahkriin's",                -- Claw of Yolnahkriin
    [448]="Perfected Nahviintaas's",      -- Perfected Eye of Nahviintaas
    [449]="Perfected False God's",        -- Perfected False God's Devotion
    [450]="Perfected Lokkestiiz's",       -- Perfected Tooth of Lokkestiiz
    [452]="Hollowfang",                   -- Hollowfang Thirst
    [456]="Azureblight",                  -- Azureblight Reaper
    [457]="Defiled Dragon's",             -- Dragon's Defilement
    [451]="Perfected Yolnahkriin's",      -- Perfected Claw of Yolnahkriin
    [453]="Dro'zakar's",                  -- Dro'Zakar's Claws
    [454]="Renald's",                     -- Renald's Resolve
    [455]="Z'en's",                       -- Z'en's Redress
    [457]="Defiled Dragon's",             -- Dragon's Defilement
    [471]="Hiti's",                       -- Hiti's Hearth
    [472]="Titanborn's",                  -- Titanborn Strength
    [473]="Bani's",                       -- Bani's Torment
    [474]="Draugrkin",                    -- Draugrkin's Grip
    [488]="Venomous",                     -- Venomous Smite
    [490]="Stuhn's",                      -- Stuhn's Favor
    [494]="Vrol's",                       -- Vrol's Command
    [495]="Vrol's Perfected",             -- Perfected Vrol's Command
    [497]="Roaring Opportunist's Perfected", -- Perfected Roaring Opportunist
    [498]="Yandir's",                     -- Yandir's Might
    [499]="Yandir's Perfected",           -- Perfected Yandir's Might
    [513]="Talfyg's",                     -- Talfyg's Treachery
    [514]="Unleashed",                    -- Unleashed Terror
    [515]="Crimson",                      -- Crimson Twilight
    [516]="Catalyst",                     -- Elemental Catalyst
    [517]="Kraglen's",                    -- Kraglen's Howl
    [518]="Arkasis's",                    -- Arkasis's Genius
    [522]="The Maelstrom's Perfected",    -- Perfected Merciless Charge
    [523]="The Maelstrom's Perfected",    -- Perfected Rampaging Slash
    [525]="The Maelstrom's Perfected",    -- Perfected Thunderous Volley
    [526]="The Maelstrom's Perfected",    -- Perfected Crushing Wall
    [524]="The Maelstrom's Perfected",    -- Perfected Cruel Flurry
    [527]="The Maelstrom's Perfected",    -- Perfected Precise Regeneration
    [528]="The Master's Perfected",       -- Perfected Titanic Cleave
    [529]="The Master's Perfected",       -- Perfected Puncturing Remedy
    [530]="The Master's Perfected",       -- Perfected Stinging Slashes
    [531]="The Master's Perfected",       -- Perfected Caustic Arrow
    [532]="The Master's Perfected",       -- Perfected Destructive Impact
    [533]="The Master's Perfected",       -- Perfected Grand Rejuvenation
    [538]="Witch-Knight's",               -- Witch-Knight's Defiance
    [540]="Karth's",                      -- Legacy of Karth
    [542]="Hex Siphoner's",               -- Hex Siphon
    [557]="Vateshran's",                  -- Executioner's Blade
    [558]="Vateshran's",                  -- Void Bash
    [559]="Vateshran's",                  -- Frenzied Momentum
    [560]="Vateshran's",                  -- Point-Blank Snipe
    [561]="Vateshran's",                  -- Wrath of Elements
    [562]="Vateshran's",                  -- Force Overflow
    [563]="Vateshran's Perfected",        -- Perfected Executioner's Blade
    [564]="Vateshran's Perfected",        -- Perfected Void Bash
    [565]="Vateshran's Perfected",        -- Perfected Frenzied Momentum
    [567]="Vateshran's Perfected",        -- Perfected Wrath of Elements
    [568]="Vateshran's Perfected",        -- Perfected Force Overflow
    [570]="Kinras's",                     -- Kinras's Wrath
    [572]="Ritualist",                    -- Unleashed Ritualist
    [573]="Dagon's",                      -- Dagon's Dominion
    [574]="Foolkiller's",                 -- Foolkiller's Ward
    [588]="Stone-Talker's",               -- Stone-Talker's Oath
    [589]="Saxhleel Champion's Perfected", -- Perfected Saxhleel Champion
    [592]="Stone-Talker's Perfected ",    -- Perfected Stone-Talker's Oath
    [602]="Crimson Oath",                 -- Crimson Oath's Rive
    [603]="Scorion's",                    -- Scorion's Feast
    [604]="Rushing Agony",                -- Rush of Agony
    [605]="Silver Rose",                  -- Silver Rose Vigil
    [618]="Hrothgar's",                   -- Hrothgar's Chill
    [619]="Maligalig's",                  -- Maligalig's Maelstrom
    [623]="Storm-Cursed",                 -- Storm-Cursed's Revenge
    [631]="Enervating",                   -- Enervating Aura
    [642]="Druid's",                      -- Druid's Braid
    [643]="High Isle",                    -- Blessing of High Isle
    [645]="Systres'",                     -- Systres' Scowl
    [646]="Depths",                       -- Whorl of the Depths
    [648]="Pearlescent",                  -- Pearlescent Ward
    [649]="Pillager's",                   -- Pillager's Profit
    [650]="Perfected Pillager's",         -- Perfected Pillager's Profit
    [651]="Perfected Pearlescent",        -- Perfected Pearlescent Ward
    [657]="Sea Serpent",                  -- Sea-Serpent's Coil
    [673]="Draoife",                      -- Bastion of the Draoife
    [671]="Gourmand's",                   -- Back-Alley Gourmand
    [672]="Phoenix Moth",                 -- Phoenix Moth Theurge
    [677]="Chimera's",                    -- Chimera's Rebuke
    [678]="Old Growth",                   -- Old Growth Brewer
    [679]="Forest Wraith's",              -- Claw of the Forest Wraith
    [690]="Akatosh's Law",                -- Judgement of Akatosh
}


