CollectThemAllData_Crates_2022_1_SunkenTroveCrate = {
    name = "Sunken Trove Crate (2022)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Cat O' War Senche Lion", q = 1 },
            { name = "Coral Crawler Dwarven Spider", q = 1 },
            { name = "Surfglow Courser", q = 1 },
            { name = "Reefborn Bear", q = 2 },
            { name = "Reefborn Charger", q = 2 },
            { name = "Reefborn Guar", q = 2 },
            { name = "Reefborn Senche-Lion", q = 2 },
            { name = "Reefborn Wolf", q = 2 },
            { name = "Keptu Bear", q = 3 },
            { name = "Pellitine Scorch Senche-Lion", q = 3 },
            { name = "Shadowghost Wolf", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Aurulun Fledgling Gryphon", q = 4 },
            { name = "Meadowglass Wolf Pup", q = 4 },
            { name = "Mustardseed Moth", q = 4 },
            { name = "Rustbite Ringtail", q = 4 },
            { name = "Alcaire Blue Cockeral", q = 5 },
            { name = "Karthspire Coney", q = 5 },
            { name = "Keptu Bear Cub", q = 5 },
            { name = "Mzark Jade-Cap Shroom Shalk", q = 5 },
            { name = "Sooty Breton Terrier", q = 5 },
            { name = "Tortoiseshell Echatere", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Mariner's Nimbus Stone", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Sword Dance", q = 3 },
            { name = "Crab Pinch", q = 4 },
            { name = "Feed Bird", q = 4 },
            { name = "Where's My Drink?", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Reefborn Battle Axe", q = 3 },
            { name = "Reefborn Bow", q = 3 },
            { name = "Reefborn Shield", q = 3 },
            { name = "Reefborn Staff", q = 3 },
            { name = "Reefborn Sword", q = 3 },
            { name = "Keptu Chief Cuirass", q = 5 },
            { name = "Keptu Chief Gauntlets", q = 5 },
            { name = "Keptu Chief Greaves", q = 5 },
            { name = "Keptu Chief Helm", q = 5 },
            { name = "Keptu Chief Pauldrons", q = 5 },
            { name = "Keptu Chief Sabatons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Rainsiren Nereid", q = 2 },
            { name = "Labyrinthian Luminary", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Nereid's Seafoam Raiment", q = 3 },
            { name = "Traveling Merchant", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Nereid's Seafoam Coiffure", q = 4 },
            { name = "Savvy Scoundrel's Mask", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Enchanting Cherry Blossom Marks", q = 3 },
            { name = "Ket Keptu Body Marks", q = 4 },
            { name = "Old Salt Body Tattoos", q = 5 },
            { name = "Saint Kaladas Body Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Darloc's Golden Eyes", q = 4 },
            { name = "Ket Keptu Face Marks", q = 5 },
            { name = "Mirthless Mirror Face Paint", q = 5 },
            { name = "Old Salt Face Tattoos", q = 5 },
            { name = "Saint Kaladas Face Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Aurelian Osprey Coronel", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Splendid Seabird Earring", q = 4 },
        },
    },
}
