CollectThemAllData_Crates_2018_2_PsijicVaultCrate = {
    name = "Psijic Vault Crate (2018)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Green-Graht Ghost Cat", q = 1 },
            { name = "Phantom Ice Wolf", q = 1 },
            { name = "Psijic Spectral Steed", q = 1 },
            { name = "Psijic Bear Exemplar", q = 2 },
            { name = "Psijic Camel Exemplar", q = 2 },
            { name = "Psijic Guar Exemplar", q = 2 },
            { name = "Psijic Horse Exemplar", q = 2 },
            { name = "Psijic Senche Exemplar", q = 2 },
            { name = "Psijic Wolf Exemplar", q = 2 },
            { name = "Black Senche-Lion", q = 3 },
            { name = "Dwarven Spider", q = 3 },
            { name = "Skyfire Guar", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Skein Scorpion", q = 3 },
            { name = "Skein Shalk", q = 3 },
            { name = "Skein Spider", q = 3 },
            { name = "Skein Wasp", q = 3 },
            { name = "Longhair Welwa", q = 4 },
            { name = "Ruby Shroom Shalk", q = 4 },
            { name = "Gray Morthal Mastiff", q = 5 },
            { name = "Sylvan Nixad", q = 5 },
            { name = "Vvardvark", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Sapiarchic Discorporation Lens", q = 3 },
            { name = "Psijic Tautology Glass", q = 4 },
            { name = "Psijic Celestial Orb", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Showtime", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Psijic Flame Gauntlets", q = 3 },
            { name = "Psijic Frost Gauntlets", q = 3 },
            { name = "Psijic Shock Gauntlets", q = 3 },
            { name = "Pyandonean", q = 5, motif = 64 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Falkreath Thane", q = 3 },
            { name = "Buoyant Gentility Ensemble", q = 4 },
            { name = "Upriver Striped Sash-Kilt", q = 4 },
            { name = "Arvel's Ashland Attire", q = 4 },
            { name = "Seyda Neen Jodhpur Ensemble", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Muttonchop Skullcap", q = 4 },
            { name = "Sideburn Skullcap", q = 4 },
            { name = "Inferno Facade", q = 5 },
            { name = "Plumed Wide-Brim Acorn-Warder", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Eagle Plume Flurry Body Tattoo", q = 4 },
            { name = "Scrying Eye Psijic Body Tattoo", q = 4 },
            { name = "Mystic Magicka Flow Body Tattoos", q = 5 },
            { name = "Regal Eagle Wing Body Tattoos", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Eagle Plume Face Tattoo", q = 4 },
            { name = "Scrying Eye Psijic Face Tattoo", q = 4 },
            { name = "Mystic Magicka Flow Face Tattoos", q = 5 },
            { name = "Regal Eagle Wing Face Tattoo", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {
            { name = "Magicka Zephyr Lashes", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Magicka Brow Medallion", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Magicka Ear Clasps", q = 5 },
            { name = "Magicka Nasal Rods", q = 5 },
        },
    },
}
