CollectThemAllData_Crates_2018_4_XanmeerCrate = {
    name = "Xanmeer Crate (2018)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Scorching Horse-Lizard", q = 1 },
            { name = "Venomous Wolf-Lizard", q = 1 },
            { name = "Chilling Senche-Lizard", q = 1 },
            { name = "Wolf-Lizard Steed", q = 2 },
            { name = "Senche-Lizard Steed", q = 2 },
            { name = "Guar-Lizard Steed", q = 2 },
            { name = "Camel-Lizard Steed", q = 2 },
            { name = "Bear-Lizard Steed", q = 2 },
            { name = "Horse-Lizard Steed", q = 2 },
            { name = "Hist Guar", q = 3 },
            { name = "Nightfall Sabre Cat", q = 3 },
            { name = "Lustrous Nix-Ox Fabricant Steed", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Nightfall Sabre Cat Cub", q = 3 },
            { name = "Firepet Spider", q = 3 },
            { name = "Sep Adder", q = 4 },
            { name = "Daemon Chicken", q = 4 },
            { name = "Riverwood White Hen", q = 4 },
            { name = "Kaleidotropic Dragon Frog", q = 4 },
            { name = "Butterscotch Dragon Frog", q = 4 },
            { name = "Craglorn Welwa", q = 5 },
            { name = "Amber Ash Hopper", q = 5 },
            { name = "Bitter Coast Cliff Strider", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Vossa-Satl", q = 3 },
            { name = "Mire Drum", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Voriplasm Sword", q = 3 },
            { name = "Voriplasm Battle Axe", q = 3 },
            { name = "Voriplasm Bow", q = 3 },
            { name = "Voriplasm Staff", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Bright-Throat Scale", q = 3 },
            { name = "Dead-Water Scale", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Marshlord Formal Bugshell Robes", q = 4 },
            { name = "Lizardly Four-Fabric Skirt Set", q = 4 },
            { name = "Xanmeer Doyen's Worship Robe", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Xanmeer Doyen's Feather Tiara", q = 4 },
            { name = "Bonding Rite Headdress", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Dead-Water Blood Body Tattoos", q = 4 },
            { name = "Bright-Throat Chalk Body Tattoo", q = 5 },
            { name = "Bright-Throat Woad Body Tattoo", q = 5 },
            { name = "Bright-Throat Algae Body Tattoo", q = 5 },
            { name = "Bright-Throat Yolk Body Tattoo", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Dead-Water Blood Face Tattoos", q = 4 },
            { name = "Bright-Throat Chalk Face Tattoo", q = 5 },
            { name = "Bright-Throat Woad Face Tattoo", q = 5 },
            { name = "Bright-Throat Algae Face Tattoo", q = 5 },
            { name = "Bright-Throat Yolk Face Tattoo", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Dead-Water Tooth-and-Tusk Tiara", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
