CollectThemAllData_Crates_2017_5_FlameAtronachCrate = {
    name = "Flame Atronach Crate (2017)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Cold-Flame Atronach Wolf", q = 1 },
            { name = "Night Frost Atronach Steed", q = 1 },
            { name = "Shadow Atronach Senche", q = 1 },
            { name = "Flame Atronach Bear", q = 2 },
            { name = "Flame Atronach Camel", q = 2 },
            { name = "Flame Atronach Guar", q = 2 },
            { name = "Flame Atronach Horse", q = 2 },
            { name = "Flame Atronach Wolf", q = 2 },
            { name = "Flame Atronach Senche", q = 2 },
            { name = "Black Camel of Ill Omen", q = 3 },
            { name = "Ice Wolf", q = 3 },
            { name = "Masked Bear", q = 3 },
            { name = "Senche-Leopard", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Ebony Brassilisk", q = 3 },
            { name = "Mages Guild Sentry Cat", q = 3 },
            { name = "Scorpion Fabricant", q = 3 },
            { name = "Senche-Leopard Cub", q = 3 },
            { name = "White River Ice Wolf Pup", q = 3 },
            { name = "Arctic Fennec Fox", q = 4 },
            { name = "Prodigious Brass Mudcrab", q = 4 },
            { name = "Regal Dovah-Fly", q = 4 },
            { name = "Turquoise Nixad", q = 4 },
            { name = "Freckled Guar", q = 5 },
            { name = "Pocket Mammoth", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Flame Eruption", q = 3 },
            { name = "Flame Pixie", q = 4 },
            { name = "Fiery Orb", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Akaviri", q = 3, motif = 18 },
            { name = "Yokudan", q = 3, motif = 20 },
            { name = "Outlaw", q = 3, motif = 24 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Infernal Epidermis", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Elder Council Tunic and Sash", q = 4 },
            { name = "Cyrod Patrician Formal Gown", q = 4 },
            { name = "Centurion Dress Armor", q = 5 },
            { name = "Centurion Field Armor", q = 5 },
            { name = "Imperial Guard Centurion Uniform", q = 5 },
            { name = "Mages Guild Formal Robes", q = 5 },
            { name = "Mages Guild Leggings Uniform", q = 5 },
            { name = "Mages Guild Research Robes", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Brass Fortress Rebreather", q = 4 },
            { name = "Flamebrow Fire Veil", q = 4 },
            { name = "Radius Mask", q = 5 },
            { name = "Radius Rebreather", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Dremora Kyn Body Tattoo", q = 3 },
            { name = "Fire Cyclone Body Markings", q = 4 },
            { name = "Clockwork Apostle Body Imprints", q = 5 },
            { name = "Inferno Ink Body Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Dremora Kyn Face Tattoo", q = 3 },
            { name = "Fire Cyclone Face Markings", q = 4 },
            { name = "Clockwork Apostle Face Imprints", q = 5 },
            { name = "Crimson Flame Lipstick", q = 5 },
            { name = "Inferno Ink Face Markings", q = 5 },
            { name = "Royal Purple Lipstick", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "The Standing Flame", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Alloy Circlet", q = 4 },
            { name = "Mechanist Tiara", q = 4 },
            { name = "Brazenheart Circlet", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
