CollectThemAllData_Crates_2020_1_GloomsporeCrate = {
    name = "Gloomspore Crate (2020)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Embermould Warhorse", q = 1 },
            { name = "Fungiflare Wolf", q = 1 },
            { name = "Shadowcap Cave-Senche", q = 1 },
            { name = "Gloomspore Bear", q = 2 },
            { name = "Gloomspore Camel", q = 2 },
            { name = "Gloomspore Guar", q = 2 },
            { name = "Gloomspore Horse", q = 2 },
            { name = "Gloomspore Senche", q = 2 },
            { name = "Gloomspore Wolf", q = 2 },
            { name = "Auroran Twilight Warhorse", q = 3 },
            { name = "Auroran Zenith Warhorse", q = 3 },
            { name = "Firemoth Nix-Ox", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Blue Shock Nixad", q = 4 },
            { name = "Ice-Glow Salamander", q = 4 },
            { name = "Mint Swamp Jelly", q = 4 },
            { name = "Bright Moons Lunar Moth", q = 5 },
            { name = "Coldspring Nix-Hound", q = 5 },
            { name = "Emberthroat Durzog", q = 5 },
            { name = "Slate-Skinned Daedrat", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Bone Digger's Trinket", q = 4 },
            { name = "Fungimancer's Prayer-Beads", q = 4 },
            { name = "Meridian Possession Prism", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Arachnophobia", q = 4 },
            { name = "Egg Scramble", q = 4 },
            { name = "Angry Dust Off", q = 5 },
            { name = "Horrifying Egg Hatch", q = 5 },
            { name = "Let There Be Lichen!", q = 5 },
            { name = "On Your Mark …", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Gloomspore Bow", q = 3 },
            { name = "Gloomspore Mace", q = 3 },
            { name = "Gloomspore Maul", q = 3 },
            { name = "Gloomspore Shield", q = 3 },
            { name = "Gloomspore Staff", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Bloodfiend", q = 3 },
            { name = "Mireheart Scale", q = 3 },
            { name = "Namira's Bile", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Auroran Knight", q = 3 },
            { name = "Graverobber", q = 3 },
            { name = "Tavern Maid", q = 4 },
            { name = "Blacksmith", q = 5 },
            { name = "Corseted Riding Outfit", q = 5 },
            { name = "Graht-Climber's Active Wear", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Graverobber's Appraising Hood", q = 4 },
            { name = "Graverobber's Mask", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Chittering Chaurus Body Markings", q = 5 },
            { name = "Frigid Ritual Body Markings", q = 5 },
            { name = "Gloomlurker Body Markings", q = 5 },
            { name = "Grave Plunderer Bodypaint", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Chittering Chaurus Face Markings", q = 5 },
            { name = "Frigid Ritual Face Markings", q = 5 },
            { name = "Gloomlurker Face Markings", q = 5 },
            { name = "Grave Plunderer Facepaint", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Crone's Wicker Coronal", q = 5 },
            { name = "High Vampiric Headdress", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
