CollectThemAllData_Crates_2026_2_AnuVsPadomayCrate = {
    name = "Anu vs Padomay Crate (2026)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Manifestation of Order Steed", q = 1 },
            { name = "Manifestation of Chaos Steed", q = 1 },
            { name = "Eye of Magrus Senche", q = 1 },
            { name = "Armored Senche of Anu", q = 2 },
            { name = "Armored Wolf of Padomay", q = 2 },
            { name = "Armored Elk of Anu", q = 2 },
            { name = "Armored Bear of Padomay", q = 2 },
            { name = "Belkarth Senche-Tiger", q = 3 },
            { name = "Greenshade Zebra", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Luminous Raven", q = 4 },
            { name = "Goat of Chaos", q = 4 },
            { name = "Eye of Magnus Tomeshell", q = 4 },
            { name = "Manifestation of Order Pony", q = 4 },
            { name = "Duality Feathered Sep Adder", q = 5 },
            { name = "Belkarth Senche-Tiger Cub", q = 5 },
            { name = "Greenshade Zebra Pony", q = 5 },
            { name = "Daggerfall Longhair Cat", q = 5 },
            { name = "Turquoise Swamp Jelly", q = 5 },
            { name = "Striated Pony Guar", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Harp of Harmonious Order", q = 3 },
            { name = "Channel Duality", q = 3 },
            { name = "Play to the Crowd", q = 4 },
            { name = "Admire Me", q = 5 },
            { name = "Muscle Flex", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Militant Monk", q = 3, motif = 131 },
            { name = "Chosen of Anu Battle Axe", q = 3 },
            { name = "Chosen of Anu Maul", q = 3 },
            { name = "Chosen of Anu Shield", q = 3 },
            { name = "Chosen of Anu Sword", q = 3 },
            { name = "Chosen of Padomay Greatsword", q = 3 },
            { name = "Chosen of Padomay Mace", q = 3 },
            { name = "Chosen of Padomay Staff", q = 3 },
            { name = "Chosen of Padomay Axe", q = 3 },
            { name = "Chosen of Padomay Cuirass", q = 4 },
            { name = "Chosen of Padomay Helmet", q = 4 },
            { name = "Chosen of Anu Jack", q = 4 },
            { name = "Chosen of Anu Helm", q = 4 },
            { name = "Chosen of Anu Dagger", q = 4 },
            { name = "Chosen of Padomay Bow", q = 4 },
            { name = "Chosen of Anu Belt", q = 5 },
            { name = "Chosen of Anu Guards", q = 5 },
            { name = "Chosen of Anu Boots", q = 5 },
            { name = "Chosen of Anu Bracers", q = 5 },
            { name = "Chosen of Anu Arm Cops", q = 5 },
            { name = "Chosen of Padomay Girdle", q = 5 },
            { name = "Chosen of Padomay Greaves", q = 5 },
            { name = "Chosen of Padomay Sabatons", q = 5 },
            { name = "Chosen of Padomay Gauntlets", q = 5 },
            { name = "Chosen of Padomay Pauldrons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Luminous Recall of Anu", q = 3 },
            { name = "Void Recall of Padomay", q = 2 },
            { name = "Claw of Magrus Harvest", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {
            { name = "Elemental Storm, Chaos Vortex", q = 3 },
            { name = "Regeneration, Luminous Order", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Manifestation of Order", q = 2 },
            { name = "Manifestation of Chaos", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Eternal Marble", q = 3 },
            { name = "Chaos of Padomay", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Finery of Elegant Chaos", q = 2 },
            { name = "Tunic of Symmetry", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Padomay's Headdress", q = 4 },
            { name = "Mask of Elegant Chaos", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Body Marks of Padomay", q = 5 },
            { name = "Body Marks of Anu", q = 5 },
            { name = "Sign of Magrus Body Marks", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Eyes of Magrus", q = 4 },
            { name = "Eyes of Anu", q = 4 },
            { name = "Face Marks of Padomay", q = 5 },
            { name = "Face Marks of Anu", q = 5 },
            { name = "Sign of Magrus Face Marks", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Daggerfall Side Tress", q = 4 },
            { name = "Fade to Light War-Locks", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Padomay's Voidmask", q = 4 },
            { name = "Band of Symmetry", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Order's Symmetry Earcharms", q = 4 },
        },
    },
}
