CollectThemAllData_Crates_2020_2_NightfallCrate = {
    name = "Nightfall Crate (2020)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Cursebound Lichsteed", q = 1 },
            { name = "Cursebound Senche-Raht Darkfang", q = 1 },
            { name = "Cursebound Sabre Cat Prowler", q = 1 },
            { name = "Cursebound Bear", q = 2 },
            { name = "Cursebound Horse", q = 2 },
            { name = "Cursebound Kagouti", q = 2 },
            { name = "Cursebound Sabre Cat", q = 2 },
            { name = "Cursebound Wolf", q = 2 },
            { name = "Druadach Mountain Bear", q = 3 },
            { name = "Karthstalker Sabre Cat", q = 3 },
            { name = "White Spotted Courser", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Brown Steeple Bat", q = 4 },
            { name = "Dappled Cactus Bat", q = 4 },
            { name = "Frostbite Spider", q = 4 },
            { name = "Shadowswift Bat", q = 4 },
            { name = "Snow Throat Fruit Bat", q = 4 },
            { name = "Alabaster Jerboa", q = 5 },
            { name = "Rihad Coffee Scorpion", q = 5 },
            { name = "Tu'whacca's Sphynx Cat", q = 5 },
            { name = "Twilight Striped Lynx", q = 5 },
            { name = "Whiterun Mottled Goat", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Accursed Gray Reliquary", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Falkreath Frolic", q = 3 },
            { name = "Tame Lightning", q = 3 },
            { name = "Play Tiny Violin", q = 4 },
            { name = "Psijic Cosmic Starburst", q = 4 },
            { name = "Bite Me", q = 5 },
            { name = "Ponder Poorly Drawn Map", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Greymoor Lycanthrope Axe", q = 3 },
            { name = "Greymoor Lycanthrope Bow", q = 3 },
            { name = "Greymoor Lycanthrope Greatsword", q = 3 },
            { name = "Greymoor Lycanthrope Shield", q = 3 },
            { name = "Greymoor Lycanthrope Staff", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Accursed Death", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Frosthaunt Glister", q = 3 },
            { name = "Runic Seabrume", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Karthwatch Jarl Finery", q = 3 },
            { name = "Morthal Jarl Finery", q = 3 },
            { name = "City Isle Tunic Dress", q = 4 },
            { name = "Innkeeper", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Dibella's Crescendo Tam", q = 4 },
            { name = "Spirited Soubrette Round Cap", q = 4 },
            { name = "Wayrest Canto Chapeau", q = 4 },
            { name = "Karthwatch Spangenhelm", q = 5 },
            { name = "Traditional Wizard's Cowl", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Thrall's Arterial Map Body Marks", q = 4 },
            { name = "Bards College Skald Body Marks", q = 5 },
            { name = "Forsaken Sacrifice Body Markings", q = 5 },
            { name = "Karthwatch Guardian Body Tattoo", q = 5 },
            { name = "Umbral Snarl Body Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Thrall's Arterial Map Face Marks", q = 4 },
            { name = "Bards College Skald Face Marks", q = 5 },
            { name = "Forsaken Sacrifice Face Markings", q = 5 },
            { name = "Karthwatch Guardian Face Tattoo", q = 5 },
            { name = "Umbral Snarl Face Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Seafarer's Crowning Trim", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Blood Scion Razorguard", q = 5 },
            { name = "Morthal Jarl Circlet", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
