CollectThemAllData_Crates_2025_3_HiddenKindredCrate = {
    name = "Hidden Kindred Crate (2025)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Dreadmare of a Thousand Truths", q = 1 },
            { name = "Mara's Glory Wolf", q = 1 },
            { name = "Plaguewater Swamp Skeever", q = 1 },
            { name = "Nightmare Alchemy Elk", q = 2 },
            { name = "Nightmare Alchemy Senche", q = 2 },
            { name = "Nightmare Alchemy Tharriker", q = 2 },
            { name = "Nightmare Alchemy Vvardvark", q = 2 },
            { name = "Pestilent Guar", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Mara's Glory Wolf Pup", q = 4 },
            { name = "Swamp Skeever Pup", q = 4 },
            { name = "Plaguerot Dragon Imp", q = 4 },
            { name = "Blighted Sep Adder", q = 4 },
            { name = "Grisly Banekin Mummy", q = 5 },
            { name = "Aswala Scorpion", q = 5 },
            { name = "Dreamharrow Wasp", q = 5 },
            { name = "Anequina Ginger Cat", q = 5 },
            { name = "Pestilent Pony Guar", q = 5 },
            { name = "Skitteris", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Valenwood Skull Blocks", q = 3 },
            { name = "Tentacular Tome", q = 4 },
            { name = "Slumberglow the Great", q = 4 },
            { name = "Brandish Lantern", q = 4 },
            { name = "Snake Sidekick", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Clan Dreamcarver", q = 3, motif = 121 },
            { name = "Kindred's Concord", q = 3, motif = 123 },
            { name = "Dark Dream Contagion Greatsword", q = 3 },
            { name = "Dark Dream Contagion Bow", q = 3 },
            { name = "Dark Dream Contagion Shield", q = 3 },
            { name = "Dark Dream Contagion Staff", q = 3 },
            { name = "Dark Dream Contagion Mace", q = 3 },
            { name = "Vaermina's Terror Jerkin", q = 5 },
            { name = "Vaermina's Terror Breeches", q = 5 },
            { name = "Vaermina's Terror Hat", q = 5 },
            { name = "Vaermina's Terror Shoes", q = 5 },
            { name = "Vaermina's Terror Gloves", q = 5 },
            { name = "Vaermina's Terror Epaulets", q = 5 },
            { name = "Vaermina's Terror Belt", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Dreamwalker's Recall", q = 2 },
            { name = "Skeever Swarm Removal", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {
            { name = "Flurry, Peryite", q = 3 },
            { name = "Defensive Posture, Spell Breaker", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Bone Colossus", q = 3 },
            { name = "Hunger", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Phantasma of Terror", q = 3 },
            { name = "Dreamharrowed Dancer", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Dreadful Dreams Dress", q = 2 },
            { name = "Kindred Kynmarcher Garb", q = 3 },
            { name = "Mara's Disciple Frock", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Skinned Skeever Cap", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Quagmire's Touch Body Marks", q = 5 },
            { name = "Night Terrors Body Marking", q = 5 },
            { name = "Peryite's Fervor Body Marks", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Dark Queen's Sight", q = 4 },
            { name = "Eyebite Nightmares", q = 4 },
            { name = "Quagmire's Touch Face Marks", q = 5 },
            { name = "Night Terrors Face Marking", q = 5 },
            { name = "Peryite's Fervor Face Marks", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Viper's Strike", q = 4 },
            { name = "Curly Tresses", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Tiara of the Nightmare Queen", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Whispers of Fear Earcuff", q = 4 },
        },
    },
}
