CollectThemAllData_Crates_2017_4_ReapersHarvestCrate = {
    name = "Reaper's Harvest Crate (2017)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Cinder Wolf", q = 1 },
            { name = "Frost Draugr Senche", q = 1 },
            { name = "Plague Husk Horse", q = 1 },
            { name = "Skeletal Bear", q = 2 },
            { name = "Skeletal Camel", q = 2 },
            { name = "Skeletal Guar", q = 2 },
            { name = "Skeletal Horse", q = 2 },
            { name = "Skeletal Senche", q = 2 },
            { name = "Skeletal Wolf", q = 2 },
            { name = "Black Bear", q = 3 },
            { name = "Kagouti", q = 3 },
            { name = "Senche-Lioness", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Black Bear Cub", q = 3 },
            { name = "Shadowghost Guar", q = 4 },
            { name = "Shadowghost Pack Wolf", q = 4 },
            { name = "Shadowghost Senche-Panther", q = 4 },
            { name = "Colovian Badger", q = 5 },
            { name = "Northern Lynx", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Murderous Strike", q = 3 },
            { name = "Swarm of Crows", q = 4 },
            { name = "Crow's Calling", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Dark Brotherhood", q = 3, motif = 36 },
            { name = "Buoyant Armiger", q = 3, motif = 47 },
            { name = "Ashlander", q = 3, motif = 48 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Dragon Warrior", q = 3 },
            { name = "Sheogorath Costume", q = 3 },
            { name = "Pirate First Mate's Outfit", q = 4 },
            { name = "Pirate Sash and Bandolier Garb", q = 4 },
            { name = "Pirate Swab Outfit", q = 4 },
            { name = "Summit Lord's Silken Robes", q = 4 },
            { name = "Whisperweft Gala Wear", q = 4 },
            { name = "Dominion Scout", q = 5 },
            { name = "Jaqspur", q = 5 },
            { name = "Wood Elf Vanguard", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Bull-Heart Skull Sallet", q = 3 },
            { name = "Casual Plague Doctor", q = 3 },
            { name = "Cinder Mask", q = 3 },
            { name = "Stag-Heart Skull Sallet", q = 3 },
            { name = "Winterhold Blizzard Hood", q = 3 },
            { name = "Darloc Brae Beast Mask", q = 5 },
            { name = "Death Grin Skull Mask", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Death Grin Body Tattoo", q = 4 },
            { name = "Inkwing Death Crow Body Tattoo", q = 4 },
            { name = "Karthwolf Body Tattoo", q = 4 },
            { name = "Dragon Cult Body Tattoo", q = 5 },
            { name = "Dreadhorn Body Tattoo", q = 5 },
            { name = "Serpentine Interlace Body Tattoo", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Death Grin Face Tattoo", q = 4 },
            { name = "Inkwing Death Crow Face Tattoo", q = 4 },
            { name = "Karthwolf Face Tattoo", q = 4 },
            { name = "Azure Sky Blue Lip Tint", q = 5 },
            { name = "Dragon Cult Face Tattoo", q = 5 },
            { name = "Dreadhorn Face Tattoo", q = 5 },
            { name = "Dremora's Kiss Purple Lip Tint", q = 5 },
            { name = "Nocturnal Indigo Lip Tint", q = 5 },
            { name = "Sanguine's Rose Red Lip Tint", q = 5 },
            { name = "Serpentine Interlace Face Tattoo", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
