CollectThemAllData_Crates_2023_3_BuoyantArmigerCrate = {
    name = "Buoyant Armiger Crate (2023)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Harrowstorm Destrier", q = 1 },
            { name = "Necrom Armiger Senche", q = 1 },
            { name = "Spellscar Quasigriff", q = 1 },
            { name = "Buoyant Armiger Bear", q = 2 },
            { name = "Buoyant Armiger Dwarven Spider", q = 2 },
            { name = "Buoyant Armiger Kagouti", q = 2 },
            { name = "Buoyant Armiger Ornaug", q = 2 },
            { name = "Buoyant Armiger Ram", q = 2 },
            { name = "Elden Root Elk", q = 3 },
            { name = "Goldscale Guar", q = 3 },
            { name = "Oleander Senche-Serval", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Spellscar Salamander", q = 3 },
            { name = "Ancestral Haj Mota", q = 4 },
            { name = "Chaotic Creatia Cub", q = 4 },
            { name = "Discord Dremnaken Runt", q = 4 },
            { name = "Peninsula Hermit Crab", q = 4 },
            { name = "Ashen Cliff Strider", q = 5 },
            { name = "Ashsorrow Vvardvark", q = 5 },
            { name = "Clockwork Nix-Hound", q = 5 },
            { name = "Ebontusk Pocket Mammoth", q = 5 },
            { name = "Fungal Ash Hopper", q = 5 },
            { name = "Senchal Striped Cat", q = 5 },
            { name = "Snowbarrow Boar", q = 5 },
            { name = "Wolf-Lizard Pup", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Hunter's Carved Bone", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Ashlander's Fungal Beat", q = 3 },
            { name = "Cliff Racer Catastrophe", q = 4 },
            { name = "Play Netch Bagpipes", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Morag Tong", q = 3, motif = 30 },
            { name = "Crimson Oath", q = 3, motif = 105 },
            { name = "Necrom Armiger Battle Axe", q = 3 },
            { name = "Necrom Armiger Bow", q = 3 },
            { name = "Necrom Armiger Shield", q = 3 },
            { name = "Necrom Armiger Staff", q = 3 },
            { name = "Necrom Armiger Sword", q = 3 },
            { name = "Necrom Armiger Arm Cops", q = 5 },
            { name = "Necrom Armiger Belt", q = 5 },
            { name = "Necrom Armiger Boots", q = 5 },
            { name = "Necrom Armiger Bracers", q = 5 },
            { name = "Necrom Armiger Guards", q = 5 },
            { name = "Necrom Armiger Helmet", q = 5 },
            { name = "Necrom Armiger Jack", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Bound Pickaxe Strike", q = 3 },
            { name = "Armiger Axing", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Harrowing Reaper", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Spellscar Sheathe", q = 3 },
            { name = "Preening Peacock", q = 3 },
            { name = "Harvestleaf Lacquer", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Necrom Evening Attire", q = 2 },
            { name = "Necrom Prelate Robes", q = 4 },
            { name = "Orc Wise Woman's Vestment", q = 4 },
            { name = "Classic Ordinator Armor", q = 5 },
            { name = "Grazelands Gentlemer Farmer", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Auroran Commander Helm", q = 4 },
            { name = "Necrom Attire Hood", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Necrom Armiger Body Markings", q = 3 },
            { name = "Dreamstrider Body Art", q = 5 },
            { name = "Elder Dragon Body Marks", q = 5 },
            { name = "Mycoturge Body Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Necrom Armiger Face Markings", q = 4 },
            { name = "Dreamstrider Face Art", q = 5 },
            { name = "Elder Dragon Face Marks", q = 5 },
            { name = "Mycoturge Face Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Coiled Bob", q = 4 },
            { name = "Color Streaked River Braid", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Chimer Half-Mask", q = 4 },
            { name = "Mycoturge Fascinator", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
