CollectThemAllData_Crates_2018_1_ScalecallerCrate = {
    name = "Scalecaller Crate (2018)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Dragonfire Wolf", q = 1 },
            { name = "Galvanic Storm Steed", q = 1 },
            { name = "Shadow-Rider Senche", q = 1 },
            { name = "Frostbane Bear", q = 2 },
            { name = "Frostbane Camel", q = 2 },
            { name = "Frostbane Guar", q = 2 },
            { name = "Frostbane Horse", q = 2 },
            { name = "Frostbane Sabre Cat", q = 2 },
            { name = "Frostbane Wolf", q = 2 },
            { name = "Great Elk", q = 3 },
            { name = "Pellitine Mustang", q = 3 },
            { name = "Sabre Cat", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Big-Eared Ginger Mouser", q = 3 },
            { name = "Magma Scamp", q = 3 },
            { name = "Sabre Cat Cub", q = 3 },
            { name = "Senche-Tiger Cub", q = 3 },
            { name = "Flameback Boar", q = 4 },
            { name = "Gold-Cap Shroom Shalk", q = 4 },
            { name = "Housecat", q = 5 },
            { name = "Tan Morthal Mastiff", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Bone Dragon Summons Focus", q = 3 },
            { name = "Scalecaller Frost Shard", q = 4 },
            { name = "Scalecaller Rune of Levitation", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Come Get Some", q = 5 },
            { name = "Flip the Bird", q = 5 },
            { name = "I See You", q = 5 },
            { name = "Kick the Dirt", q = 5 },
            { name = "Line in Sand", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Dro-m'Athra", q = 3, motif = 35 },
            { name = "Silken Ring", q = 3, motif = 44 },
            { name = "Mazzatun", q = 3, motif = 45 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {
            { name = "Scholar", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Decayed Zombie", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Dragon Priest", q = 3 },
            { name = "Desert Garden Gala Overdress", q = 4 },
            { name = "Majestic \"Dune Rider\" Ensemble", q = 4 },
            { name = "Soiree in Camlorn Evening Suit", q = 4 },
            { name = "Vested Interest Banquet Garb", q = 4 },
            { name = "Wayrest Suede Doublet Ensemble", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Archaic Dragon Priest Mask", q = 3 },
            { name = "Tusked Dragon Priest Mask", q = 3 },
            { name = "Malefic Standing Collar Hood", q = 4 },
            { name = "Ruffian's Turban Balaclava", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Dragon Vassal Body Markings", q = 4 },
            { name = "Necromantic Sigil Body Tattoos", q = 4 },
            { name = "Dragonbone Chain Body Marking", q = 5 },
            { name = "Serpent Scale Body Marking", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Dragon Vassal Face Markings", q = 4 },
            { name = "Necromantic Sigil Face Tattoos", q = 4 },
            { name = "Dragonbone Chain Face Marking", q = 5 },
            { name = "Serpent Scale Face Marking", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Beaded Skull Chaplet", q = 5 },
            { name = "Eternal Hunger Coronal", q = 5 },
            { name = "Sacred Rhombus Circlet", q = 5 },
            { name = "Star-Brow Diadem", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
