CollectThemAllData_Crates_2021_4_CelestialCrate = {
    name = "Celestial Crate (2021)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Celestial Ram", q = 1 },
            { name = "Nebulous Star-Born Steed", q = 1 },
            { name = "Starchaser Senche", q = 1 },
            { name = "Star-Born Guardian Bear", q = 2 },
            { name = "Star-Born Guardian Guar", q = 2 },
            { name = "Star-Born Guardian Horse", q = 2 },
            { name = "Star-Born Guardian Senche", q = 2 },
            { name = "Star-Born Guardian Wolf", q = 2 },
            { name = "Chyle Seamed Nix-Ox Steed", q = 3 },
            { name = "Elder Dragon Hunter Horse", q = 3 },
            { name = "Mind-Shriven Wolf", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Anthorbred Avalanche Dog", q = 4 },
            { name = "Blue Cloisonne Clockwork Shalk", q = 4 },
            { name = "Skald-Muse Fledgling Gryphon", q = 4 },
            { name = "Bleakrock Black Sheep", q = 5 },
            { name = "Elder Dragon Hunter Wolf Pup", q = 5 },
            { name = "Mind-Shriven Cat", q = 5 },
            { name = "Nectarthief Nixad", q = 5 },
            { name = "Niben River Fellrunner", q = 5 },
            { name = "Orcrest Rathound", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Astral Aurora Projector", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Play Qanun", q = 4 },
            { name = "Bumbling Artificer", q = 5 },
            { name = "Feline's Fancy Juggling", q = 5 },
            { name = "Stargazer", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Fang Lair", q = 3, motif = 58 },
            { name = "Stags of Z'en", q = 3, motif = 77 },
            { name = "Spellscar Lithoarms Battle Axe", q = 3 },
            { name = "Spellscar Lithoarms Bow", q = 3 },
            { name = "Spellscar Lithoarms Shield", q = 3 },
            { name = "Spellscar Lithoarms Staff", q = 3 },
            { name = "Spellscar Lithoarms Sword", q = 3 },
            { name = "Scorianite Gladiator Helmet", q = 4 },
            { name = "Scorianite Gladiator Jack", q = 4 },
            { name = "Scorianite Gladiator Belt", q = 5 },
            { name = "Scorianite Gladiator Boots", q = 5 },
            { name = "Scorianite Gladiator Bracers", q = 5 },
            { name = "Scorianite Gladiator Arm Cops", q = 5 },
            { name = "Scorianite Gladiator Guards", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Astral Sheen", q = 2 },
            { name = "Impish Epidermis", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Celestial Robes", q = 2 },
            { name = "Dark Shaman", q = 3 },
            { name = "Logger", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Xivilai Vilegilt Linework Brand", q = 3 },
            { name = "Xivilai Weltwine Linework Brand", q = 4 },
            { name = "Fortune's Anvil Body Markings", q = 5 },
            { name = "Xivilai Cruelean Linework Brand", q = 5 },
            { name = "Xivilai Rubyfire Linework Brand", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Azure Eyes", q = 4 },
            { name = "Xivilai Vilegilt Linework Visage", q = 4 },
            { name = "Xivilai Weltwine Linework Visage", q = 4 },
            { name = "Fortune's Anvil Face Markings", q = 5 },
            { name = "Xivilai Cruelean Linework Visage", q = 5 },
            { name = "Xivilai Rubyfire Linework Visage", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Hopesbud Coronal", q = 4 },
            { name = "Shrouded Crown", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
