CollectThemAllData_Crates_2023_2_UnfeatheredCrate = {
    name = "Unfeathered Crate (2023)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Ahz-m'Athra", q = 1 },
            { name = "Auroran Polychrome Wolf", q = 1 },
            { name = "Legion Zero Sabre Cat", q = 1 },
            { name = "Umaril's Radiance Elk", q = 2 },
            { name = "Umaril's Radiance Guar", q = 2 },
            { name = "Umaril's Radiance Senche", q = 2 },
            { name = "Umaril's Radiance Wolf", q = 2 },
            { name = "Duskfall Welwa", q = 3 },
            { name = "Khenarthi's Windwalker", q = 3 },
            { name = "Indigo Twilight Camel", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Abyssal Tomeshell", q = 4 },
            { name = "Chromatic Scorpion", q = 4 },
            { name = "Evermore Painter's Moth", q = 4 },
            { name = "Heartland Coon Cat", q = 4 },
            { name = "Nenalata Ayleid Wolf Pup", q = 4 },
            { name = "Balmora Constrictor", q = 5 },
            { name = "Biscuit Bear-Dog", q = 5 },
            { name = "Brindle Bear Cub", q = 5 },
            { name = "Duskfall Ancestor Lizard", q = 5 },
            { name = "Faun Fawn", q = 5 },
            { name = "Sterling Cavy", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Soul Crystals of the Returned", q = 3 },
            { name = "Fighter's Guild Blade Barrel", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Handy Pocket Scrib", q = 4 },
            { name = "Sapphire Knighting", q = 4 },
            { name = "Wayrest Party Incident", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Dro-m'Athra", q = 3, motif = 35 },
            { name = "Meridian", q = 3, motif = 72 },
            { name = "Unfeathered Greatsword", q = 3 },
            { name = "Unfeathered Bow", q = 3 },
            { name = "Unfeathered Mace", q = 3 },
            { name = "Unfeathered Shield", q = 3 },
            { name = "Unfeathered Staff", q = 3 },
            { name = "Dreugh Queen Cuirass", q = 5 },
            { name = "Dreugh Queen Gauntlets", q = 5 },
            { name = "Dreugh Queen Girdle", q = 5 },
            { name = "Dreugh Queen Greaves", q = 5 },
            { name = "Dreugh Queen Helm", q = 5 },
            { name = "Dreugh Queen Pauldrons", q = 5 },
            { name = "Dreugh Queen Sabatons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Legionnaire's Recall", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Armor of the Unfeathered", q = 3 },
            { name = "Lich", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Do'Krin Ascetic's Henna", q = 3 },
            { name = "Glowgill Guarhide", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Dwemerdelve Scavenger", q = 2 },
            { name = "Telvanni Master Wizard", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Scavenger Legion Helm", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Hoardwalker Body Marks", q = 3 },
            { name = "Ayleid Body Ruinmarks", q = 5 },
            { name = "Cathay Baandari Body Brand", q = 5 },
            { name = "Swaying Skeleton Body Art", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Coldharbour Corruption Eyes", q = 4 },
            { name = "Hoardwalker Face Marks", q = 4 },
            { name = "Ayleid Face Ruinmarks", q = 5 },
            { name = "Cathay Baandari Face Brand", q = 5 },
            { name = "Swaying Skeleton Face Art", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Braided Tresses", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Steadfast Society Ball Domino", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Bright Lady's Baubles", q = 4 },
        },
    },
}
