CollectThemAllData_Crates_2019_4_FrostAtronachCrate = {
    name = "Frost Atronach Crate (2019)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Dark Aeon Wolf", q = 1 },
            { name = "Dark Opaline Steed", q = 1 },
            { name = "Volcanic Senche-Panther", q = 1 },
            { name = "Frost Atronach Bear", q = 2 },
            { name = "Frost Atronach Dwarven Spider", q = 2 },
            { name = "Frost Atronach Horse", q = 2 },
            { name = "Frost Atronach Kagouti", q = 2 },
            { name = "Frost Atronach Senche", q = 2 },
            { name = "Frost Atronach Wolf", q = 2 },
            { name = "Coalsmoke Forge Horse", q = 3 },
            { name = "Graysmoke Forge Bear", q = 3 },
            { name = "Snow Leopard Sabre Cat", q = 3 },
            { name = "Witch Knight Charger", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Boralis Gray Wolf Pup", q = 4 },
            { name = "Fawn", q = 4 },
            { name = "Snowcap Fledgling Gryphon", q = 4 },
            { name = "Black Cat", q = 5 },
            { name = "Milady's Cloud Cat", q = 5 },
            { name = "Senchal Harbor-Mutt", q = 5 },
            { name = "Slateback Haj Mota", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Blizzard Globe", q = 4 },
            { name = "Everlasting Snowball", q = 4 },
            { name = "Snow Cadwell", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Festive Bell Ring", q = 5 },
            { name = "Mistletoe", q = 5 },
            { name = "Mistletoe Posterior", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Ancient Orc", q = 3, motif = 21 },
            { name = "Trinimac", q = 3, motif = 22 },
            { name = "Malacath", q = 3, motif = 23 },
            { name = "Pellitine Outlaw Bow", q = 3 },
            { name = "Pellitine Outlaw Dagger", q = 3 },
            { name = "Pellitine Outlaw Greatsword", q = 3 },
            { name = "Pellitine Outlaw Staff", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {
            { name = "Treasure Hunter", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Deadlands Brand", q = 3 },
            { name = "Maormer Fish", q = 3 },
            { name = "Opalescent Epidermis", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Bleakrock Housecarl Dress", q = 4 },
            { name = "Bonding Rite Vestment", q = 4 },
            { name = "Eternity Tunic with Pants", q = 5 },
            { name = "Grazelands Gentlemer Farmer", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "First Cat's Pride Tattoo", q = 4 },
            { name = "Legendary Dragon Body Marks", q = 4 },
            { name = "Frigid Impact Body Marking", q = 5 },
            { name = "New Moon Cultist Body Tattoo", q = 5 },
            { name = "Nocturnal Outlaw Body Tattoo", q = 5 },
            { name = "Senchal Brigand Body Tattoo", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "First Cat's Pride Tattoo", q = 4 },
            { name = "Legendary Dragon Face Marks", q = 4 },
            { name = "Frigid Impact Face Marking", q = 5 },
            { name = "New Moon Cultist Face Tattoo", q = 5 },
            { name = "Nocturnal Outlaw Face Tattoo", q = 5 },
            { name = "Senchal Brigand Face Tattoo", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {
            { name = "Winter Princess Glamour", q = 4 },
            { name = "Frosty Features", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Snowcrystal Tiara", q = 4 },
            { name = "Legendary Dragon Coronal", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Legendary Dragon Piercing", q = 5 },
        },
    },
}
