CollectThemAllData_Crates_2022_3_WraithtideCrate = {
    name = "Wraithtide Crate (2022)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Forge Master's Charger", q = 1 },
            { name = "Reefstrider Ornaug", q = 1 },
            { name = "Warmaiden's Wolf", q = 1 },
            { name = "Wraithtide Bear", q = 2 },
            { name = "Wraithtide Guar", q = 2 },
            { name = "Wraithtide Senche", q = 2 },
            { name = "Wraithtide Wolf", q = 2 },
            { name = "Hel Ra Camel of Kingship", q = 3 },
            { name = "Nibenay Bay Ram", q = 3 },
            { name = "Speckled Welwa", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Lemondot Netch", q = 4 },
            { name = "Mnemoflare Fabricant", q = 4 },
            { name = "Ringtail Jerboa", q = 4 },
            { name = "Crusader's Coin Chicken", q = 5 },
            { name = "Hay-Crown Chub Loon", q = 5 },
            { name = "Morthal Bear-Dog", q = 5 },
            { name = "Mottled Sheep", q = 5 },
            { name = "Silver-Gray Mouser Cat", q = 5 },
            { name = "Topaz Fledgling Terror Bird", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Darkswarm Talisman", q = 4 },
            { name = "Fargrave Occult Curio", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Runepriest's Bow", q = 3 },
            { name = "Runepriest's Greatsword", q = 3 },
            { name = "Runepriest's Shield", q = 3 },
            { name = "Runepriest's Staff", q = 3 },
            { name = "Runepriest's Sword", q = 3 },
            { name = "Nighthollow", q = 3, motif = 95 },
            { name = "Sea Giant", q = 3, motif = 86 },
            { name = "Thorn Legion", q = 3, motif = 90 },
            { name = "Seamount Raider Gauntlets", q = 5 },
            { name = "Seamount Raider Greaves", q = 5 },
            { name = "Seamount Raider Helm", q = 5 },
            { name = "Seamount Raider Jack", q = 5 },
            { name = "Seamount Raider Pauldrons", q = 5 },
            { name = "Seamount Raider Sabatons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Boneman", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Brineglow", q = 2 },
            { name = "Magmaheart", q = 2 },
            { name = "Shallowbay Nereid", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Stillrise Ritecaller", q = 2 },
            { name = "Nordic Knot Doublet and Breeches", q = 4 },
            { name = "Forge-Wife's Impervious Frock", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Sailor-at-Arms Helm", q = 4 },
            { name = "Sentinel Fox Mask", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Netchspot Abstraction Body Marks", q = 4 },
            { name = "Red Diamond Body Stainwork", q = 4 },
            { name = "Shagrath's Favor Body Marks", q = 5 },
            { name = "Skald's Body Branding", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Wyrd Sight", q = 4 },
            { name = "Eyes of Umaril", q = 4 },
            { name = "Netchspot Abstraction Face Marks", q = 5 },
            { name = "Red Diamond Face Stainwork", q = 5 },
            { name = "Shagrath's Favor Face Marks", q = 5 },
            { name = "Skald's Face Branding", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
