CollectThemAllData_Crates_2025_1_CarnavalCrate = {
    name = "Carnaval Crate (2025)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Carnaval Feathered Guar", q = 1 },
            { name = "Kynareth's Quasigriff", q = 1 },
            { name = "Sanguine Gargoyle", q = 1 },
            { name = "Carnaval Indrik", q = 2 },
            { name = "Carnaval Jaguar", q = 2 },
            { name = "Carnaval Nix-Ox", q = 2 },
            { name = "Carnaval Welwa", q = 2 },
            { name = "Arenthian Skewbald Horse", q = 3 },
            { name = "Striped War Pangrit", q = 3 },
            { name = "Wind Keep Bear", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Black Heights Squirrel", q = 4 },
            { name = "Kynareth's Fledgling Gryphon", q = 4 },
            { name = "Root-Whisper Crested Dart Frog", q = 4 },
            { name = "Tenmar Magpie", q = 4 },
            { name = "Arenthian Skewbald Pony", q = 5 },
            { name = "Lilmoth Crocodile Hatchling", q = 5 },
            { name = "Russafeld Fellrunner", q = 5 },
            { name = "Saltwater Bog Dog", q = 5 },
            { name = "Silsailen Tortie-Calico Cat", q = 5 },
            { name = "Striped Pangrit Nymphling", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Carnaval Festive Dance", q = 3 },
            { name = "Carnaval Fan Dance", q = 3 },
            { name = "Play Solstice Rattlers", q = 4 },
            { name = "Street Food Juggle", q = 4 },
            { name = "Tipsy Topple", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Dead-Water", q = 3, motif = 69 },
            { name = "Carnaval Maul", q = 3 },
            { name = "Carnaval Bow", q = 3 },
            { name = "Carnaval Shield", q = 3 },
            { name = "Carnaval Staff", q = 3 },
            { name = "Carnaval Sword", q = 3 },
            { name = "Welwa Feathered Warrior Jerkin", q = 5 },
            { name = "Welwa Feathered Warrior Breeches", q = 5 },
            { name = "Welwa Feathered Warrior Hat", q = 5 },
            { name = "Welwa Feathered Warrior Shoes", q = 5 },
            { name = "Welwa Feathered Warrior Gloves", q = 5 },
            { name = "Welwa Feathered Warrior Epaulets", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Featherdance Carnaval Recall", q = 2 },
            { name = "Kyne's Cleave", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {
            { name = "War Horn, Aquatic", q = 3 },
            { name = "Wall of Elements, Autumn Leaves", q = 3 },
            { name = "Vigor, Verdant Green", q = 4 },
            { name = "Whirlwind, Cinnabar Red", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Voskrona Guardian", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {
            { name = "Dancer", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Sanguine's Disciple", q = 2 },
            { name = "Dawnwood Tender's Skin", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Carnaval Celebrant", q = 2 },
            { name = "Carnaval Feathered Dancing Dress", q = 3 },
            { name = "Lizardly Four-Fabric Skirt Set", q = 4 },
            { name = "Black Marsh Keeper", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Xanmeer Doyen's Feather Tiara", q = 4 },
            { name = "Carnaval Feathered Headdress", q = 4 },
            { name = "Bonding Rite Headdress", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Blackwood Carnaval Body Paint", q = 5 },
            { name = "Sanguine's Indulgence Body Marks", q = 5 },
            { name = "Stone-Nest Orator Body Paint", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Carnaval Alluring Eyes", q = 4 },
            { name = "Carnaval Feathered Gaze", q = 4 },
            { name = "Blackwood Carnaval Face Paint", q = 5 },
            { name = "Sanguine's Indulgence Face Marks", q = 5 },
            { name = "Stone-Nest Orator Face Paint", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Carnaval Side Part", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Carnaval Beaded Veil", q = 4 },
            { name = "Carnaval Dancing Tiara", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Carnaval Emerald Earrings", q = 4 },
        },
    },
}
