CollectThemAllData_Crates_2020_4_AkaviriPotentateCrate = {
    name = "Akaviri Potentate Crate (2020)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Potentate Aphotic Wolf", q = 1 },
            { name = "Potentate Cloudracer Courser", q = 1 },
            { name = "Potentate Halcyon Senche", q = 1 },
            { name = "Akaviri Potentate Bear", q = 2 },
            { name = "Akaviri Potentate Camel", q = 2 },
            { name = "Akaviri Potentate Charger", q = 2 },
            { name = "Akaviri Potentate Guar", q = 2 },
            { name = "Akaviri Potentate Sabre Cat", q = 2 },
            { name = "Akaviri Potentate Wolf", q = 2 },
            { name = "Ambergill Guar", q = 3 },
            { name = "Daggerfall Dapple Horse", q = 3 },
            { name = "Floral Tattoo Shorn Camel", q = 3 },
            { name = "Helkarn Wolf", q = 3 },
            { name = "Snowy Sabre Cat", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Druadach Mountain Dog", q = 4 },
            { name = "Dusklight Lunar Moth", q = 4 },
            { name = "Ghostly Housecat", q = 4 },
            { name = "Helkarn Wolf Pup", q = 4 },
            { name = "Tawny Lambent Guar", q = 4 },
            { name = "Karthwasten Silver Boar", q = 5 },
            { name = "Mara's Blush Butterfly", q = 5 },
            { name = "Orcrest Jerboa", q = 5 },
            { name = "Sable Tenmar Stray", q = 5 },
            { name = "Snowy Sabre Cat Cub", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Campfire Kit", q = 4 },
            { name = "Temporary Candlefly Lantern", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Boozy Boot", q = 4 },
            { name = "Karthwatch Banner", q = 4 },
            { name = "Morthal Banner", q = 4 },
            { name = "Solitude Banner", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Potentate Smiling Viper Helm", q = 3 },
            { name = "Potentate Scaled Dragon Helm", q = 3 },
            { name = "Akaviri Potentate Cuirass", q = 5 },
            { name = "Akaviri Potentate Pauldrons", q = 5 },
            { name = "Akaviri Potentate Gauntlets", q = 5 },
            { name = "Akaviri Potentate Girdle", q = 5 },
            { name = "Akaviri Potentate Greaves", q = 5 },
            { name = "Akaviri Potentate Helm", q = 5 },
            { name = "Akaviri Potentate Sabatons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Dusky Guarhide", q = 3 },
            { name = "Red Diamond Guardian", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Dungeon Explorer", q = 3 },
            { name = "Harboursworn Occultist", q = 3 },
            { name = "Bardic Tavern-Singer's Dress", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Lambent Guar Body Markings", q = 4 },
            { name = "Eye of Shalidor Body Markings", q = 5 },
            { name = "Glenmoril Wyrd Body Markings", q = 5 },
            { name = "Riften Rogue Body Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Lambent Guar Face Markings", q = 4 },
            { name = "Eye of Shalidor Face Markings", q = 5 },
            { name = "Glenmoril Wyrd Face Markings", q = 5 },
            { name = "Riften Rogue Face Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Unruly Bangs", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Anthor's Shadow Crown", q = 5 },
            { name = "Dawn's Eye Crown", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
