CollectThemAllData_Crates_2021_1_AyleidCrate = {
    name = "Ayleid Crate (2021)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Culanda-Born Senche", q = 1 },
            { name = "Varla-Born Wolf", q = 1 },
            { name = "Welkynd-Born Courser", q = 1 },
            { name = "Nenalata Ayleid Bear", q = 2 },
            { name = "Nenalata Ayleid Camel", q = 2 },
            { name = "Nenalata Ayleid Guar", q = 2 },
            { name = "Nenalata Ayleid Horse", q = 2 },
            { name = "Nenalata Ayleid Senche", q = 2 },
            { name = "Nenalata Ayleid Wolf", q = 2 },
            { name = "Dagon Fel Nix-Ox Steed", q = 3 },
            { name = "Deadlands Guar", q = 3 },
            { name = "Legion Zero Destrier", q = 3 },
            { name = "Scorched Alley Howler", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Gloam Wolf Cub", q = 3 },
            { name = "Meridian Sabre Cub", q = 3 },
            { name = "Deadlands Daedrat", q = 4 },
            { name = "Pale-Plume Fledgling Gryphon", q = 4 },
            { name = "Vale Fawn", q = 4 },
            { name = "Bal Ur Cliff Strider", q = 5 },
            { name = "Cloud Spring White Sheep", q = 5 },
            { name = "Lilmoth Ancestor Lizard", q = 5 },
            { name = "Linchal Titian Fox", q = 5 },
            { name = "Snow Bear Cub", q = 5 },
            { name = "Wickerfright Banekin", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Painter's Easel and Canvas", q = 3 },
            { name = "Phial of Clockwork Lubricant", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Day of Lights Spectacle", q = 3 },
            { name = "Own the Throne", q = 4 },
            { name = "Barkeep", q = 5 },
            { name = "Miser's Muse", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Silyanorn Ayleid Bow", q = 4 },
            { name = "Silyanorn Ayleid Maul", q = 4 },
            { name = "Silyanorn Ayleid Shield", q = 4 },
            { name = "Silyanorn Ayleid Staff", q = 4 },
            { name = "Silyanorn Ayleid Sword", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Hollow Void Husk", q = 3 },
            { name = "Varla-Born", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Fisherfolk Work Wear", q = 3 },
            { name = "Treethane's Mosaic Jerkin", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Courtly Crow Mask", q = 5 },
            { name = "Silvenari Felt Bycoket", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Blessed Life-Tree Body Markings", q = 3 },
            { name = "Warrior-Poet Body Tattoos", q = 4 },
            { name = "Maddening Mishap Body Markings", q = 5 },
            { name = "Saliache Scholar Body Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Blessed Life-Tree Face Markings", q = 4 },
            { name = "Spiderkith Eyes", q = 4 },
            { name = "Warrior-Poet Face Tattoos", q = 4 },
            { name = "Maddening Mishap Face Markings", q = 5 },
            { name = "Prankster Purple Face Paint", q = 5 },
            { name = "Raconteur Red Face Paint", q = 5 },
            { name = "Saliache Scholar Face Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Cherry Blossom Anadem", q = 5 },
            { name = "Dagon's Thorns", q = 5 },
            { name = "Saliache Aetherial Tiara", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
