CollectThemAllData_Crates_2025_2_AkatoshVsAlduinCrate = {
    name = "Akatosh vs. Alduin Crate (2025)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Stone-Nest Landloper", q = 1 },
            { name = "Kyne-Blessed Thundersnow Steed", q = 1 },
            { name = "Dragonclash Living Armor Senche", q = 1 },
            { name = "Akatosh Living Armor Senche", q = 1 },
            { name = "Alduin Living Armor Senche", q = 1 },
            { name = "Scaleborn Bear", q = 2 },
            { name = "Scaleborn Ram", q = 2 },
            { name = "Scaleborn Senche-Raht", q = 2 },
            { name = "Scaleborn Wolf", q = 2 },
            { name = "Golden Nix-Ox Steed", q = 3 },
            { name = "Twilight Kagouti Destroyer", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Dragonclash Tomeshell", q = 4 },
            { name = "Honeybutter Dragon Frog", q = 4 },
            { name = "Ruinous Bone Dragon", q = 4 },
            { name = "Windhelm Snow Owl", q = 4 },
            { name = "Golden Shalk", q = 5 },
            { name = "Navire Chicken", q = 5 },
            { name = "Understone Obsidian Hare", q = 5 },
            { name = "Twilight Kagouti Hatchling", q = 5 },
            { name = "Solstice Flats Dovah-Fly", q = 5 },
            { name = "Bright Moons Dragon Imp", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Dragonclash Flame Orbs", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "World-Eater's Fire Dance", q = 3 },
            { name = "Nordic Yell and Yawp", q = 4 },
            { name = "Fingers Crossed", q = 5 },
            { name = "Warm Hands", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Greymoor", q = 3, motif = 85 },
            { name = "Dragonguard", q = 3, motif = 76 },
            { name = "Devourer's Dragonbone Axe", q = 3 },
            { name = "Devourer's Dragonbone Greatsword", q = 3 },
            { name = "Devourer's Dragonbone Mace", q = 3 },
            { name = "Devourer's Dragonbone Staff", q = 3 },
            { name = "Time's Herald Battleaxe", q = 3 },
            { name = "Time's Herald Maul", q = 3 },
            { name = "Time's Herald Shield", q = 3 },
            { name = "Time's Herald Sword", q = 3 },
            { name = "Time's Herald Helm", q = 4 },
            { name = "Time's Herald Pauldrons", q = 4 },
            { name = "Time's Herald Bow", q = 4 },
            { name = "World-Eater's Ruin Helm", q = 4 },
            { name = "World-Eater's Ruin Pauldrons", q = 4 },
            { name = "Devourer's Dragonbone Dagger", q = 4 },
            { name = "Time's Herald Cuirass", q = 5 },
            { name = "Time's Herald Gauntlets", q = 5 },
            { name = "Time's Herald Girdle", q = 5 },
            { name = "Time's Herald Greaves", q = 5 },
            { name = "Time's Herald Sabatons", q = 5 },
            { name = "World-Eater's Ruin Cuirass", q = 5 },
            { name = "World-Eater's Ruin Gauntlets", q = 5 },
            { name = "World-Eater's Ruin Girdle", q = 5 },
            { name = "World-Eater's Ruin Greaves", q = 5 },
            { name = "World-Eater's Ruin Sabatons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "World-Eater's Fiery Recall", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {
            { name = "Shield Charge, Dragonclash", q = 3 },
            { name = "Volley of the World-Eater", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Time's Herald Living Armor", q = 2 },
            { name = "World-Eater's Living Armor", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Blaze of Akatosh", q = 2 },
            { name = "World-Eater's Flame", q = 2 },
            { name = "Scaly Sun Basker", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Dragon Rage Berserker's Garb", q = 2 },
            { name = "Highborn Jarl's Dress", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Dragonclash Body Marking", q = 5 },
            { name = "Timebound Sovereign Body Tattoo", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "World-Eater Eyes", q = 4 },
            { name = "Akatosh Golden Eye", q = 4 },
            { name = "Dragonclash Face Marking", q = 5 },
            { name = "Timebound Sovereign Face Tattoo", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Dragonfire Tresses", q = 4 },
            { name = "High Hrothgar Braid", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Highborn Jarl's Brow Band", q = 4 },
            { name = "Dragon Cult Piercings", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Lord of Dragons Ear Cuff", q = 4 },
        },
    },
}
