CollectThemAllData_Crates_2021_2_IronAtronachCrate = {
    name = "Iron Atronach Crate (2021)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Black Forge Iron Senche", q = 1 },
            { name = "Sunflare Iron Wolf", q = 1 },
            { name = "Viridian Iron Steed", q = 1 },
            { name = "Iron Atronach Bear", q = 2 },
            { name = "Iron Atronach Camel", q = 2 },
            { name = "Iron Atronach Guar", q = 2 },
            { name = "Iron Atronach Horse", q = 2 },
            { name = "Iron Atronach Senche", q = 2 },
            { name = "Iron Atronach Wolf", q = 2 },
            { name = "Bull Kagouti Charger", q = 3 },
            { name = "Dappled Elinhir Camel", q = 3 },
            { name = "Solstheim Lunar Wolf", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Brimstone Nixad", q = 3 },
            { name = "Nightmare Firestalker Cub", q = 3 },
            { name = "Deadlands Scorpion", q = 4 },
            { name = "Hearthfire Hatchling", q = 4 },
            { name = "Stitchfur Cavy", q = 4 },
            { name = "Tourmaline Swamp Jelly", q = 4 },
            { name = "Goldspine Boar", q = 5 },
            { name = "Hallin's Jackal", q = 5 },
            { name = "Iliac Spotted Goat", q = 5 },
            { name = "Necrom Ghostgazer Cat", q = 5 },
            { name = "Scutecicle Haj Mota", q = 5 },
            { name = "Sea Sapphire Dovah-Fly", q = 5 },
            { name = "Wasten Coraldale Mudcrab", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Inferno Cleats", q = 3 },
            { name = "Impartial Decision Coin", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Blow Bubbles", q = 4 },
            { name = "Crochet", q = 4 },
            { name = "Fire Salts", q = 5 },
            { name = "Spicy Soup", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Iron Atronach Battle Axe", q = 3 },
            { name = "Iron Atronach Bow", q = 3 },
            { name = "Iron Atronach Dagger", q = 3 },
            { name = "Iron Atronach Shield", q = 3 },
            { name = "Iron Atronach Staff", q = 3 },
            { name = "Knight-Aspirant Courting Helm", q = 4 },
            { name = "Knight-Aspirant Tourney Helm", q = 4 },
            { name = "Knight-Aspirant Cuirass", q = 5 },
            { name = "Knight-Aspirant Gauntlets", q = 5 },
            { name = "Knight-Aspirant Girdle", q = 5 },
            { name = "Knight-Aspirant Greaves", q = 5 },
            { name = "Knight-Aspirant Helm", q = 5 },
            { name = "Knight-Aspirant Pauldrons", q = 5 },
            { name = "Knight-Aspirant Sabatons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Iron Atronach", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Deadlands Excoriated", q = 3 },
            { name = "Hist-Tsoko", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Naryu's Morag Tong Costume", q = 3 },
            { name = "Nibenese Noble's Shawled Robe", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Dagon's Aspirant Body Markings", q = 5 },
            { name = "Sul-Xan Prophet Body Markings", q = 5 },
            { name = "Triptych Motion Body Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Dagon's Aspirant Face Markings", q = 5 },
            { name = "Sul-Xan Prophet Face Markings", q = 5 },
            { name = "Triptych Motion Face Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Morag Tong Spatter Lenses", q = 4 },
            { name = "Nibenese Laurel Coronet", q = 4 },
            { name = "Stallion-Liege Brow Medallion", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
