CollectThemAllData_Crates_2024_1_OrderOfTheLampCrate = {
    name = "Order of the Lamp Crate (2024)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Altered Ornaug", q = 1 },
            { name = "Galerion's Indrik", q = 1 },
            { name = "Mystical Quasigriff", q = 1 },
            { name = "Order of the Lamp Destrier", q = 2 },
            { name = "Order of the Lamp Jackal", q = 2 },
            { name = "Order of the Lamp Lion", q = 2 },
            { name = "Order of the Lamp Vvardvark", q = 2 },
            { name = "Brindle Bear", q = 3 },
            { name = "Master-Wizard's Ram", q = 3 },
            { name = "Sunset Welwa", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Conjured Dragon Imp", q = 4 },
            { name = "Prismatic Senche Cub", q = 4 },
            { name = "Ruby Haj Mota", q = 4 },
            { name = "Stainedwing Butterfly", q = 4 },
            { name = "Blueblood Frog Hound Pup", q = 5 },
            { name = "Emerald Oak Nixad", q = 5 },
            { name = "Guild Conjured Wisp", q = 5 },
            { name = "Meridia-Touched Asp", q = 5 },
            { name = "Saarthal Shepherd", q = 5 },
            { name = "Sugarsnow Monkey", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Play Glass Armonica", q = 3 },
            { name = "Varkenel's Hat Trick", q = 3 },
            { name = "Apprentice's Idle Magic", q = 4 },
            { name = "Clap Hands", q = 4 },
            { name = "Potion Peddler", q = 4 },
            { name = "Syrabane Living Statue", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "New Moon Priest", q = 3, motif = 81 },
            { name = "Celestial", q = 3, motif = 41 },
            { name = "Order of the Lamp Battle Axe", q = 3 },
            { name = "Order of the Lamp Bow", q = 3 },
            { name = "Order of the Lamp Shield", q = 3 },
            { name = "Order of the Lamp Staff", q = 3 },
            { name = "Order of the Lamp Sword", q = 3 },
            { name = "Order of the Lamp Cuirass", q = 5 },
            { name = "Order of the Lamp Gauntlets", q = 5 },
            { name = "Order of the Lamp Greaves", q = 5 },
            { name = "Order of the Lamp Helm", q = 5 },
            { name = "Order of the Lamp Pauldrons", q = 5 },
            { name = "Order of the Lamp Sabatons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Accursed Recall", q = 3 },
            { name = "Meteor Mining", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Storm Atronach", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Aether-Tempered Mystic", q = 2 },
            { name = "Mystic Magicka Molt", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Evoker on Errantry", q = 3 },
            { name = "Wizard About Town", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Plumed Cavalier", q = 4 },
            { name = "Windhelm Fox Mask", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Aristocratic Astrologer Body Art", q = 5 },
            { name = "Magicka Everlasting Body Marks", q = 5 },
            { name = "Sheogorat Body Branding", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Mages Guild Sigil Makeup", q = 4 },
            { name = "Midnight Rising Makeup", q = 4 },
            { name = "Aristocratic Astrologer Face Art", q = 5 },
            { name = "Magicka Everlasting Face Marks", q = 5 },
            { name = "Sheogorat Face Branding", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Arcanist's Crest", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Eyevea Evoker's Flair", q = 4 },
            { name = "Warlock's Veil", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
