CollectThemAllData_Crates_2019_3_NewMoonCrate = {
    name = "New Moon Crate (2019)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Plagueborn Senche-Panther", q = 1 },
            { name = "Planemeld Courser", q = 1 },
            { name = "Sanguivorian Howler", q = 1 },
            { name = "New Moon Bear", q = 2 },
            { name = "New Moon Camel", q = 2 },
            { name = "New Moon Guar", q = 2 },
            { name = "New Moon Horse", q = 2 },
            { name = "New Moon Senche", q = 2 },
            { name = "New Moon Wolf", q = 2 },
            { name = "Death Mask Sabre Cat", q = 3 },
            { name = "Eerie Elk of Dread", q = 3 },
            { name = "Grisly Horse Mummy", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Dread-Aurelian Dragonslayer Wolf", q = 4 },
            { name = "Ghostly Daedrat", q = 4 },
            { name = "Haunting Netch", q = 4 },
            { name = "Haunted House Cat", q = 4 },
            { name = "Nightmare Wolf Pup", q = 4 },
            { name = "Solar Arc Dwarven Spider", q = 4 },
            { name = "Spectral Chicken", q = 4 },
            { name = "Badger Ruff Echalette", q = 5 },
            { name = "Masked Bear Cub", q = 5 },
            { name = "Shadowghost Pony", q = 5 },
            { name = "Spotted Snow Senche-Leopard", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Arkay's Warding Gesture", q = 5 },
            { name = "Drink From Skull", q = 5 },
            { name = "Summon Bat", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "New Moon Bow", q = 3 },
            { name = "New Moon Maul", q = 3 },
            { name = "New Moon Shield", q = 3 },
            { name = "New Moon Staff", q = 3 },
            { name = "New Moon Sword", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Wraith-of-Crows", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Blood-Drained Thrall", q = 3 },
            { name = "Ebony Epidermis", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Orc Wise Woman's Vestment", q = 4 },
            { name = "Skald's Damask Jerkin", q = 4 },
            { name = "Telvanni Wizard-Lord Robe", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Daedric Death Mask", q = 5 },
            { name = "Deep Elf Executioner's Hood", q = 5 },
            { name = "Z'en Vengeance Kiss-Me-Not Cap", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Death Dealer Body Markings", q = 5 },
            { name = "Dragondancer Body Markings", q = 5 },
            { name = "Gargoyle Body Flair", q = 5 },
            { name = "Trophy of Balorgh Body Tattoo", q = 5 },
            { name = "Wings of Darkness Body Tattoos", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Death Dealer Facial Markings", q = 5 },
            { name = "Dragondancer Facial Markings", q = 5 },
            { name = "Gargoyle Facial Flair", q = 5 },
            { name = "Trophy of Balorgh Facial Tattoo", q = 5 },
            { name = "Wings of Darkness Face Tattoos", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Ancient Dragon Hunter Coronal", q = 5 },
            { name = "Dragondancer's Circlet", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Ancient Dragon Hunter Piercing", q = 5 },
            { name = "Dragondancer's Cheek Cord", q = 5 },
        },
    },
}
