CollectThemAllData_Crates_2023_1_RageboundCrate = {
    name = "Ragebound Crate (2023)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Harrowforged Durzog", q = 1 },
            { name = "Icerage Bear", q = 1 },
            { name = "Voidmother's Welwa", q = 1 },
            { name = "Ragebound Bear", q = 2 },
            { name = "Ragebound Durzog", q = 2 },
            { name = "Ragebound Kagouti", q = 2 },
            { name = "Ragebound Sabre Cat", q = 2 },
            { name = "Ragebound Steed", q = 2 },
            { name = "Duskember Fox", q = 3 },
            { name = "Karth River Sabre Cat", q = 3 },
            { name = "King's Guard Ram", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Menevian Coachdog", q = 4 },
            { name = "Sungard Sabre Cat", q = 4 },
            { name = "South Weald Prairie Dog", q = 4 },
            { name = "Xylo Pollen Bat", q = 4 },
            { name = "Grahtwood Fisher", q = 5 },
            { name = "Heartland River Crab", q = 5 },
            { name = "Rimmen Jerboa", q = 5 },
            { name = "Silver-Bellied Guarling", q = 5 },
            { name = "Vvardvark", q = 5 },
            { name = "Yoltoor Dovah-Fly", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Key Harp", q = 3 },
            { name = "Aerial Escapades", q = 4 },
            { name = "Foe Crusher", q = 4 },
            { name = "Play Pan Flute", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Bloodrage Bow", q = 3 },
            { name = "Bloodrage Dagger", q = 3 },
            { name = "Bloodrage Battle Axe", q = 3 },
            { name = "Bloodrage Shield", q = 3 },
            { name = "Bloodrage Staff", q = 3 },
            { name = "Dreadhorn", q = 3, motif = 55 },
            { name = "Welkynar", q = 3, motif = 67 },
            { name = "Balfieran Sentinel Helm", q = 5 },
            { name = "Balfieran Sentinel Pauldrons", q = 5 },
            { name = "Balfieran Sentinel Cuirass", q = 5 },
            { name = "Balfieran Sentinel Gauntlets", q = 5 },
            { name = "Balfieran Sentinel Greaves", q = 5 },
            { name = "Balfieran Sentinel Sabatons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Bitter Coast Recall", q = 3 },
            { name = "Reach Witch Removal", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Shade", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Flesh of the Harrowed", q = 2 },
            { name = "Rain's Hand Renewal", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Ragebound Harness", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Crow-Heart Skull Sallet", q = 4 },
            { name = "Icerage Helm", q = 4 },
            { name = "Mercymother's Crown", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Briarheart Body Scarification", q = 5 },
            { name = "Hircine's Chosen Body Marks", q = 5 },
            { name = "Ode to Clockwork Body Art", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Eyes of the Scamp", q = 4 },
            { name = "Briarheart Face Scarification", q = 5 },
            { name = "Hircine's Chosen Face Marks", q = 5 },
            { name = "Ode to Clockwork Face Art", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Topknot Cascade", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Mercymother's Coronet", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Balfieran Nose Studs", q = 4 },
        },
    },
}
