CollectThemAllData_Crates_2018_3_HollowjackCrate = {
    name = "Hollowjack Crate (2018)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Hollowjack Daedra-Skull Wolf", q = 1 },
            { name = "Hollowjack Flame-Skull Senche", q = 1 },
            { name = "Hollowjack Wraith-Lantern Steed", q = 1 },
            { name = "Hollowjack Rider Bear", q = 2 },
            { name = "Hollowjack Rider Camel", q = 2 },
            { name = "Hollowjack Rider Guar", q = 2 },
            { name = "Hollowjack Rider Horse", q = 2 },
            { name = "Hollowjack Rider Senche", q = 2 },
            { name = "Hollowjack Rider Wolf", q = 2 },
            { name = "Atmoran Snow Bear", q = 3 },
            { name = "Tattooed Shorn Camel", q = 3 },
            { name = "Zombie Horse", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Atmoran Snow Bear Cub", q = 3 },
            { name = "Daemon Cockerel", q = 3 },
            { name = "Lava Line Salamander", q = 3 },
            { name = "Crested Reef Viper", q = 4 },
            { name = "Goldenback Spider Lackey", q = 4 },
            { name = "Black Morthal Mastiff", q = 5 },
            { name = "Heartland Brindle Badger", q = 5 },
            { name = "Senchal Striped Cat", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Gourd-Gallows Stump", q = 3 },
            { name = "Ghost Lantern", q = 4 },
            { name = "Rind-Renewing Pumpkin", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Festival Beggar", q = 5 },
            { name = "Festive Treats", q = 5 },
            { name = "Jugglin' Pumpkins", q = 5 },
            { name = "Skull Ponder", q = 5 },
            { name = "Throw Rotten Egg", q = 5 },
            { name = "Tracker", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Abah's Watch", q = 3, motif = 32 },
            { name = "Apostle", q = 3, motif = 56 },
            { name = "Ebonshadow", q = 3, motif = 57 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {
            { name = "Zombie", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Decayed Zombie", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Ancestral Homage Formal Gown", q = 4 },
            { name = "Glenmoril Witch Robes", q = 4 },
            { name = "Imperial City Temple Tunic", q = 4 },
            { name = "Treasure Hunter", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Jhunal's Owl Mask", q = 5 },
            { name = "Rajhin's Cat Mask", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Hrokkibeg's Claw Body Marks", q = 4 },
            { name = "Hunting Grounds Body Tattoo", q = 4 },
            { name = "Uricanbeg the Stag Body Tattoo", q = 4 },
            { name = "Dragon Wings Body Markings", q = 5 },
            { name = "Twilight Wings Body Tattoo", q = 5 },
            { name = "Werewolf Claw Body Scars", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Hrokkibeg's Claw Face Marks", q = 4 },
            { name = "Hunting Grounds Face Tattoo", q = 4 },
            { name = "Uricanbeg the Stag Face Tattoo", q = 4 },
            { name = "Dragon Wings Face Markings", q = 5 },
            { name = "Twilight Wings Face Tattoo", q = 5 },
            { name = "Werewolf Claw Face Scars", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Great Stag Brow Antlers", q = 5 },
            { name = "Wolfsbane Ear Posy", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Sacred Antler Earring", q = 5 },
        },
    },
}
