CollectThemAllData_Crates_2019_1_DragonscaleCrate = {
    name = "Dragonscale Crate (2019)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Dragonscale Frost Senche", q = 1 },
            { name = "Dragonscale Solar Horse", q = 1 },
            { name = "Dragonscale Storm Wolf", q = 1 },
            { name = "Dragonscale Barded Bear", q = 2 },
            { name = "Dragonscale Barded Camel", q = 2 },
            { name = "Dragonscale Barded Guar", q = 2 },
            { name = "Dragonscale Barded Senche", q = 2 },
            { name = "Dragonscale Barded War-Horse", q = 2 },
            { name = "Dragonscale Barded Wolf", q = 2 },
            { name = "Karthwolf Charger", q = 3 },
            { name = "Sweetroll Grizzly", q = 3 },
            { name = "Tenmar Senche-Tiger", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Fledgling Vulture Gryphon", q = 3 },
            { name = "Lustrated Daedrat", q = 3 },
            { name = "Seht's Dovah-Fly", q = 3 },
            { name = "Atmoran Chub Loon", q = 4 },
            { name = "Karth Winter Pup", q = 4 },
            { name = "Winterhold Wolfhound", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Prismatic Banner Ribbon", q = 3 },
            { name = "Kick Ball", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Chatty Hand Puppet", q = 5 },
            { name = "Wall Pantomime", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Dwarven Remnant Battle Axe", q = 3 },
            { name = "Dwarven Remnant Bow", q = 3 },
            { name = "Dwarven Remnant Staff", q = 3 },
            { name = "Dwarven Remnant Sword", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Arctic Rime Skin", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Dwarven Centurion Body Tattoos", q = 4 },
            { name = "Ghost Goblin Body War Paint", q = 4 },
            { name = "Meridian Sunburst Body Tattoos", q = 4 },
            { name = "Alftand Glacial Body Tattoos", q = 5 },
            { name = "Dwarven Geometry Body Markings", q = 5 },
            { name = "Meridian Radiance Body Tattoos", q = 5 },
            { name = "Meridian War Burst Body Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Dwarven Centurion Face Tattoos", q = 4 },
            { name = "Ghost Goblin Face War Paint", q = 4 },
            { name = "Meridian Sunburst Face Tattoos", q = 4 },
            { name = "Alftand Glacial Face Tattoos", q = 5 },
            { name = "Dwarven Geometry Face Markings", q = 5 },
            { name = "Meridian Radiance Face Tattoos", q = 5 },
            { name = "Meridian War Burst Face Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {
            { name = "Bronze Color Eyeshadow", q = 5 },
            { name = "Feather Brows of Mystery", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "\"Chained Wrath\" Piercings", q = 5 },
            { name = "Coral Snake Nose Ring", q = 5 },
            { name = "Dwarven Sprocket Earrings", q = 5 },
        },
    },
}
