CollectThemAllData_Crates_2024_3_DarkBrotherhoodCrate = {
    name = "Dark Brotherhood Crate (2024)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Ardor's Devotion Senche-Raht", q = 1 },
            { name = "Bloodmoon Wolf", q = 1 },
            { name = "Hollowsoul Steed", q = 1 },
            { name = "Dark Brotherhood Crew Steed", q = 2 },
            { name = "Dark Brotherhood Durzog", q = 2 },
            { name = "Dark Brotherhood Kagouti", q = 2 },
            { name = "Dark Brotherhood Sabre Cat", q = 2 },
            { name = "Dragontail Mountain Bear", q = 3 },
            { name = "Oasis-Strider Nix-Ox", q = 3 },
            { name = "Snowclaw Senche-Serval", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Bloodmoon Wolf Pup", q = 4 },
            { name = "Moorpecker Magpie", q = 4 },
            { name = "Nightflame Larval Yaghra", q = 4 },
            { name = "Sepulchral Swamp Jelly", q = 4 },
            { name = "Doomcrag Salamander", q = 5 },
            { name = "Dragontail Mountain Bear Cub", q = 5 },
            { name = "Markarth Squirrel", q = 5 },
            { name = "Oliis Bay Fellrunner", q = 5 },
            { name = "Snowclaw Senche-Serval Kitten", q = 5 },
            { name = "West Weald Retriever", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Vaermina's Shadow", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Fetcherfly Frustration", q = 3 },
            { name = "Blademaster's Conundrum", q = 4 },
            { name = "Night Mother's Touch", q = 4 },
            { name = "Knife Savant", q = 4 },
            { name = "Blademaster's Taunt", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Whispers of Sithis Battle Axe", q = 3 },
            { name = "Whispers of Sithis Mace", q = 3 },
            { name = "Whispers of Sithis Shield", q = 3 },
            { name = "Whispers of Sithis Staff", q = 3 },
            { name = "Whispers of Sithis Sword", q = 3 },
            { name = "Dark Executioner Axe", q = 3 },
            { name = "Dark Executioner Bow", q = 3 },
            { name = "Dark Executioner Dagger", q = 3 },
            { name = "Dark Executioner Greatsword", q = 3 },
            { name = "Dark Executioner Maul", q = 3 },
            { name = "Hircine Bloodhunter", q = 3, motif = 129 },
            { name = "Sul-Xan", q = 3, motif = 102 },
            { name = "Dark Executioner Arm Cops", q = 5 },
            { name = "Dark Executioner Bracers", q = 5 },
            { name = "Dark Executioner Boots", q = 5 },
            { name = "Dark Executioner Guards", q = 5 },
            { name = "Dark Executioner Helmet", q = 5 },
            { name = "Dark Executioner Jack", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Recall of the Outer Darkness", q = 2 },
            { name = "Assassin's Chop", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Minotaur", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Woebringer", q = 2 },
            { name = "Black Sacrament Skincarving", q = 3 },
            { name = "Ardor's Devotion", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Claw Seer of Sithis", q = 3 },
            { name = "Dark Eliminator's Garb", q = 3 },
            { name = "Naryu's Assassin's Armor", q = 5 },
            { name = "Off-the-Shoulder Evening Dress", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Fashionably Deadly Hat", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Black Sacrament Mass Body Marks", q = 5 },
            { name = "Morag Tong Writ Count Body Art", q = 5 },
            { name = "Night Mother's Embrace Body Art", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Bloodmoon Eyes", q = 4 },
            { name = "Eyes of Sithis", q = 4 },
            { name = "Black Sacrament Mass Face Marks", q = 5 },
            { name = "Night Mother's Embrace Face Art", q = 5 },
            { name = "Morag Tong Writ Count Face Art", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Keen-Edged Shag", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Nightshade Hair Comb", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Heart's Rend Earrings", q = 4 },
        },
    },
}
