CollectThemAllData_Crates_2024_4_MirrormoorCrate = {
    name = "Mirrormoor Crate (2024)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Fargrave Walker Welwa", q = 1 },
            { name = "Glass Atronach Dwarven Spider", q = 1 },
            { name = "Mirrormoor Shard Senche", q = 1 },
            { name = "Lucent Guardian Horse", q = 2 },
            { name = "Lucent Guardian Ornaug", q = 2 },
            { name = "Lucent Guardian Senche-Raht", q = 2 },
            { name = "Lucent Guardian Wolf", q = 2 },
            { name = "Riverhold Chestnut Horse", q = 3 },
            { name = "Silver-Limned Guar Charger", q = 3 },
            { name = "Sword-Singer's Tufted Camel", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Mirrormoor Shard Wildcat", q = 4 },
            { name = "Mirrormoor Dragon Frog", q = 4 },
            { name = "Stainedwing Bat", q = 4 },
            { name = "Mirrorworm", q = 4 },
            { name = "Pearl White Sep Adder", q = 5 },
            { name = "Majestic Alpine Cat", q = 5 },
            { name = "Ashen Scar Fellrunner", q = 5 },
            { name = "Goldcrest Ancestor Lizard", q = 5 },
            { name = "Iliac Bay Hermit Crab", q = 5 },
            { name = "Tel Aruhn Guarling", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Sands of the Lucent Citadel", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Mirrormoor Glass Harp", q = 3 },
            { name = "Self Reflection", q = 4 },
            { name = "Regent's Wave", q = 4 },
            { name = "Mirrorball Trickery", q = 4 },
            { name = "Pop the Cork", q = 5 },
            { name = "Wash Your Damn Hands", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Ancient Mirrormoor Battle Axe", q = 3 },
            { name = "Ancient Mirrormoor Bow", q = 3 },
            { name = "Ancient Mirrormoor Mace", q = 3 },
            { name = "Ancient Mirrormoor Shield", q = 3 },
            { name = "Ancient Mirrormoor Staff", q = 3 },
            { name = "Fargrave Guardian", q = 3, motif = 108 },
            { name = "Waking Flame", q = 3, motif = 99 },
            { name = "Ancient Mirrormoor Breeches", q = 5 },
            { name = "Ancient Mirrormoor Epaulets", q = 5 },
            { name = "Ancient Mirrormoor Gloves", q = 5 },
            { name = "Ancient Mirrormoor Hat", q = 5 },
            { name = "Ancient Mirrormoor Jerkin", q = 5 },
            { name = "Ancient Mirrormoor Shoes", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Fate Strand Harvest", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Glass Atronach", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Mirrormoor Metamorphosis", q = 2 },
            { name = "Fargrave Walker", q = 3 },
            { name = "Warrior Starskin", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Fatemirror Evening Wear", q = 2 },
            { name = "Fargrave Relic Collector", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Mirrorglass Crescent Headdress", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Body Soul-Mark of the Sapiarchs", q = 5 },
            { name = "Rajaska's Snarl Body Tattoos", q = 5 },
            { name = "Mirrormoor Memory Body Marking", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Mirrormoor Eyes", q = 4 },
            { name = "Apocrypha Corrupted Eye", q = 4 },
            { name = "Face Soul-Mark of the Sapiarchs", q = 5 },
            { name = "Rajaska's Snarl Face Tattoos", q = 5 },
            { name = "Mirrormoor Memory Face Marking", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "High Elven Instigator", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Mirrormoor Masque", q = 4 },
            { name = "Dremora Deceiver's Diadem", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Lucent Earrings", q = 4 },
        },
    },
}
