CollectThemAllData_Crates_2021_3_GrimHarlequinCrate = {
    name = "Grim Harlequin Crate (2021)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Dark Delirium Senche", q = 1 },
            { name = "Infernal Trickster Death Hound", q = 1 },
            { name = "Ram of Dark Delights", q = 1 },
            { name = "Grinning Terror Bear", q = 2 },
            { name = "Grinning Terror Guar", q = 2 },
            { name = "Grinning Terror Senche", q = 2 },
            { name = "Grinning Terror Steed", q = 2 },
            { name = "Grinning Terror Wolf", q = 2 },
            { name = "Dunecoat Senche-Serval", q = 3 },
            { name = "Snow-Blanket Sorrel Horse", q = 3 },
            { name = "Sunback Bear", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Carmine Wood Moth", q = 4 },
            { name = "Lowland Bristleback", q = 4 },
            { name = "Sapphire Sep Adder", q = 4 },
            { name = "Vale Sabre Cat", q = 4 },
            { name = "Wamasu Hatchling", q = 4 },
            { name = "Ascadian Umber Sheep", q = 5 },
            { name = "Cropsford Hen", q = 5 },
            { name = "Greenhill Farmdog", q = 5 },
            { name = "Sunback Bear Cub", q = 5 },
            { name = "Topal Durzog", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Bone Colossus Illusion Gem", q = 3 },
            { name = "Daedroth Illusion Gem", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Chef Kiss", q = 5 },
            { name = "Fight Me", q = 5 },
            { name = "Pet Plant", q = 5 },
            { name = "Two Thumbs Up", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Maniacal Jester Bow", q = 3 },
            { name = "Maniacal Jester Dagger", q = 3 },
            { name = "Maniacal Jester Maul", q = 3 },
            { name = "Maniacal Jester Shield", q = 3 },
            { name = "Maniacal Jester Staff", q = 3 },
            { name = "Chitinous Arm Cops", q = 5 },
            { name = "Chitinous Belt", q = 5 },
            { name = "Chitinous Boots", q = 5 },
            { name = "Chitinous Bracers", q = 5 },
            { name = "Chitinous Guards", q = 5 },
            { name = "Chitinous Helmet", q = 5 },
            { name = "Chitinous Jack", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {
            { name = "Maniacal Jester", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Grace of the Green", q = 3 },
            { name = "Scourger's Scales", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Garb of Grinning Horrors", q = 2 },
            { name = "Gem Prospector", q = 4 },
            { name = "Hakoshae Festival Attire", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Dread-Etched Dragon Priest Mask", q = 4 },
            { name = "Moonshadow Wings Mask", q = 4 },
            { name = "Netch Handler Cap", q = 4 },
            { name = "Scorched Dragon Priest Mask", q = 4 },
            { name = "Terrorgleam Dragon Priest Mask", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Viridian Valor Body Markings", q = 4 },
            { name = "Thorns of Ecstasy Body Marks", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Conjurer's Eyes", q = 4 },
            { name = "Thorns of Ecstasy Face Marks", q = 5 },
            { name = "Viridian Valor Face Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "The Adoring Stand", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Gemcutter's Spectacles", q = 5 },
            { name = "Hakoshae Festival Laurel", q = 5 },
            { name = "Shimmerene Soiree Circlet", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
