CollectThemAllData_Crates_2019_2_BaandariPedlarCrate = {
    name = "Baandari Pedlar Crate (2019)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Anka-Ra Sandcamel", q = 1 },
            { name = "Anka-Ra Senche-Lion", q = 1 },
            { name = "Ebony Dwarven Spider", q = 1 },
            { name = "Baandari Dwarven Spider", q = 2 },
            { name = "Baandari Pedlar Camel", q = 2 },
            { name = "Baandari Pedlar Guar", q = 2 },
            { name = "Baandari Pedlar Senche-Lion", q = 2 },
            { name = "Baandari Pedlar Steed", q = 2 },
            { name = "Baandari Pedlar Brindle Wolf", q = 2 },
            { name = "Indigo Senche-Panther", q = 3 },
            { name = "Steed of the Afflicted", q = 3 },
            { name = "Tuxedo Bear", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Coral Mudcrab", q = 3 },
            { name = "Ja'khajiit Raz", q = 3 },
            { name = "Unholy Glow Bone Dragon", q = 3 },
            { name = "Cerulean Scorpion", q = 4 },
            { name = "Dusky Fennec Fox", q = 4 },
            { name = "Senche-Serval Kitten", q = 4 },
            { name = "Alinor Ringtail", q = 5 },
            { name = "Monarch Butterfly", q = 5 },
            { name = "Prong-Eared Odd-Eyed Cat", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Bright Moons", q = 4 },
            { name = "Gold Dragon Hand Projector", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Bright Moons Greeting", q = 5 },
            { name = "Desert Rain Kata", q = 5 },
            { name = "Goutfang Kata", q = 5 },
            { name = "Play Esraj", q = 5 },
            { name = "Whispering Claw Kata", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Baandari Pedlar Battle Axe", q = 3 },
            { name = "Baandari Pedlar Bow", q = 3 },
            { name = "Baandari Pedlar Staff", q = 3 },
            { name = "Baandari Pedlar Sword", q = 3 },
            { name = "Glass", q = 3, motif = 16 },
            { name = "Ra Gada", q = 3, motif = 28 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Factotum", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Peryite's Afflicted", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Song of the Night Ensemble", q = 3 },
            { name = "Queen's-Eye Spymaster", q = 3 },
            { name = "Cyrod Gentry's Town Gown", q = 4 },
            { name = "Kinlord's Alinor Attire", q = 4 },
            { name = "Moon-Sugar Festival Suit", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Blackmarrow Necro-Turban", q = 5 },
            { name = "Dibella's Doll Mask, Khajiiti", q = 5 },
            { name = "Nightmare Daemon Mask, Khajiiti", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Draco Aerius Body Markings", q = 5 },
            { name = "Dragonsmoke Body Markings", q = 5 },
            { name = "Plague Dragon Body Stains", q = 5 },
            { name = "Pride of Alkosh Body Marks", q = 5 },
            { name = "Tenmar Leopard Body Marks", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Draco Aerius Face Markings", q = 5 },
            { name = "Dragonsmoke Face Markings", q = 5 },
            { name = "Plague Dragon Face Stains", q = 5 },
            { name = "Pride of Alkosh Face Marks", q = 5 },
            { name = "Tenmar Leopard Face Marks", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Baandari Luck Circlet", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Baandari Cheek Chain", q = 4 },
            { name = "Baandari Luck Veil", q = 4 },
        },
    },
}
