CollectThemAllData_Crates_2022_2_DarkChivalryCrate = {
    name = "Dark Chivalry Crate (2022)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Luminous Meridian Charger", q = 1 },
            { name = "Wailing Shackler Wolf", q = 1 },
            { name = "Wealdspirit Bear", q = 1 },
            { name = "Soulrazer Bear", q = 2 },
            { name = "Soulrazer Guar", q = 2 },
            { name = "Soulrazer Senche", q = 2 },
            { name = "Soulrazer Steed", q = 2 },
            { name = "Soulrazer Wolf", q = 2 },
            { name = "Graniteclaw Durzog", q = 3 },
            { name = "Piebald Senche-Serval", q = 3 },
            { name = "Salamandrine Guar", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Hermit Crab", q = 4 },
            { name = "Heartland Butcher's Dog", q = 4 },
            { name = "Amberdust Wamasu Hatchling", q = 4 },
            { name = "Nightcrest Fellrunner", q = 5 },
            { name = "Screaming Midyear Nixad", q = 5 },
            { name = "Stoneglow Imp", q = 5 },
            { name = "Glimmergreen Dovah-Fly", q = 5 },
            { name = "Mossy Vvardvark", q = 5 },
            { name = "Ruby Fledgling Terror Bird", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Lover's Quandary Flower", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Souvenir Conch Shell", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Honor Guard", q = 3, motif = 68 },
            { name = "Silver Dawn", q = 3, motif = 66 },
            { name = "Soulrazer Battle Axe", q = 3 },
            { name = "Soulrazer Bow", q = 3 },
            { name = "Soulrazer Shield", q = 3 },
            { name = "Soulrazer Staff", q = 3 },
            { name = "Soulrazer Sword", q = 3 },
            { name = "Dawn's Avenger Helm", q = 4 },
            { name = "Dawn's Avenger Cuirass", q = 5 },
            { name = "Dawn's Avenger Gauntlets", q = 5 },
            { name = "Dawn's Avenger Girdle", q = 5 },
            { name = "Dawn's Avenger Greaves", q = 5 },
            { name = "Dawn's Avenger Pauldrons", q = 5 },
            { name = "Dawn's Avenger Sabatons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Soulrazer Knight", q = 2 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Ethertide", q = 3 },
            { name = "Reefdweller", q = 3 },
            { name = "Mossblood Imp Epidermis", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Za'ji's Sailing Apparel", q = 4 },
            { name = "Royal Courier", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Royal Courier Hood", q = 4 },
            { name = "Society Domino Mask", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Defensive Rune Body Tattoos", q = 5 },
            { name = "Knights of St. Pelin Body Marks", q = 5 },
            { name = "High Isle Mariner's Body Tattoos", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Defensive Rune Face Tattoos", q = 5 },
            { name = "Knights of St. Pelin Face Marks", q = 5 },
            { name = "High Isle Mariner's Face Tattoos", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Cutting Edge", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Scholar's Spectacles", q = 4 },
            { name = "Monarch Hairpin", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
