CollectThemAllData_Crates_2022_4_StoneloreCrate = {
    name = "Stonelore Crate (2022)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Glimmertarn Ursauk", q = 1 },
            { name = "Harvestleaf Lynx", q = 1 },
            { name = "Oldefire Elk", q = 1 },
            { name = "Stonelore Bear", q = 2 },
            { name = "Stonelore Elk", q = 2 },
            { name = "Stonelore Fox", q = 2 },
            { name = "Stonelore Guar", q = 2 },
            { name = "Stonelore Lynx", q = 2 },
            { name = "Scarlet War Pangrit", q = 3 },
            { name = "Rimmen Ringtailed Wolf", q = 3 },
            { name = "Ashgray Senche-Serval", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Moss Spine Daedrat", q = 4 },
            { name = "Autumnal Indrik", q = 4 },
            { name = "Sweetgrape Dragon Frog", q = 4 },
            { name = "Spotted Plow Spider", q = 4 },
            { name = "Orchid Whisper Moth", q = 4 },
            { name = "Spectral Mudcrab", q = 4 },
            { name = "Piebald Cat", q = 5 },
            { name = "Bergama Fennec Fox", q = 5 },
            { name = "Dockside Paper Wasp", q = 5 },
            { name = "Fledgling Terror Bird", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Blossom Bloom", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Pale Lord's Throne", q = 3 },
            { name = "Round of Applause", q = 5 },
            { name = "Teeba Warm-Up", q = 5 },
            { name = "Alik'r Shrieking Cheese", q = 5 },
            { name = "Spyglass", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Galenstone Bow", q = 3 },
            { name = "Galenstone Dagger", q = 3 },
            { name = "Galenstone Maul", q = 3 },
            { name = "Galenstone Shield", q = 3 },
            { name = "Galenstone Staff", q = 3 },
            { name = "Huntsman", q = 3, motif = 65 },
            { name = "Pyre Watch", q = 3, motif = 83 },
            { name = "Stonelore Arm Cops", q = 5 },
            { name = "Stonelore Boots", q = 5 },
            { name = "Stonelore Bracers", q = 5 },
            { name = "Stonelore Guards", q = 5 },
            { name = "Stonelore Helmet", q = 5 },
            { name = "Stonelore Jack", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Gyrfalcon Gather", q = 3 },
            { name = "Recall of the Galen Wilds", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Glimmertarn Glow", q = 2 },
            { name = "Bargain-Marked Skaafin", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Vengeance Day Dress", q = 5 },
            { name = "Ancestral Honor Garments", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Firesong Body Art", q = 4 },
            { name = "Dreadsail Body Tattoo", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Eyes of Sanguine", q = 4 },
            { name = "Eyes of the Xivilai", q = 4 },
            { name = "Dreadsail Face Tattoo", q = 5 },
            { name = "Firesong Face Art", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Galenwood Mask", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Amberleaf Earring", q = 4 },
        },
    },
}
