CollectThemAllData_Crates_2017_1_StormAtronachCrate = {
    name = "Storm Atronach Crate (2017)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Storm Atronach Bear", q = 2 },
            { name = "Storm Atronach Camel", q = 2 },
            { name = "Storm Atronach Guar", q = 2 },
            { name = "Storm Atronach Horse", q = 2 },
            { name = "Storm Atronach Senche", q = 2 },
            { name = "Storm Atronach Wolf", q = 2 },
            { name = "Black Mane Lion", q = 3 },
            { name = "Clouded Senche-Leopard", q = 3 },
            { name = "Frost Mare", q = 3 },
            { name = "Mind-Shriven Horse", q = 3 },
            { name = "Red Pit Wolf", q = 3 },
            { name = "Golden Eye Guar", q = 4 },
            { name = "Palomino Horse", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Black Mask Bear-Dog", q = 3 },
            { name = "Clouded Senche-Leopard Cub", q = 3 },
            { name = "Orchid Nixad", q = 3 },
            { name = "Red Pit Wolf Pup", q = 3 },
            { name = "Rosy Netch Calf", q = 3 },
            { name = "Tangerine Dragon Frog", q = 3 },
            { name = "Chub Loon", q = 4 },
            { name = "Purple Daggerback", q = 4 },
            { name = "Daedric Scamp", q = 5 },
            { name = "Helstrom Ancestor Lizard", q = 5 },
            { name = "Shornhelm Shepherd", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Storm Atronach Transform", q = 3 },
            { name = "Storm Orb Juggle", q = 4 },
            { name = "Storm Atronach Aura", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Mind-Shriven", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Brilliance Brocade Robes", q = 4 },
            { name = "High-Collared Coin Ball Gown", q = 4 },
            { name = "Battlemage Palatine Armor", q = 5 },
            { name = "Battlemage Scout Captain Uniform", q = 5 },
            { name = "Battlemage Tribune Armor", q = 5 },
            { name = "Evening Dress", q = 5 },
            { name = "Soul-Shriven Armor Outfit", q = 5 },
            { name = "Soul-Shriven Leather Outfit", q = 5 },
            { name = "Soul-Shriven Ragged Clothing", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Dwarf-Style Mage's Hat", q = 3 },
            { name = "Imperial Mananaut Cap & Goggles", q = 3 },
            { name = "Hedge Wizard's Claw Cap", q = 4 },
            { name = "Upright Antler Skullcap", q = 4 },
            { name = "\"Clever Man\" Wizard Hat", q = 5 },
            { name = "Feathered Bycoket Cap", q = 5 },
            { name = "Fibonaccus Spiral Hat", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Aurbical Symbols", q = 4 },
            { name = "Enveloping Scales", q = 4 },
            { name = "Shadow Striping", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Shadow Stripe Headwrap", q = 4 },
            { name = "The Aurbic Eye", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Feathered Headdress", q = 4 },
            { name = "Roostertail Frills", q = 5 },
            { name = "Wrestler's Buzz Cut", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Azure Brow-to-Temple Circlet", q = 5 },
            { name = "Jawbone Blades", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Belly Dancer Veil", q = 4 },
        },
    },
}
