CollectThemAllData_Crates_2023_4_AllMakerCrate = {
    name = "All-Maker Crate (2023)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Blessed Highmane Lion", q = 1 },
            { name = "Solstheim Shiver Wolf", q = 1 },
            { name = "Star-Orphan Elk", q = 1 },
            { name = "All-Maker's Bear", q = 2 },
            { name = "All-Maker's Dwarven Spider", q = 2 },
            { name = "All-Maker's Horse", q = 2 },
            { name = "All-Maker's Senche-Raht", q = 2 },
            { name = "All-Maker's Wolf", q = 2 },
            { name = "Quintessential Camel", q = 3 },
            { name = "Speckled Wolf", q = 3 },
            { name = "Urshilaku Nix-Ox", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Deepsnow Prairie Dog", q = 4 },
            { name = "Hearthhome Moth", q = 4 },
            { name = "Solstheim Shiver Wolf", q = 4 },
            { name = "Star-Orphan Fawn", q = 4 },
            { name = "Fellbraun Chub Loon", q = 5 },
            { name = "Gideon Trail Dog", q = 5 },
            { name = "Ginger Pocket Mammoth", q = 5 },
            { name = "Prodigious Crimson Mudcrab", q = 5 },
            { name = "Shezarr's Chicken", q = 5 },
            { name = "Silent Moons Sheep", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Cursed Reach Doll", q = 3 },
            { name = "Enchanted Saturalia Tree", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Boneshaped Handpan", q = 3 },
            { name = "Galenwood Leafshade", q = 4 },
            { name = "Jester's Jig", q = 4 },
            { name = "Skaal Maul Dance", q = 4 },
            { name = "Knightly Bow", q = 5 },
            { name = "Pantomime Tug-of-War", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Blackreach Vanguard", q = 3, motif = 84 },
            { name = "Annihilarch's Chosen", q = 3, motif = 107 },
            { name = "Iceshard Battle Axe", q = 3 },
            { name = "Iceshard Bow", q = 3 },
            { name = "Iceshard Shield", q = 3 },
            { name = "Iceshard Staff", q = 3 },
            { name = "Iceshard Mace", q = 3 },
            { name = "All-Maker Cuirass", q = 5 },
            { name = "All-Maker Gauntlets", q = 5 },
            { name = "All-Maker Greaves", q = 5 },
            { name = "All-Maker Helm", q = 5 },
            { name = "All-Maker Pauldrons", q = 5 },
            { name = "All-Maker Sabatons", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Frostfall Recall", q = 2 },
            { name = "Icefist Runegathering", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Solstheimstone Incarnate", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Orphan of the Stars", q = 2 },
            { name = "Thief Starskin", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Windcaller Garb", q = 2 },
            { name = "Dremora Deceiver Duster", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Incognito Adventurer's Hood", q = 4 },
            { name = "Sun's Dusk Winter Hood", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "All-Maker's Body Art", q = 5 },
            { name = "Highmane's Hero Body Marks", q = 5 },
            { name = "Windcaller Body Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Eyes of the Prophet", q = 4 },
            { name = "Eyes of S'rendarr", q = 4 },
            { name = "All-Maker's Face Art", q = 5 },
            { name = "Highmane's Hero Face Marks", q = 5 },
            { name = "Windcaller Face Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Azure Ombre", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Alinor Eye Crest", q = 4 },
            { name = "Knower's Eye Hairpin", q = 4 },
            { name = "Skaal's Brow Band", q = 4 },
            { name = "Windcaller's Circlet", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Solstheim Earrings", q = 4 },
        },
    },
}
