CollectThemAllData_Crates_2017_3_DwarvenCrate = {
    name = "Dwarven Crate (2017)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Adamant Dwarven Horse", q = 1 },
            { name = "Ebon Dwarven Senche", q = 1 },
            { name = "Vitrine Dwarven Wolf", q = 1 },
            { name = "Dwarven Bear", q = 2 },
            { name = "Dwarven Camel", q = 2 },
            { name = "Dwarven Guar", q = 2 },
            { name = "Dwarven Horse", q = 2 },
            { name = "Dwarven Senche", q = 2 },
            { name = "Dwarven Wolf", q = 2 },
            { name = "Dro-m'Athra Senche", q = 3 },
            { name = "Gorne Striped Wolf", q = 3 },
            { name = "Pale Velothi Guar", q = 3 },
            { name = "Green Narsis Guar", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Clockwork Shalk", q = 3 },
            { name = "Copperback Bear-Dog", q = 3 },
            { name = "Dro-m'Athra Senche Cub", q = 3 },
            { name = "Mossy Netch Calf", q = 3 },
            { name = "Blue-Cap Shroom Shalk", q = 4 },
            { name = "Deep-Moss Ash Hopper", q = 4 },
            { name = "Fennec Fox", q = 4 },
            { name = "Molag Amur Cliff Strider", q = 4 },
            { name = "Ninendava Sacred Goat", q = 4 },
            { name = "Tuxedo Vvardvark", q = 4 },
            { name = "Bal Foyen Nix-Hound", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Dwemervamidium Mirage", q = 3 },
            { name = "Dwarven Tonal Forks", q = 4 },
            { name = "Dwarven Puzzle Orb", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Draugr", q = 3, motif = 38 },
            { name = "Minotaur", q = 3, motif = 39 },
            { name = "Order of the Hour", q = 3, motif = 40 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Breton Hero Armor", q = 3 },
            { name = "Elven Hero Armor", q = 3 },
            { name = "Nord Hero Armor", q = 3 },
            { name = "Ashlander Kagesh Tribe Armor", q = 5 },
            { name = "Ashlander Mabrigash Hunt Clothes", q = 5 },
            { name = "Ashlander Mabrigash Travel Wear", q = 5 },
            { name = "Classic Ordinator Armor", q = 5 },
            { name = "Hand of Almalexia Uniform", q = 5 },
            { name = "Nedic Duraki Armor", q = 5 },
            { name = "Nedic Keptu Armor", q = 5 },
            { name = "Nedic Perena Armor", q = 5 },
            { name = "Ordinator Night-Raid Armor", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Blossom Burst Bonnet", q = 3 },
            { name = "Dwarven Master Miter", q = 3 },
            { name = "Dwarven Spiked Miter", q = 3 },
            { name = "Dwemeri Tonal Attenuator", q = 3 },
            { name = "Blooming Bouquet Hat", q = 4 },
            { name = "Dwarven Crested Hood", q = 4 },
            { name = "Dwarven Visor Miter", q = 4 },
            { name = "Crimson Garden Flower Hat", q = 5 },
            { name = "Sadrith Mora Quilted Snood", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Magenta Rainbow Hair", q = 4 },
            { name = "White River Braids", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {
            { name = "Anvil Sunset Eyeshadow", q = 4 },
            { name = "Tangerine Spike Eyeshadow", q = 4 },
            { name = "White-Gold Eyeshadow", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Nchuleft Tonal Visor", q = 3 },
            { name = "Deep Elf Goggle-Horn", q = 4 },
            { name = "Dwarf-Style Sun Goggles", q = 4 },
            { name = "Dwarf-Style Brow Shields", q = 5 },
            { name = "Dwemeri Monocular Contrivance", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
