CollectThemAllData_Crates_2020_3_SovngardeCrate = {
    name = "Sovngarde Crate (2020)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Auric Sabre Cat Duskstalker", q = 1 },
            { name = "Lambent Shadowmane Courser", q = 1 },
            { name = "Silver Nimbus Wolf", q = 1 },
            { name = "Sovngarde Stoutheart Bear", q = 2 },
            { name = "Resplendent Sovngarde Camel", q = 2 },
            { name = "Valorous Sovngarde Guar Strider", q = 2 },
            { name = "Valiant Sovngarde Charger", q = 2 },
            { name = "Sovngarde Valorfang Sabre Cat", q = 2 },
            { name = "Sovngarde Clawthane Wolf", q = 2 },
            { name = "Glenumbra Border Wolf", q = 3 },
            { name = "Khefrem Senche-Serval", q = 3 },
            { name = "Zeht's Cloud Camel", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Cantaloupe Swamp Jelly", q = 4 },
            { name = "Firepoint Fledgling Gryphon", q = 4 },
            { name = "Frostshriek Imp", q = 4 },
            { name = "Graywinter Sabre Cat Cub", q = 4 },
            { name = "Teal-Faced Fellrunner", q = 5 },
            { name = "Breton Terrier", q = 5 },
            { name = "Coldsnap Durzog Pup", q = 5 },
            { name = "Merle Paddock Hound", q = 5 },
            { name = "Springlight Moth", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Nascent Netherroot Brew", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Fire Spinning", q = 3 },
            { name = "Scarecrow Pose", q = 4 },
            { name = "Hiss", q = 5 },
            { name = "Memorial Toast", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Valorous Sovngarde Greatsword", q = 3 },
            { name = "Valorous Sovngarde Axe", q = 3 },
            { name = "Valorous Sovngarde Bow", q = 3 },
            { name = "Valorous Sovngarde Shield", q = 3 },
            { name = "Valorous Sovngarde Staff", q = 3 },
            { name = "Eccentric Experimenter Jack", q = 5 },
            { name = "Eccentric Experimenter Boots", q = 5 },
            { name = "Eccentric Experimenter Gloves", q = 5 },
            { name = "Eccentric Experimenter Hat", q = 5 },
            { name = "Eccentric Experimenter Breeches", q = 5 },
            { name = "Eccentric Experimenter Arm Cops", q = 5 },
            { name = "Eccentric Experimenter Belt", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Draugr", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Xoleel Scale", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Ancient Sites Explorer", q = 3 },
            { name = "Renegade Dragon Priest", q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Mask of Bloody Passions", q = 4 },
            { name = "Mask of Entangled Paths", q = 4 },
            { name = "Pentarch Vassal's Oathmask", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Morthal Champion Body Markings", q = 5 },
            { name = "Path of Valor Body Markings", q = 5 },
            { name = "Whiterun Windracer Body Markings", q = 5 },
            { name = "Wolf of Solitude Body Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Morthal Champion Face Markings", q = 5 },
            { name = "Path of Valor Face Markings", q = 5 },
            { name = "Whiterun Windracer Face Markings", q = 5 },
            { name = "Wolf of Solitude Face Markings", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Misanthropic Lycanthrope", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Carmine Monocle", q = 4 },
            { name = "Dark Passions Circlet", q = 4 },
            { name = "Keizaal Coronet", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Greymoor Ruby Earrings", q = 4 },
        },
    },
}
