CollectThemAllData_Crates_2017_2_WildHuntCrate = {
    name = "Wild Hunt Crate (2017)",
    source = "Crates",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Wild Hunt Bear", q = 2 },
            { name = "Wild Hunt Camel", q = 2 },
            { name = "Wild Hunt Guar", q = 2 },
            { name = "Wild Hunt Horse", q = 2 },
            { name = "Wild Hunt Senche", q = 2 },
            { name = "Wild Hunt Wolf", q = 2 },
            { name = "Black Senche-Panther", q = 3 },
            { name = "Doom Wolf", q = 3 },
            { name = "Banded Guar Charger", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Black Senche-Panther Kitten", q = 3 },
            { name = "Blue Oasis Dragon Frog", q = 3 },
            { name = "Cobalt Sep Adder", q = 3 },
            { name = "Dark Moons Lynx", q = 3 },
            { name = "Doom Wolf Pup", q = 3 },
            { name = "Ancestor Moth Swarm", q = 4 },
            { name = "Baby Netch", q = 4 },
            { name = "Sanguine's Black Goat", q = 4 },
            { name = "Banekin", q = 5 },
            { name = "Bravil Retriever", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Wild Hunt Transform", q = 3 },
            { name = "Floral Swirl Aura", q = 4 },
            { name = "Wild Hunt Leaf-Dance Aura", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Moth Priest", q = 4 },
            { name = "Priest of the Green", q = 4 },
            { name = "Toxin Doctor", q = 4 },
            { name = "Black Marsh Keeper", q = 5 },
            { name = "East Skyrim Scout Outfit", q = 5 },
            { name = "Orcish Scout Armor", q = 5 },
            { name = "Tree-Minder", q = 5 },
            { name = "Valenwood Spinner", q = 5 },
            { name = "West Skyrim Scout Outfit", q = 5 },
            { name = "Winterborn Hunter's Costume", q = 5 },
            { name = "Winterborn Shaman's Costume", q = 5 },
            { name = "Winterborn Warrior's Costume", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "12-Point Antler Skullcap", q = 3 },
            { name = "14-Point Antler Skullcap", q = 3 },
            { name = "Wild Hunt Antler Skullcap", q = 3 },
            { name = "Forester's Hood with Flower", q = 4 },
            { name = "Rootbrim Hat with Flower", q = 4 },
            { name = "Flannel Forester's Hood", q = 5 },
            { name = "Wild Hunt Rootbrim Hat", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Uricanbeg Antler Tattoos", q = 4 },
            { name = "Wild Vines' Embrace Tattoos", q = 4 },
            { name = "Wyrd Root Tattoos", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Uricanbeg Antlers Face Tattoo", q = 5 },
            { name = "Wild Vines Face Tattoo", q = 5 },
            { name = "Wyrd Root Face Tattoo", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Feathered Kelp-Scalp", q = 5 },
            { name = "Mane-of-Many-Rivers", q = 5 },
            { name = "Rotmeth Hangover Bed-Head", q = 5 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {
            { name = "Amethyst Eyelashes", q = 4 },
            { name = "Azure Feather Eyelashes", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Eight-Fang Nose Chain", q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
