CollectThemAllData_Game_MonsterArmors = {
    name = "Monster Armors",
    source = "Game",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_DLC] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Euphotic Gatekeeper", armorOnly = true },
            { name = "Kjalnar's Nightmare", armorOnly = true },
            { name = "Encratis's Behemoth", armorOnly = true },
            { name = "Nazaray", armorOnly = true },
            { name = "Lady Thorn", armorOnly = true },
            { name = "Prior Thierric", armorOnly = true },
            { name = "Baron Zaudrus", armorOnly = true },
            { name = "Mother Ciannait", armorOnly = true },
            { name = "Grundwulf", armorOnly = true },
            { name = "Maarselok", armorOnly = true },
            { name = "Thurvokun", armorOnly = true },
            { name = "Selene", armorOnly = true },
            { name = "Vykosa", armorOnly = true },
            { name = "Zaan", armorOnly = true },
            { name = "Stonekeeper", armorOnly = true },
            { name = "Symphony of Blades", armorOnly = true },
            { name = "Infernal Guardian", armorOnly = true },
            { name = "Sentinel of Rkugamz", armorOnly = true },
            { name = "Kra'gh", armorOnly = true },
            { name = "Tremorscale", armorOnly = true },
            { name = "Maw of the Infernal", armorOnly = true },
            { name = "Maw of the Infernal's", armorOnly = true },
            { name = "Earthgore", armorOnly = true },
            { name = "Nerien'eth", armorOnly = true },
            { name = "Domihaus", armorOnly = true },
            { name = "Scourge Harvester", armorOnly = true },
            { name = "Balorgh", armorOnly = true },
            { name = "Stormfist", armorOnly = true },
            { name = "Slimecraw", armorOnly = true },
            { name = "Valkyn Skoria", armorOnly = true },
            { name = "Iceheart", armorOnly = true },
            { name = "Pirate Skeleton", armorOnly = true },
            { name = "Chokethorn", armorOnly = true },
            { name = "Velidreth", armorOnly = true },
            { name = "Mighty Chudan", armorOnly = true },
            { name = "Lord Warden", armorOnly = true },
            { name = "Nightflame", armorOnly = true },
            { name = "Engine Guardian", armorOnly = true },
            { name = "Sellistrix", armorOnly = true },
            { name = "Sellistrix's", armorOnly = true },
            { name = "Swarm Mother", armorOnly = true },
            { name = "Bloodspawn", armorOnly = true },
            { name = "Troll King", armorOnly = true },
            { name = "Grothdarr", armorOnly = true },
            { name = "Shadowrend", armorOnly = true },
            { name = "Molag Kena", armorOnly = true },
            { name = "Molag Kena's", armorOnly = true },
            { name = "Ilambris", armorOnly = true },
            { name = "Ilambris'", armorOnly = true },
            { name = "Anthelmir's Construct", armorOnly = true },
            { name = "Archdruid Devyric", armorOnly = true },
            { name = "Bar-Sakka", armorOnly = true },
            { name = "Black Gem Monstrosity", armorOnly = true },
            { name = "Kargaeda", armorOnly = true },
            { name = "Magma Incarnate", armorOnly = true },
            { name = "Orpheon the Tactician", armorOnly = true },
            { name = "Ozezan the Inferno", armorOnly = true },
            { name = "Roksa the Warped", armorOnly = true },
            { name = "Spawn of Mephala", armorOnly = true },
            { name = "Squall of Retribution", armorOnly = true },
            { name = "The Blind", armorOnly = true },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
