CollectThemAllData_Game_GameRewards = {
    name = "Game Rewards",
    source = "Game",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_ACCOUNT_UPGRADE] = {
            { name = "Bastian's Julianos Medallion" },
            { name = "Ancient Anticipations Idol" },
            { name = "Luxury Thieves Tools" },
            { name = "Stendarr's Sweets Vault" },
            { name = "Abyssal Tea Set" },
            { name = "Sharp's Handmade Fishing Lure" },
            { name = "Garland Ring Humming Pick" },
            { name = "Ja'kh's Bell of Bounty" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {
            { name = "Rogue's Refuge", no = 128, achievement = "Get Away from It All", info = "Obtained by collecting four notes while performing acts related to thievery." }, -- not for gold
            { name = "Hall of the Lunar Champion", no = 70, info = "Two Queens quest" }, -- not for gold

            { name = "The Sleepy Sloth", no = 118, info = "Room to Spare quest or 3,000 gold" },
            { name = "Rosewine Retreat", no = 109, info = "Room to Spare quest or 3,000 gold" },
            { name = "Journey's End Lodgings", no = 100, info = "Room to Spare quest or 3,000 gold" },
            { name = "Ancient Anchor Berth", no = 95, info = "Room to Spare quest or 3,000 gold" },
            { name = "Pilgrim's Rest", no = 87, info = "Room to Spare quest or 3,000 gold" },
            { name = "Snowmelt Suite", no = 77, info = "Room to Spare quest or 3,000 gold" },
            { name = "Sugar Bowl Suite", no = 68, info = "Room to Spare quest or 3,000 gold" },
            { name = "Golden Gryphon Garret", no = 58, info = "Room to Spare quest or 3,000 gold" },
            { name = "Saint Delyn Penthouse", no = 42, info = "Room to Spare quest or 3,000 gold" },
            { name = "The Ebony Flask Inn Room", no = 3, info = "Room to Spare quest or 3,000 gold" },
            { name = "The Rosy Lion", no = 2, info = "Room to Spare quest or 3,000 gold" },
            { name = "Mara's Kiss Public House", no = 1, info = "Room to Spare quest or 3,000 gold" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {
            -- Companions as Houseguests
            { name = "Bastian Hallix" },
            { name = "Mirri Elendis" },
            { name = "Ember" },
            { name = "Isobel Veloise" },
            { name = "Azandar" },
            { name = "Sharp-as-Night" },
            { name = "Tanlorin" },
            { name = "Zerith-var" },

            -- Other Houseguests
            { name = "Brahgas" },
            { name = "Captain Kaleen" },
            { name = "Alchemy" },

            -- Quest and Achievement rewards
            { name = "Aeonstone Formation" },
            { name = "Augur of the Obscure" },
            { name = "Behold Khunzar-ri's Ambition" },
            { name = "Behold Khunzar-ri's Betrayal" },
            { name = "Behold Khunzar-ri's Guile" },
            { name = "Behold the Lunar Champion" },
            { name = "Fan of False-Face" },
            { name = "How to Scribe" },
            { name = "Khajiit of the Moons Replica" },
            { name = "Khunzar-ri's Rest" },
            { name = "Lady Garick's Sacred Shield" },
            { name = "Replica of the Xinchei-Konu" },
            { name = "Replica Rithana-Di-Renada" },
            { name = "Replica Zenithar Adytum Gate" },
            { name = "Revolving Celestiodrome" },
            { name = "Vvardenfell Scale Model" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {
            { name = "Pirharri the Smuggler" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {
            { name = "Bastian Hallix" },
            { name = "Mirri Elendis" },
            { name = "Ember" },
            { name = "Isobel Veloise" },
            { name = "Azandar al-Cybiades" },
            { name = "Sharp-as-Night" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Berylglow Nix-Ox Steed" },
            { name = "Dragonclaw Imperial Warbear" },
            { name = "Heart's Grief Welwa" },
            { name = "Maligraphic Mount" },
            { name = "Ram of Dark Dreams" },
            { name = "Refulgent Mirrormoor Steed" },
            { name = "Sorrel Horse" },
            { name = "Stormsurge Howler" },
            { name = "Sul-Xan Fleshripper" },
            { name = "Sunspire Champion Senche-Lion" },
            { name = "Wildburn Lynx" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Abecean Ratter Cat" },
            { name = "Alik'r Dune-Hound" },
            { name = "Big-Eared Ginger Kitten" },
            { name = "Bog Dog" },
            { name = "Coral Haj Mota" },
            { name = "Crystaljack" },
            { name = "Dremnaken Runt" },
            { name = "Dwarven Theodolite" },
            { name = "Echalette" },
            { name = "Elinhir Arena Lion" },
            { name = "Eminent Slothcerer" },
            { name = "Energetic Dwarven Shock-Spider" },
            { name = "Graht-Oak Squirrel" },
            { name = "Grisly Mummy Tabby", achievement = "Alfiq Mummy Master" },
            { name = "Icebound Dwarven Spider" },
            { name = "Jackal" },
            { name = "Jackdaw Daedrat" },
            { name = "Jerall Rescue Dog" },
            { name = "Maligraphic Skeever" },
            { name = "Mind-Shriven Mudcrab" },
            { name = "Mirrormoor Mudcrab" },
            { name = "Mulberry Hermit Crab" },
            { name = "Necrotic Hoarvor" },
            { name = "Obsidian Dwarven Sphere" },
            { name = "Phoenix Moth" },
            { name = "Razak's Opus" },
            { name = "Regal Dragon Imp" },
            { name = "Scintillant Dovah-Fly" },
            { name = "Scorion Pyreling" },
            { name = "Solitude Silver Wolf" },
            { name = "Solstice Sloth" },
            { name = "Somnolent Void Rot" },
            { name = "Swamp Jelly" },
            { name = "Undaunted Porter Scamp" },
            { name = "Verdigris Haj Mota" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Antiquarian's Eye", id = 8006 },
            { name = "Cartoklept Map" },
            { name = "Fire Rock" },
            { name = "Relic of the Sentinel" },
            { name = "Agonymium Stone" },
            { name = "Almalexia's Enchanted Lantern" },
            { name = "Antiquarian's Telescope" },
            { name = "Battered Bear Trap" },
            { name = "Blackfeather Court Whistle" },
            { name = "Blade of the Blood Oath" },
            { name = "Bonesnap Binding Stone" },
            { name = "Box of Forbidden Relics" },
            { name = "Brittle Burial Urn" },
            { name = "Butcher Haefal's Accursed Knife" },
            { name = "Chains of the Ice Witch" },
            { name = "Clockwork Obscuros" },
            { name = "Coin of Illusory Riches" },
            { name = "Corruption of Maarselok" },
            { name = "Crimson Bone Hammer" },
            { name = "Daedric Unwarding Amulet" },
            { name = "Dhulef's Bubble Ward" },
            { name = "Discourse Amaranthine" },
            { name = "Dragon Flight Illusion Gem" },
            { name = "Dragonhorn Curio" },
            { name = "Draoife Old Growth Sigils Basin" },
            { name = "Dream Amulet of Argon" },
            { name = "Dreamer's Chime" },
            { name = "Dust of the Conqueror's Flame" },
            { name = "Echo of the Abolisher" },
            { name = "Echonir Examination" },
            { name = "Echonir Fragment" },
            { name = "Exalted Bread" },
            { name = "Fetish of Anger" },
            { name = "Finvir's Trinket" },
            { name = "Full-Scale Golden Anvil Replica" },
            { name = "Ghastly Glowstalk" },
            { name = "Ghost Haven Caravel" },
            { name = "Glanir's Smoke Bomb" },
            { name = "Gryphon Feather Talisman" },
            { name = "Guardian's Frozen Shard" },
            { name = "Haunted Mirror of Introspection" },
            { name = "Hidden Pressure Vent" },
            { name = "Illusory Salamander Stone" },
            { name = "Incarnate Illusion Gem" },
            { name = "Iterative Onyx Glyphic" },
            { name = "Justal's Falcon" },
            { name = "Kyne's Tablet of Storms" },
            { name = "Lena's Wand of Finding" },
            { name = "Lodorr's Crown" },
            { name = "Malacath Helm Haunt" },
            { name = "Malacath's Wrathful Flame" },
            { name = "Malkhest's Accursed Mirror" },
            { name = "Maormer Ocean Pearl" },
            { name = "Meln's Soul Gem" },
            { name = "Mezha-dro's Sealing Amulet" },
            { name = "Miniature Dwarven Sun" },
            { name = "Mostly Stable Juggling Potions" },
            { name = "Murkmire Grave-Stake" },
            { name = "Nanwen's Sword" },
            { name = "Neramo's Lightning Stick" },
            { name = "Nirnroot Wine" },
            { name = "Prism of Moribund Sapience" },
            { name = "Questionable Meat Sack" },
            { name = "Red Revelry Bottle" },
            { name = "Reliquary of Dark Designs" },
            { name = "Replica Tonal Inverter" },
            { name = "Ritual Circle Totem" },
            { name = "Sanguine's Goblet" },
            { name = "Sea Sload Dorsal Fin" },
            { name = "Seed-Heavy Hist Bulb" },
            { name = "Slippery Soul Gem" },
            { name = "Summoned Booknado" },
            { name = "Token of Root Sunder" },
            { name = "Twilight Shard" },
            { name = "Umbral Projector" },
            { name = "Unstable Emerald Glyphic" },
            { name = "Void Shard" },
            { name = "Wall of Life Brush" },
            { name = "Werewolf Behemoth Sigil" },
            { name = "Wilting Weed Killer Phial" },
            { name = "Winnowing Plague Decoction" },
            { name = "Wyrd Elemental Plume" },
            { name = "Yokudan Totem" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Alliance Banner" },
            { name = "Begone!" },
            { name = "Bull Horns" },
            { name = "Card Conjuring" },
            { name = "Cardsharp" },
            { name = "Gladiator Taunt" },
            { name = "Glimmer Dust" },
            { name = "Guar Stomp" },
            { name = "Lost in the Woods" },
            { name = "Petal Presentation" },
            { name = "Psijic Glowglobe" },
            { name = "Rage of the Reach" },
            { name = "Sailor's Sextant" },
            { name = "Sapphire Heraldry Horn 1" },
            { name = "Sapphire Heraldry Horn 2" },
            { name = "Sapphire Heraldry Horn 3" },
            { name = "Siegestomper" },
            { name = "True-Sight Viewing" },
            { name = "Wargame Trebuchet" },
            { name = "Wickerman Mishap" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Knight of the Circle" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {
            { name = "Accelerate, Lilac Purple" },
            { name = "Annulment, Vibrant Yellow" },
            { name = "Barrier, Turquoise Blue" },
            { name = "Blessing of Protection, Sky Blue" },
            { name = "Cleave, Cinnabar Red" },
            { name = "Dawnbreaker, Dusk Purple" },
            { name = "Entropy, Vibrant Yellow" },
            { name = "Entropy, Violet Purple" },
            { name = "Eviscerate, Violet Purple" },
            { name = "Expert Hunter, Carmine Red" },
            { name = "Fire Rune, Dazzling White" },
            { name = "Force Shock, Onyx Black" },
            { name = "Force Shock, Wildburn" },
            { name = "Grand Healing, Lilac Purple" },
            { name = "Grand Healing, Seawater" },
            { name = "Low Slash, Burnt Orange" },
            { name = "Magelight, Viridian Green" },
            { name = "Meteor, Blazing Orange" },
            { name = "Mist Form, Lilac Purple" },
            { name = "Poison Arrow, Crimson Red" },
            { name = "Puncture, Lavaburst" },
            { name = "Regeneration, Azure Blue" },
            { name = "Reverse Slash, Ruby Red" },
            { name = "Roar, Verdant Green" },
            { name = "Silver Bolts, Vibrant Yellow" },
            { name = "Snipe, Scarlet Red" },
            { name = "Soul Trap, Carmine Red" },
            { name = "Soul Trap, Orchid Purple" },
            { name = "Soul Trap, Wormwrithe" },
            { name = "Trap Beast, Dawnlight Orange" },
            { name = "Undo, Lilac Purple" },
            { name = "Vigor, Soothing Blue" },
            { name = "Wall of Elements, Verdant Green" },
            { name = "Wall of Elements, Violet Purple" },
            { name = "War Horn, Amber Orange" },
            { name = "Weakness to Elements, Orange" },
            { name = "Weakness to Elements, Purple" },
            { name = "Whirlwind, Ochre Orange" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {
            { name = "Cadaverous Assassin" },
            { name = "Clockwork Curator" },
            { name = "Maelstrom Baron" },
            { name = "Skeleton" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {
            { name = "Assassin" },
            { name = "Beast", achievement = "March of Sacrifices Challenger" },
            { name = "Heroic" },
            { name = "Telvanni Magister" },
            { name = "Worm Wizard", achievement = "Fang Lair Challenger" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Amber Plasm" },
            { name = "Blackmarrow Necromancer" },
            { name = "Bloodmarks of Malacath" },
            { name = "Dagon's Viscerent" },
            { name = "Dreadhorn Shaman" },
            { name = "Dro-m'Athra" },
            { name = "Fabrication Sheath" },
            { name = "Fractured Glory" },
            { name = "Reanimated Vampiric Thrall" },
            { name = "Sable Man-Beast" },
            { name = "Sanctified Silver" },
            { name = "Seaborn Silver" },
            { name = "Spiderkith" },
            { name = "Sunspire Ice-Fire" },
            { name = "Tactician's Gold Lattice Skin" },
            { name = "The Taskmaster's Banner" },
            { name = "Twin Titan's Retribution" },
            { name = "Void Pathosis" },
            { name = "Xanmeer Defender" },
            { name = "Z'Maja's Shadow" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Master Field Cartographer", fragments = { "Cartographer's Mask", "Cartographer's Coat", "Cartographer's Leggings", "Cartographer's Gloves", "Cartographer's Boots", "Cartographer's Belt", "Cartographer's Backpack" } },
            { name = "Antiquarian Field Garb" },
            { name = "Antiquarian Robes" },
            { name = "Arena Gladiator" },
            { name = "Black Hand Robe" },
            { name = "Blackheart Pirate Armor" },
            { name = "Bloodthorn Robes" },
            { name = "Cavalier of the Sworn Oath" },
            { name = "Colovian Uniform" },
            { name = "Courier Uniform" },
            { name = "Courtly Traveling Attire" },
            { name = "Crown Dishdasha" },
            { name = "Dark Seducer" },
            { name = "Dunmer Cultural Garb" },
            { name = "Emperor's Regalia" },
            { name = "Fate Scryer" },
            { name = "Forebear Dishdasha" },
            { name = "Fort Amol Guard Armor" },
            { name = "Frostedge Bandit Armor" },
            { name = "Golden Saint" },
            { name = "Hollow Moon Garb" },
            { name = "Imperial Chancellor" },
            { name = "Keeper's Garb" },
            { name = "Mannimarco" },
            { name = "Merchant Lord's Formal Regalia" },
            { name = "Midnight Union Garb" },
            { name = "Northwind Disguise" },
            { name = "Oblivion Explorer Garb" },
            { name = "Old Orsinium Sentry" },
            { name = "Peryite Skeevemaster" },
            { name = "Phaer Mercenary Armor" },
            { name = "Quendelunn Veiled Heritance Garb" },
            { name = "Red Rook Armor" },
            { name = "Regalia of the Orsimer King" },
            { name = "Regalia of the Scarlet Judge" },
            { name = "Satakalaaam Imperial Armor" },
            { name = "Sea Drake Garb" },
            { name = "Sea Viper Armor" },
            { name = "Servant's Outfit" },
            { name = "Servant's Robes" },
            { name = "Seventh Legion Armor" },
            { name = "Shrouded Armor" },
            { name = "Siegemaster's Uniform" },
            { name = "Sixth House Robe" },
            { name = "Steel Shrike Uniform" },
            { name = "Stormfist Uniform" },
            { name = "Thieves Guild Leathers" },
            { name = "Thrafey Debutante Gown" },
            { name = "Timbercrow Wanderer" },
            { name = "Trinimac's Penitent Knight" },
            { name = "Vanguard Uniform" },
            { name = "Vulkhel Guard Marine Armor" },
            { name = "Za'ji's Dragonguard Uniform" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Arena Gladiator Helm" },
            { name = "Arkthzand Anfractuosity Shroud" },
            { name = "Ayleid Royal Crown" },
            { name = "Cadwell's Helm of Heroism" },
            { name = "Firesong Obsidian Mask" },
            { name = "Helm of the Black Fin" },
            { name = "Keptu-Horn Skull Sallet" },
            { name = "Madgod's Turban" },
            { name = "Mask of Alkosh" },
            { name = "Oblivion Explorer's Headwrap" },
            { name = "Psijic Skullcap" },
            { name = "Reach-Mage Ceremonial Skullcap" },
            { name = "Renegade Dragon Priest Mask" },
            { name = "Sacred Watcher Hood" },
            { name = "Siegemaster Close Helm" },
            { name = "Vosh Rakh Ceremonial Mask" },
            { name = "Werewolf Hunter Hat" },
            { name = "Witchwise Headdress" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Abyssal Cephaliarch's Body Art" },
            { name = "Abyssal Embrace Body Markings" },
            { name = "Archival Access Body Tattoos" },
            { name = "Bloodrune Body Markings" },
            { name = "Body Imprint of the Psijic Order" },
            { name = "Buoyant Armiger Body Tattoos" },
            { name = "Drakes and Daemons Duel Body Art" },
            { name = "Fargrave Soullattice Body Marks" },
            { name = "Feral Favor Body Tattoo" },
            { name = "Mirrorscribe Body Markings" },
            { name = "Morag Tong Body Tattoo" },
            { name = "Reach Rebel Body Markings" },
            { name = "Shattered Chivalry Body Tattoo" },
            { name = "Shattered Mirror Maze Body Marks" },
            { name = "Stone-Nest Xanmeer Body Tattoos" },
            { name = "Stonelore's Legend Body Paint" },
            { name = "Stormsurge Body Markings" },
            { name = "Sul-Xan Raider Body Markings" },
            { name = "Threads of Mirrormoor Body Art" },
            { name = "Touch of the Draoife Body Marks" },
            { name = "Unfeathered Battle Tattoo" },
            { name = "Unkindness of Ravens Body Art" },
            { name = "Veteran of the Infinite Body Art" },
            { name = "Whorls of the Dark Dream Marks" },
            { name = "Y'ffelon's Body Brand" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Abyssal Cephaliarch's Face Art" },
            { name = "Abyssal Embrace Face Markings" },
            { name = "Aldmeri Dominion War Marks" },
            { name = "Archival Access Face Tattoos" },
            { name = "Bloodrune Face Markings" },
            { name = "Buoyant Armiger Face Tattoo" },
            { name = "Daggerfall Covenant War Marks" },
            { name = "Drakes and Daemons Duel Face Art" },
            { name = "Dwemer Face Markings" },
            { name = "Ebonheart Pact War Marks" },
            { name = "Face Imprint of the Psijic Order" },
            { name = "Fargrave Soullattice Face Marks" },
            { name = "Feral Favor Face Tattoo" },
            { name = "Mirrorscribe Face Markings" },
            { name = "Morag Tong Face Tattoo" },
            { name = "Obnoxious Mute Face Paint" },
            { name = "Reach Rebel Face Markings" },
            { name = "Shadows of Blackwood Face Marks" },
            { name = "Shattered Chivalry Face Tattoo" },
            { name = "Shattered Mirror Maze Face Marks" },
            { name = "Stone-Nest Xanmeer Face Tattoos" },
            { name = "Stonelore's Legend Face Paint" },
            { name = "Stormsurge Face Markings" },
            { name = "Sul-Xan Raider Face Markings" },
            { name = "Threads of Mirrormoor Face Art" },
            { name = "Touch of the Draoife Face Marks" },
            { name = "Unfeathered Battle Visage" },
            { name = "Unkindness of Ravens Face Art" },
            { name = "Veteran of the Infinite Face Art" },
            { name = "Whorls of the Dark Dream Visage" },
            { name = "Y'ffelon's Face Brand" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Drakes and Daemons Mask" },
            { name = "Grave Elegance Mask" },
            { name = "Malign Ambitions Crown" },
            { name = "Solstice Bismuth Tiara" },
            { name = "Solstice Pinned Blooms" },
            { name = "Wolfcrown of Solitude" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Azure Plasmstone Earrings" },
        },
    },
}
