CollectThemAllData_GoldCoastBazaar_SeasonZero = {
    name = "Season Zero: Dawn and Dusk",
    source = "Gold Coast Bazaar",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {
            { name = "Dragon's Treasure Trove", bars = 2550 },
            { name = "Jester Anglidor", bars = 1200 },

            { name = "Painting: All Flags on High", bars = 450 },
            { name = "Painting: Arrival at Bal Foyen", bars = 450 },
            { name = "Painting: Infinite Archive", bars = 450 },
            { name = "Painting: The Gates of Brass", bars = 450 },
            { name = "Statuette: Auri-El, Aldmer King", bars = 600 },
            { name = "Statuette: Azura, Moon and Star", bars = 600 },
            { name = "Statuette: Boethra, Orkha-Bane", bars = 600 },
            { name = "Statuette: Child of the Sky", bars = 600 },
            { name = "Statuette: High Elf Mage", bars = 600 },
            { name = "Statuette: Kaalgrontiid", bars = 600 },
            { name = "Statuette: Kaladas of Leyawiin", bars = 600 },
            { name = "Statuette: Kinlord Nemfarion", bars = 600 },
            { name = "Statuette: Malacath, Orc-Father", bars = 600 },
            { name = "Statuette: Mermaid of Anvil", bars = 600 },
            { name = "Statuette: Orc Warrior", bars = 600 },
            { name = "Statuette: Peryite, Blightlord", bars = 600 },
            { name = "Statuette: Sithis, Dread Lord", bars = 600 },
            { name = "Statuette: Suthay, Nimble Bishop", bars = 600 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Flint-Pelt Fox", bars = 4400 },
            { name = "Snowdrift Vale Elk", bars = 5000 },
            { name = "White Lion", bars = 4000 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Bright Moons Dragon Imp", bars = 850 },
            { name = "Dusky Fennec Fox", bars = 1000 },
            { name = "Ebony Dwarven Scarab", bars = 700 },
            { name = "Flame Atronach Bear Cub", bars = 1100 },
            { name = "Flame Atronach Pack Wolf", bars = 1100 },
            { name = "Flame Atronach Pocket Horse", bars = 1100 },
            { name = "Flame Atronach Pony Guar", bars = 1100 },
            { name = "Flame Atronach Senche-Jaguar", bars = 1100 },
            { name = "Green Dragon Imp", bars = 750 },
            { name = "Mara's Spring Chicken", bars = 600 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Flower Fling", bars = 700 },
            { name = "Pop the Cork", bars = 750 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Morthal Jarl Finery", bars = 1400 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Cycle Behind the Stars Body Art", bars = 500 },
            { name = "Shadows of Blackwood Body Marks", bars = 850 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Cycle Behind the Stars Face Art", bars = 350 },
            { name = "Enchanting Cherry Blossom Visage", bars = 375 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Chaurus Egg Ear Studs", bars = 400 },
            { name = "Moon-and-Star Earrings", bars = 500 },
        },
    },
}
