CollectThemAllData_GoldCoastBazaar_SeasonOne = {
    name = "Season One: Return of the Thieves Guild",
    source = "Gold Coast Bazaar",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {
            { name = "Statue, Ascendant Lord", bars = 1200 },
            { name = "Alchemy", bars = 1750 },

            { name = "Painting: Carapace Caverns", bars = 450 },
            { name = "Painting: Leyawiin Awaits", bars = 450 },
            { name = "Painting: The Stitches", bars = 450 },
            { name = "Statuette: Auriel of Garlas Agea", bars = 600 },
            { name = "Statuette: Dibella, Blessed Lady", bars = 600 },
            { name = "Statuette: Kynareth, Air Goddess", bars = 600 },
            { name = "Statuette: Meridia, Bright Lady", bars = 600 },
            { name = "Statuette: Mora, Lord of Secrets", bars = 600 },
            { name = "Statuette: Nocturnal, Gloamqueen", bars = 600 },
            { name = "Statuette: Peryite, Taskmaster", bars = 600 },
            { name = "Statuette: Prince Hew", bars = 600 },
            { name = "Statuette: Redguard Warrior", bars = 600 },
            { name = "Statuette: Steadfast Stendarr", bars = 600 },
            { name = "Statuette: Syrabane, the Warlock", bars = 600 },
            { name = "Statuette: Trinimac, Paragon", bars = 600 },
            { name = "Statuette: Vaermina, Dreamweaver", bars = 600 },
            { name = "Statuette: Wolf and Warrior", bars = 600 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Nix-Ox War-Steed", bars = 4500 },
            { name = "Treasure Hunter's Horse", bars = 4000 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Atmoran Bantam Guar", bars = 900 },
            { name = "Clouded Senche-Leopard Cub", bars = 500 },
            { name = "Coldharbour Bantam Guar", bars = 900 },
            { name = "Nenalata Ayleid Wolf Pup", bars = 1000 },
            { name = "Orchidfall Vale Fawn", bars = 700 },
            { name = "Pedlar Pack Pony", bars = 1100 },
            { name = "Pedlar Pack Senche-Lion Cub", bars = 1100 },
            { name = "Pedlar Pack Spider", bars = 1100 },
            { name = "Pedlar Pack Wolf Cub", bars = 1100 },
            { name = "Pellucid Swamp Jelly", bars = 850 },
            { name = "Scruffy Skyrim Paint Pony", bars = 600 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Plant Yourself", bars = 700 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Dungeon Explorer", bars = 2100 },
            { name = "Fisherfolk Work Wear", bars = 2000 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Druidic Knotwork Body Tattoos", bars = 500 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Druidic Knotwork Face Tattoos", bars = 300 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Dremora Deceiver's Diadem", bars = 550 },
            { name = "Seastone Browplate", bars = 350 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
