CollectThemAllData_GoldCoastBazaar_GoldCoastWares = {
    name = "Gold Coast Wares",
    source = "Gold Coast Bazaar",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {
            { name = "Grand Gallery of Tamriel", no = 114, bars = 11000 },
            { name = "Kelesan'ruhn", no = 104, bars = 9600 },
            { name = "Sword-Singer's Redoubt", no = 103, bars = 8500 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {
            { name = "Kynareth's Icon of Storm Control", bars = 3900 },

            -- TODO: these are not collectibles, kept here to know these for a new furnishing feature
            -- { name = "Music Box, Oath of the Keepers", bars = 2000 },
            -- { name = "Statue of Molag Bal, Harvester", bars = 2000 },
            -- { name = "Statue, Breton Hero", bars = 2000 },
            -- { name = "Statue, Elven Hero", bars = 2000 },
            -- { name = "Statue, Nord Hero", bars = 2000 },
            -- { name = "Target Ogrim", bars = 1950 },

            { name = "Mizzik Thunderboots", bars = 1750 },
            { name = "Necrom Guard Miraso", bars = 1000, info = "Previously in Crown Store" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Glowgill Guar", bars = 4000 },
            { name = "Iron Orc Welwa", bars = 5100 },
            { name = "Russet Brekka", bars = 6000 },
            { name = "Shoal Bear", bars = 8100 },
            { name = "Sungold Bay Thoroughbred", bars = 4500 },
            { name = "Verdant Tattoo Shorn Camel", bars = 4200 },
            { name = "Wayrest Vanner Pillion Steed", bars = 8200, info = "Previously in Crown Store" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Anchorborn Pony", bars = 1600 },
            { name = "Ayrenn's Fledgling Gryphon", bars = 1200 },
            { name = "Barnacle-Back Coral Crab", bars = 950 },
            { name = "Bruma Spotted Pig", bars = 900 },
            { name = "Chaosball Cohort", bars = 900 },
            { name = "Devoted Torchbug", bars = 1000 },
            { name = "Dozen-Banded Vvardvark", bars = 850 },
            { name = "Firebelly Shalk", bars = 1050 },
            { name = "Golden Honor", bars = 1800 },
            { name = "Hot-Blooded Bantam Guar", bars = 1500 },
            { name = "Infernium Dwarven Spiderling", bars = 1650 },
            { name = "Nightrose Vale Fawn", bars = 1000 },
            { name = "Noble Riverhold Senche-Lion Cub", bars = 500 },
            { name = "Pony-Lizard", bars = 1350 },
            { name = "Salamandrine Pony Guar", bars = 650 },
            { name = "Vampiric Dragon Imp", bars = 1150, info = "Previously in Crown Store as part of Player Appreciation Bundle" },
            { name = "Viridescent Dragon Frog", bars = 700 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Dibella's Sweetroll Stack", bars = 900 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Ritual Casting", bars = 800 },
            { name = "Sit and Drink", bars = 600 },
            { name = "Skingrad Noble Snack", bars = 740 },
            { name = "Trumpet Solo", bars = 670 },
            { name = "Uh … Never Mind", bars = 600 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Dibella's Exaltation Arm Cops", bars = 750, info = "Dibella's Exaltation Armor Pack" },
            { name = "Dibella's Exaltation Belt", bars = 500, info = "Dibella's Exaltation Armor Pack" },
            { name = "Dibella's Exaltation Boots", bars = 500, info = "Dibella's Exaltation Armor Pack" },
            { name = "Dibella's Exaltation Bracers", bars = 500, info = "Dibella's Exaltation Armor Pack" },
            { name = "Dibella's Exaltation Guards", bars = 500, info = "Dibella's Exaltation Armor Pack" },
            { name = "Dibella's Exaltation Helmet", bars = 750, info = "Dibella's Exaltation Armor Pack" },
            { name = "Dibella's Exaltation Jack", bars = 500, info = "Dibella's Exaltation Armor Pack" },
            { name = "Thurvokun Bow", bars = 720, info = "Thurvokun Arms Pack" },
            { name = "Thurvokun Dagger", bars = 720, info = "Thurvokun Arms Pack" },
            { name = "Thurvokun Maul", bars = 720, info = "Thurvokun Arms Pack" },
            { name = "Thurvokun Shield", bars = 720, info = "Thurvokun Arms Pack" },
            { name = "Thurvokun Staff", bars = 720, info = "Thurvokun Arms Pack" },
            { name = "Tree-Sap Legion Axe", bars = 200, info = "Tree-Sap Legion Arms Pack" },
            { name = "Tree-Sap Legion Battle Axe", bars = 200, info = "Tree-Sap Legion Arms Pack" },
            { name = "Tree-Sap Legion Bow", bars = 200, info = "Tree-Sap Legion Arms Pack" },
            { name = "Tree-Sap Legion Dagger", bars = 200, info = "Tree-Sap Legion Arms Pack" },
            { name = "Tree-Sap Legion Greatsword", bars = 200, info = "Tree-Sap Legion Arms Pack" },
            { name = "Tree-Sap Legion Mace", bars = 200, info = "Tree-Sap Legion Arms Pack" },
            { name = "Tree-Sap Legion Maul", bars = 200, info = "Tree-Sap Legion Arms Pack" },
            { name = "Tree-Sap Legion Shield", bars = 200, info = "Tree-Sap Legion Arms Pack" },
            { name = "Tree-Sap Legion Staff", bars = 200, info = "Tree-Sap Legion Arms Pack" },
            { name = "Tree-Sap Legion Sword", bars = 200, info = "Tree-Sap Legion Arms Pack" },
            { name = "Mace of Molag Bal", bars = 800, info = "Previously in Crown Store as part of Player Appreciation Bundle" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            
            { name = "Frost Draugr Runegathering", bars = 2000 },
            { name = "Gold Road Recall", bars = 4200, info = "Previously in Crown Store for free to those who earned the Champion of Vivec achievement within the promotional window. Its availability ran from July 2 to August 15, 2024 for all platforms. Unlocking the achievement required completing the main quest in the Morrowind chapter." },
            { name = "Mini Siege Mining", bars = 3200 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {
            { name = "Backlash, Ice Blue", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Puncturing Strikes, Ice Blue", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Rushed Ceremony, Azure Blue", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Assassin's Blade, Lilac Purple", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Death Stroke, Lilac Purple", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Veiled Strike, Lilac Purple", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Dragonfire Breath, Azure Blue", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Earthspike Mantle, Azure Blue", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Lava Whip, Azure Blue", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Arctic Wind, Blazing Orange", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Fungal Growth, Blazing Orange", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Scorch, Blazing Orange", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Death Scythe, Carmine Red", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Flame Skull, Onyx and Red", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Frozen Colossus, Carmine Red", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Fatecarver, Soothing Blue", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Runeblades, Azure Blue", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Runemend, Azure Blue", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Crystal Shard, Ruby Red", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Daedric Curse, Ruby Red", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },
            { name = "Lightning Form, Ruby Red", bars = 500, info = "Previously in Crown Store for free - Class Style Pack: Tamriel United" },

            { name = "Abyssal Impact, Azure Blue", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Bone Armor, Carmine Red", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Cleansing Ritual, Azure Blue", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Dark Exchange, Ruby Red", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Frost Cloak, Blazing Orange", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Healing Seed, Blazing Orange", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Mages' Fury, Ruby Red", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Magma Armor, Azure Blue", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Molten Weapons, Azure Blue", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Radiant Destruction, Ice Blue", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Render Flesh, Carmine Red", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Runespite Ward, Azure Blue", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Siphoning Strikes, Lilac Purple", bars = 500, info = "New in Gold Coast Bazaar" },
            { name = "Strife, Violet Purple", bars = 500, info = "New in Gold Coast Bazaar" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "10-Year Anniversary Breton Hero", bars = 3500 },
            { name = "10-Year Anniversary Elven Hero", bars = 3500 },
            { name = "10-Year Anniversary Nord Hero", bars = 3500 },
            { name = "Cumberland Anniversary Attire", bars = 2750 },
            { name = "Sailor-at-Arms", bars = 2000 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "Ancient Dragon Body Marks", bars = 600 },
            { name = "Eldertide Body Ink", bars = 600 },
            { name = "Rose of Tamriel Body Marks", bars = 600 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "Ancient Dragon Face Marks", bars = 300 },
            { name = "Eldertide Face Ink", bars = 300 },
            { name = "Rose of Tamriel Face Marks", bars = 300 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {
            { name = "Draping Locks", bars = 650 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {
            { name = "Old Salt's Chin-Trinket", bars = 400 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Miscarcand Monocle", bars = 650 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {
            { name = "Adventure-Ending Arrow", bars = 800 },
            { name = "Soul Harvester Earrings", bars = 500 },
        },
    },
}
