-- LibLootSummary Russian localization using ZO_CreateStringId
-- This properly defines and registers string constants in one step

ZO_CreateStringId("SI_LLS_ITEM_SUMMARY", "Отчет о предметах")
ZO_CreateStringId("SI_LLS_ITEM_SUMMARY_TOOLTIP", "<<1>> напечатает отчет о предметах после всех действий.")
ZO_CreateStringId("SI_LLS_LOOT_SUMMARY", "Отчет о добыче")
ZO_CreateStringId("SI_LLS_LOOT_SUMMARY_TOOLTIP", "<<1>> напечатает отчет о добыче после всех действий.")
ZO_CreateStringId("SI_LLS_MIN_ITEM_QUALITY", "Минимальное качество предмета")
ZO_CreateStringId("SI_LLS_MIN_ITEM_QUALITY_TOOLTIP", "Предметы с качеством ниже этого значения не включаются в отчет.")
ZO_CreateStringId("SI_LLS_MIN_LOOT_QUALITY", "Минимальное качество добычи")
ZO_CreateStringId("SI_LLS_MIN_LOOT_QUALITY_TOOLTIP", "Добыча с качеством ниже этого значения не включается в отчет.")
ZO_CreateStringId("SI_LLS_SHOW_ITEM_ICONS", "Показывать иконки предметов")
ZO_CreateStringId("SI_LLS_SHOW_ITEM_ICONS_TOOLTIP", "Показывать иконку слева от имени предметов, появляющихся в отчете.")
ZO_CreateStringId("SI_LLS_ICON_SIZE", "Размер иконки")
ZO_CreateStringId("SI_LLS_ICON_SIZE_TOOLTIP", "Установите размер иконки в процентах.")
ZO_CreateStringId("SI_LLS_SHOW_LOOT_ICONS", "Показывать иконки добычи")
ZO_CreateStringId("SI_LLS_SHOW_LOOT_ICONS_TOOLTIP", "Показывать иконку слева от имени добычи, появляющейся в отчете.")
ZO_CreateStringId("SI_LLS_SHOW_ITEM_TRAITS", "Показать особенности предметов")
ZO_CreateStringId("SI_LLS_SHOW_ITEM_TRAITS_TOOLTIP", "Показать особенности предметов в скобках справа от имени в отчете.")
ZO_CreateStringId("SI_LLS_SHOW_LOOT_TRAITS", "Показать особенности добычи")
ZO_CreateStringId("SI_LLS_SHOW_LOOT_TRAITS_TOOLTIP", "Показать особенности добычи в скобках справа от имени в отчете.")
ZO_CreateStringId("SI_LLS_HIDE_ITEM_SINGLE_QTY", "Скрыть количество для одного предмета")
ZO_CreateStringId("SI_LLS_HIDE_ITEM_SINGLE_QTY_TOOLTIP", "Количество будет напечатано справа от названий предметов только если оно больше единицы.")
ZO_CreateStringId("SI_LLS_HIDE_LOOT_SINGLE_QTY", "Скрыть количество для одной добычи")
ZO_CreateStringId("SI_LLS_HIDE_LOOT_SINGLE_QTY_TOOLTIP", "Количество будет напечатано справа от названия добычи только если оно больше единицы.")
ZO_CreateStringId("SI_LLS_COMBINE_DUPLICATES", "Объединять повторяющиеся предметы")
ZO_CreateStringId("SI_LLS_COMBINE_DUPLICATES_TOOLTIP", "Ссылки, появляющиеся несколько раз в отчете, будут объединены в одну и количество предметов будет просуммировано.")
ZO_CreateStringId("SI_LLS_SHOW_ITEM_NOT_COLLECTED", "<<1>> Показывать иконки для сетов не в коллекции")
ZO_CreateStringId("SI_LLS_SHOW_ITEM_NOT_COLLECTED_TOOLTIP", "Отображать иконку справа от названия предмета, если он не добавлен в коллекцию.")
ZO_CreateStringId("SI_LLS_SHOW_LOOT_NOT_COLLECTED", "<<1>> Показывать иконки для сетов не в коллекции")
ZO_CreateStringId("SI_LLS_SHOW_LOOT_NOT_COLLECTED_TOOLTIP", "Отображать иконку справа от названия добычи, если он не добавлен в коллекцию.")
ZO_CreateStringId("SI_LLS_SORT_ORDER_TOOLTIP", "Выберите как будет сортироваться отчет")
ZO_CreateStringId("SI_LLS_DELIMITER", "Список разделителей")
ZO_CreateStringId("SI_LLS_DELIMITER_TOOLTIP", "Выберите какие символы будут разделять предметы в отчете. \"\\n\" значит, что каждый предмет будет отображаться на отдельной строке. ")
ZO_CreateStringId("SI_LLS_LINK_STYLE", "Стиль ссылки")
ZO_CreateStringId("SI_LLS_LINK_STYLE_TOOLTIP", "Выберите как будут отображаться ссылки.")
ZO_CreateStringId("SI_LLS_QUOTES", "\"<<X:1>>\"")
ZO_CreateStringId("SI_LLS_SHOW_COUNTER", "Показать количества <<1>>")
ZO_CreateStringId("SI_LLS_SHOW_COUNTER_TOOLTIP", "Показать количество <<1>> в конце отчете.")
ZO_CreateStringId("SI_LLS_COUNTER_FORMAT_SINGLE", "(<<1>> <<2>>)")
ZO_CreateStringId("SI_LLS_COUNTER_FORMAT_PLURAL", "(<<1*2>>)")
ZO_CreateStringId("SI_LLS_PLURAL", "<<1*2>>")

-- Fallback strings for error conditions and missing localization
ZO_CreateStringId("SI_LLS_FALLBACK_SHOW_UNCOLLECTED", "Показать иконки несобранных наборов")
ZO_CreateStringId("SI_LLS_FALLBACK_SETTINGS_FOR", "Настройки для")
ZO_CreateStringId("SI_LLS_FALLBACK_SHOW_COUNTER", "Показать счетчик")
ZO_CreateStringId("SI_LLS_FALLBACK_SHOW_COUNT_OF", "Показать количество")
ZO_CreateStringId("SI_LLS_FALLBACK_ITEMS", "Предметы")
ZO_CreateStringId("SI_LLS_FALLBACK_ITEMS_LOWER", "предметы")
ZO_CreateStringId("SI_LLS_ERROR_CONSTANTS_NOT_DEFINED", "Строковые константы не определены")
ZO_CreateStringId("SI_LLS_ERROR_VALUES_NOT_LOADED", "Строковые значения не загружены")