local Hermes = _G['Hermes']

HermesLocalizationData = {
    de = {
        --General
        NAME = "Hermes",
        --Changelog
        CHANGELOG_TITLE = "<<1>> Changelog",
        CHANGELOG_FROM = "v<<1>> von <<2>>",
        changelog_message = {
            "|cFFA500Hermes Version 1.5.2|r",
            "",
            "|cFFFF00Allgemein:|r",
            "[*] API-Anpassung auf Version 50 - Season Zero Pt. 2. [NEU]",
            "",
            "|cFFFF00Folianten:|r",
            "[+] Fortschrittsbalken pro Aufgabe hinzugefügt (deaktivierbar in den Einstellungen).",
            "[+] Automatische Aufgabenverfolgung hinzugefügt (deaktivierbar in den Einstellungen).",
            "[+] Begonnene Aufgaben werden nun zuerst angezeigt.",
            "[*] Fortschritt wird nun farblich dargestellt: Grün = einsammelbar, Orange = in Arbeit.",
            "[*] Einsammelbare Aufgaben haben nun einen dezenten grünen Hintergrund.",
            "[*] Hover-Hervorhebung überarbeitet – keine Lücken mehr zwischen den Zeilen.",
            "[*] Fehler beim Hovern über die Schaltfläche 'Alle abholen' behoben.",
            "[*] Das Fenster wird nach einem Reroll nun sofort aktualisiert. [NEU]",
            "[*] Einige Strings für die englische Übersetzung haben gefehlt.",
            "",
        },
        --Settings
        SETTINGS_SHOW_TELEPORT = "Teleport im Chat anzeigen",
        SETTINGS_SHOW_MAIL = "Neue Nachricht im Chat anzeigen",
        SETTINGS_SHOW_HOUSE = "Teleport zum Haupthaus im Chat anzeigen",
        SETTINGS_SHOW_CHANGELOG = "Changelog automatisch öffnen [Update]",
        SETTINGS_BUTTON_CHANGELOG = "Changelog öffnen",
        SETTINGS_TOME_HEADER_CHAT = "Chat",
        SETTINGS_TOME_HEADER_WINDOW = "Fenster",
        SETTINGS_TOME_TITLE = "Folianten",
        SETTINGS_TOME_ENABLE = "Fortschritt anzeigen",
        SETTINGS_TOME_LOCATION = "Anzeigeort",
        SETTINGS_TOME_ICON_UI = "Folianten Icon anzeigen",
        SETTINGS_TOME_CHOICE0 = "Chatfenster",
        SETTINGS_TOME_CHOICE1 = "Bildschirm",
        SETTINGS_TOME_COLOR_WEEKLY = "Textfarbe (wöchentliche Herausforderungen)",
        SETTINGS_TOME_COLOR_SEASONAL = "Textfarbe (saisonale Herausforderungen)",
        SETTINGS_TOME_REWARD = "Belohnung in [] darstellen",
        SETTINGS_TOME_SEASONAL_PROGRESS = "Saisonalen Fortschritt immer anzeigen",
        SETTINGS_TOME_CLAIM = "Foliantenpunkte automatisch abholen",
        SETTINGS_TOME_AUTO_TRACK = "Aufgabe automatisch verfolgen",
        SETTINGS_TOME_PROGRESS_BAR = "Fortschrittsbalken anzeigen",
        SETTINGS_TOME_WINDOW_INFO = "Tome-Fenster über das Fenster-Icon oder mit /htomes öffnen.",
        SETTINGS_TOME_COMPACT_MODE = "Kompakter Fenstermodus",
        SETTINGS_TOME_BGTRANSPARENCY = "Fenster Transparenz",
        SETTINGS_TOOLTIP_TOMES = "Stelle hier ein ob du eine Anzeige bezüglich der Folianten-Herausforderungen haben möchtest.",
        SETTINGS_TOOLTIP_TOME_SEASONAL_PROGRESS = "Wenn deaktiviert, werden saisonale Herausforderungen nur bei Abschluss gemeldet.",
        SETTINGS_TOOLTIP_TOME_AUTO_TRACK = "Verfolgt automatisch die am weitesten fortgeschrittene offene Aufgabe wenn keine aktiv verfolgt wird.",
        -- Tome
        TOME_WINDOW_TITLE = "Foliantenübersicht",
        TOME_WINDOW_TAB_WEEKLY = "Wöchentlich",
        TOME_WINDOW_TAB_SEASONAL = "Saisonal",
        TOME_WINDOW_BUTTON_TRACK = "Verfolgen",
        TOME_WINDOW_BUTTON_UNTRACK = "Nicht mehr verfolgen",
        TOME_WINDOW_BUTTON_CLAIM = "Abholen",
        TOME_WINDOW_BUTTON_REROLL = "Erneuern",
        TOME_WINDOW_LABEL_NAME = "Aufgaben",
        TOME_WINDOW_LABEL_PROGRESS = "Fortschritt",
        TOME_WINDOW_LABEL_REWARD = "Belohnung",
        TOME_WINDOW_EMPTY = "Keine passenden Herausforderungen gefunden.",
        TOME_WINDOW_TIME_WEEKLY = "Weekly endet in",
        TOME_WINDOW_TIME_SEASONAL = "Saisonal endet in",
        TOME_WINDOW_BUTTON_REROLL_UNAVAILABLE = "Keine Rerolls mehr übrig",
        TOME_WINDOW_LABEL_TOTAL = "Gesamt:",
        TOME_ICON_UI_OPEN = "Foliantenfenster öffnen",
        TOME_WINDOW_BUTTON_CLAIM_ALL = "Alle abholen",
        TOME_WINDOW_BUTTON_CLAIM_ALL_TOOLTIP = "Alle verfügbaren Foliantenbelohnungen abholen.",
        TOME_WINDOW_BUTTON_CLAIM_ALL_UNAVAILABLE = "Keine Foliantenbelohnungen zum Abholen verfügbar.",
        --Bindings
        BINDING_OPEN_TOMES_WINDOW = "Folianten öffnen",
    },

    en = {
        --General
        NAME = "Hermes",
        --Changelog
        CHANGELOG_TITLE = "<<1>> Changelog",
        CHANGELOG_FROM = "v<<1>> from <<2>>",
        changelog_message = {
            "|cFFA500Hermes Version 1.5.2|r",
            "",
            "|cFFFF00General:|r",
            "[*] API bump to version 50 - Season Zero Pt. 2. [NEW]",
            "",
            "|cFFFF00Tomes:|r",
            "[+] Added progress bar per task, toggleable in settings.",
            "[+] Added automatic task tracking when nothing is actively tracked, toggleable in settings.",
            "[+] In-progress tasks are now sorted to the top.",
            "[*] Task progress is now colour-coded: green = claimable, orange = in progress.",
            "[*] Claimable tasks now have a subtle green background.",
            "[*] Fixed hover highlight to cover full row height with no gaps between rows.",
            "[*] Fixed error when hovering over the claim all button.",
            "[*] Window now refreshes immediately after a reroll. [NEW]",
            "[*] Fixed missing localization.",
            "",
        },
        --Settings
        SETTINGS_SHOW_TELEPORT = "Show teleport in chat",
        SETTINGS_SHOW_MAIL = "Show new message in chat",
        SETTINGS_SHOW_HOUSE = "Show teleport to primary house in chat",
        SETTINGS_SHOW_CHANGELOG = "Open Changelog automatically [Update]",
        SETTINGS_BUTTON_CHANGELOG = "Open Changelog",
        SETTINGS_TOME_HEADER_CHAT = "Chat",
        SETTINGS_TOME_HEADER_WINDOW = "Window",
        SETTINGS_TOME_TITLE = "Tomes",
        SETTINGS_TOME_ENABLE = "Show progress",
        SETTINGS_TOME_LOCATION = "Location",
        SETTINGS_TOME_ICON_UI = "Show Tomes icon",
        SETTINGS_TOME_CHOICE0 = "Chat window",
        SETTINGS_TOME_CHOICE1 = "Screen",
        SETTINGS_TOME_COLOR_WEEKLY = "Text color (weekly challenges)",
        SETTINGS_TOME_COLOR_SEASONAL = "Text color (seasonal challenges)",
        SETTINGS_TOME_REWARD = "Display reward in []",
        SETTINGS_TOME_SEASONAL_PROGRESS = "Always show seasonal progress",
        SETTINGS_TOME_CLAIM = "Auto-claim Tome points",
        SETTINGS_TOME_AUTO_TRACK = "Auto-track task",
        SETTINGS_TOME_PROGRESS_BAR = "Show progress bar",
        SETTINGS_TOME_WINDOW_INFO = "Open the Tome window via the window icon or with /htomes.",
        SETTINGS_TOME_COMPACT_MODE = "Compact window mode",
        SETTINGS_TOME_BGTRANSPARENCY = "Window transparency",
        SETTINGS_TOOLTIP_TOMES = "Choose here whether you want progress alerts for Tamriel Tome challenges.",
        SETTINGS_TOOLTIP_TOME_SEASONAL_PROGRESS = "If disabled, seasonal challenges are only shown when completed.",
        SETTINGS_TOOLTIP_TOME_AUTO_TRACK = "Automatically tracks the most progressed incomplete task when none is currently tracked.",
        -- Tome
        TOME_WINDOW_TITLE = "Tome Overview",
        TOME_WINDOW_TAB_WEEKLY = "Weekly",
        TOME_WINDOW_TAB_SEASONAL = "Seasonal",
        TOME_WINDOW_BUTTON_TRACK = "Track",
        TOME_WINDOW_BUTTON_UNTRACK = "Untrack",
        TOME_WINDOW_BUTTON_CLAIM = "Claim",
        TOME_WINDOW_BUTTON_REROLL = "Reroll",
        TOME_WINDOW_LABEL_NAME = "Challenges",
        TOME_WINDOW_LABEL_PROGRESS = "Progress",
        TOME_WINDOW_LABEL_REWARD = "Reward",
        TOME_WINDOW_EMPTY = "No matching challenges found.",
        TOME_WINDOW_TIME_WEEKLY = "Weekly ends in",
        TOME_WINDOW_TIME_SEASONAL = "Seasonal ends in",
        TOME_WINDOW_BUTTON_REROLL_UNAVAILABLE = "No rerolls left",
        TOME_WINDOW_LABEL_TOTAL = "Total:",
        TOME_ICON_UI_OPEN = "Open Tome window",
        TOME_WINDOW_BUTTON_CLAIM_ALL = "Claim All",
        TOME_WINDOW_BUTTON_CLAIM_ALL_TOOLTIP = "Claim all available Tome rewards.",
        TOME_WINDOW_BUTTON_CLAIM_ALL_UNAVAILABLE = "No Tome rewards available to claim.",
        --Bindings
        BINDING_OPEN_TOMES_WINDOW = "Open Tomes",
    },
}

local function GetLocaleString(langId, langStr)
    if (HermesLocalizationData[langId] ~= nil) and (HermesLocalizationData[langId][langStr] ~= nil) then
        return HermesLocalizationData[langId][langStr]
    end

    return HermesLocalizationData["en"][langStr]
end

function Hermes.GetDefaultLocaleString(langStr)
    return GetLocaleString(GetCVar("language.2"), langStr)
end