CollectThemAllData_Motifs_Motifs = {
    name = "Motifs",
    source = "Motifs",
    specific = true,
    basesort = true,
    collection = { -- TODO: this could be improved by information about where to acquire, but not all of these can be acquired in game
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "High Elf", motif = 1, q = 5 },
            { name = "Dark Elf", motif = 2, q = 5 },
            { name = "Wood Elf", motif = 3, q = 5 },
            { name = "Nord", motif = 4, q = 5 },
            { name = "Breton", motif = 5, q = 5 },
            { name = "Redguard", motif = 6, q = 5 },
            { name = "Khajiit", motif = 7, q = 5 },
            { name = "Orc", motif = 8, q = 5 },
            { name = "Argonian", motif = 9, q = 5 },
            { name = "Imperial", motif = 10, q = 3 },
            { name = "Ancient Elf", motif = 11, q = 4 },
            { name = "Barbaric", motif = 12, q = 4 },
            { name = "Primal", motif = 13, q = 4 },
            { name = "Daedric", motif = 14, q = 4 },
            { name = "Dwarven", motif = 15, q = 4 },
            { name = "Glass", motif = 16, q = 4 },
            { name = "Xivkyn", motif = 17, q = 4 },
            { name = "Akaviri", motif = 18, q = 4 },
            { name = "Mercenary", motif = 19, q = 4 },
            { name = "Yokudan", motif = 20, q = 4 },
            { name = "Ancient Orc", motif = 21, q = 4 },
            { name = "Trinimac", motif = 22, q = 4 },
            { name = "Malacath", motif = 23, q = 4 },
            { name = "Outlaw", motif = 24, q = 4 },
            { name = "Aldmeri", motif = 25, q = 4 },
            { name = "Daggerfall", motif = 26, q = 4 },
            { name = "Ebonheart", motif = 27, q = 4 },
            { name = "Ra Gada", motif = 28, q = 4 },
            { name = "Soul Shriven", motif = 29, q = 3 },
            { name = "Morag Tong", motif = 30, q = 4 },
            { name = "Skinchanger", motif = 31, q = 4 },
            { name = "Abah's Watch", motif = 32, q = 4 },
            { name = "Thieves Guild", motif = 33, q = 4 },
            { name = "Assassins League", motif = 34, q = 4 },
            { name = "Dro-m'Athra", motif = 35, q = 4 },
            { name = "Dark Brotherhood", motif = 36, q = 4 },
            { name = "Ebony", motif = 37, q = 3 },
            { name = "Draugr", motif = 38, q = 4 },
            { name = "Minotaur", motif = 39, q = 4 },
            { name = "Order of the Hour", motif = 40, q = 4 },
            { name = "Celestial", motif = 41, q = 4 },
            { name = "Hollowjack", motif = 42, q = 4 },
            { name = "Grim Harlequin", motif = 43, q = 3 },
            { name = "Silken Ring", motif = 44, q = 4 },
            { name = "Mazzatun", motif = 45, q = 4 },
            { name = "Frostcaster", motif = 46, q = 3 },
            { name = "Buoyant Armiger", motif = 47, q = 4 },
            { name = "Ashlander", motif = 48, q = 4 },
            { name = "Militant Ordinator", motif = 49, q = 4 },
            { name = "Telvanni", motif = 50, q = 4 },
            { name = "Hlaalu", motif = 51, q = 4 },
            { name = "Redoran", motif = 52, q = 4 },
            { name = "Tsaesci", motif = 53, q = 3 },
            { name = "Bloodforge", motif = 54, q = 4 },
            { name = "Dreadhorn", motif = 55, q = 4 },
            { name = "Apostle", motif = 56, q = 4 },
            { name = "Ebonshadow", motif = 57, q = 4 },
            { name = "Fang Lair", motif = 58, q = 4 },
            { name = "Scalecaller", motif = 59, q = 4 },
            { name = "Worm Cult", motif = 60, q = 4 },
            { name = "Psijic Order", motif = 61, q = 4 },
            { name = "Sapiarch", motif = 62, q = 4 },
            { name = "Dremora", motif = 63, q = 4 },
            { name = "Pyandonean", motif = 64, q = 4 },
            { name = "Huntsman", motif = 65, q = 4 },
            { name = "Silver Dawn", motif = 66, q = 4 },
            { name = "Welkynar", motif = 67, q = 4 },
            { name = "Honor Guard", motif = 68, q = 4 },
            { name = "Dead-Water", motif = 69, q = 4 },
            { name = "Elder Argonian", motif = 70, q = 4 },
            { name = "Coldsnap Goblin", motif = 71, q = 4 },
            { name = "Meridian", motif = 72, q = 4 },
            { name = "Anequina", motif = 73, q = 4 },
            { name = "Pellitine", motif = 74, q = 4 },
            { name = "Sunspire", motif = 75, q = 4 },
            { name = "Dragonguard", motif = 76, q = 4 },
            { name = "Stags of Z'en", motif = 77, q = 4 },
            { name = "Moongrave Fane", motif = 78, q = 4 },
            { name = "Refabricated", motif = 79, q = 4 },
            { name = "Shield of Senchal", motif = 80, q = 4 },
            { name = "New Moon Priest", motif = 81, q = 4 },
            { name = "Icereach Coven", motif = 82, q = 4 },
            { name = "Pyre Watch", motif = 83, q = 4 },
            { name = "Blackreach Vanguard", motif = 84, q = 4 },
            { name = "Greymoor", motif = 85, q = 4 },
            { name = "Sea Giant", motif = 86, q = 4 },
            { name = "Ancestral Nord", motif = 87, q = 4 },
            { name = "Ancestral Orc", motif = 88, q = 4 },
            { name = "Ancestral High Elf", motif = 89, q = 4 },
            { name = "Thorn Legion", motif = 90, q = 4 },
            { name = "Hazardous Alchemy", motif = 91, q = 4 },
            { name = "Ancestral Akaviri", motif = 92, q = 4 },
            { name = "Ancestral Breton", motif = 93, q = 4 },
            { name = "Ancestral Reach", motif = 94, q = 4 },
            { name = "Nighthollow", motif = 95, q = 4 },
            { name = "Arkthzand Armory", motif = 96, q = 4 },
            { name = "Wayward Guardian", motif = 97, q = 4 },
            { name = "House Hexos", motif = 98, q = 4 },
            { name = "Waking Flame", motif = 99, q = 4 },
            { name = "True-Sworn", motif = 100, q = 4 },
            { name = "Ivory Brigade", motif = 101, q = 4 },
            { name = "Sul-Xan", motif = 102, q = 4 },
            { name = "Black Fin Legion", motif = 103, q = 4 },
            { name = "Ancient Daedric", motif = 104, q = 4 },
            { name = "Crimson Oath", motif = 105, q = 4 },
            { name = "Silver Rose", motif = 106, q = 4 },
            { name = "Annihilarch's Chosen", motif = 107, q = 4 },
            { name = "Fargrave Guardian", motif = 108, q = 4 },
            -- { name = "UNRELEASED", motif = 109, q = 4 },
            { name = "Dreadsails", motif = 110, q = 4 },
            { name = "Ascendant Order", motif = 111, q = 4 },
            { name = "Syrabanic Marine", motif = 112, q = 4 },
            { name = "Steadfast Society", motif = 113, q = 4 },
            { name = "Systres Guardian", motif = 114, q = 4 },
            { name = "Y'ffre's Will", motif = 115, q = 4 },
            { name = "Drowned Mariner", motif = 116, q = 4 },
            { name = "Firesong", motif = 117, q = 4 },
            { name = "House Mornard", motif = 118, q = 4 },
            { name = "Blessed Inheritor", motif = 119, q = 4 },
            { name = "Scribes of Mora", motif = 120, q = 4 },
            { name = "Clan Dreamcarver", motif = 121, q = 4 },
            { name = "Dead Keeper", motif = 122, q = 4 },
            { name = "Kindred's Concord", motif = 123, q = 4 },
            { name = "The Recollection", motif = 124, q = 4 },
            { name = "Blind Path Cultist", motif = 125, q = 4 },
            { name = "Shardborn", motif = 126, q = 4 },
            { name = "West Weald Legion", motif = 127, q = 4 },
            { name = "Lucent Sentinel", motif = 128, q = 4 },
            { name = "Hircine Bloodhunter", motif = 129, q = 3 },
            { name = "Exile's Revenge", motif = 130, q = 4 },
            { name = "Militant Monk", motif = 131, q = 4 },
            { name = "Stirk Fellowship", motif = 132, q = 4 },
            { name = "Coldharbour Dominator", motif = 133, q = 4 },
            { name = "Tide-Born", motif = 134, q = 4 },
            { name = "Black Soul Gem", motif = 135, q = 4 },
            { name = "Voskrona Guardian", motif = 136, q = 4 },
            { name = "Koldane Cartel", motif = 137, q = 4 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
