CollectThemAllData_Events_JestersFestival = {
    name = "Jester's Festival",
    source = "Events",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Sovereign Sow", fragments = { "Sovereign Brush", "Sovereign Fodder", "Sovereign Lead", "Sovereign Libations", "Sovereign Oil", "Sovereign Sash", "Sovereign Tiara" } },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "The Pie of Misrule" },
            { name = "Cherry Blossom Branch" },
            { name = "Jester's Scintillator" },
            { name = "Playful Prankster's Surprise Box", info = "Combine 5 Mirth Shards" },
            { name = "Cadwell's Surprise Box", info = "Combine 5 Revelry Shards" },
            { name = "Festive Noise Maker", achievement = "Festive Noise Maker" },
            { name = "Jester's Festival Joke Popper", achievement = "Jester's Festival Joke Popper" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "One Bad Knight", armorOnly = true },

            { name = "Broom" },
            { name = "Bucket" },
            { name = "Jester's Aldmeri Mimicry Helmet" },
            { name = "Jester's Aldmeri Mimicry Jack" },
            { name = "Jester's Covenant Mimicry Helmet" },
            { name = "Jester's Covenant Mimicry Jack" },
            { name = "Jester's Pact Mimicry Helmet" },
            { name = "Jester's Pact Mimicry Jack" },

            { name = "Jester's Seeker Suit", armorOnly = true },
            { name = "Regal Regalia", armorOnly = true },
            { name = "Second Seed Raiment", armorOnly = true },

            { name = "Cadwell's \"Axe\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Battle Axe\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Bow\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Dagger\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Greatsword\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Mace\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Maul\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Shield\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Staff\"", info = "Cadwell's Kitchen Style Pack" },
            { name = "Cadwell's \"Sword\"", info = "Cadwell's Kitchen Style Pack" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {
            { name = "Jester's Daedroth Suit", info = "Combine 10 Scrap of Minstrel's Cloth" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {
            { name = "Crown of Misrule" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Jester's Deadly Headband" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
