CollectThemAllData_Events_PanTamrielCelebration = {
    name = "Pan-Tamriel Celebration",
    source = "Events",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Gloam Gryphon Fledgling" },
            { name = "Microtized Verminous Fabricant", info = "Combine 10 Sealed Fabrication Materials" },

            { name = "Aurora Firepot Spider" }, -- Firepot, Front Legs, Rear Legs
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Thetys Ramarys's Bait Kit" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Lion Guard Captain", armorOnly = true },
            { name = "Apocrypha Expedition", armorOnly = true },
            { name = "Oaken Order", armorOnly = true },
            { name = "Y'ffre's Fallen-Wood", armorOnly = true },
            { name = "Saarthal Scholar", armorOnly = true },
            { name = "Sovngarde Stalwart", armorOnly = true },
            { name = "Claw-Dance Acolyte", armorOnly = true },
            { name = "Ja'zennji Siir", armorOnly = true },
            { name = "Evergloam Champion", weaponOnly = true },
            { name = "Doctrine Ordinator", armorOnly = true },
            { name = "Snowhawk Mage", armorOnly = true },
            { name = "Barbas Helmet Replica" },
            { name = "Staff of Worms Replica" },
            { name = "Sunna'rah Replica" },
            { name = "Trueflame Sword Replica" },
            { name = "Ul'vor Staff Replica" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {
            { name = "Slag Town Diver" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
