CollectThemAllData_Events_AnniversaryJubilee = {
    name = "Anniversary Jubilee",
    source = "Events",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Jubilee Steed", achievement = "Jubilee Confetti Conveyor" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Aurora Firepot Spider" }, -- Firepot, Front Legs, Rear Legs
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {
            { name = "Jubilee Cake 2016" },
            { name = "Jubilee Cake 2017" },
            { name = "Jubilee Cake 2018" },
            { name = "Jubilee Cake 2019" },
            { name = "Jubilee Cake 2020" },
            { name = "Jubilee Cake 2021" },
            { name = "Jubilee Cake 2022" },
            { name = "Jubilee Cake 2023" },
            { name = "Jubilee Cake 2024" },
            { name = "Jubilee Cake 2025" },
            { name = "Jubilee Cake 2026" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Nokvroz's Greatsword Replica" },
            { name = "Barbas Helmet Replica" },
            { name = "Staff of Worms Replica" },
            { name = "Sunna'rah Replica" },
            { name = "Trueflame Sword Replica" },
            { name = "Ul'vor Staff Replica" },

            { name = "Dapper Daredevil", armorOnly = true },
            { name = "Abnur Tharn's" },
            { name = "Jephrine Paladin" },
            { name = "Lyris Titanborn's" },
            { name = "Prophet's" },
            { name = "Sai Sahan's" },
            { name = "Bonemold", armorOnly = true },
            { name = "Earthbone Ayleid", armorOnly = true },
            { name = "Imperial Champion", weaponOnly = true },
            { name = "Saberkeel Panoply", armorOnly = true },
            { name = "Worm Cult Hunter", armorOnly = true },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
