CollectThemAllData_Events_WhitestrakesMayhem = {
    name = "Whitestrake's Mayhem",
    source = "Events",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Covenant Breton Terrier" },
            { name = "Dominion Breton Terrier" },
            { name = "Pact Breton Terrier" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {
            { name = "Aldmeri Dominion Banner" },
            { name = "Daggerfall Covenant Banner" },
            { name = "Ebonheart Pact Banner" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Tava's Goshawk", armorOnly = true },
            { name = "Truth in Wisdom", armorOnly = true },
            { name = "Arkay Unending Cycle", armorOnly = true },
            { name = "Ayleid Lich", armorOnly = true },
            { name = "Dovah's Du'ul", armorOnly = true },
            { name = "Sancre Tor Sentry" },
            { name = "Legion Zero", armorOnly = true },
            { name = "Legion Zero Vigiles", armorOnly = true },
            { name = "Second Legion", armorOnly = true },
            { name = "Ebonsteel Knight", armorOnly = true },
            { name = "Black Drake Clanwrap", armorOnly = true },
            { name = "House Dufort Banneret", armorOnly = true },
            { name = "Gloamsedge", armorOnly = true },
            { name = "Tools of Domination", weaponOnly = true },
            
            { name = "Covenant Banner-Bearer Shield" },
            { name = "Covenant Banner-Bearer Staff" },
            { name = "Dominion Banner-Bearer Shield" },
            { name = "Dominion Banner-Bearer Staff" },
            { name = "Pact Banner-Bearer Shield" },
            { name = "Pact Banner-Bearer Staff" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {
            { name = "The Black Drake's Body Warpaint" },
            { name = "Battle-Scarred Body" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {
            { name = "The Black Drake's Face Warpaint" },
            { name = "Battle-Scarred Visage" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {
            { name = "Mayhem Victor's Laurel Wreath", achievement = "Star-Made Knight" }, -- TODO: we don't support other achievemnt conditions to display in info
        },
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
