--[[
File: Modules/CIM/ParametricScrollListTemplates.lua
Purpose: Base definitions for BetterUI Scroll Lists.
         Contains sound mappings and list constants used by list classes.
Author: BetterUI Team
Last Modified: 2026-01-26
]]

BETTERUI.CIM = BETTERUI.CIM or {}
BETTERUI.CIM.ListGlobals = BETTERUI.CIM.ListGlobals or {}
local LIST_GLOBALS = BETTERUI.CIM.ListGlobals

-- Tab bar movement types (extends ZO_PARAMETRIC_MOVEMENT_TYPES).
LIST_GLOBALS.TABBAR_MOVEMENT_TYPES = LIST_GLOBALS.TABBAR_MOVEMENT_TYPES or
{
    PAGE_FORWARD = ZO_PARAMETRIC_MOVEMENT_TYPES.LAST,
    PAGE_BACK = ZO_PARAMETRIC_MOVEMENT_TYPES.LAST + 1,
    PAGE_NAVIGATION_FAILED = ZO_PARAMETRIC_MOVEMENT_TYPES.LAST + 2,
}

-- Sound mappings for list navigation
LIST_GLOBALS.PARAMETRIC_SCROLL_MOVEMENT_SOUNDS = LIST_GLOBALS.PARAMETRIC_SCROLL_MOVEMENT_SOUNDS or
{
    [ZO_PARAMETRIC_MOVEMENT_TYPES.MOVE_NEXT] = SOUNDS.GAMEPAD_MENU_DOWN,
    [ZO_PARAMETRIC_MOVEMENT_TYPES.MOVE_PREVIOUS] = SOUNDS.GAMEPAD_MENU_UP,
    [ZO_PARAMETRIC_MOVEMENT_TYPES.JUMP_NEXT] = SOUNDS.GAMEPAD_MENU_JUMP_DOWN,
    [ZO_PARAMETRIC_MOVEMENT_TYPES.JUMP_PREVIOUS] = SOUNDS.GAMEPAD_MENU_JUMP_UP,
    [LIST_GLOBALS.TABBAR_MOVEMENT_TYPES.PAGE_FORWARD] = SOUNDS.GAMEPAD_PAGE_FORWARD,
    [LIST_GLOBALS.TABBAR_MOVEMENT_TYPES.PAGE_BACK] = SOUNDS.GAMEPAD_PAGE_BACK,
    [LIST_GLOBALS.TABBAR_MOVEMENT_TYPES.PAGE_NAVIGATION_FAILED] = SOUNDS.GAMEPAD_PAGE_NAVIGATION_FAILED,
}

LIST_GLOBALS.ORIENTATION = LIST_GLOBALS.ORIENTATION or {
    VERTICAL = true,
    HORIZONTAL = false,
}

LIST_GLOBALS.DEFAULT_GRADIENT_SIZE = LIST_GLOBALS.DEFAULT_GRADIENT_SIZE or {
    VERTICAL = 32,
    HORIZONTAL = 32,
}

--[[
Function: BETTERUI.GamepadParametricScrollListPlaySound
Description: Plays navigation sound for scroll list movement.
param: movementType (number) - The type of movement (next, prev, jump, etc.).
]]
function BETTERUI.GamepadParametricScrollListPlaySound(movementType)
    local soundId = LIST_GLOBALS.PARAMETRIC_SCROLL_MOVEMENT_SOUNDS[movementType]
    if soundId then
        PlaySound(soundId)
    end
end
