-- THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
-- L is a convenience table so we don't have to write ZO_CreateStringId a bunch of times
local L = {}

-- Undaunted Pledges. Maj al-Ragath's Pledges
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_01 = GetQuestName(5274) -- "Pledge: Darkshade Caverns I"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_02 = GetQuestName(5275) -- "Pledge: Darkshade II"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_03 = GetQuestName(5276) -- "Pledge: Elden Hollow I"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_04 = GetQuestName(5277) -- "Pledge: Elden Hollow II"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_05 = GetQuestName(5247) -- "Pledge: Fungal Grotto I"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_06 = GetQuestName(5248) -- "Pledge: Fungal Grotto II"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_07 = GetQuestName(5260) -- "Pledge: Spindleclutch I"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_08 = GetQuestName(5273) -- "Pledge: Spindleclutch II"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_09 = GetQuestName(5244) -- "Pledge: Banished Cells I"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_10 = GetQuestName(5246) -- "Pledge: Banished Cells II"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_11 = GetQuestName(5278) -- "Pledge: Wayrest Sewers I"
L.DQT_UNDAUNTED_PLEDGES_MAJ_AL_RAGATH_S_PLEDGES_12 = GetQuestName(5282) -- "Pledge: Wayrest Sewers II"

-- Undaunted Pledges. Glirion the Redbeard's Pledges
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_01 = GetQuestName(5288) -- "Pledge: Arx Corinium"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_02 = GetQuestName(5305) -- "Pledge: Blackheart Haven"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_03 = GetQuestName(5306) -- "Pledge: Blessed Crucible I"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_04 = GetQuestName(5290) -- "Pledge: City of Ash I"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_05 = GetQuestName(5381) -- "Pledge: City of Ash II"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_06 = GetQuestName(5283) -- "Pledge: Crypt of Hearts I"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_07 = GetQuestName(5284) -- "Pledge: Crypt of Hearts II"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_08 = GetQuestName(5291) -- "Pledge: Direfrost Keep I"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_09 = GetQuestName(5307) -- "Pledge: Selene's Web"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_10 = GetQuestName(5301) -- "Pledge: Tempest Island"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_11 = GetQuestName(5309) -- "Pledge: Vaults of Madness"
L.DQT_UNDAUNTED_PLEDGES_GLIRION_THE_REDBEARD_S_PLEDGES_12 = GetQuestName(5303) -- "Pledge: Volenfell"

-- Undaunted Pledges. Urgarlag Chief-bane's Pledges
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_01 = GetQuestName(6053) -- "Pledge: Bloodroot Forge"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_02 = GetQuestName(5780) -- "Pledge: Cradle of Shadows"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_03 = GetQuestName(6054) -- "Pledge: Falkreath Hold"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_04 = GetQuestName(6155) -- "Pledge: Fang Lair"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_05 = GetQuestName(5382) -- "Pledge: Imperial City Prison"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_06 = GetQuestName(6189) -- "Pledge: March of Sacrifices"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_07 = GetQuestName(6187) -- "Pledge: Moon Hunter Keep"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_08 = GetQuestName(5636) -- "Pledge: Ruins of Mazzatun"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_09 = GetQuestName(6154) -- "Pledge: Scalecaller Peak"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_10 = GetQuestName(5431) -- "Pledge: White-Gold Tower"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_11 = GetQuestName(6250) -- "Pledge: Frostvault"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_12 = GetQuestName(6252) -- "Pledge: Depths of Malatar"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_13 = GetQuestName(6352) -- "Pledge: Lair of Maarselok"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_14 = GetQuestName(6350) -- "Pledge: Moongrave Fane"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_15 = GetQuestName(6415) -- "Pledge: Icereach"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_16 = GetQuestName(6417) -- "Pledge: Unhallowed Grave"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_17 = GetQuestName(6508) -- "Pledge: Castle Thorn"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_18 = GetQuestName(6506) -- "Pledge: Stone Garden"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_19 = GetQuestName(6577) -- "Pledge: Black Drake Villa"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_20 = GetQuestName(6579) -- "Pledge: The Cauldron"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_21 = GetQuestName(6684) -- "Pledge: Red Petal Bastion"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_22 = GetQuestName(6686) -- "Pledge: The Dread Cellar"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_23 = GetQuestName(6741) -- "Pledge: Coral Aerie"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_24 = GetQuestName(6743) -- "Pledge: Shipwright's Regret"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_25 = GetQuestName(6836) -- "Pledge: Earthen Root Enclave"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_26 = GetQuestName(6838) -- "Pledge: Graven Deep"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_27 = GetQuestName(6897) -- "Pledge: Bal Sunnar"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_28 = GetQuestName(7028) -- "Pledge: Scrivener's Hall"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_29 = GetQuestName(7106) -- "Pledge: Oathsworn Pit"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_30 = GetQuestName(7156) -- "Pledge: Bedlam Veil"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_31 = GetQuestName(7236) -- "Pledge: Exiled Redoubt"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_32 = GetQuestName(7238) -- "Pledge: Lep Seclusa"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_33 = GetQuestName(7321) -- "Pledge: Naj-Caldeesh"
L.DQT_UNDAUNTED_PLEDGES_URGARLAG_CHIEF_BANE_S_PLEDGES_34 = GetQuestName(7324) -- "Pledge: Black Gem Foundry"

-- Guild Daily Quests. Fighters Guild Daily Quests
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_01 = GetQuestName(5786) -- "Dark Anchors in Alik'r Desert"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_02 = GetQuestName(5793) -- "Dark Anchors in Auridon"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_03 = GetQuestName(5787) -- "Dark Anchors in Bangkorai"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_04 = GetQuestName(5789) -- "Dark Anchors in Deshaan"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_05 = GetQuestName(5791) -- "Dark Anchors in Eastmarch"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_06 = GetQuestName(5833) -- "Dark Anchors in Glenumbra"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_07 = GetQuestName(5794) -- "Dark Anchors in Grahtwood"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_08 = GetQuestName(5796) -- "Dark Anchors in Greenshade"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_09 = GetQuestName(5795) -- "Dark Anchors in Malabal Tor"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_10 = GetQuestName(5797) -- "Dark Anchors in Reaper's March"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_11 = GetQuestName(5785) -- "Dark Anchors in Rivenspire"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_12 = GetQuestName(5790) -- "Dark Anchors in Shadowfen"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_13 = GetQuestName(5788) -- "Dark Anchors in Stonefalls"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_14 = GetQuestName(5784) -- "Dark Anchors in Stormhaven"
L.DQT_GUILD_DAILY_QUESTS_FIGHTERS_GUILD_DAILY_QUESTS_15 = GetQuestName(5792) -- "Dark Anchors in the Rift"

-- Guild Daily Quests. Mages Guild Daily Quests
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_01 = GetQuestName(5814) -- "Madness in Alik'r Desert"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_02 = GetQuestName(5816) -- "Madness in Auridon"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_03 = GetQuestName(5818) -- "Madness in Bangkorai"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_04 = GetQuestName(5819) -- "Madness in Deshaan"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_05 = GetQuestName(5820) -- "Madness in Eastmarch"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_06 = GetQuestName(5822) -- "Madness in Glenumbra"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_07 = GetQuestName(5823) -- "Madness in Grahtwood"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_08 = GetQuestName(5824) -- "Madness in Greenshade"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_09 = GetQuestName(5825) -- "Madness in Malabal Tor"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_10 = GetQuestName(5826) -- "Madness in Reaper's March"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_11 = GetQuestName(5827) -- "Madness in Rivenspire"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_12 = GetQuestName(5828) -- "Madness in Shadowfen"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_13 = GetQuestName(5829) -- "Madness in Stonefalls"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_14 = GetQuestName(5830) -- "Madness in Stormhaven"
L.DQT_GUILD_DAILY_QUESTS_MAGES_GUILD_DAILY_QUESTS_15 = GetQuestName(5831) -- "Madness in the Rift"

-- Guild Daily Quests. Undaunted Daily Quests
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_01 = GetQuestName(5735) -- "Ancestor Wards in Deshaan"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_02 = GetQuestName(5733) -- "Ancient Armaments in Bangkorai"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_03 = GetQuestName(5738) -- "Ayleid Trinkets in Grahtwood"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_04 = GetQuestName(5853) -- "Culinary Justice in Greenshade"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_05 = GetQuestName(5800) -- "Cursed Baubles of Stormhaven"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_06 = GetQuestName(5808) -- "Darkness Blooms in Rivenspire"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_07 = GetQuestName(5737) -- "Dwarven Relics of Stonefalls"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_08 = GetQuestName(5778) -- "Give and Take in Shadowfen"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_09 = GetQuestName(5779) -- "Icy Intrigue in Eastmarch"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_10 = GetQuestName(5802) -- "Inflamed Pyres of the Rift"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_11 = GetQuestName(5744) -- "Mascot Theft in Reaper's March"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_12 = GetQuestName(5745) -- "Molten Pearls of Alik'r Desert"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_13 = GetQuestName(5739) -- "Red Rook Ransack in Glenumbra"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_14 = GetQuestName(5734) -- "The Spirit Trap in Malabal Tor"
L.DQT_GUILD_DAILY_QUESTS_UNDAUNTED_DAILY_QUESTS_15 = GetQuestName(5798) -- "Veiled Darkness in Auridon"

-- Crafting Writs. Consumables Crafting Writs
L.DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_01 = GetQuestName(6105) -- "Alchemist Writ"
L.DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_02 = GetQuestName(5407) -- "Enchanter Writ"
L.DQT_CRAFTING_WRITS_CONSUMABLES_CRAFTING_WRITS_03 = GetQuestName(5414) -- "Provisioner Writ"

-- Crafting Writs. Equipment Crafting Writs
L.DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_01 = GetQuestName(5377) -- "Blacksmith Writ"
L.DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_02 = GetQuestName(5374) -- "Clothier Writ"
L.DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_03 = GetQuestName(6228) -- "Jewelry Crafting Writ"
L.DQT_CRAFTING_WRITS_EQUIPMENT_CRAFTING_WRITS_04 = GetQuestName(5395) -- "Woodworker Writ"

-- Crafting Writs. Master Writs
L.DQT_CRAFTING_WRITS_MASTER_WRITS_01 = GetQuestName(5991) -- "A Masterful Concoction"
L.DQT_CRAFTING_WRITS_MASTER_WRITS_02 = GetQuestName(5977) -- "A Masterful Feast"
L.DQT_CRAFTING_WRITS_MASTER_WRITS_03 = GetQuestName(6017) -- "A Masterful Glyph"
L.DQT_CRAFTING_WRITS_MASTER_WRITS_04 = GetQuestName(6022) -- "Masterful Leatherwear"
L.DQT_CRAFTING_WRITS_MASTER_WRITS_05 = GetQuestName(6018) -- "A Masterful Plate"
L.DQT_CRAFTING_WRITS_MASTER_WRITS_06 = GetQuestName(6020) -- "A Masterful Shield"
L.DQT_CRAFTING_WRITS_MASTER_WRITS_07 = GetQuestName(6021) -- "Masterful Tailoring"
L.DQT_CRAFTING_WRITS_MASTER_WRITS_08 = GetQuestName(6452) -- "Masterful Jewelry"
L.DQT_CRAFTING_WRITS_MASTER_WRITS_09 = GetQuestName(5972) -- "A Masterful Weapon"
L.DQT_CRAFTING_WRITS_MASTER_WRITS_10 = GetQuestName(5975) -- "A Masterful Weapon"

-- Craglorn Quests. Lower Craglorn
L.DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_01 = GetQuestName(5756) -- "Critical Mass"
L.DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_02 = GetQuestName(5750) -- "The Fallen City of Shada"
L.DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_03 = GetQuestName(5762) -- "The Reason We Fight"
L.DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_04 = GetQuestName(5749) -- "The Seeker's Archive"
L.DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_05 = GetQuestName(5755) -- "Supreme Power"
L.DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_06 = GetQuestName(5751) -- "The Trials of Rahni'Za"
L.DQT_CRAGLORN_QUESTS_LOWER_CRAGLORN_07 = GetQuestName(5754) -- "Waters Run Foul"

-- Craglorn Quests. Upper Craglorn
L.DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_01 = GetQuestName(5767) -- "The Blood of Nirn"
L.DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_02 = GetQuestName(5777) -- "The Gray Passage"
L.DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_03 = GetQuestName(5766) -- "Iron and Scales"
L.DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_04 = GetQuestName(5770) -- "Souls of the Betrayed"
L.DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_05 = GetQuestName(5765) -- "Taken Alive"
L.DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_06 = GetQuestName(5764) -- "The Truer Fangs"
L.DQT_CRAGLORN_QUESTS_UPPER_CRAGLORN_07 = GetQuestName(5772) -- "Uncaged"

-- Black Marsh. Cyrodilic Collections
L.DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_01 = GetQuestName(6263) -- "A Taste for Toxins"
L.DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_02 = GetQuestName(6255) -- "Anti-Venom Agitation"
L.DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_03 = GetQuestName(6257) -- "Bug Off!"
L.DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_04 = GetQuestName(6256) -- "Reeling in Recruits"
L.DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_05 = GetQuestName(6260) -- "Salty Meats"
L.DQT_BLACK_MARSH_CYRODILIC_COLLECTIONS_06 = GetQuestName(6261) -- "The Winds of Kyne"

-- Imperial City. Imperial City Quests
L.DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_01 = GetQuestName(5500) -- "Dousing the Fires of Industry"
L.DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_02 = GetQuestName(5498) -- "Historical Accuracy"
L.DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_03 = GetQuestName(5492) -- "The Lifeblood of an Empire"
L.DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_04 = GetQuestName(5495) -- "Priceless Treasures"
L.DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_05 = GetQuestName(5491) -- "Speaking For The Dead"
L.DQT_IMPERIAL_CITY_IMPERIAL_CITY_QUESTS_06 = GetQuestName(5501) -- "Watch Your Step"

-- Wrothgar Quests. Delve Dailies
L.DQT_WROTHGAR_QUESTS_DELVE_DAILIES_01 = GetQuestName(5507) -- "Breakfast of the Bizarre"
L.DQT_WROTHGAR_QUESTS_DELVE_DAILIES_02 = GetQuestName(5505) -- "Fire in the Hold"
L.DQT_WROTHGAR_QUESTS_DELVE_DAILIES_03 = GetQuestName(5515) -- "Free Spirits"
L.DQT_WROTHGAR_QUESTS_DELVE_DAILIES_04 = GetQuestName(5514) -- "Getting a Bellyful"
L.DQT_WROTHGAR_QUESTS_DELVE_DAILIES_05 = GetQuestName(5509) -- "Parts of the Whole"
L.DQT_WROTHGAR_QUESTS_DELVE_DAILIES_06 = GetQuestName(5504) -- "The Skin Trade"

-- Wrothgar Quests. Group Boss Dailies
L.DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_01 = GetQuestName(5522) -- "Heresy of Ignorance"
L.DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_02 = GetQuestName(5518) -- "Meat for the Masses"
L.DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_03 = GetQuestName(5521) -- "Nature's Bounty"
L.DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_04 = GetQuestName(5524) -- "Reeking of Foul Play"
L.DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_05 = GetQuestName(5519) -- "Scholarly Salvage"
L.DQT_WROTHGAR_QUESTS_GROUP_BOSS_DAILIES_06 = GetQuestName(5523) -- "Snow and Steam"

-- Thieves Guild Larceny Quests. Guild Jobs
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_01 = GetQuestName(5584) -- "The Covetous Countess"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_02 = GetQuestName(5647) -- "Crime Spree"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_03 = GetQuestName(5640) -- "Idle Hands"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_04 = GetQuestName(5642) -- "Plucking Fingers"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_GUILD_JOBS_05 = GetQuestName(5644) -- "Under Our Thumb"

-- Thieves Guild Larceny Quests. Rye's Reacquisitions
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_01 = GetQuestName(5586) -- "The Lost Pearls"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_02 = GetQuestName(5588) -- "Memories of Youth"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_03 = GetQuestName(5589) -- "The Sailor's Pipe"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_RYE_S_REACQUISITIONS_04 = GetQuestName(5587) -- "Thrall Cove"

-- Thieves Guild Larceny Quests. Heists
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_01 = GetQuestName(5536) -- "Heist: Deadhollow Halls"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_02 = GetQuestName(5575) -- "Heist: Glittering Grotto"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_03 = GetQuestName(5572) -- "Heist: The Hideaway"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_04 = GetQuestName(5577) -- "Heist: Secluded Sewers"
L.DQT_THIEVES_GUILD_LARCENY_QUESTS_HEISTS_05 = GetQuestName(5573) -- "Heist: Underground Sepulcher"

-- Gold Coast Quests. Bounties
L.DQT_GOLD_COAST_QUESTS_BOUNTIES_01 = GetQuestName(5603) -- "Buried Evil"
L.DQT_GOLD_COAST_QUESTS_BOUNTIES_02 = GetQuestName(5604) -- "The Common Good"
L.DQT_GOLD_COAST_QUESTS_BOUNTIES_03 = GetQuestName(5605) -- "Looming Shadows"
L.DQT_GOLD_COAST_QUESTS_BOUNTIES_04 = GetQuestName(5606) -- "The Roar of the Crowds"

-- Gold Coast Quests. Dark Brotherhood Contracts
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_01 = GetQuestName(5627) -- "Contract: Alik'r Desert"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_02 = GetQuestName(5693) -- "Contract: Alik'r Desert Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_03 = GetQuestName(5657) -- "Contract: Auridon"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_04 = GetQuestName(5694) -- "Contract: Auridon Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_05 = GetQuestName(5632) -- "Contract: Bangkorai"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_06 = GetQuestName(5696) -- "Contract: Bangkorai Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_07 = GetQuestName(5652) -- "Contract: Deshaan"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_08 = GetQuestName(5698) -- "Contract: Deshaan Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_09 = GetQuestName(5670) -- "Contract: Eastmarch"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_10 = GetQuestName(5699) -- "Contract: Eastmarch Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_11 = GetQuestName(5594) -- "Contract: Glenumbra"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_12 = GetQuestName(5700) -- "Contract: Glenumbra Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_13 = GetQuestName(5688) -- "Contract: Gold Coast Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_14 = GetQuestName(5672) -- "Contract: Grahtwood"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_15 = GetQuestName(5701) -- "Contract: Grahtwood Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_16 = GetQuestName(5677) -- "Contract: Greenshade"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_17 = GetQuestName(5703) -- "Contract: Greenshade Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_18 = GetQuestName(5665) -- "Contract: Malabal Tor"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_19 = GetQuestName(5704) -- "Contract: Malabal Tor Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_20 = GetQuestName(5680) -- "Contract: Reaper's March"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_21 = GetQuestName(5705) -- "Contract: Reaper's March Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_22 = GetQuestName(5626) -- "Contract: Rivenspire"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_23 = GetQuestName(5706) -- "Contract: Rivenspire Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_24 = GetQuestName(5684) -- "Contract: Shadowfen"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_25 = GetQuestName(5707) -- "Contract: Shadowfen Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_26 = GetQuestName(5690) -- "Contract: Stonefalls"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_27 = GetQuestName(5709) -- "Contract: Stonefalls Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_28 = GetQuestName(5621) -- "Contract: Stormhaven"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_29 = GetQuestName(5710) -- "Contract: Stormhaven Spree"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_30 = GetQuestName(5697) -- "Contract: The Rift"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_CONTRACTS_31 = GetQuestName(5711) -- "Contract: The Rift Spree"

-- Gold Coast Quests. Dark Brotherhood Sacraments
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_01 = GetQuestName(5720) -- "Sacrament: Smuggler's Den"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_02 = GetQuestName(5726) -- "Sacrament: Sewer Tenement"
L.DQT_GOLD_COAST_QUESTS_DARK_BROTHERHOOD_SACRAMENTS_03 = GetQuestName(5714) -- "Sacrament: Trader's Cove"

-- Vvardenfell Quests. Bounty
L.DQT_VVARDENFELL_QUESTS_BOUNTY_01 = GetQuestName(5916) -- "The Anxious Apprentice"
L.DQT_VVARDENFELL_QUESTS_BOUNTY_02 = GetQuestName(5918) -- "A Creeping Hunger"
L.DQT_VVARDENFELL_QUESTS_BOUNTY_03 = GetQuestName(5865) -- "Culling the Swarm"
L.DQT_VVARDENFELL_QUESTS_BOUNTY_04 = GetQuestName(5866) -- "Oxen Free"
L.DQT_VVARDENFELL_QUESTS_BOUNTY_05 = GetQuestName(5904) -- "Salothan's Curse"
L.DQT_VVARDENFELL_QUESTS_BOUNTY_06 = GetQuestName(5906) -- "Siren's Song"

-- Vvardenfell Quests. Exploratory
L.DQT_VVARDENFELL_QUESTS_EXPLORATORY_01 = GetQuestName(5956) -- "Daedric Disruptions"
L.DQT_VVARDENFELL_QUESTS_EXPLORATORY_02 = GetQuestName(5962) -- "Kwama Conundrum"
L.DQT_VVARDENFELL_QUESTS_EXPLORATORY_03 = GetQuestName(5961) -- "Planting Misinformation"
L.DQT_VVARDENFELL_QUESTS_EXPLORATORY_04 = GetQuestName(5934) -- "Tax Deduction"
L.DQT_VVARDENFELL_QUESTS_EXPLORATORY_05 = GetQuestName(5915) -- "Tribal Troubles"
L.DQT_VVARDENFELL_QUESTS_EXPLORATORY_06 = GetQuestName(5958) -- "Unsettled Syndicate"

-- Vvardenfell Quests. Hunt
L.DQT_VVARDENFELL_QUESTS_HUNT_01 = GetQuestName(5911) -- "Ash-Eater Hunt"
L.DQT_VVARDENFELL_QUESTS_HUNT_02 = GetQuestName(5907) -- "Great Zexxin Hunt"
L.DQT_VVARDENFELL_QUESTS_HUNT_03 = GetQuestName(5913) -- "King Razor-Tusk Hunt"
L.DQT_VVARDENFELL_QUESTS_HUNT_04 = GetQuestName(5910) -- "Mother Jagged-Claw Hunt"
L.DQT_VVARDENFELL_QUESTS_HUNT_05 = GetQuestName(5912) -- "Old Stomper Hunt"
L.DQT_VVARDENFELL_QUESTS_HUNT_06 = GetQuestName(5908) -- "Tarra-Suj Hunt"
L.DQT_VVARDENFELL_QUESTS_HUNT_07 = GetQuestName(5909) -- "Writhing Sveeth Hunt"

-- Vvardenfell Quests. Relics
L.DQT_VVARDENFELL_QUESTS_RELICS_01 = GetQuestName(5930) -- "Relics of Ashalmawia"
L.DQT_VVARDENFELL_QUESTS_RELICS_02 = GetQuestName(5927) -- "Relics of Ashurnabitashpi"
L.DQT_VVARDENFELL_QUESTS_RELICS_03 = GetQuestName(5925) -- "Relics of Assarnatamat"
L.DQT_VVARDENFELL_QUESTS_RELICS_04 = GetQuestName(5929) -- "Relics of Dushariran"
L.DQT_VVARDENFELL_QUESTS_RELICS_05 = GetQuestName(5928) -- "Relics of Ebernanit"
L.DQT_VVARDENFELL_QUESTS_RELICS_06 = GetQuestName(5926) -- "Relics of Maelkashishi"
L.DQT_VVARDENFELL_QUESTS_RELICS_07 = GetQuestName(5924) -- "Relics of Yasammidan"

-- Clockwork City Quests. Bounty
L.DQT_CLOCKWORK_CITY_QUESTS_BOUNTY_01 = GetQuestName(6077) -- "A Fine-Feathered Foe"
L.DQT_CLOCKWORK_CITY_QUESTS_BOUNTY_02 = GetQuestName(6076) -- "Inciting the Imperfect"

-- Clockwork City Quests. Exploratory
L.DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_01 = GetQuestName(6088) -- "Changing the Filters"
L.DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_02 = GetQuestName(6081) -- "Oiling the Fans"
L.DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_03 = GetQuestName(6089) -- "Replacing the Commutators"
L.DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_04 = GetQuestName(6079) -- "Again Into the Shadows"
L.DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_05 = GetQuestName(6080) -- "A Shadow Malfunction"
L.DQT_CLOCKWORK_CITY_QUESTS_EXPLORATORY_06 = GetQuestName(6073) -- "A Shadow Misplaced"

-- Clockwork City Quests. Tarnished
L.DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_01 = GetQuestName(6042) -- "A Bitter Pill"
L.DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_02 = GetQuestName(6038) -- "A Daily Grind"
L.DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_03 = GetQuestName(6040) -- "A Sticky Solution"
L.DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_04 = GetQuestName(6041) -- "Enchanted Accumulation"
L.DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_05 = GetQuestName(6037) -- "Fuel for our Fires"
L.DQT_CLOCKWORK_CITY_QUESTS_TARNISHED_06 = GetQuestName(6039) -- "Loose Strands"

-- Clockwork City Quests. Blackfeather Court
L.DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_01 = GetQuestName(6024) -- "Glitter and Gleam"
L.DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_02 = GetQuestName(6107) -- "A Matter of Leisure"
L.DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_03 = GetQuestName(6072) -- "A Matter of Respect"
L.DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_04 = GetQuestName(6106) -- "A Matter of Tributes"
L.DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_05 = GetQuestName(6071) -- "Morsels and Pecks"
L.DQT_CLOCKWORK_CITY_QUESTS_BLACKFEATHER_COURT_06 = GetQuestName(6070) -- "Nibbles and Bits"

-- Summerset Quests. Bounty
L.DQT_SUMMERSET_QUESTS_BOUNTY_01 = GetQuestName(6084) -- "The Abyssal Alchemist"
L.DQT_SUMMERSET_QUESTS_BOUNTY_02 = GetQuestName(6085) -- "Birds of a Feather"
L.DQT_SUMMERSET_QUESTS_BOUNTY_03 = GetQuestName(6086) -- "Never Forgotten"
L.DQT_SUMMERSET_QUESTS_BOUNTY_04 = GetQuestName(6087) -- "Run Aground"
L.DQT_SUMMERSET_QUESTS_BOUNTY_05 = GetQuestName(6082) -- "The Sickening Sea"
L.DQT_SUMMERSET_QUESTS_BOUNTY_06 = GetQuestName(6083) -- "Taming the Wild"

-- Summerset Quests. Exploratory
L.DQT_SUMMERSET_QUESTS_EXPLORATORY_01 = GetQuestName(6159) -- "Culling Serpents"
L.DQT_SUMMERSET_QUESTS_EXPLORATORY_02 = GetQuestName(6152) -- "Pilgrimage's End"
L.DQT_SUMMERSET_QUESTS_EXPLORATORY_03 = GetQuestName(6158) -- "Relic Runaround"
L.DQT_SUMMERSET_QUESTS_EXPLORATORY_04 = GetQuestName(6157) -- "A Rose's Beauty"
L.DQT_SUMMERSET_QUESTS_EXPLORATORY_05 = GetQuestName(6156) -- "Snuffing Out the Light"
L.DQT_SUMMERSET_QUESTS_EXPLORATORY_06 = GetQuestName(6160) -- "Struck from Memory"

-- Summerset Quests. Abyssal Geysers
L.DQT_SUMMERSET_QUESTS_ABYSSAL_GEYSERS_01 = GetQuestName(6202) -- "Sinking Summerset"

-- Murkmire Quests. Bounty
L.DQT_MURKMIRE_QUESTS_BOUNTY_01 = GetQuestName(6233) -- "Grave Circumstances"
L.DQT_MURKMIRE_QUESTS_BOUNTY_02 = GetQuestName(6236) -- "Grave Expectations"
L.DQT_MURKMIRE_QUESTS_BOUNTY_03 = GetQuestName(6237) -- "Grave Mementos"
L.DQT_MURKMIRE_QUESTS_BOUNTY_04 = GetQuestName(6235) -- "Old Baubles"
L.DQT_MURKMIRE_QUESTS_BOUNTY_05 = GetQuestName(6238) -- "Old Enemies"
L.DQT_MURKMIRE_QUESTS_BOUNTY_06 = GetQuestName(6234) -- "Old Growth"

-- Murkmire Quests. Exploratory
L.DQT_MURKMIRE_QUESTS_EXPLORATORY_01 = GetQuestName(6253) -- "Antique Armor"
L.DQT_MURKMIRE_QUESTS_EXPLORATORY_02 = GetQuestName(6268) -- "Grave Subject Matter"
L.DQT_MURKMIRE_QUESTS_EXPLORATORY_03 = GetQuestName(6248) -- "Old Scrolls"
L.DQT_MURKMIRE_QUESTS_EXPLORATORY_04 = GetQuestName(6264) -- "Sacred Candles"
L.DQT_MURKMIRE_QUESTS_EXPLORATORY_05 = GetQuestName(6267) -- "Tools of Slaughter"
L.DQT_MURKMIRE_QUESTS_EXPLORATORY_06 = GetQuestName(6247) -- "The Weight of Words"

-- Murkmire Quests. Root-Whisper
L.DQT_MURKMIRE_QUESTS_ROOT_WHISPER_01 = GetQuestName(6286) -- "Aloe That Heals"
L.DQT_MURKMIRE_QUESTS_ROOT_WHISPER_02 = GetQuestName(6288) -- "Envoys Who Cower"
L.DQT_MURKMIRE_QUESTS_ROOT_WHISPER_03 = GetQuestName(6290) -- "Leather That Protects"
L.DQT_MURKMIRE_QUESTS_ROOT_WHISPER_04 = GetQuestName(6287) -- "Mushrooms That Nourish"
L.DQT_MURKMIRE_QUESTS_ROOT_WHISPER_05 = GetQuestName(6289) -- "Offerings That Hide"

-- Cyrodiil. Cyrodiil Settlement Quests. Bruma
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_01 = GetQuestName(4561) -- "Dangerously Low"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_02 = GetQuestName(4563) -- "Capstone Caps"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_03 = GetQuestName(4564) -- "Lost and Alone"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_04 = GetQuestName(4568) -- "The Standing Stones"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_05 = GetQuestName(4569) -- "Enemy Reinforcements"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_06 = GetQuestName(4570) -- "Know thy Enemy"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_07 = GetQuestName(4572) -- "Requests for Aid"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_08 = GetQuestName(4579) -- "Bring Down the Magister"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_09 = GetQuestName(4581) -- "The Unseen"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_BRUMA_10 = GetQuestName(4591) -- "Timely Intervention"

-- Cyrodiil. Cyrodiil Settlement Quests. Cheydinhal
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_01 = GetQuestName(4421) -- "Thorns in Our Side"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_02 = GetQuestName(4422) -- "Spice"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_03 = GetQuestName(4425) -- "Prisoners of War"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_04 = GetQuestName(4430) -- "The Burned Estate"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_05 = GetQuestName(4433) -- "Ayleid Treasure"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_06 = GetQuestName(4417) -- "Bloodied Waters"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_07 = GetQuestName(4420) -- "Keepsake"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_08 = GetQuestName(4424) -- "A Debt Come Due"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_09 = GetQuestName(4426) -- "Stacking the Odds"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHEYDINHAL_10 = GetQuestName(4434) -- "For Piety's Sake"

-- Cyrodiil. Cyrodiil Settlement Quests. Chorrol and Weynon Priory
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_01 = GetQuestName(4226) -- "Death to the Black Daggers!"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_02 = GetQuestName(4247) -- "Guard Work is Never Done"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_03 = GetQuestName(4263) -- "Field of Fire"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_04 = GetQuestName(4265) -- "The High Cost of Lying"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_05 = GetQuestName(4270) -- "The Cache"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_06 = GetQuestName(4224) -- "Abominations"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_07 = GetQuestName(4228) -- "Claw of Akatosh"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_08 = GetQuestName(4238) -- "Overdue Supplies"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_09 = GetQuestName(4242) -- "The Lich"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CHORROL_AND_WEYNON_PRIORY_10 = GetQuestName(4244) -- "Black Dagger Supplies"

-- Cyrodiil. Cyrodiil Settlement Quests. Cropsford
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_01 = GetQuestName(4505) -- "Seeds of Hope"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_02 = GetQuestName(4507) -- "Offerings to Zenithar"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_03 = GetQuestName(4509) -- "Harvest Time"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_04 = GetQuestName(4512) -- "The Dead of Culotte"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_05 = GetQuestName(4517) -- "Crown Point"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_06 = GetQuestName(4520) -- "Bloody Hand Spies!"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_07 = GetQuestName(4522) -- "The Hedoran Estate"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_08 = GetQuestName(4527) -- "Securing Knowledge"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_CROPSFORD_09 = GetQuestName(4540) -- "Timberscar Troubles"

-- Cyrodiil. Cyrodiil Settlement Quests. Vlastarus
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_01 = GetQuestName(4048) -- "The Direct Approach"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_02 = GetQuestName(4052) -- "Death to the Crone"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_03 = GetQuestName(4065) -- "An Evil Presence"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_04 = GetQuestName(4066) -- "Bear Essentials"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_05 = GetQuestName(4068) -- "Mementos"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_06 = GetQuestName(4072) -- "Rock Bone Diplomacy"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_07 = GetQuestName(4073) -- "Stolen Banner"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_08 = GetQuestName(4074) -- "For a Friend"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_09 = GetQuestName(4079) -- "Essence of Flame"
L.DQT_CYRODIIL_CYRODIIL_SETTLEMENT_QUESTS_VLASTARUS_10 = GetQuestName(4081) -- "Silver Scales"

-- Cyrodiil. Fighters Guild Bounty Quests
L.DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_01 = GetQuestName(4877) -- "Bounty: Black Daggers"
L.DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_02 = GetQuestName(4880) -- "Bounty: Goblins"
L.DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_03 = GetQuestName(4878) -- "Bounty: Gray Vipers"
L.DQT_CYRODIIL_FIGHTERS_GUILD_BOUNTY_QUESTS_04 = GetQuestName(4879) -- "Bounty: Shadowed Path"

-- Cyrodiil. PvP Quests. Battle Missions
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_01 = GetQuestName(3206) -- "Capture Alessia Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_02 = GetQuestName(3244) -- "Capture Alessia Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_03 = GetQuestName(3262) -- "Capture Alessia Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_04 = GetQuestName(3198) -- "Capture Aleswell Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_05 = GetQuestName(3236) -- "Capture Aleswell Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_06 = GetQuestName(3254) -- "Capture Aleswell Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_07 = GetQuestName(3201) -- "Capture Arrius Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_08 = GetQuestName(3239) -- "Capture Arrius Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_09 = GetQuestName(3257) -- "Capture Arrius Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_10 = GetQuestName(3197) -- "Capture Ash Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_11 = GetQuestName(3234) -- "Capture Ash Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_12 = GetQuestName(3253) -- "Capture Ash Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_13 = GetQuestName(3210) -- "Capture Black Boot Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_14 = GetQuestName(3248) -- "Capture Black Boot Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_15 = GetQuestName(3268) -- "Capture Black Boot Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_16 = GetQuestName(2970) -- "Capture Bloodmayne Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_17 = GetQuestName(3249) -- "Capture Bloodmayne Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_18 = GetQuestName(3269) -- "Capture Bloodmayne Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_19 = GetQuestName(3204) -- "Capture Blue Road Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_20 = GetQuestName(3242) -- "Capture Blue Road Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_21 = GetQuestName(3260) -- "Capture Blue Road Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_22 = GetQuestName(3209) -- "Capture Brindle Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_23 = GetQuestName(3247) -- "Capture Brindle Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_24 = GetQuestName(3266) -- "Capture Brindle Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_25 = GetQuestName(3200) -- "Capture Chalman Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_26 = GetQuestName(3238) -- "Capture Chalman Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_27 = GetQuestName(3256) -- "Capture Chalman Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_28 = GetQuestName(2958) -- "Capture Dragonclaw Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_29 = GetQuestName(3237) -- "Capture Dragonclaw Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_30 = GetQuestName(3255) -- "Capture Dragonclaw Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_31 = GetQuestName(3205) -- "Capture Drakelowe Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_32 = GetQuestName(3243) -- "Capture Drakelowe Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_33 = GetQuestName(2944) -- "Capture Drakelowe Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_34 = GetQuestName(3207) -- "Capture Faregyl Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_35 = GetQuestName(3245) -- "Capture Faregyl Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_36 = GetQuestName(3263) -- "Capture Faregyl Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_37 = GetQuestName(3203) -- "Capture Farragut Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_38 = GetQuestName(3241) -- "Capture Farragut Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_39 = GetQuestName(3259) -- "Capture Farragut Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_40 = GetQuestName(3196) -- "Capture Glademist Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_41 = GetQuestName(3233) -- "Capture Glademist Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_42 = GetQuestName(3252) -- "Capture Glademist Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_43 = GetQuestName(3202) -- "Capture Kingscrest Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_44 = GetQuestName(3240) -- "Capture Kingscrest Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_45 = GetQuestName(3258) -- "Capture Kingscrest Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_46 = GetQuestName(3102) -- "Capture Rayles Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_47 = GetQuestName(3140) -- "Capture Rayles Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_48 = GetQuestName(3251) -- "Capture Rayles Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_49 = GetQuestName(3208) -- "Capture Roebeck Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_50 = GetQuestName(3246) -- "Capture Roebeck Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_51 = GetQuestName(3265) -- "Capture Roebeck Mine"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_52 = GetQuestName(3194) -- "Capture Warden Farm"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_53 = GetQuestName(2972) -- "Capture Warden Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_BATTLE_MISSIONS_54 = GetQuestName(3250) -- "Capture Warden Mine"

-- Cyrodiil. PvP Quests. Bounty Missions
L.DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_01 = GetQuestName(5228) -- "Kill Enemy Dragonknights"
L.DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_02 = GetQuestName(5231) -- "Kill Enemy Nightblades"
L.DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_03 = GetQuestName(4349) -- "Kill Enemy Players"
L.DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_04 = GetQuestName(5234) -- "Kill Enemy Sorcerers"
L.DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_05 = GetQuestName(5222) -- "Kill Enemy Templars"
L.DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_06 = GetQuestName(6012) -- "Kill Enemy Wardens"
L.DQT_CYRODIIL_PVP_QUESTS_BOUNTY_MISSIONS_07 = GetQuestName(7066) -- "Kill Enemy Arcanists" -- Added by notnear

-- Cyrodiil. PvP Quests. Conquest Missions
L.DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_01 = GetQuestName(6207) -- "Capture All 3 Towns"
L.DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_02 = GetQuestName(6208) -- "Capture Any Nine Resources"
L.DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_03 = GetQuestName(6210) -- "Capture All Three Keeps"
L.DQT_CYRODIIL_PVP_QUESTS_CONQUEST_MISSIONS_04 = GetQuestName(6209) -- "Kill 40 Enemy Players"

-- Cyrodiil. PvP Quests. Scouting Missions
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_01 = GetQuestName(2816) -- "Scout Alessia Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_02 = GetQuestName(2893) -- "Scout Alessia Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_03 = GetQuestName(2870) -- "Scout Alessia Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_04 = GetQuestName(2808) -- "Scout Aleswell Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_05 = GetQuestName(2826) -- "Scout Aleswell Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_06 = GetQuestName(2862) -- "Scout Aleswell Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_07 = GetQuestName(2811) -- "Scout Arrius Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_08 = GetQuestName(2847) -- "Scout Arrius Keep"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_09 = GetQuestName(2829) -- "Scout Arrius Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_10 = GetQuestName(2865) -- "Scout Arrius Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_11 = GetQuestName(2807) -- "Scout Ash Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_12 = GetQuestName(2825) -- "Scout Ash Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_13 = GetQuestName(2861) -- "Scout Ash Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_14 = GetQuestName(2820) -- "Scout Black Boot Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_15 = GetQuestName(2838) -- "Scout Black Boot Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_16 = GetQuestName(2802) -- "Scout Black Boot Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_17 = GetQuestName(2821) -- "Scout Bloodmayne Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_18 = GetQuestName(2839) -- "Scout Bloodmayne Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_19 = GetQuestName(2803) -- "Scout Bloodmayne Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_20 = GetQuestName(2814) -- "Scout Blue Road Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_21 = GetQuestName(2850) -- "Scout Blue Road Keep"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_22 = GetQuestName(2832) -- "Scout Blue Road Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_23 = GetQuestName(2868) -- "Scout Blue Road Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_24 = GetQuestName(2819) -- "Scout Brindle Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_25 = GetQuestName(2837) -- "Scout Brindle Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_26 = GetQuestName(2801) -- "Scout Brindle Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_27 = GetQuestName(2852) -- "Scout Castle Alessia"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_28 = GetQuestName(2856) -- "Scout Castle Black Boot"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_29 = GetQuestName(2857) -- "Scout Castle Bloodmayne"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_30 = GetQuestName(2855) -- "Scout Castle Brindle"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_31 = GetQuestName(2853) -- "Scout Castle Faregyl"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_32 = GetQuestName(2854) -- "Scout Castle Roebeck"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_33 = GetQuestName(2810) -- "Scout Chalman Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_34 = GetQuestName(2846) -- "Scout Chalman Keep"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_35 = GetQuestName(2828) -- "Scout Chalman Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_36 = GetQuestName(2864) -- "Scout Chalman Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_37 = GetQuestName(2809) -- "Scout Dragonclaw Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_38 = GetQuestName(2827) -- "Scout Dragonclaw Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_39 = GetQuestName(2863) -- "Scout Dragonclaw Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_40 = GetQuestName(2815) -- "Scout Drakelowe Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_41 = GetQuestName(2851) -- "Scout Drakelowe Keep"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_42 = GetQuestName(2833) -- "Scout Drakelowe Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_43 = GetQuestName(2869) -- "Scout Drakelowe Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_44 = GetQuestName(2817) -- "Scout Faregyl Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_45 = GetQuestName(2835) -- "Scout Faregyl Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_46 = GetQuestName(2871) -- "Scout Faregyl Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_47 = GetQuestName(2813) -- "Scout Farragut Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_48 = GetQuestName(2849) -- "Scout Farragut Keep"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_49 = GetQuestName(2831) -- "Scout Farragut Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_50 = GetQuestName(2867) -- "Scout Farragut Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_51 = GetQuestName(2844) -- "Scout Fort Aleswell"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_52 = GetQuestName(2843) -- "Scout Fort Ash"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_53 = GetQuestName(2845) -- "Scout Fort Dragonclaw"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_54 = GetQuestName(2842) -- "Scout Fort Glademist"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_55 = GetQuestName(2841) -- "Scout Fort Rayles"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_56 = GetQuestName(2840) -- "Scout Fort Warden"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_57 = GetQuestName(2806) -- "Scout Glademist Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_58 = GetQuestName(2824) -- "Scout Glademist Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_59 = GetQuestName(2860) -- "Scout Glademist Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_60 = GetQuestName(2812) -- "Scout Kingscrest Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_61 = GetQuestName(2848) -- "Scout Kingscrest Keep"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_62 = GetQuestName(2830) -- "Scout Kingscrest Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_63 = GetQuestName(2866) -- "Scout Kingscrest Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_64 = GetQuestName(2805) -- "Scout Rayles Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_65 = GetQuestName(2823) -- "Scout Rayles Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_66 = GetQuestName(2859) -- "Scout Rayles Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_67 = GetQuestName(2818) -- "Scout Roebeck Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_68 = GetQuestName(2836) -- "Scout Roebeck Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_69 = GetQuestName(2800) -- "Scout Roebeck Mine"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_70 = GetQuestName(2804) -- "Scout Warden Farm"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_71 = GetQuestName(2822) -- "Scout Warden Lumbermill"
L.DQT_CYRODIIL_PVP_QUESTS_SCOUTING_MISSIONS_72 = GetQuestName(2858) -- "Scout Warden Mine"

-- Cyrodiil. PvP Quests. Warfront Missions
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_01 = GetQuestName(2927) -- "Capture Castle Alessia"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_02 = GetQuestName(2931) -- "Capture Castle Black Boot"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_03 = GetQuestName(2932) -- "Capture Castle Bloodmayne"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_04 = GetQuestName(2930) -- "Capture Castle Brindle"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_05 = GetQuestName(2928) -- "Capture Castle Faregyl"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_06 = GetQuestName(2929) -- "Capture Castle Roebeck"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_07 = GetQuestName(2919) -- "Capture Fort Aleswell"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_08 = GetQuestName(2918) -- "Capture Fort Ash"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_09 = GetQuestName(2920) -- "Capture Fort Dragonclaw"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_10 = GetQuestName(2917) -- "Capture Fort Glademist"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_11 = GetQuestName(2916) -- "Capture Fort Rayles"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_12 = GetQuestName(2915) -- "Capture Fort Warden"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_13 = GetQuestName(2922) -- "Capture Arrius Keep"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_14 = GetQuestName(2925) -- "Capture Blue Road Keep"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_15 = GetQuestName(2921) -- "Capture Chalman Keep"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_16 = GetQuestName(2926) -- "Capture Drakelowe Keep"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_17 = GetQuestName(2924) -- "Capture Farragut Keep"
L.DQT_CYRODIIL_PVP_QUESTS_WARFRONT_MISSIONS_18 = GetQuestName(2923) -- "Capture Kingscrest Keep"

-- Cyrodiil. PvP Quests. Elder Scrolls Missions
L.DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_01 = GetQuestName(2661) -- "The Elder Scroll of Alma Ruma"
L.DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_02 = GetQuestName(2610) -- "The Elder Scroll of Altadoon"
L.DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_03 = GetQuestName(2640) -- "The Elder Scroll of Chim"
L.DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_04 = GetQuestName(2658) -- "The Elder Scroll of Ghartok"
L.DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_05 = GetQuestName(2656) -- "The Elder Scroll of Mnem"
L.DQT_CYRODIIL_PVP_QUESTS_ELDER_SCROLLS_MISSIONS_06 = GetQuestName(2660) -- "The Elder Scroll of Ni-Mohk"

-- Reaper's March. Hadran's Caravan Quests
L.DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_01 = GetQuestName(4668) -- "Lizard Racing"
L.DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_02 = GetQuestName(4669) -- "Spikeball"
L.DQT_REAPER_S_MARCH_HADRAN_S_CARAVAN_QUESTS_03 = GetQuestName(4670) -- "Troll Arena"

-- Event Quests. New Life Festival
L.DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_01 = GetQuestName(5845) -- "Castle Charm Challenge"
L.DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_02 = GetQuestName(5855) -- "Fish Boon Feast"
L.DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_03 = GetQuestName(5837) -- "Lava Foot Stomp"
L.DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_04 = GetQuestName(5838) -- "Mud Ball Merriment"
L.DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_05 = GetQuestName(5839) -- "Signal Fire Sprint"
L.DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_06 = GetQuestName(5811) -- "Snow Bear Plunge"
L.DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_07 = GetQuestName(5856) -- "Stonetooth Bash"
L.DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_08 = GetQuestName(5834) -- "The Trial of Five-Clawed Guile"
L.DQT_EVENT_QUESTS_NEW_LIFE_FESTIVAL_09 = GetQuestName(5852) -- "War Orphan's Sojourn"

-- Event Quests. Jester's Festival
L.DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_01 = GetQuestName(5937) -- "Royal Revelry"
L.DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_02 = GetQuestName(5931) -- "A Noble Guest"
L.DQT_EVENT_QUESTS_JESTER_S_FESTIVAL_03 = GetQuestName(5921) -- "Springtime Flair"

-- Weekly. Trials
L.DQT_WEEKLY_TRIALS_01 = GetQuestName(5087) -- "Assaulting the Citadel"
L.DQT_WEEKLY_TRIALS_02 = GetQuestName(5894) -- "Forging the Future"
L.DQT_WEEKLY_TRIALS_03 = GetQuestName(5352) -- "Into the Maw"
L.DQT_WEEKLY_TRIALS_04 = GetQuestName(5102) -- "The Mage's Tower"
L.DQT_WEEKLY_TRIALS_05 = GetQuestName(5171) -- "The Oldest Ghost"
L.DQT_WEEKLY_TRIALS_06 = GetQuestName(6090) -- "Saints' Mercy"
L.DQT_WEEKLY_TRIALS_07 = GetQuestName(6503) -- "The Fight for Kyne's Aegis"
L.DQT_WEEKLY_TRIALS_08 = GetQuestName(6654) -- "Of Stone and Steam"
L.DQT_WEEKLY_TRIALS_09 = GetQuestName(6353) -- "The Return of Alkosh"
L.DQT_WEEKLY_TRIALS_10 = GetQuestName(6192) -- "Woe of the Welkynars"

-- Northern Elsweyr Defense Force
L.DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_01 = GetQuestName(6318) -- "Dark Souls, Mighty Weapons"
L.DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_02 = GetQuestName(6346) -- "Dragon Lore: Icehammer's Vault"
L.DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_03 = GetQuestName(6347) -- "Dragon Lore: Shroud Hearth"
L.DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_04 = GetQuestName(6345) -- "Dragon Lore: Stormcrag Crypt"
L.DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_05 = GetQuestName(6342) -- "Goblin Demonstration"
L.DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_06 = GetQuestName(6344) -- "Lamia Demonstration"
L.DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_07 = GetQuestName(6343) -- "Lurcher Demonstration"
L.DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_08 = GetQuestName(6341) -- "Skeleton Demonstration"
L.DQT_NORTHERN_ELSWEYR_DEFENSE_FORCE_09 = GetQuestName(6329) -- "Spider Demonstration"

-- Northern Elsweyr Bounty Quests -- Modified by DarkPhalanx
L.DQT_ELSWEYR_QUESTS_BOUNTY_01 = GetQuestName(6381) -- "A Dastardly Duo"
L.DQT_ELSWEYR_QUESTS_BOUNTY_02 = GetQuestName(6377) -- "Sword of the Serpent"
L.DQT_ELSWEYR_QUESTS_BOUNTY_03 = GetQuestName(6382) -- "The Senche of Decay"
L.DQT_ELSWEYR_QUESTS_BOUNTY_04 = GetQuestName(6378) -- "The Traders' Terror"
L.DQT_ELSWEYR_QUESTS_BOUNTY_05 = GetQuestName(6379) -- "A Waking Nightmare"
L.DQT_ELSWEYR_QUESTS_BOUNTY_06 = GetQuestName(6380) -- "Another Day, Another Death"

-- Northern Elsweyr Exploratory Quests -- Modified by DarkPhalanx
L.DQT_ELSWEYR_QUESTS_EXPLORATORY_01 = GetQuestName(6356) -- "Dousing the Daedric Flame"
L.DQT_ELSWEYR_QUESTS_EXPLORATORY_02 = GetQuestName(6360) -- "Rifling Through Ruins"
L.DQT_ELSWEYR_QUESTS_EXPLORATORY_03 = GetQuestName(6361) -- "The Hungry Cat's Favor"
L.DQT_ELSWEYR_QUESTS_EXPLORATORY_04 = GetQuestName(6362) -- "The Serpent's Stampede"
L.DQT_ELSWEYR_QUESTS_EXPLORATORY_05 = GetQuestName(6363) -- "Tangled Tea Leaves"
L.DQT_ELSWEYR_QUESTS_EXPLORATORY_06 = GetQuestName(6359) -- "Wisdom in the Winds"

-- Northern Elsweyr Dragon World Events -- Added by DarkPhalanx
L.DQT_ELSWEYR_QUESTS_DRAGONHUNT_01 = GetQuestName(6384) -- "Dragon Hunt"

-- Southern Elsweyr Bounty Quest -- Added by DarkPhalanx
L.DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_01 = GetQuestName(6425) -- "Fletching Fetching"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_02 = GetQuestName(6422) -- "A Rogue and His Rice"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_03 = GetQuestName(6423) -- "Dust Smote"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_04 = GetQuestName(6376) -- "Goutfang Pariah"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_05 = GetQuestName(6421) -- "Helping the Healers"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_WORLDBOSS_06 = GetQuestName(6424) -- "Scholarly Observations"

-- Southern Elsweyr Exploratory Quest - Senchal -- Added by DarkPhalanx
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_01 = GetQuestName(6419) -- "Tomes of the Tsaesci"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_02 = GetQuestName(6432) -- "Solace By Candlelight"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_03 = GetQuestName(6436) -- "Lilies for Remembrance"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_04 = GetQuestName(6438) -- "An Answer in Blood"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_05 = GetQuestName(6437) -- "Moonlit Mushrooms"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_06 = GetQuestName(6431) -- "Sourcing the Ensorcelled"

-- Southern Elsweyr Dragon Hunts - Dragonguard Sanctum -- Added by DarkPhalanx
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DRAGONHUNT_01 = GetQuestName(6444) -- "Dawn of the Dragonguard"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DRAGONHUNT_02 = GetQuestName(6435) -- "The Dragonguard's Quarry"

-- Southern Elsweyr New Moon Quests - Dragonguard Sanctum -- Added by DarkPhalanx
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_07 = GetQuestName(6406) -- "A Lonely Grave"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_08 = GetQuestName(6430) -- "File Under D"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_09 = GetQuestName(6428) -- "Sticks and Bones"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_10 = GetQuestName(6429) -- "Digging Up the Garden"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_11 = GetQuestName(6433) -- "Rude Awakening"
L.DQT_SOUTHERN_ELSWEYR_QUESTS_DELVE_12 = GetQuestName(6405) -- "Taking Them to Tusk"

-- Western Skyrim Bounty Quests -- Added by DarkPhalanx
L.DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_01 = GetQuestName(6518) -- "Circle of Cheaters"
L.DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_02 = GetQuestName(6526) -- "Feasting in the Dark"
L.DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_03 = GetQuestName(6509) -- "Lost Along the Shore"
L.DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_04 = GetQuestName(6517) -- "Moonlight Kidnapping"
L.DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_05 = GetQuestName(6519) -- "Mother of Shadows"
L.DQT_WESTERN_SKYRIM_QUESTS_WORLDBOSS_06 = GetQuestName(6527) -- "Problem Growth"

-- Western Skyrim Exploratory Quests -- Added by DarkPhalanx
L.DQT_WESTERN_SKYRIM_QUESTS_DELVE_01 = GetQuestName(6523) -- "Dwemer Disassembly"
L.DQT_WESTERN_SKYRIM_QUESTS_DELVE_02 = GetQuestName(6520) -- "Precious Bark"
L.DQT_WESTERN_SKYRIM_QUESTS_DELVE_03 = GetQuestName(6495) -- "The Preservation of Life"
L.DQT_WESTERN_SKYRIM_QUESTS_DELVE_04 = GetQuestName(6493) -- "The Strength of Giants"
L.DQT_WESTERN_SKYRIM_QUESTS_DELVE_05 = GetQuestName(6524) -- "Spiritual Release"
L.DQT_WESTERN_SKYRIM_QUESTS_DELVE_06 = GetQuestName(6494) -- "A Trail Gone Cold"

-- Western Skyrim Harrowstorms -- Added by DarkPhalanx
L.DQT_WESTERN_SKYRIM_QUESTS_HARROWSTORM_01 = GetQuestName(6512) -- "Halt the Harrowstorms"

-- The Reach - Added By DarkPhalanx
L.DQT_THE_REACH_QUESTS_WORLDBOSS_01 = GetQuestName(6585) -- "Discarded Treasures"
L.DQT_THE_REACH_QUESTS_WORLDBOSS_02 = GetQuestName(6556) -- "Namira's Perversions"
L.DQT_THE_REACH_QUESTS_WORLDBOSS_03 = GetQuestName(6582) -- "Ruptures in the Reach"
L.DQT_THE_REACH_QUESTS_WORLDBOSS_04 = GetQuestName(6583) -- "The Scholar's Request"
L.DQT_THE_REACH_QUESTS_WORLDBOSS_05 = GetQuestName(6584) -- "Guides to the Deep"
L.DQT_THE_REACH_QUESTS_WORLDBOSS_06 = GetQuestName(6581) -- "Notes of the Void"

-- The Reach Harrowstorms -- Added by DarkPhalanx
L.DQT_THE_REACH_QUESTS_HARROWSTORM_01 = GetQuestName(6559) -- "Halt the Harrowstorms"

-- The Reach Exploratory Quests -- Added by DarkPhalanx
L.DQT_THE_REACH_QUESTS_DELVE_01 = GetQuestName(6573) -- "Unhatched Menace"
L.DQT_THE_REACH_QUESTS_DELVE_02 = GetQuestName(6557) -- "Wild Talismans"
L.DQT_THE_REACH_QUESTS_DELVE_03 = GetQuestName(6569) -- "What's Hers is Ours"
L.DQT_THE_REACH_QUESTS_DELVE_04 = GetQuestName(6571) -- "Magic Mycology"
L.DQT_THE_REACH_QUESTS_DELVE_05 = GetQuestName(6567) -- "The Tainted Briarheart"
L.DQT_THE_REACH_QUESTS_DELVE_06 = GetQuestName(6572) -- "Strange Contamination"

-- The Reach Ardanir Quests -- Added by DarkPhalanx
L.DQT_THE_REACH_QUESTS_RESISTANCE_01 = GetQuestName(6603) -- "Alone in the Dark"
L.DQT_THE_REACH_QUESTS_RESISTANCE_02 = GetQuestName(6604) -- "Defenders of the Reach"
L.DQT_THE_REACH_QUESTS_RESISTANCE_03 = GetQuestName(6600) -- "Remnants of the Deep Folk"
L.DQT_THE_REACH_QUESTS_RESISTANCE_04 = GetQuestName(6605) -- "The Language of the Night"
L.DQT_THE_REACH_QUESTS_RESISTANCE_05 = GetQuestName(6602) -- "The Light of Arkthzand"
L.DQT_THE_REACH_QUESTS_RESISTANCE_06 = GetQuestName(6606) -- "The Lost Shrine"
L.DQT_THE_REACH_QUESTS_RESISTANCE_07 = GetQuestName(6601) -- "To Burn Away Evil"

-- Blackwood Delve Quests -- Added by DarkPhalanx
L.DQT_BLACKWOOD_QUESTS_DELVE_01 = GetQuestName(6644) -- "A Proper Blessing"
L.DQT_BLACKWOOD_QUESTS_DELVE_02 = GetQuestName(6668) -- "Beauty Amid Danger"
L.DQT_BLACKWOOD_QUESTS_DELVE_03 = GetQuestName(6674) -- "Breaking the Chain"
L.DQT_BLACKWOOD_QUESTS_DELVE_04 = GetQuestName(6673) -- "Conflict of Interest"
L.DQT_BLACKWOOD_QUESTS_DELVE_05 = GetQuestName(6675) -- "Insect Savior"
L.DQT_BLACKWOOD_QUESTS_DELVE_06 = GetQuestName(6665) -- "Shadow Tactics"

-- Blackwood World Boss Quests -- Added by DarkPhalanx
L.DQT_BLACKWOOD_QUESTS_WORLDBOSS_01 = GetQuestName(6651) -- "A Reign of Frogs"
L.DQT_BLACKWOOD_QUESTS_WORLDBOSS_02 = GetQuestName(6653) -- "Call of the Ruinach"
L.DQT_BLACKWOOD_QUESTS_WORLDBOSS_03 = GetQuestName(6649) -- "Goblin Research"
L.DQT_BLACKWOOD_QUESTS_WORLDBOSS_04 = GetQuestName(6645) -- "Legend of the Man-Bull"
L.DQT_BLACKWOOD_QUESTS_WORLDBOSS_05 = GetQuestName(6650) -- "Rites of the Sul-Xan"
L.DQT_BLACKWOOD_QUESTS_WORLDBOSS_06 = GetQuestName(6652) -- "The Trophy-Taker"

-- Deadlands World Boss Quests -- Added by g4m3r7ag
L.DQT_DEADLANDS_QUESTS_WORLDBOSS_01 = GetQuestName(6716) -- "Dangerous Business"
L.DQT_DEADLANDS_QUESTS_WORLDBOSS_02 = GetQuestName(6720) -- "Retrieval Gone Awry"
L.DQT_DEADLANDS_QUESTS_WORLDBOSS_03 = GetQuestName(6718) -- "Unmaker's Hoard"
L.DQT_DEADLANDS_QUESTS_WORLDBOSS_04 = GetQuestName(6719) -- "Careless Contamination"
L.DQT_DEADLANDS_QUESTS_WORLDBOSS_05 = GetQuestName(6721) -- "A Paralyzing Lesson"
L.DQT_DEADLANDS_QUESTS_WORLDBOSS_06 = GetQuestName(6717) -- "The Mind's Eye"

-- Deadlands Delve Quests -- Added by g4m3r7ag
L.DQT_DEADLANDS_QUESTS_DELVE_01 = GetQuestName(6714) -- "Clandestine Communications"
L.DQT_DEADLANDS_QUESTS_DELVE_02 = GetQuestName(6715) -- "A Discreet Pickup"
L.DQT_DEADLANDS_QUESTS_DELVE_03 = GetQuestName(6712) -- "Forgotten Grave Goods"
L.DQT_DEADLANDS_QUESTS_DELVE_04 = GetQuestName(6710) -- "Propaganda Suppressed"
L.DQT_DEADLANDS_QUESTS_DELVE_05 = GetQuestName(6713) -- "Flowers in the Folly"
L.DQT_DEADLANDS_QUESTS_DELVE_06 = GetQuestName(6711) -- "Brandfire Reformatory Relics"

-- High Isle World Boss Quests -- Added by g4m3r7ag
L.DQT_HIGH_ISLE_QUESTS_WORLDBOSS_01 = GetQuestName(6821) -- "Ascendant Shadows"
L.DQT_HIGH_ISLE_QUESTS_WORLDBOSS_02 = GetQuestName(6803) -- "Avarice of the Eldertide"
L.DQT_HIGH_ISLE_QUESTS_WORLDBOSS_03 = GetQuestName(6807) -- "The Sable Knight"
L.DQT_HIGH_ISLE_QUESTS_WORLDBOSS_04 = GetQuestName(6816) -- "The Serpent Caller"
L.DQT_HIGH_ISLE_QUESTS_WORLDBOSS_05 = GetQuestName(6822) -- "A Special Reagent"
L.DQT_HIGH_ISLE_QUESTS_WORLDBOSS_06 = GetQuestName(6808) -- "Wildhorn's Wrath"

-- High Isle Delve Quests -- Added by g4m3r7ag
L.DQT_HIGH_ISLE_QUESTS_DELVE_01 = GetQuestName(6809) -- "Arcane Research"
L.DQT_HIGH_ISLE_QUESTS_DELVE_02 = GetQuestName(6826) -- "Druidic Research"
L.DQT_HIGH_ISLE_QUESTS_DELVE_03 = GetQuestName(6805) -- "A Final Peace"
L.DQT_HIGH_ISLE_QUESTS_DELVE_04 = GetQuestName(6825) -- "Pirate Problems"
L.DQT_HIGH_ISLE_QUESTS_DELVE_05 = GetQuestName(6818) -- "Prison Problems"
L.DQT_HIGH_ISLE_QUESTS_DELVE_06 = GetQuestName(6815) -- "Seek and Destroy"

-- High Isle Volcanic Vents Quests -- Added by g4m3r7ag
L.DQT_HIGH_ISLE_QUESTS_VOLCANIC_VENTS_01 = GetQuestName(6812) -- "Venting the Threat"

-- High Isle Tales of Tribute Quests -- Added by g4m3r7ag
L.DQT_TALES_OF_TRIBUTE_QUESTS_01 = GetQuestName(6831) -- "Cards Across the Continent"
L.DQT_TALES_OF_TRIBUTE_QUESTS_02 = GetQuestName(6832) -- "Dueling Tributes"

-- Galen Delve  Quests -- Added by g4m3r7ag
L.DQT_GALEN_QUESTS_DELVE_01 = GetQuestName(6886) -- "Flower Fancier"
L.DQT_GALEN_QUESTS_DELVE_02 = GetQuestName(6887) -- "Helpful Handbills"
L.DQT_GALEN_QUESTS_DELVE_03 = GetQuestName(6884) -- "Volcanic Virtuoso"
L.DQT_GALEN_QUESTS_DELVE_04 = GetQuestName(6883) -- "Radiant Souvenirs"
L.DQT_GALEN_QUESTS_DELVE_05 = GetQuestName(6888) -- "Marking the Path"
L.DQT_GALEN_QUESTS_DELVE_06 = GetQuestName(6885) -- "Critter Capture"

-- Galen World Boss Quests -- Added by g4m3r7ag
L.DQT_GALEN_QUESTS_WORLDBOSS_01 = GetQuestName(6878) -- "Sunflower Stamina"
L.DQT_GALEN_QUESTS_WORLDBOSS_02 = GetQuestName(6891) -- "Three-Pronged Approach"
L.DQT_GALEN_QUESTS_WORLDBOSS_03 = GetQuestName(6881) -- "A Wailing Wood"
L.DQT_GALEN_QUESTS_WORLDBOSS_04 = GetQuestName(6890) -- "Recovered Relics"
L.DQT_GALEN_QUESTS_WORLDBOSS_05 = GetQuestName(6889) -- "The Moth Study"
L.DQT_GALEN_QUESTS_WORLDBOSS_06 = GetQuestName(6892) -- "Shrines on Shaky Ground"

-- Galen Volcanic Vents Quests -- Added by g4m3r7ag
L.DQT_GALEN_QUESTS_VOLCANIC_VENTS_01 = GetQuestName(6901) -- "Imminent Hazard"

-- Necrom World Boss Quests -- Added by notnear
L.DQT_NECROM_QUESTS_WORLDBOSS_01 = GetQuestName(7042) -- "An Ancient Omniscience"
L.DQT_NECROM_QUESTS_WORLDBOSS_02 = GetQuestName(7041) -- "Devourer of Dreams"
L.DQT_NECROM_QUESTS_WORLDBOSS_03 = GetQuestName(7043) -- "Knowledge is Power"
L.DQT_NECROM_QUESTS_WORLDBOSS_04 = GetQuestName(7039) -- "Reenactment Gone Awry"
L.DQT_NECROM_QUESTS_WORLDBOSS_05 = GetQuestName(7040) -- "Tracking Nightmares"

-- Necrom Delve Quests -- Added by notnear
L.DQT_NECROM_QUESTS_DELVE_01 = GetQuestName(7035) -- "Bound in Secrecy"
L.DQT_NECROM_QUESTS_DELVE_02 = GetQuestName(7037) -- "Secret Protection"
L.DQT_NECROM_QUESTS_DELVE_03 = GetQuestName(7036) -- "Secrets Reclaimed"
L.DQT_NECROM_QUESTS_DELVE_04 = GetQuestName(7034) -- "Snatch and Run"

-- Necrom Bastion Nymic Quests -- Added by notnear
L.DQT_NECROM_QUESTS_BASTION_NYMIC_01 = GetQuestName(7013) -- "Bastion Nymic - Glasscrag"
L.DQT_NECROM_QUESTS_BASTION_NYMIC_02 = GetQuestName(7056) -- "Bastion Nymic - Fungal Downs"
L.DQT_NECROM_QUESTS_BASTION_NYMIC_03 = GetQuestName(7057) -- "Bastion Nymic - Writhing Wastes"
L.DQT_NECROM_QUESTS_BASTION_NYMIC_04 = GetQuestName(7058) -- "Bastion Nymic - Fallen Hues"

-- Endless Archive Quests -- Added by notnear
L.DQT_ENDLESSARCHIVE_QUESTS_MISC_01 = GetQuestName(7065) -- "Replication Elimination"

-- West Weald World Boss Quests -- Added by notnear
L.DQT_WEST_WEALD_QUESTS_WORLDBOSS_01 = GetQuestName(7116) -- "Fate Eater"
L.DQT_WEST_WEALD_QUESTS_WORLDBOSS_02 = GetQuestName(7117) -- "Training Camp"
L.DQT_WEST_WEALD_QUESTS_WORLDBOSS_03 = GetQuestName(7118) -- "Baleful Bluffs"
L.DQT_WEST_WEALD_QUESTS_WORLDBOSS_04 = GetQuestName(7119) -- "Recollection Rendezvous"
L.DQT_WEST_WEALD_QUESTS_WORLDBOSS_05 = GetQuestName(7120) -- "Hazardous Waters"
L.DQT_WEST_WEALD_QUESTS_WORLDBOSS_06 = GetQuestName(7109) -- "Spinning Out"

-- West Weald Delve Quests -- Added by notnear
L.DQT_WEST_WEALD_QUESTS_DELVE_01 = GetQuestName(7111) -- "Loan Recall"
L.DQT_WEST_WEALD_QUESTS_DELVE_02 = GetQuestName(7112) -- "Trinkets from the Reach"
L.DQT_WEST_WEALD_QUESTS_DELVE_03 = GetQuestName(7113) -- "A Calamitous Error"
L.DQT_WEST_WEALD_QUESTS_DELVE_04 = GetQuestName(7114) -- "A Study in Tharriker"
L.DQT_WEST_WEALD_QUESTS_DELVE_05 = GetQuestName(7115) -- "Ruinous Evaluation"
L.DQT_WEST_WEALD_QUESTS_DELVE_06 = GetQuestName(7108) -- "Venom Hunt"

-- West Weald Mirrormoor Incursion Quests -- Added by notnear
L.DQT_WEST_WEALD_QUESTS_MIRRORMOOR_INCURSION_01 = GetQuestName(7110) -- "Mirrormoor Incursion"
-- L.DQT_WEST_WEALD_QUESTS_MIRRORMOOR_INCURSION_02 = GetQuestName(7182) -- "Mirrormoor Incursion"

-- Solstice World Boss Quests -- Added by notnear
L.DQT_SOLSTICE_QUESTS_WORLDBOSS_01 = GetQuestName(7264) -- "Gaulm's Lair"
L.DQT_SOLSTICE_QUESTS_WORLDBOSS_02 = GetQuestName(7265) -- "Guardians Gone Bad"
L.DQT_SOLSTICE_QUESTS_WORLDBOSS_03 = GetQuestName(7266) -- "Tidewash Stranded"
L.DQT_SOLSTICE_QUESTS_WORLDBOSS_04 = GetQuestName(7270) -- "Ghishzor's Ritual" -- Added by calculoso
L.DQT_SOLSTICE_QUESTS_WORLDBOSS_05 = GetQuestName(7271) -- "Soulcaller's Curse" -- Added by calculoso
L.DQT_SOLSTICE_QUESTS_WORLDBOSS_06 = GetQuestName(7272) -- "Wo-Xeeth's Wrath" -- Added by calculoso

-- Solstice Delve Quests -- Added by notnear
L.DQT_SOLSTICE_QUESTS_DELVE_01 = GetQuestName(7261) -- "Save the Ruins!"
L.DQT_SOLSTICE_QUESTS_DELVE_02 = GetQuestName(7262) -- "Sanguine's Solace"
L.DQT_SOLSTICE_QUESTS_DELVE_03 = GetQuestName(7263) -- "Candleflies for the Dead"
L.DQT_SOLSTICE_QUESTS_DELVE_04 = GetQuestName(7267) -- "Samples Needed" -- Added by calculoso
L.DQT_SOLSTICE_QUESTS_DELVE_05 = GetQuestName(7268) -- "Black Worm Relics" -- Added by calculoso
L.DQT_SOLSTICE_QUESTS_DELVE_06 = GetQuestName(7269) -- "Fragments of Fear" -- Added by calculoso

-- Solstice Siege Camp Quests -- Added by calculoso
L.DQT_SOLSTICE_QUESTS_SIEGE_CAMP_01 = GetQuestName(7471) -- Siege camp "Protecting the Besieged"
-- L.DQT_SOLSTICE_QUESTS_SIEGE_CAMP_02 = GetQuestName(7275) -- Siege Camp "Protecting the Besieged"

for stringId, translation in pairs(L) do
	ZO_CreateStringId(stringId, translation)
end
