ZO_CreateStringId('SI_KEYBINDINGS_CATEGORY_IMPROVED_TOMES_UI', 'Improved Tamriel Tomes')
ZO_CreateStringId('SI_BINDING_NAME_IMPROVED_TAMRIEL_TOMES', 'Show/Hide Panel')
ZO_CreateStringId('SI_BINDING_NAME_IMPROVED_TAMRIEL_TOMES_SHOW_CHALLENGES', GetString(SI_TAMRIEL_TOMES_VIEW_CHALLENGES_LABEL))