CollectThemAllData_Vendors_Nenuluare = {
    name = "Nenuluare",
    source = "Vendors",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {
            { name = "Nascent Indrik", bars = 500, fragments = { "Emerald Indrik Feather", "Gilded Indrik Feather", "Onyx Indrik Feather", "Opaline Indrik Feather" } },
            { name = "Dawnwood Indrik", bars = 1000, fragments = { "Dawnwood Berries of Bloom", "Dawnwood Berries of Budding", "Dawnwood Berries of Growth", "Dawnwood Berries of Ripeness" } },
            { name = "Spectral Indrik", bars = 1000, fragments = { "Spectral Berries of Bloom", "Spectral Berries of Budding", "Spectral Berries of Growth", "Spectral Berries of Ripeness" } },
            { name = "Luminous Indrik", bars = 1000, fragments = { "Luminous Berries of Bloom", "Luminous Berries of Budding", "Luminous Berries of Growth", "Luminous Berries of Ripeness" } },
            { name = "Icebreath Indrik", bars = 1000, fragments = { "Icebreath Berries of Bloom", "Icebreath Berries of Budding", "Icebreath Berries of Growth", "Icebreath Berries of Ripeness" } },
            { name = "Onyx Indrik", bars = 1000, fragments = { "Onyx Berries of Bloom", "Onyx Berries of Budding", "Onyx Berries of Growth", "Onyx Berries of Ripeness" } },
            { name = "Mossheart Indrik", bars = 1000, fragments = { "Mossheart Berries of Bloom", "Mossheart Berries of Budding", "Mossheart Berries of Growth", "Mossheart Berries of Ripeness" } },
            { name = "Pure-Snow Indrik", bars = 1000, fragments = { "Pure-Snow Berries of Bloom", "Pure-Snow Berries of Budding", "Pure-Snow Berries of Growth", "Pure-Snow Berries of Ripeness" } },
            { name = "Crimson Indrik", bars = 1000, fragments = { "Crimson Berries of Bloom", "Crimson Berries of Budding", "Crimson Berries of Growth", "Crimson Berries of Ripeness" } },
        },
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {
            { name = "Springtide Indrik", bars = 1000 },
            { name = "Haunting Indrik", bars = 1000 },
            { name = "Rimedusk Indrik", bars = 1000 },
            { name = "Shimmering Indrik", bars = 1000 },
            { name = "Ebon-Glow Indrik", bars = 1000 },
            { name = "Sapling Indrik", bars = 1000 },
            { name = "Frost-Light Indrik", bars = 1000 },
            { name = "Rosethorn Indrik", bars = 1000 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
