CollectThemAllData_Vendors_RolisHlaalu = {
    name = "Rolis Hlaalu",
    source = "Vendors",
    collection = {
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE_BANK] = {
            { name = "Furnishing Vault" },
            { name = "Storage Chest, Fortified" },
            { name = "Storage Chest, Oaken" },
            { name = "Storage Chest, Secure" },
            { name = "Storage Chest, Sturdy" },
            { name = "Storage Coffer, Oaken" },
            { name = "Storage Coffer, Secure" },
            { name = "Storage Coffer, Sturdy" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_HOUSE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FURNITURE] = {
            { name = "Chronometer of the Tribunal" },
            { name = "Sea Witch Weather Totem" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ASSISTANT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COMPANION] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MOUNT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_VANITY_PET] = {},
        [COLLECTIBLE_CATEGORY_TYPE_MEMENTO] = {},
        [COLLECTIBLE_CATEGORY_TYPE_EMOTE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_OUTFIT_STYLE] = {
            { name = "Glass", motif = 16, q = 4 },
            { name = "Ebony", motif = 37, q = 3 },
        },
        [COLLECTIBLE_CATEGORY_TYPE_PLAYER_FX_OVERRIDE] = {
            { name = "Hroldan Hammer Mining" },
        },
        [COLLECTIBLE_CATEGORY_TYPE_ABILITY_FX_OVERRIDE] = {},
        [COLLECTIBLE_CATEGORY_TYPE_POLYMORPH] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PERSONALITY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_SKIN] = {},
        [COLLECTIBLE_CATEGORY_TYPE_COSTUME] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAT] = {},
        [COLLECTIBLE_CATEGORY_TYPE_BODY_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HEAD_MARKING] = {},
        [COLLECTIBLE_CATEGORY_TYPE_HAIR] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_HAIR_HORNS] = {},
        [COLLECTIBLE_CATEGORY_TYPE_FACIAL_ACCESSORY] = {},
        [COLLECTIBLE_CATEGORY_TYPE_PIERCING_JEWELRY] = {},
    },
}
